### ISSUE TITLE
Ability to use free memtest86+ with systemd-boot

### ISSUE THREAD

**Issue by est31** [NixOS/nixpkgs#100014]
**Describe the bug**

There are the bootable programs memtest86 and its fork memtest86+. Both perform the same task, but former has went proprietary a while ago, which makes the fork the only free option. The proprietary one also has EFI support while the fork only supports legacy booting.

When you enable memtest86 with grub, it checks whether EFI is enabled, and if yes, uses memtest86, and otherwise the free fork 7b5550a3fc72cc3c41c4143732502a0787cb17a0. The systemd-boot analog doesn't have this feature, it always uses the proprietary memtest86.

I haven't allowed nonfree software on my system, and don't have EFI enabled. It would be great if I were able to use systemd-boot together with memtest86+.

**Notify maintainers**

@cdepillabout , author of #61036

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
