### ISSUE TITLE
Vlc crashes on startup but cvlc does not

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#100037]
**Describe the bug**
After installing VLC from latest nixpkgs,if I run`vlc` it crashes,whether I run from the cli or from the graphical launcher.
However if I run `cvlc` from the cli it works normally

**To Reproduce**
1. nix profile install nixpkgs#vlc
2. Run `vlc`
3. See it crash immediately
4. Run `cvlc` and see it work normally

**Expected behavior**
VLC works normally when run as `vlc`

**Notify maintainers**
@ttuegel @andrew-d @peterhoeg 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67, NixOS, 21.03.20200927.84d74ae (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200622_334e26b`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1"`
 - nixpkgs: `/nix/store/gwpi140dfjmbn0pj1hspf4hhqa550iyi-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - vlc
# a list of nixos modules affected by the problem
module:
```
