### ISSUE TITLE
gnome3 logout button doesn't show

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#100108]
**Describe the bug**
With `gnome3` and `gdm` you won't see the logout button in the session.

**To Reproduce**
1. Login to gnome session
2. Run:
```
nix-shell -p gobject-introspection -p gdm -p gjs --run 'gjs -c "print(imports.gi.Gdm.get_session_ids().length)"'
```

This will return `0` and the logout button won't be visible per https://github.com/GNOME/gnome-shell/blob/b2d6c11ec39042855910f36d59e0789e16593fb9/js/misc/systemActions.js#L394

**Expected behavior**
You can see the logout button with multiple sessions (the default gnome).

Meaning
```
nix-shell -p gobject-introspection -p gdm -p gjs --run 'gjs -c "print(imports.gi.Gdm.get_session_ids().length)"'
```

will return `2` in the default gnome install.

Should we create a regression test for this?

**Additional context**
This was discovered when looking into https://github.com/NixOS/nixpkgs/issues/84634.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: gnome3
```
