### ISSUE TITLE
Pantheon: no wallpapers

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#100293]
**Describe the bug**

![Screenshot from 2020-10-07 15-38-20](https://user-images.githubusercontent.com/91113/95708488-b77ed800-0c5c-11eb-929b-7cdd625a6c41.png)

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
have wallpapers like before. this is a regression

**Additional context**

**Notify maintainers**
@worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.13, NixOS, 20.09beta992.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta992.7badbf18c45, nixos-hardware, nixos-unstable-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
