### ISSUE TITLE
chromium build fails, No space left on device

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#100281]
**Describe the bug**
The build of chromium fails with the error

> No space left on device

**To Reproduce**
1. nix-build 'https://github.com/worldofpeace/nixpkgs/archive/pantheon-stuff-20.09.tar.gz' -A chromium

**Expected behavior**
Nix builds packages with the resources available

**Screenshots**
![Screenshot from 2020-10-12 00-37-44](https://user-images.githubusercontent.com/91113/95692002-cf863580-0c23-11eb-81d4-22a237b89ec3.png)

The strange thing is that `/tmp` and the RAM don't seem full!
So it's not the same issue as https://github.com/NixOS/nixpkgs/issues/54707

**Additional context**
Maybe Chromium is a special case? How many resources does it need?

**Notify maintainers**
@primeos

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.13, NixOS, 20.09beta992.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta992.7badbf18c45, nixos-hardware, nixos-unstable-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: chromium
# a list of nixos modules affected by the problem
module:
```
