### ISSUE TITLE
Tmux is broken on Mac OS

### ISSUE THREAD

**Issue by ashkan-leo** [NixOS/nixpkgs#100371]
**Describe the bug**
tmux crashes with the following error when I invoke it:

```
error creating /run/user/$(id -u)/tmux-501 (No such file or directory)
```

**To Reproduce**
1. Install tmux. `nix-env -iA nixpkgs.tmux`
2. run tmux on mac os. `tmux`

**Expected behavior**
tmux should work with no problem

**Screenshots**

**Additional context**

**Notify maintainers**

@rissson 
@gnidorah 
@oxij 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixpkgs-20.09pre236005.2b7c0dcdaab"`
 - channels(ashkanaleali): `"darwin, home-manager-20.03, nixpkgs-21.03pre245942.89281dd1dfe, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
