### ISSUE TITLE
Pantheon: screenshots selection is saved after an additional click

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#100470]
**Describe the bug**

https://youtu.be/0Is0wlYuhSA

**To Reproduce**
1. hit SHIFT + PRINT
2. select area to screenshot
3. click once or select new selection (this should not happen!!!!!)

**Expected behavior**
screenshot saved after selection

**Additional context**

**Notify maintainers**
@worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 20.09beta1057.0b8799ecaaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta1057.0b8799ecaaf, nixos-hardware, nixos-unstable-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
