### ISSUE TITLE
breeze-icons-5.73.0: hash mismatch

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#100429]
**Describe the bug**
```
hash mismatch importing path '/nix/store/prs85ry75yzfq4789p3nvx3xzb50i636-breeze-icons-5.73.0';
  wanted: sha256:0vkx0isjvc5l7l8j9byw05y2rvqpr25dr52bx8hd1v3nknljlh9h
  got:    sha256:0y0arwcqhwqdxf3vynjhim69mfg4cmzkbr8a8s463iqy4bpfmpdy
copying path '/nix/store/nfnx4yqr2cmnc0fdba2aixf4a2w4m2p9-hook' to 'local'...
```
https://nix-cache.s3.amazonaws.com/log/5xi3ljg4c1f8jqga0m3pv7wangahg3c0-nixos-ova-21.03pre246445.b13bb2402be-x86_64-linux.drv

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `breeze-icons`
# a list of nixos modules affected by the problem
module:
```

cc @ttuegel
