### ISSUE TITLE
opensmtpd: missing makemap binary

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#100419]
**Describe the bug**

The `makemap` utility is missing from the `opensmtpd` package.

```
$ ls -l /nix/store/2x67rywz1vkav70x4kn353ispbwl5lxs-opensmtpd-6.7.1p1/bin
total 808
-r-xr-xr-x 1 root root  67864 Dec 31  1969 smtp
-r-xr-xr-x 1 root root 194280 Dec 31  1969 smtpctl
-r-xr-xr-x 1 root root 560232 Dec 31  1969 smtpd
```

**Notify maintainers**

cc @obadz @ekleog

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.11, NixOS, 21.03.git.a373d69351a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: opensmtpd
# a list of nixos modules affected by the problem
module:
```
