### ISSUE TITLE
broadcom-wl-dkms: Doesn't compile with kernel >= 5.9

### ISSUE THREAD

**Issue by bagnaram** [NixOS/nixpkgs#101040]
**Describe the bug**
In kernel versions before 5.9 there was a macro called "segment_eq". This macro was only used to implement "uaccess_kernel"  and removed with 5.9.0. Now broadcom-wl-dkms fails to build as it can't find it.

See: for patch https://bugs.archlinux.org/task/68030

**To Reproduce**

1. Enable broadcom-sta
```
boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
```

**Screenshots**
```
/build/broadcom-sta/src/wl/sys/wl_linux.c:1667:6: error: implicit declaration of function 'segment_eq' [-Werror=implicit-function-declaration]
```

**Notify maintainers**

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.8.7, NixOS, 21.03.git.d44dbf3549a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-21.03pre246543.24c9b05ac53"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
