### ISSUE TITLE
aspellDicts.en-science doesn't build

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#101184]
**Describe the bug**

**To Reproduce**
1. `nix-build -A aspellDicts.en-science`

```
these derivations will be built:
  /nix/store/v3m40ghhnl2xf9lj7q7bxq2bffmdacxa-aspell-dict-en-science.drv
building '/nix/store/v3m40ghhnl2xf9lj7q7bxq2bffmdacxa-aspell-dict-en-science.drv'...
preBuild
building
building en_US-science
grep: (standard input): binary file matches
builder for '/nix/store/v3m40ghhnl2xf9lj7q7bxq2bffmdacxa-aspell-dict-en-science.drv' failed with exit code 1
error: build of '/nix/store/v3m40ghhnl2xf9lj7q7bxq2bffmdacxa-aspell-dict-en-science.drv' failed
```

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-zen1, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre237686.96069f7d890"`
 - channels(bbigras): `"home-manager"`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
