### ISSUE TITLE
Pantheon: Settings - About: NixOS logo missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#101221]
**Describe the bug**
logo is missing

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
logo as before

**Screenshots**
![Screenshot from 2020-10-20 22-58-54](https://user-images.githubusercontent.com/91113/96652542-685d3500-1337-11eb-8bcd-f102df79c1de.png)

**Additional context**

**Notify maintainers**
@worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.16, NixOS, 20.09beta1322.ba2ec4867d7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta1322.ba2ec4867d7, nixos-hardware, nixos-unstable-21.03pre248062.5265d49a36b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
