### ISSUE TITLE
Chromium: Fontconfig error: Cannot load default config file: No such file: (null)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#101211]
**Describe the bug**
When i open Chromium in terminal, i see this error

`Fontconfig error: Cannot load default config file: No such file: (null)`

even tho i have enabled Fontconfig

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
I guess that error should not appear?

**Additional context**
Here is my config: https://codeberg.org/davidak/nixos-config/src/commit/df95bdeef09bc510fe9de66b762a2e657ed79031/services/fonts/default.nix

**Notify maintainers**
@primeos 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 20.09beta1057.0b8799ecaaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta1057.0b8799ecaaf, nixos-hardware, nixos-unstable-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: chromium
# a list of nixos modules affected by the problem
module:
```
