### ISSUE TITLE
inkscape fails to run from `nix shell`

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#101466]
**Describe the bug**
```
$ nix shell nixpkgs#inkscape

$ inkscape
No protocol specified
ConcreteInkscapeApplication<T>::create_window: Should not be called!
```

```
$ which inkscape
/nix/store/r770brq0w2l6xj7wcpvb92j26mixk026-inkscape-1.0.1/bin/inkscape
```

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

nixpkgs is probably cfed29bfcb28259376713005d176a6f82951014a

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
