### ISSUE TITLE
Firefox 82 and firefox-bin 82 do not run under Wayland when LTO is enabled

### ISSUE THREAD

**Issue by artemist** [NixOS/nixpkgs#101429]
**Describe the bug**
When I attempt to run firefox-wayland within my Sway session it runs under X11. This happens even if I set `XDG_SESSION_TYPE=wayland` and `MOZ_ENABLE_WAYLAND=1`. If I set `GDK_BACKEND=wayland` then Firefox prints to stderr:
```
(firefox:4408): Gtk-WARNING **: 23:20:43.048: cannot open display: :0
mozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Device or resource busy
```
and then crashes with a segfault. I get the same result with firefox-bin

**To Reproduce**
1.`nix-shell -p firefox-wayland --run "env GDK_BACKEND=wayland firefox"`

**Expected behavior**
Firefox runs using Wayland

**Screenshots**

**Additional context**

**Notify maintainers**

@edolstra @andir

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 21.03.git.a920bf43082 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre246543.24c9b05ac53"`
 - channels(artemis): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [firefox,firefox-bin,firefox-wayland]
# a list of nixos modules affected by the problem
module:
```
