### ISSUE TITLE
foundationdb60: flow/Knobs.cpp:131:63: error: 'log' was not declared in this scope

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#101509]
**Describe the bug**
Building `foundationdb60` fails with the following messages:
```
flow/Knobs.cpp: In constructor 'FlowKnobs::FlowKnobs(bool, bool)':
flow/Knobs.cpp:131:63: error: 'log' was not declared in this scope
  init( METRIC_LEVEL_DIVISOR,                             log(4) );
                                                               ^
flow/Knobs.cpp:26:45: note: in definition of macro 'init'
 #define init( knob, value ) initKnob( knob, value, #knob )
```

**To Reproduce**
1. `nix-build . -A foundationdb60`

**Expected behavior**
It builds successfully.

**Notify maintainers**
@thoughtpolice 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.128-microsoft-standard, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(omasanori): `"nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/home/omasanori/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - foundationdb60
  - python27Packages.foundationdb60
  - python37Packages.foundationdb60
  - python38Packages.foundationdb60
# a list of nixos modules affected by the problem
module:
```
