### ISSUE TITLE
wingpannel applications not reloaded when installing into profile

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#101527]
**Describe the bug**

When I install a desktop app into my profile, it does not appear in the "Applications" menu automatically.

**To Reproduce**

1. Use Pantheon.
2. Install some desktop app using `nix profile install`.
3. Try to find it in the "Applications" menu.

**Expected behavior**
It is there.

**Notify maintainers**
@worldofpeace 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - pantheon.wingpanel-applications-menu
module:
```

-----

My understanding is that there is code in the indicator that collects `applications` subdirs from `XDG_DATA_DIRS`, reads the files from them and then sets up a `FileMonitor` for each directory. However, in the case of a NixOS profile, the directory itself, naturally, never changes, so it needs to also monitor all directories on the way to the root.

That's not really a Nixpkgs issue, but something that needs to be fixed upstream, however, I'm pretty sure they will be not particularly impressed by our use-case, so I'm opening an issue here. I do hope they will accept a PR, even if useful only for us.
