### ISSUE TITLE
libressl: netcat doesn't work on macos

### ISSUE THREAD

**Issue by sdier** [NixOS/nixpkgs#101601]
**Describe the bug**
netcat from libressl doesn't work on macos

**To Reproduce**
1. as root: dtruss -W nc
2. nc localhost 22
3. note that the socket open shown in dtruss shows error 41

**Expected behavior**
Connects.

**Additional context**
I have opened https://github.com/libressl-portable/portable/issues/631

I don't think anyone actually ever used this successfully on macos.  I suspect it should be disabled from building for this platform if possible until its fixed so nobody else has to go through the debugging.

**Notify maintainers**
@fpletz 
@thoughtpolice 

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS `
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(sdier): `"home-manager, nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/Users/sdier/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: libressl.nc
```
