### ISSUE TITLE
fix circular dependency between cinnamon-session and cinnamon-settings-daemon

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#101772]
**Describe the bug**
In https://github.com/NixOS/nixpkgs/pull/101394 we noticed that cinnamon-settings-daemon needs gsettings from cinnamon-session when seeing the error
```
./result/libexec/csd-power
(csd-power:17877): GLib-GIO-ERROR **: 12:10:39.813: Settings schema 'org.cinnamon.SessionManager' is not installed
```

It's not uncommon, because of the global mess that is the GSettings API, to create circular dependencies this fashion. Actually, a similar issue occured in Pantheon. 

To resolve this we'd either need to move those settings to a separate package at the top of the dependency tree, or something else that I can't really remember :rofl: But that's the best option. And it'd be best to tell the linuxmint people that they should fix this.

**To Reproduce**
1. Try to start an executable from cinnamon-settings-daemon that needs cinnamon-session (in a pure environment)
2. Watch it crash because it's not wrapped with cinnamon-session

Cinnamon actually still starts because this gets polluted into the global environment.

**Additional context**
https://github.com/NixOS/nixpkgs/pull/101394

**Notify maintainers**

@mkg20001 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cinnamon
# a list of nixos modules affected by the problem
module: cinnamon
```
