### ISSUE TITLE
Fontconfig 2.13 without recent patches makes parts of Emacs unusable

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#101813]
**Describe the bug**
Searching for fonts matching a pattern has become incredibly slow; we're talking like, 20+seconds; as Emacs tries to match for fonts in real-time, it has rendered it effectively unusable (for example, `M-x describe-fontset RET RET`). Commits to fontconfig's `master` branch in late August, 2020 have greatly improved matters greatly.

Please include these performance fix commits as patches.

**Additional context**
The specific emacs behaviour occurs on my NixOS system, but not my Ubuntu + Nix system.
**Notify maintainers**
@vcunat 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fontconfig
# a list of nixos modules affected by the problem
module: fonts.fontconfig
```
