### ISSUE TITLE
super-productivity segfault

### ISSUE THREAD

**Issue by fxkrait** [NixOS/nixpkgs#101883]
**Describe the bug**
- super-productivity segfaults on launch

**To Reproduce**
1. Install super-productivity
2. run it

**Expected behavior**
- It should run

**Screenshots**
![image](https://user-images.githubusercontent.com/7407672/97374029-8e716080-1874-11eb-83f6-eaae1478e2e7.png)

**Additional context**
- Don't know how to debug this, so making a bug report so those that know can look into into it.

**Notify maintainers**

@offlinehacker 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.16, NixOS, 20.09.1469.13d0c311e3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1469.13d0c311e3a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
