### ISSUE TITLE
kwallet is not unlocked with SDDM

### ISSUE THREAD

**Issue by xfix** [NixOS/nixpkgs#101904]
**Describe the bug**

After logging in with SDDM I see the following window:

![](https://user-images.githubusercontent.com/8165792/77233680-54870000-6ba9-11ea-8349-1593efb44d48.png)

Every time. This is annoying and should not happen. Previously, no manual intervention was necessary. This is a regression in 20.09.

This is like #83095, but for 20.09 this time.

**To Reproduce**
1. Enable NetworkManager, SDDM and Plasma.
2. Store Wi-Fi password in KDE Wallet (store password for this user only - encrypted).
3. Set KDE Wallet password to password used to log in.
4. Log out.
5. Observe the above-mentioned window.

**Expected behavior**

No manual intervention should be necessary.

**Notify maintainers**

@ttuegel @nyanloutre 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1469.13d0c311e3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(xfix): `""`
 - channels(root): `"nixos-20.09.1469.13d0c311e3a, home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: plasma5
```
