### ISSUE TITLE
Add gdk-pixbuf support to libavif

### ISSUE THREAD

**Issue by krolokis-0xdf3** [NixOS/nixpkgs#102063]
**Describe the bug**
libavif should be configure to build the gdk-pixbuf module

**To Reproduce**
1. gtk applications don't support the AVIF format

**Expected behavior**
Open avif files with eog or generate thumbnails in Nautilus

**Additional context**
- [Upstream bug report](https://github.com/AOMediaCodec/libavif/pull/182)

**Notify maintainers**
@mkg20001

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
