### ISSUE TITLE
nixos/tests/prometheus fails since thanos 0.14.0 -> 0.15.0 upgrade

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#102112]
**Describe the bug**
Commit fc2a1452facc7cfea585096e411f643d7699f717 breaks the prometheus test.

**To Reproduce**
```
git checkout master
nix-build nixos/tests/prometheus.nix
git revert fc2a1452facc7cfea585096e411f643d7699f717
nix-build nixos/tests/prometheus.nix
```

**Additional context**
https://github.com/NixOS/nixpkgs/pull/98901

**Notify maintainers**
@basvandijk 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: thanos, nixosTests.prometheus
# a list of nixos modules affected by the problem
module:
```
