### ISSUE TITLE
NetworkManager fail since 20.09

### ISSUE THREAD

**Issue by pinage404** [NixOS/nixpkgs#102256]
**Describe the bug**
I was having a working configuration with NixOS 20.03
At startup, KWallet ask me for the password of my wallet to open it and allow NetworkManager to access to the password of the WiFi

Since the upgrade, i still type my password of my wallet to open it, but NetworkManager can't connect to the WiFi

`journalctl --unit NetworkManager`
`oct. 31 17:56:21 pinage404-nixos NetworkManager[1004]: <warn>  [1604163381.8783] device (wlp4s0): no secrets: No agents were available for this request`

**To Reproduce**
1. have a working configuration with NixOS 20.03, with WiFi's password stored in the wallet
2. upgrade to NixOS 20.09
3. broken

**Expected behavior**
NetworkManager should find KWallet as secrets agents

**Additional context**
Maybe related to https://github.com/NixOS/nixpkgs/issues/69368

**Notify maintainers**

teams.freedesktop.members

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(pinage404): `"home-manager-20.03, nixos-20.03.3158.7c2a362b58a, nixos-unstable-21.03pre248170.007126eef72"`
 - channels(root): `"nixos-20.09.1500.edb26126d98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: networking.networkmanager
```
