### ISSUE TITLE
ordering cycle for nix-daemon.socket/start job

### ISSUE THREAD

**Issue by hyperfekt** [NixOS/nixpkgs#102372]
**Describe the bug**
Seldomly, Nix will not be able to communicate with the daemon via the socket. The following can be found in the journal:
```
Oct 30 13:04:49 bismuth systemd[1]: sockets.target: Found ordering cycle on nix-daemon.socket/start
Oct 30 13:04:49 bismuth systemd[1]: sockets.target: Job nix-daemon.socket/start deleted to break ordering cycle starting with sockets.target/start
```

**To Reproduce**
Unclear. 

**Expected behavior**

** Notes **
Has symptoms equal to but seems to have a different cause than #87818.

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.8.13, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/cfg/patched`
```
nixpkgs rev was 0b8799ecaaf0dc6b4c11583a3c96ca5b40fcfdfb with patches.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- services/misc/nix-daemon.nix
```
