### ISSUE TITLE
Mailman module in NixOS requires postfix even though Mailman supports other MTAs

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#102641]
**Describe the bug**
Mailman module in NixOS requires postfix enabled and has no way to configure Mailman to work with other MTAs supported by both NixOS and mailman upstream.

**To Reproduce**
1. Disable postfix
2. Enable mailman
3. Fail the evaluation with an assertion

**Expected behavior**
The Mailman module allows to select an MTA of choice (or even adapts to the currently enabled MTA)

**Screenshots**
n/a

**Additional context**
[Link to Mailman docs about MTA support](https://mailman.readthedocs.io/en/latest/src/mailman/docs/mta.html#exim)

**Notify maintainers**
cc @lheckemann 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.150, NixOS, 21.03.20201011.24c9b05 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `""`
 - channels(vika): `""`
 - nixpkgs: `/nix/store/vjj6vlbfq661l2zllgvyspdsdyvz8hl9-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: ["mailman"]
```
