### ISSUE TITLE
rspamd for aarch64 is broken on latest unstable

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#102751]
**Describe the bug**
rspamd for aarch64 can't find luajit and fails to build.

**To Reproduce**
`nix build github:NixOS/nixpkgs#legacyPackages.aarch64-linux.rspamd`

At the moment of writing, the latest unstable seems to be `34ad166a830d3ac1541dcce571c52231f2f0865a`.

**Expected behavior**
Build succeeds

**Screenshots**
n/a

**Additional context**
Hydra build log: https://hydra.nixos.org/build/128842971/nixlog/1

**Notify maintainers**
@avnik @fpletz @globin

**Metadata**
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - rspamd
# a list of nixos modules affected by the problem
module:
 - rspamd
```
