### ISSUE TITLE
system.autoUpgrade: run when shutting down

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#102745]
**Describe the bug**
Offer a possibility to autoUpgrade a system upon shutdown.

**Additional context**
For anything but servers often a very convenient time to perform updates is when the user is not using the system. One indicator, though not always reliable, is the time a user chooses to shut down their system.

It should be possible to configure both a time (using `dates`) as well as the shutdown job, in case one does not often shut down. E.g., think about hibernating laptops.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: `system.autoUpgrade`
```
