### ISSUE TITLE
 services.ceph.client.extraConfig not working as expected

### ISSUE THREAD

**Issue by leonardp** [NixOS/nixpkgs#102756]
**Describe the bug**
The example given for [services.ceph.client.extraConfig](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/nixos/modules/services/network-filesystems/ceph.nix#L327) does not seem work as expected.

**To Reproduce**
1. add the following to configuration.nix:
```nix
{    
  services.ceph = {    
    enable = true;    
    global = {    
      fsid = "fsid";
      monHost = "127.0.0.1";
    };            
    client = {
      enable = true;
      extraConfig = {
        "client.radosgw.node0" = { "some config option" = "true"; };
      };
    };
  };
}

```
2. run nixos-rebuild switch
3.
```
error: The option value `services.ceph.client.extraConfig.client.radosgw.node0' in `/etc/nixos/example.nix' is not of type `string'.
```

**Expected behavior**
Creation of a proper ceph client configuration.

**Additional context**
I am trying to build a NixOS configuration with a minimal ceph client configuration.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.73, NixOS, 20.09.1599.d105075a1fd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1599.d105075a1fd, nixpkgs-unstable-21.03pre250093.0da76dab4c2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.ceph.client.extraConfig
```
