### ISSUE TITLE
haskellPackages.tz is incompatible with new tzdata format

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#102937]
**Describe the bug**

Build failure.
Example:
https://hydra.nixos.org/build/129855941/nixlog/1

Upstream is working on a solution. https://github.com/nilcons/haskell-tz/issues/26
When available, `master` can pick up the new hackage package. 20.09 will require a backport.

**To Reproduce**

1. In nixpkgs master, run `nix-build haskellPackages.tz`

**Expected behavior**

Build successfully.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
