### ISSUE TITLE
"lvm2-activation-generator: lvmconfig failed" displayed during boot etc.

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#103188]
**Describe the bug**
While the configuration contains no settings related to LVM, `lvm2-activation-generator` is launched during boot, `nixos-rebuild switch` and so on, and the "lvm2-activation-generator: lvmconfig failed" message is logged in the journal.

**Expected behavior**
At least, `lvm2-activation-generator` does not produce error messages. It might be better if the service is not activated if the system does not use LVM at all.

**Additional context**
[#917164 - "lvm2-activation-generator: lvmconfig failed" message at boot time - Debian Bug report logs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917164) may or may not be relevant.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.75-hardened, NixOS, 20.09.1648.bc7c121a569 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1648.bc7c121a569"`
 - channels(omasanori): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
