### ISSUE TITLE
moodle: phpfpm times out

### ISSUE THREAD

**Issue by Kloenk** [NixOS/nixpkgs#103187]
**Describe the bug**
moodle times out when using via httpd

**To Reproduce**
1. enable and configure moodle (`services.moodle.enable`)
2. use master from 2020-11-09
3. try to access moodle via http
4. php times out

**Expected behavior**
moodle loads

**Notify maintainers**
@aanderse 

**Metadata**
already switch to older generation

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.moodle
```
