### ISSUE TITLE
Allow passing a template config file to gitlab-runner register

### ISSUE THREAD

**Issue by MartinPotier** [NixOS/nixpkgs#103210]
**Describe the bug**
Some options cannot be passed to gitlab-runner service, for example, the autoscaling periods, replacing off-peak-time configuration for the machine executor.

**Notify maintainers**

**Metadata**
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.gitlab-runner.services
```
