### ISSUE TITLE
Non-root ZFS data pool is not imported with -f

### ISSUE THREAD

**Issue by lzhang10** [NixOS/nixpkgs#103373]
**Describe the bug**

When boot.zfs.forceImportAll is set (default is true), or zfs_force=1 kernel parameter is given, non-root ZFS data pool should be imported with zpool -f option.

This is not implemented in the current master 23b939c. If a data pool was not exported from another host, NixOS boot will hang trying to import the pool without -f option. This happens regardless of the value of boot.zfs.forceImportAll or the zfs_force=1 option.

**To Reproduce**

  boot.zfs.forceImportAll = true;
  boot.zfs.extraPools = ["tank"];

will cause boot to hang when data pool tank was last used by another host and was not exported.

**Expected behavior**
tank was import with zpool -f

**Additional context**
PR incoming.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.62, NixOS, 21.03.git.450ff80f2M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - nixpkgs: `/home/user/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
