### ISSUE TITLE
fwupd build broken, permission error in meson-install

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#103365]
**Describe the bug**
fwupd (v1.5.1) does not build on the latest nixos-unstable-small channel.

Fails on meson-install with a permission error.

[Build log](https://github.com/NixOS/nixpkgs/files/5520806/fwupd.log)

**To Reproduce**
1. `nix-build --no-out-link -E 'with import <nixpkgs> { }; fwupd'`

**Expected behavior**
The package builds

**Additional context**
This is blocking rebuilds because gnome-software depends on fwupd.

**Notify maintainers**
@jtojnar 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-rc1, NixOS, 21.03pre250043.f38d5cf727d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre251600.4b5c6c8a58a, home-manager"`
 - channels(anna): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fwupd
# a list of nixos modules affected by the problem
module: fwupd
```
