### ISSUE TITLE
STAR WARS Battlefront II don't start from Steam

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#103547]
**Describe the bug**
Other people report that the game works for them with the latest Proton version, but i have no luck on NixOS.

https://www.protondb.com/app/1237950

**To Reproduce**
1. buy the game in sale
2. try to run it with proton
3. crash

**Expected behavior**
playable game like on other distros

**Additional context**
https://gist.github.com/davidak/148189f386065f76964629eaf3e86cb5

tried on 20.03
https://gist.github.com/davidak/d5c424ff86d709d07f5e15395eb49e1e

Maybe related to https://github.com/NixOS/nixpkgs/issues/100655

**Notify maintainers**
@jagajaga

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.1721.896270d629e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09.1721.896270d629e, nixos-hardware, nixos-unstable-21.03pre251123.b839d4a8557"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module:
```
