### ISSUE TITLE
Idris2: repl fails to start

### ISSUE THREAD

**Issue by mcncm** [NixOS/nixpkgs#103557]
**Describe the bug**
The Idris2 repl fails to start, instead emitting a cryptic error and immediately exiting.

**To Reproduce**
1. Install the `idris2` package, either by editing your `configuration.nix` or running `$ nix-shell -p idris2`
2. Run `$ idris2`
3. Observe the output
```
     ____    __     _         ___
    /  _/___/ /____(_)____   |__ \
    / // __  / ___/ / ___/   __/ /     Version 0.2.1
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org
 /___/\__,_/_/  /_/____/   /____/      Type :? for help

Welcome to Idris 2.  Enjoy yourself!
Exception in foreign-procedure: no entry for "idris2_readBufferData"
```
before the program exits.

**Expected behavior**
I would expect to drop into a repl.

**Additional context**
I wish I knew more, and could provide more helpful context!

**Notify maintainers**

@wchresta

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(mcncm): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: idris2
# a list of nixos modules affected by the problem
module:
```
