### ISSUE TITLE
fontconfig: missing manpages

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#103695]
**Describe the bug**

The fontconfig package is missing its manpages.

**To Reproduce**

```
$ nix shell github:NixOS/Nixpkgs/nixos-unstable#fontconfig

$ man 1 fc-cache
No manual entry for fc-cache in section 1
```

**Expected behavior**

The fontconfig package should have manpages.

**Additional context**

I already opened an upstream ticket a while ago: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/256

Also my failed attempts to add manpages can be found here: https://github.com/erictapen/nixpkgs/tree/fontconfig-manpages

**Notify maintainers**

@vcunat , also pinging @jtojnar @worldofpeace as they recently edited the file.

**Metadata**
I guess this can be skipped since I tested on `nixos-unstable`.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fontconfig
# a list of nixos modules affected by the problem
module:
```
