### ISSUE TITLE
`crrcsim` doesn't start

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#104066]
**Describe the bug**
The program doesn't start, as it references some non existing path in the nix store up on initial load.

**To Reproduce**
1. Start the program

**Expected behavior**
The program starts without issues.

**Additional context**

```
$ crrcsim
# ...
XMLException: Error opening
Unable to initialize scenery from file /nix/store/81ah6kzy7xvmk1bxnl3hvwj9vqq28bbl-crrcsim-0.9.13/share/crrcsim/scenery/cape_cod.xml
```

When the path of `crrcsim` instead is: `/nix/store/pq97ds79gyv9qhgv6awxjmmq66yq90b6-crrcsim-0.9.13`

**Notify maintainers**
@raskin 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.16, NixOS, 20.09.1819.f41c0fc7d8e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1819.f41c0fc7d8e, nixos-unstable-21.03pre252083.2deeb58f494"`
 - channels(wucke13): `"nixos-unstable-21.03pre246062.420f89ceb26, nixpkgs-unstable-19.09pre170896.6e5caa3f8ac, nixos-unstable-small-19.03pre161392.50bb0afa7ce"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
