### ISSUE TITLE
AQBanking cannot connect to OFX providers in 6.0.2

### ISSUE THREAD

**Issue by jasom** [NixOS/nixpkgs#104095]
**Describe the bug**

With aqbanking 5.7.8, I can e.g. request the balance for an existing account, with aqbanking 6.0.2 it fails

**To Reproduce**
1. Setup aqbanking
2. /nix/store/zg04zl84pp3r75qzc3ynar104i1kw0iy-aqbanking-5.7.8/bin/aqbanking-cli request --balance --account=XXXXXXXXXX
3. /nix/store/15wi0fgjphvxiqhans7m1rhdy59zfld8-aqbanking-6.0.2/bin/aqbanking-cli request --balance --account=XXXXXXXXXX

**Expected behavior**
Both versions should return balance information.

**Output**
aqbanking-6.0.2 prints the following:

```
Error Sending commands to provider "aqofxconnect":-104
accountInfoList {
} #accountInfoList

securityList {
} #securityList

messageList {
} #messageList
```

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1758.3090c650411 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(aidenn): `""`
 - channels(root): `"nixos-20.09.1758.3090c650411"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
