### ISSUE TITLE
qbittorrent doesn't see python

### ISSUE THREAD

**Issue by NeoTheFox** [NixOS/nixpkgs#104221]
**Describe the bug**
For the search functionality qBittorrent requires Python. The version from nixpkgs can't find it.

**To Reproduce**
1. Open qBittorrent
2. Press "View" and try to enable "Search Engine"
3. An error message about not having Python will be displayed.

**Expected behavior**
A new tab named "Search" appears in the UI

**Additional context**
Looks like the path to python doesn't get set right during the build

@Anton-Latukha 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.8-xanmod1, NixOS, 20.09.1870.14cf906f33c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1870.14cf906f33c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qbittorrent
# a list of nixos modules affected by the problem
module:
```
