### ISSUE TITLE
kcm-wacomtablet not working

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#104384]
**Describe the bug**
The KDE Wacom configuration module is not working, showing "The shared library was not found":

**To Reproduce**
1. use KDE
2. set `services.xserver.wacom.enable = true`
3. open KDE system settings

**Expected behavior**
The configuration module should work

**Screenshots**
![image](https://user-images.githubusercontent.com/53291983/99806818-82c64080-2b79-11eb-907e-6402cc599604.png)

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03.20201115.069f183 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
 - channels(root): `""`
 - nixpkgs: `/nix/store/7nkxq994g75sbygb0whcjqcpwk9cyljh-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: services.xserver.wacom
# a list of nixos modules affected by the problem
module:
```
