### ISSUE TITLE
tarball job fails on master

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#104466]
**Describe the bug**
https://hydra.nixos.org/build/130890698

**To Reproduce**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
