### ISSUE TITLE
nix on darwin fails a test on master

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#104465]
**Describe the bug**
https://hydra.nixos.org/build/130869706
Restarted job again, maybe it helps. It didn't.

**Notify maintainers**

@NixOS/darwin-maintainers @edolstra 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
