### ISSUE TITLE
split dns with systemd-resolved + tailscale stop working after a deploy

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#104414]
**Describe the bug**

I have a tunnel to work using tailscale.

I'm using systemd-resolved to resolve work-related domains over the tailscale tunnel.

When I redeploy with `nixos-rebuild switch` my work-related domains doesn't resolve anymore.

I'm thinking maybe tailscale replaces my dns settings.

I think I tried `tailscale up -accept-dns false` without success.

EDIT: my "main dns config" seems to still work since https://www.cloudflare.com/ssl/encrypted-sni/ tells me that I'm still using dnssec with tls.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@danderson @mbaillie

**Metadata**

nix-pre-commit-hooks: hooks up to date
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-zen1, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre251123.b839d4a8557"`
 - channels(bbigras): `"home-manager"`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
