### ISSUE TITLE
nixos test-driver fails on master

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#104467]
**Describe the bug**
Black formatting issue.
https://hydra.nixos.org/build/130880394

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
