### ISSUE TITLE
vm-test-run-boot-bios-usb blocker

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#104642]
**Describe the bug**

Build failure on hydra release-20.09
https://hydra.nixos.org/build/131059528

([blocker](https://hydra.nixos.org/build/131060533#tabs-summary))

**To Reproduce**

https://hydra.nixos.org/build/131059528

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@edolstra @fpletz 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nixosTests.boot.biosUsb
# a list of nixos modules affected by the problem
module:
```
