### ISSUE TITLE
microcodeIntel update makes ASUS UX305CA unbootable

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#105172]
**Describe the bug**
Computer shows GRUB boot menu, upon selection of NixOS entry, the screen stays blank indefinitely.

**To Reproduce**
1. Buy ASUS UX305CA laptop
2. Update to NixOS 20.09 (any commit since c89ffdc56d3f8147305ad628745f7c0ef2356c20) *OR* NixOS unstable (any commit since a79902f23e9c84a0b6c389f75a91f103e1ef0e5e)
3. Reboot

**Expected behavior**
The OS should be able to boot

**Additional context**
I spent a bit of time reducing this to a single commit. I have this issue on `master` and `release-20.09`.
The Intel microcode updates in the above commits seem to cause the issue.

**Notify maintainers**
@mweinelt 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - microcodeIntel
# a list of nixos modules affected by the problem
module:
```
