### ISSUE TITLE
PHP default extensions not documented

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#105161]
**Describe the bug**

Our documentation doesn't include a list of extensions included by default. If I want to know what extensions `php74` comes with by default I have to install it and run `php -m` or [dig through source code](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/php/7.4.nix#L12...L16).

**Expected behavior**

Maybe the [nixpkgs manual entry on `php`](https://nixos.org/manual/nixpkgs/stable/#sec-php) could list this information :thinking: 

**Notify maintainers**

@NixOS/php 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Current `stable` manual, which is NixOS `20.09`.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: php
# a list of nixos modules affected by the problem
module:
```
