### ISSUE TITLE
Cadvisor loggs error: "zfs": executable file not found in $PATH

### ISSUE THREAD

**Issue by priegger** [NixOS/nixpkgs#105139]
**Describe the bug**
Cadvisor does not find the zfs binary. In journald I see the following line over and over:
`... cadvisor-start[...]: ... encountered error refreshing zfs watcher: exec: "zfs": executable file not found in $PATH: "zfs fs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset zroot/safe/docker" =>`

**To Reproduce**
1. Set up docker service with zfs storage.
2. Set up cadvisor service

**Expected behavior**
The cadvisor (binary or service) should be able to find the zfs binary, in case zfs filesystems are enabled in the configuration.

**Notify maintainers**
- @offlinehacker 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.2016.19db3e5ea27 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2016.19db3e5ea27"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - cadvisor
# a list of nixos modules affected by the problem
module:
 - cadvisor
```
