### ISSUE TITLE
XWayland on recent master: HiDPI no longer works well

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#105366]
**Describe the bug**
Since half november, running XWayland apps on my 4k display results in tiny text.

**To Reproduce**
1. Run Gnome under Wayland
2. Configure display to be 200%
3. Run X app, like Chrome

**Expected behavior**
4. Chrome has the same size text and title bar as Gnome native apps

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.11, NixOS, 21.03pre254279.6f0c00907bb (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201118_79aa7d9`
 - channels(wmertens): `"home-manager, nixpkgs-21.03pre254870.1121b2259b7"`
 - channels(root): `"nixos-21.03pre254279.6f0c00907bb, nixos-hardware"`
 - nixpkgs: `/home/wmertens/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
