### ISSUE TITLE
Gnome on recent master: Bluetooth links lost on boot

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#105365]
**Describe the bug**
Every time I reboot, I need to re-pair my BLE keyboard.

**To Reproduce**
1. Use Gnome on recent master (started in november I think)
2. Pair keyboard
3. Reboot

**Expected behavior**
4. Keyboard is paired after reboot

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.11, NixOS, 21.03pre254279.6f0c00907bb (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201118_79aa7d9`
 - channels(wmertens): `"home-manager, nixpkgs-21.03pre254870.1121b2259b7"`
 - channels(root): `"nixos-21.03pre254279.6f0c00907bb, nixos-hardware"`
 - nixpkgs: `/home/wmertens/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: 
```
