### ISSUE TITLE
gotify-server NixOS test fails

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#105472]
**Describe the bug**
gotify-server test fails, with gotify inside of a test machine seemingly being unable to find the files for its web interface?

**To Reproduce**
1. `nix build nixpkgs#nixosTests.gotify-server`
2. Watch it fail

**Expected behavior**
The test passes

**Screenshots**
n/a

**Additional context**
Bisection revealed commit `4e9f7bbf8573d07f7b0c87d97c026cd4aad5a758` as the culprit, authored by @zowoq.

Hydra test log: https://hydra.nixos.org/build/131660876

**Notify maintainers**
 - @Ma27 as the maintainer of the gotify-server test
 - @doronbehar as the maintainer of the gotify-server package

**Metadata**
Current master at the time of writing seems to be `a52850e30442aa0b058a7afa328679da4d38407f`.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - gotify-server
# a list of nixos modules affected by the problem
module:
```
