### ISSUE TITLE
Mindustry doesn't run on wayland

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#105592]
**Describe the bug**
Running Mindustry on Wayland requires XWayland, which is unnecessary if Mindustry is built correctly.

```
Error `arc.backend.sdl.SDLError: wayland not available`.
```

**To Reproduce**
1. nix-shell -p mindustry
2. SDL_VIDEODRIVER=wayland mindustry

**Expected behavior**
Mindustry should be built against system glew with wayland support so it can run natively under wayland.

**Additional context**
https://github.com/Anuken/Mindustry/issues/1393
https://github.com/Anuken/Arc/pull/15

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
