### ISSUE TITLE
systemd tooling does not pull in .link files defined packages

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#105689]
**Describe the bug**
`iwd` includes a `.link` unit (`lib/systemd/network/80-iwd.link`) which is ignored by the `systemd` tooling (i.e. `systemd.packages`).

**To Reproduce**
Use the `iwd` nixos module and observe that the `.link` file does not show up in `/etc/systemd/network/`

**Expected behavior**
`systemd.packages` should probably extract the file from the package and make it visible there.

**Additional context**
This came up in #105560

I think https://github.com/NixOS/nixpkgs/blob/fc7f72e1446b6eee70a0287cde9dbd84098e6625/nixos/modules/system/boot/systemd-lib.nix#L164 is the right place to fix this, but not entirely sure.

**Notify maintainers**
cc @flokli 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: systemd
```
