### ISSUE TITLE
libjpeg_turbo fails to build on darwin (blocking staging-next)

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#105854]
**Describe the bug**
https://hydra.nixos.org/build/131949309

```
cmake: enabled parallel building
building
build flags: -j1 -l1 SHELL=/nix/store/pmmh1dl7kmxi2xpagknl9qqa4wr7vv9c-bash-4.4-p23/bin/bash
Scanning dependencies of target wrjpgcom
[  1%] Building C object CMakeFiles/wrjpgcom.dir/wrjpgcom.c.o
[  2%] Linking C executable wrjpgcom
[  2%] Built target wrjpgcom
Scanning dependencies of target simd
[  2%] Building ASM_NASM object simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o
x86_64: fatal: more than one input file specified: /tmp/nix-build-libjpeg-turbo-2.0.6.drv-0/source/simd/x86_64/jsimdcpu.asm

make[2]: *** [simd/CMakeFiles/simd.dir/build.make:87: simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:562: simd/CMakeFiles/simd.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
builder for '/nix/store/s0brrmcy8mgfrnl086vyffc2ininyg23-libjpeg-turbo-2.0.6.drv' failed with exit code 2
```

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

cc @vcunat @colemickens 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libjpeg_turbo
# a list of nixos modules affected by the problem
module:
```
