### ISSUE TITLE
acme and murmur incompatibilities in 20.09

### ISSUE THREAD

**Issue by tmplt** [NixOS/nixpkgs#106068]
**Describe the bug**
Compatibility between acme and murmur appears to have changed between 20.03 and 20.09.

**To Reproduce**
In 20.03 I generate a certificate and key for murmur via
```nix
services.acme = { ... };
services.nginx.virtualHosts."mumble.example.com".enableACME = true;
security.acme.certs."mumble.example.com" = {
  group = "murmur";

  # Tell murmur to reload its SSL settings, if it is running
  postRun = ''
    if ${pkgs.systemd}/bin/systemctl is-active murmur.service; then
      ${pkgs.systemd}/bin/systemctl kill -s SIGUSR1 murmur.service
    fi
  '';
};
```
but `nginx-config-reload.service` now fails to run as it cannot read the certificate owned by the group `murmur`. If `acme.certs."mumble.example.com".group` is removed, murmur is unable to read the cert. How should this be done in 20.09?

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: [ murmur, acme ]
```
