### ISSUE TITLE
journald: log nixos-version in entries

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#106081]
**Describe the bug**
It would be useful if `journalctl` would show not just the hostname, but also the `nixos-version`.

**Expected behavior**
Aside from the hostname, `journalctl` would also show the `nixos-version`.

**Additional context**
`journalctl` shows what host a log item belongs to. On NixOS, it would be convenient to also know what revision it belongs to. That makes it easier to track down when an issue started occuring.

I imagine this isn't easily possible without a systemd change. This will take up slightly more storage.

**Notify maintainers**
cc @flokli 

**Metadata**
-

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
