### ISSUE TITLE
osu-lazer-2020.1204.0 does not launch

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#106030]
**Describe the bug**
osu-lazer-2020.1204.0 does not launch due to a dependency issue.

**To Reproduce**

```
% nix-shell --pure -p osu-lazer   

[nix-shell:~]$ 'osu!'
Error:
  An assembly specified in the application dependencies manifest (osu!.deps.json) was not found:
    package: 'System.Security.Principal.Windows', version: '5.0.0'
    path: 'runtimes/unix/lib/netcoreapp2.1/System.Security.Principal.Windows.dll'
```

**Expected behavior**
The game launches

**Notify maintainers**

@oxalica 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre256591.7ba8820008a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre256591.7ba8820008a, home-manager"`
 - channels(anna): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: osu-lazer
# a list of nixos modules affected by the problem
module:
```
