### ISSUE TITLE
Firewall started before all users created

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#106127]
**Describe the bug**

The firewall systemd service is started before all users are created -- in this case nscd --
and thus the `--uid-owner` option fails.

```
firewall-start[1165]: iptables v1.8.5 (legacy): owner: Bad value for "--uid-owner" option: "nscd"
firewall-start[1165]: Try `iptables -h' or 'iptables --help' for more information.
```

**To Reproduce**

Add an iptables firewall rule with the `--uid-owner` option to `networking.firewall.extraCommads`

**Expected behavior**

Firewall started after users are created.

**Notify maintainers**

@aszlig
@edolstra
@fpletz

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.80, NixOS, 20.09.2063.f900be57309 (Nightingale)`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
