### ISSUE TITLE
vm-test-run-installer-simpleUefiSystemdBoot blocker

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#106166]
**Describe the bug**

Test timeout on hydra.

**To Reproduce**

    nix-build -A nixosTests.boot.biosUsb.x86_64-linux

**Expected behavior**

Consistent test success.

**Screenshots**

[hb50yfz3yvpqhs956ya1hvw2z6qfycmb-vm-test-run-boot-bios-usb.drv.log](https://github.com/NixOS/nixpkgs/files/5652485/hb50yfz3yvpqhs956ya1hvw2z6qfycmb-vm-test-run-boot-bios-usb.drv.log)

**Additional context**

Channel blocker.

https://hydra.nixos.org/build/132270130

May/may not be a duplicate of https://github.com/NixOS/nixpkgs/issues/104642

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nixosTests.boot.biosUsb.x86_64-linux
# a list of nixos modules affected by the problem
module:
```
