### ISSUE TITLE
Nixos 20.09 upgrade error, may be related to matplotlib

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#106178]
**Describe the bug**
Error appeared when trying to run `sudo nixos-rebuild boot --upgrade`

**To Reproduce**
```
sudo nixos-rebuild boot --upgrade
```

**Expected behavior**
An error appeared:
```
unpacking channels...
building Nix...
building the system configuration...
error: attribute 'anything' missing, at /nix/store/gai9x1179xfn69rcnyxblp24wg55gsll-source/modules/programs/matplotlib.nix:26:28
(use '--show-trace' to show detailed location information)
```

A full strack trace generated by `--show-trace` is attached.
[trace.txt](https://github.com/NixOS/nixpkgs/files/5653054/trace.txt)

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.11, NixOS, 20.09.2106.ae47c79479a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09"`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
