### ISSUE TITLE
nixos.tests.installer.lvm stuck

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#106116]
**Describe the bug**

nixos.tests.installer.lvm got stuck, blocking the `nixos-unstable` channel.

**To Reproduce**

    nix-build -A nixosTests.installer.lvm

But it's probably non-deterministic.

**Expected behavior**

Test continues and succeeds.

**Screenshots**

I've attached the log for posterity. (It may be cleared by a restart on hydra)

[xfcs1qf3l7gqiv86bd0f44gm8sl6hs3i-vm-test-run-installer-lvm.drv.txt](https://github.com/NixOS/nixpkgs/files/5649730/xfcs1qf3l7gqiv86bd0f44gm8sl6hs3i-vm-test-run-installer-lvm.drv.txt)

[Hydra link](https://hydra.nixos.org/build/132268116) for as long as it lasts.

**Additional context**

Channel blocker.
May or may not be a duplicate of #104642

**Notify maintainers**

```
nix-repl> nixosTests.installer.lvm.meta.maintainers
[ ]
nix-repl> nixosTests.installer.simple.meta.maintainers
[ ]
```

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nixosTests.installer.lvm
# a list of nixos modules affected by the problem
module:
```
