### ISSUE TITLE
tsm-client package: broken on 20.09 due to "patchelf: unsupported overlap of SHT_NOTE and PT_NOTE"

### ISSUE THREAD

**Issue by florianjacob** [NixOS/nixpkgs#106257]
**Describe the bug**
Upgrading to NixOS 20.09 failed for me because the tsm-client package is broken on 20.09.
`patchelf: unsupported overlap of SHT_NOTE and PT_NOTE` seems to be the main error message from the rebuild log output pasted below. While this sounds similar to https://github.com/NixOS/patchelf/issues/255, tsm-client is written in Java and not in Rust.
The tsm-client package built fine on NixOS 20.03.

**To Reproduce**
```nix
programs.tsmClient.enable = true;
```

**Expected behavior**
The tsm-client package should compile on 20.09.

**Screenshots**
```
[…]
searching for dependencies of /nix/store/m0nw6ravvg8q6gzgh8mzghyvbcf977g2-tsm-client-8.1.8.0-unwrapped/opt/tivoli/tsm/client/ba/bin/dsmutillnx
  libstdc++.so.6 -> found: /nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib/libstdc++.so.6
setting RPATH to: /nix/store/bf82z1xgvpsidj26c12mm4r7fhijcpzz-lvm2-2.03.10/lib:/nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib
patchelf: unsupported overlap of SHT_NOTE and PT_NOTE
builder for '/nix/store/43w826xr9646yvhkz234wfl3hmiplyd8-tsm-client-8.1.8.0-unwrapped.drv' failed with exit code 1
cannot build derivation '/nix/store/151jk73200n362cy8bs2x3f7smijnnyy-tsm-client-8.1.8.0.drv': 1 dependencies couldn't be built
[…]
```

**Notify maintainers**
Maintainer: @Yarny0 can you reproduce this?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.tsm-client
# a list of nixos modules affected by the problem
module: programs.tsmClient services.tsmBackup
```
