### ISSUE TITLE
Faulty hashes in openjdk8 prevent build of bazel

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#106381]
**Describe the bug**

```
hash mismatch in fixed-output derivation '/nix/store/m4yb1ynp3nq1kig6ric33qqqfcg6zgv8-jdk8-jdk8u272-b10.tar.gz':
  wanted: sha256:0yivz4r0s0n10x6aj61apdyn22prvz3lqav4xpl3412hscj863lg
  got:    sha256:1nqb2nnwy54x2ysnbkxx9hqbigcgqy7fpm4kghrn4xrc7rs41plm
cannot build derivation '/nix/store/j7c3380nlgh0czsi6z46y0ckf9y6dzr0-openjdk-headless-8u272-b10.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xj9bdjqwjdvrywqqbyakhf64gizav9gn-bazel-3.3.1.drv': 1 dependencies couldn't be built
```

This also affects corba, jaxp and probably more.

The openjdk8 packages were last touched in 5db66b26785dd2206b750cb37418b60c164c1cad

**To Reproduce**
1. git checkout master
2. nix-build -A bazel

**Expected behavior**
Correct hashes. Working build.

**Notify maintainers**

@asbachb @eadwu 

**Metadata**
Trying to upgrade to 5db66b26785dd2206b750cb37418b60c164c1cad on x86_64.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: openjdk8
# a list of nixos modules affected by the problem
module:
```
