### ISSUE TITLE
Separate nix-index into wrapped and unwrapped versions

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#106515]
So that you don't need to recompile the package when overriding nix.

**Notify maintainers**

@bennofs 

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nix-index
# a list of nixos modules affected by the problem
module:
```
