### ISSUE TITLE
steam: ld segfaults in the steam-run environment

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#106519]
**Describe the bug**
in `steam-run`, `ld` segfaults.

**To Reproduce**
1. `steam-run ld`
-> `[1]    16117 segmentation fault (core dumped)  steam-run ld`

**Expected behavior**
`ld` runs and allows loading dynamically linked executables

**Additional context**
Latest unstable-small.

**Notify maintainers**

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257794.b8936e55235 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre257794.b8936e55235, home-manager"`
 - channels(anna): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
