### ISSUE TITLE
Many projects using `fetchFromGitHub` `src.rev` as a commit hash when it's now just the version

### ISSUE THREAD

**Issue by 06kellyjac** [NixOS/nixpkgs#106543]
**Describe the bug**

I was looking into whether there was a cleaner way to get a commit sha when using `fetchFromGitHub` and I found a several projects grabbing `src.rev` off of there to use as their commit sha.
That sounded great until I did a build and noticed the rev is just going to be `vX.X.X` or whatever you feed in.
I'm guessing this worked many years ago when it wasn't using `fetchzip`?? It would be nice if `fetchFromGithub` did grab the commit sha though

**To Reproduce**
1. `nix-shell -p argo
2. `argo version`
3. `GitCommit: v2.11.8`

**Expected behavior**

**Notify maintainers**

@matthewbauer 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre256292.296793637b2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"home-manager, nixos-21.03pre257339.83cbad92d73, nixos-hardware"`
 - channels(jk): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
