### ISSUE TITLE
networking.networkd.privacy test broken by systemd 247 upgrade

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#106858]
**Describe the bug**

The channel-blocking networking.networkd.privacy test is [failing](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.networking.networkd.privacy.x86_64-linux). The test hangs for 15 minutes and times out. I bisected this failure to commit ef050bc3d18d4c72da4ba238fccbf0d82565eeb9 “systemd: 246.6 -> 247-rc2” (#102355), then bisected systemd and found systemd/systemd@5e0534f1c13cd50ec2b143a8b18156cd37e502f7 (systemd/systemd#17240) to be the first bad commit.

**To Reproduce**
`nix build -Lf ~/nixpkgs nixosTests.networking.networkd.privacy`

**Notify maintainers**
@Mic92 @andir @edolstra @flokli @Kloenk 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03.git.b7c48f3ea5c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [systemd]
# a list of nixos modules affected by the problem
module: []
```
