### ISSUE TITLE
ACME renew fails if there is a local DNS server configured as the system resolver

### ISSUE THREAD

**Issue by m1cr0man** [NixOS/nixpkgs#106862]
**Describe the bug**
During a `nixos-rebuild`, ACME renewal can fail because the enabled local DNS server (confirmed with bind and dnsmasq) is not ready to serve requests.

**To Reproduce**
1. Enable bind and an acme cert on your server
2. Perform a nixos-rebuild
3. The acme renew service usually fails

**Expected behavior**
The acme renew service should not fail.

The solution here would require a generalised way to reliably wait on the DNS server to be online. Changes need to be made in the mentioned DNS server modules more than the ACME module, despite it appearing as an ACME failure.

**Screenshots**
See [this renew service output](https://github.com/NixOS/nixpkgs/issues/103121#issuecomment-744100208)

**Notify maintainers**
@nixos/acme

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.83, NixOS, 21.03.git.16f80f8221cM (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: lego
# a list of nixos modules affected by the problem
module: security.acme
```
