### ISSUE TITLE
sandboxed builds fail with kernels >=5.9 on the installer

### ISSUE THREAD

**Issue by hyperfekt** [NixOS/nixpkgs#106961]
**Describe the bug**
When creating an installation medium that uses a Linux kernel >= 5.9.?, all sandboxed builds fail with `error: linking '[nix store path A, ending on .drv.chroot]/[nix store path B, ending on multiple-outputs.sh]' to '[nix store path B]': No data available`.

**To Reproduce**
1. Create and boot from an installation flash drive using this config:
```
{ pkgs, ... }:
{
  imports = [ <nixpkgs/nixos/modules/installer/cd-dcd/installation-cd-graphical-plasma5.nix> ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
}
````
2. attempt to perform any build (not substituted)
3. observe mentioned error instead of the build succeeding
4. perform the same build successfully by adding `--option sandbox false`

**Additional context**
- Same issue does not occur with kernel versions <=5.8.?, and does occur with kernel version 5.10.?
- One other user I asked who was on the same commit said the same problem did not occur for them on a normal installation.

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 5.9.14, NixOS, 20.09.2238.b94726217f7 (Nightingale)`
- multi-user?: `no`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.9`
- channels(root): `"nixos-20.09.2238.b94726217f7"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- nix
# a list of nixos modules affected by the problem
module:
installer/cd-dvd/installation-cd-base.nix
```
