### ISSUE TITLE
pkgsCross.talloc does't build anymore

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#106953]
**Describe the bug**

Fails to build and points to this log in its build dir: https://gist.github.com/Atemu/7b54533e5ba0ffca1a93cc88624bc637

Broken since https://github.com/NixOS/nixpkgs/commit/7f4bc12f1369030a9512ef324ec42d5ed4ad2097. cc @raboof

**Additional context**

https://github.com/NixOS/nixpkgs/issues/106759

**Notify maintainers**

@symphorien (you fixed pkgsCross.wafHook and talloc before, this looks similar)
@lopsided98 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
