### ISSUE TITLE
haskell-language-server: nuked references to GHC causes hlint plugin to fail

### ISSUE THREAD

**Issue by jul1u5** [NixOS/nixpkgs#107098]
**Describe the bug**
The builder for haskell-language-server removes references to GHC in HLS binary. This causes plugins like hlint to fail: https://github.com/haskell/haskell-language-server/issues/591.

**To Reproduce**
1. `nix-shell -p haskell-language-server` (on unstable channel)
2. Launch VS Code (or any other editor that can connect to HLS)
3. Try applying any hlint quick fix ("Apply hint: ...") in the editor
4. Observe error

**Expected behavior**
Applying hlint suggestion via HLS should not fail.

**Additional context**
This seems to only affect `haskell-language-server` (and not `haskellPackages.haskell-language-server`). Applying hlint suggestions with `haskellPackages.haskell-language-server` works.

Here is the actual root cause: https://github.com/alanz/ghc-exactprint/issues/96.

Maybe it would be possible to fix this in nixpkgs while we wait for the fix upstream? I think the references to GHC are removed here https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/haskell/haskell-language-server/withWrapper.nix#L19. I am not actually sure why it's necessary to remove these references. Is it because of using `haskell.lib.justStaticExecutables`? Would something else break if references were not removed?

**Notify maintainers**
@maralorn

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ haskell-language-server ]
# a list of nixos modules affected by the problem
module:
```
