### ISSUE TITLE
tor-browser-bundle-bin: build error

### ISSUE THREAD

**Issue by privatier** [NixOS/nixpkgs#107141]
**Describe the bug**
tor-browser-bundle-bin can't be build, because https://dist.torproject.org/torbrowser/10.0.5/tor-browser-linux64-10.0.5_en-US.tar.xz is not available anymore.

**To Reproduce**
Installing tor-browser-bundle-bin fails with error: cannot download tor-browser-linux64-10.0.5_en-US.tar.xz from any mirror.

**Expected behavior**
Installing tor-browser-bundle-bin should work.

**Screenshots**

**Additional context**

**Notify maintainers**

@offlinehacker @matejc @doublec @thoughtpolice @joachifm @hax404 @scaredmushroom @KarlJoad

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.83, NixOS, 20.09.2290.647cc06986c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2290.647cc06986c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: tor-browser-bundle-bin
```
