### ISSUE TITLE
xonotic .desktop file is broken

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#107219]
**Describe the bug**
Since some time xonotic does not appear in my wofi menu anymore, which lists all .desktop files installed in the user profile.

**To Reproduce**
1. install xonotic
2. run `wofi --show drun` or a similar application to list installed .desktop files

**Expected behavior**
wofi should list xonotic

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/3250809/102697819-16eafc80-4239-11eb-8d7b-79f2a491243b.png)

**Additional context**
May be caused by changes in https://github.com/NixOS/nixpkgs/pull/105151

**Notify maintainers**
@petabyteboy (heh)
@umazalakain 
@astsmtl 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
