### ISSUE TITLE
home-assistant: fails to build

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#107376]
**Describe the bug**
home-assistant fails to build with the following output:
https://gist.github.com/pinpox/942bbfca6f46afbe775b94883ddd1476

**To Reproduce**
1.` nix-shell -p pkgs.home-assistant`

**Expected behavior**
It builds

**Additional context**
https://gist.github.com/pinpox/942bbfca6f46afbe775b94883ddd1476

**Notify maintainers**

@dotlambda @globin @mic92 @hexa

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03.20201209.e9158ec (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- home-manager
# a list of nixos modules affected by the problem
module:
```
