### ISSUE TITLE
Steam controller not recognized by steam after steam update

### ISSUE THREAD

**Issue by alapshin** [NixOS/nixpkgs#107446]
**Describe the bug**
https://github.com/NixOS/nixpkgs/pull/107295 removed steam's udev rules.
Which were used by [steam-hardware](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/hardware/steam-hardware.nix) module.
As a result steam controller (and probably other controllers) are no longer recognized by steam.

**To Reproduce**
1. Install old steam version.
2. Verify that `/etc/udev/rules.d` contains files `60-steam-input.rules` and `60-steam-vr.rules`
3. Verify that steam controller is recognized by steam
4. Update to latest steam
5. Verify that files are no longer present
6. Verify that steam controller is no longer recognized by steam

**Expected behavior**
Steam controller should be recognized by steam.

**Notify maintainers**
@jonringer 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module: steam-hardware
```
