### ISSUE TITLE
bcachefs: unable to boot from

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#107571]
**Describe the bug**
![signal-2020-12-22-110143](https://user-images.githubusercontent.com/91113/103134497-c993e280-46b1-11eb-866d-9ab1d8c9acef.jpeg)

I fixed it with

```
  # needed to boot from bcachefs
  boot.initrd.availableKernelModules = [ "sha256" ];
```

a proper fix would be to add it to https://github.com/NixOS/nixpkgs/blob/e7fe577d9803885d1191c6612b95c246cb605dde/nixos/modules/tasks/filesystems/bcachefs.nix#L53

i will create a PR and test it later

this issue is for reference and so i don't forget

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.0, NixOS, 21.03.git.2ae527c50e0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.2344.a3a3dda3bac, nixos-hardware, nixos-unstable-21.03pre257780.e9158eca70a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
