### ISSUE TITLE
osu-lazer is broken in unstable

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#107546]
**Describe the bug**
Trying to run `osu-lazer` from unstable in terminal gets you the following error message:

```
osu\! 
Error:
  An assembly specified in the application dependencies manifest (osu!.deps.json) was not found:
    package: 'System.Security.Principal.Windows', version: '5.0.0'
    path: 'runtimes/unix/lib/netcoreapp2.1/System.Security.Principal.Windows.dll'
```

I think the cause is the recent bump, that was automated: https://github.com/NixOS/nixpkgs/commit/b0e8e8365b0c5b992109344fd843f59c76910ca0#diff-3dec67e8c4897313d6229fed55da21bfd45b41d8022afabf53668d5b8ea7f583

**To Reproduce**
1. Install latest version of `osu-lazer` from unstable
2. Run from terminal to get the error

**Expected behavior**
It should work.

**Notify maintainers**
@oxalica

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.84, NixOS, 20.09.2344.a3a3dda3bac (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2344.a3a3dda3bac"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
