### ISSUE TITLE
Plasma on wayland apps doesn't work properly

### ISSUE THREAD

**Issue by CertainLach** [NixOS/nixpkgs#107595]
**Describe the bug**

- plasmashell tasklist widget doesn't show anything
- yakuake can't position itself correctly
- spectacle can't take screenshots
- some others apps (which takes screenshots, injects input, looks at active window list) are broken too

**To Reproduce**
1. Run nixos on master with those patches applied: #107472 #107476 (required for startplasma-wayland to work)
2. Start plasma with
```bash
export QT_LOGGING_RULES="kwin_*.debug=true" # For logging, doesn't required for reproduction
dbus-run-session startplasma-wayland
```
3. See some apps doesn't work correctly

**Expected behavior**

**Screenshots**

**Additional context**

There are error lines in logs:
```
KWIN_UTILS: Could not find the desktop file for "/nix/store/v24qakxc15pnj60i7ydqzsd9svdjdjp6-plasma-workspace-5.20.4/bin/.plasmashell-wrapped"
KWIN_UTILS: Could not find the desktop file for "/nix/store/0kbrkb257806lgx5q46gw59scgd2vhqm-yakuake/bin/.yakuake-wrapped"
KWIN_UTILS: Could not find the desktop file for "/nix/store/rabb2qzn14fvq4ksvd063fwcj6d9hwq8-spectacle/bin/.spectacle-wrapped"
```

But spectacle and yakuake DO have .desktop files, probally it can't be found because of wrappers?

.desktop files are required, because kwin enforces security by using them, i.e for seeing active windows 
```
X-KDE-Wayland-Interfaces=org_kde_plasma_window_management
```
should be present in .desktop file

**Notify maintainers**

@worldofpeace @ttuegel

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - plasma5.plasma-workspace 
  - yakuake
  - spectacle
  - kdeFrameworks.krunner
# a list of nixos modules affected by the problem
module:
```
