### ISSUE TITLE
tarball: k3s' version is empty

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#107624]
**Describe the bug**

```
wget -qO- https://channels.nixos.org/nixos-unstable/packages.json.br | brotli -d | jq .packages.k3s
```

**Additional context**

https://github.com/repology/repology-rules/issues/413

I thought it may be caused by the '+' in  the version string but removing that suffix didn't help.  

**Notify maintainers**

@euank 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
