### ISSUE TITLE
Firefox: about:crashes don't work

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#107889]
**Describe the bug**
Firefox crashed because my disk was full. I wanted to submit a crash report, but the site the documentation mentions don't exist.

https://support.mozilla.org/en-US/kb/mozillacrashreporter

**To Reproduce**
1. open `about:crashes` in firefox

**Expected behavior**
firefox works like an official release

**Screenshots**
![Screenshot from 2020-12-29 17-21-55](https://user-images.githubusercontent.com/91113/103299630-41894200-49fd-11eb-9cba-28f04c80ef9c.png)

**Additional context**

**Notify maintainers**
@eelco

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.1, NixOS, 21.03.git.173696f216f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.2344.a3a3dda3bac, nixos-hardware, nixos-unstable-21.03pre257780.e9158eca70a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
