### ISSUE TITLE
anki-bin: CJK characters are displayed as rectangles

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#107874]
**Describe the bug**

Title.

European non-ascii characters like äåéëþüúíóöáßðfœø etc. work fine.

**Additional context**

Anki's binary distribution is a horrible mess, I don't know whether it's fixable.

Is there any Nix patching one should be aware of when looking into font issues with non-nix-built packages?

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
