### ISSUE TITLE
GCC 10 doesn't build for any MinGW configuration

### ISSUE THREAD

**Issue by MetaDark** [NixOS/nixpkgs#107886]
**Describe the bug**
`mcfgthread` is [patched into GCC](https://github.com/NixOS/nixpkgs/blob/51ccf2d4badea4d709f8087e3fdb3fff3956d556/pkgs/development/compilers/gcc/10/default.nix#L64-L67) when building for MinGW, however an equivalent GCC 10 patch file doesn't exist. I tried looking for a GCC 10 patch on the master branch of https://github.com/lhmouse/MINGW-packages, but the `mingw-w64-gcc-git` folder that contained the patches no longer exists.

GCC9 is still currently the default on master, but this will break everything under MinGW the next time staging-next is merged to master. See https://github.com/NixOS/nixpkgs/pull/89793.

Support for `mcfgthread` was originally added in https://github.com/NixOS/nixpkgs/pull/73195.

**To Reproduce**
1. `nix-build '<nixpkgs>' -A pkgsCross.mingwW64.buildPackages.gcc10`

```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download 9000-gcc-10-branch-Added-mcf-thread-model-support-from-mcfgthread.patch from any mirror
```

**Notify maintainers**
@Ericson2314 @Synthetica9 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.2, NixOS, 21.03.git.258134b2335 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre259798.84917aa00bf, nur"`
 - channels(kira): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsCross.mingw32.buildPackages.gcc10, pkgsCross.mingwW64.buildPackages.gcc10
# a list of nixos modules affected by the problem
module:
```
