### ISSUE TITLE
Plasma: New install has wrong color scheme

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#108077]
**Describe the bug**

The default color scheme for Plasma desktop after installation should be Breeze. The color scheme on first boot is actually Oxygen. To make matters worse, System Settings will _report_ that the scheme is Breeze, even though it is obviously Oxygen.

**To Reproduce**
1. Install NixOS with `services.xserver.desktopManagers.plasma5.enable = true`.
2. Open `System Settings > Colors`.
3. Observe that `Breeze` is selected, but the actual colors are those of the Oxygen scheme (dark grey application background, blue window titlebars).
4. Select `Oxygen` and `Apply`. Observe that there is no change.
5. Select `Breeze` and `Apply`. Observe that the Breeze color scheme is now applied.

**Expected behavior**
The default color scheme at first boot is Breeze.

**Screenshots**
Oxygen colors:
![Screenshot_20201231_144612](https://user-images.githubusercontent.com/563054/103425295-0f9beb00-4b77-11eb-8f6c-86da9acc6400.png)

Breeze colors:
![Screenshot_20201231_144641](https://user-images.githubusercontent.com/563054/103425304-1aef1680-4b77-11eb-8570-d3d624779710.png)

**Notify maintainers**
@ttuegel

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: plasma5
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.plasma5
```
