### ISSUE TITLE
Keybase package is incomplete

### ISSUE THREAD

**Issue by SneakyBastardSword** [NixOS/nixpkgs#108091]
**Describe the bug**
After installing keybase, keybase-gui, and kbfs, I did not have access to the run_keybase script or the keybase service file. Running `keybase ctl start` gives the following error:

```
$ keybase ctl start
▶ INFO Starting keybase.service.
Failed to restart keybase.service: Unit keybase.service not found.
▶ ERROR Failed to start keybase.service.
▶ ERROR Error in spawning server process: exit status 5
▶ ERROR exit status 5
```
`keybase init` runs without error, but does not fix the problem. Things will run while active terminal windows are left open running `keybase service` and `kbfsfuse`, but stop working as soon as you close those terminals.

**To Reproduce**
1. install keybase
2. attempt to use `run_keybase` or `keybase ctl start`

**Notify maintainers**
@Avaq @carlsverre 

**Metadata**
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.85, NixOS, 20.09.2387.0c81b9a4f17 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: keybase, kbfs, keybase-gui
```
