### ISSUE TITLE
aarch64 build failures with gcc 10 and binutils 2.34

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#108111]
**Describe the bug**
https://github.com/NixOS/nixpkgs/pull/89793#issuecomment-751692132

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
