### ISSUE TITLE
desktopConfiguration causes gnome+kde install to fail

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#108124]
**Describe the bug**

When enabling both KDE and Gnome, the system won't eval.

The reason is https://github.com/NixOS/nixpkgs/commit/99d511124620cad08e1bac2c0ca29ea3222d7f5d, which creates a single clashing `desktopConfiguration`.

**To Reproduce**
```
  services.xserver.desktopManager.plasma5.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
```

**Expected behavior**
Have both KDE and Gnome3 available for running

**Notify maintainers**

@worldofpeace 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.xserver.desktopManager.plasma5
  - services.xserver.desktopManager.gnome3
```
