### ISSUE TITLE
ghcWithHoogle fails to build index if all dependencies are GHC core libraries

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#108100]
**Describe the bug**
`ghcWithHoogle` will fail to index if all dependencies are GHC core libraries.
It will fail with the following error message:

```
error: --- TypeError ------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
at: (69:43) in file: /nix/store/cczavfv0z5fn392v37ypc48555wagvil-source/pkgs/development/haskell-modules/hoogle.nix

    68|        + " the following were specified: "
    69|        + lib.concatMapStringsSep ", " (p: p.name) packages)}
      |                                           ^
    70|     mkdir -p $out/share/doc/hoogle

value is null while a set was expected
```

**To Reproduce**
1. clone https://github.com/poscat0x04/ghc-with-hoogle-demo
2. run `nix develop` (requires nix flake), this should fail
3. add any package that's not a GHC core library to `build-depends`
4. run `nix develop` again, now it should enter dev shell just fine

**Expected behavior**
ghcWithHoogle should handle the case where all dependencies are GHC core libraries

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: haskell.lib
# a list of nixos modules affected by the problem
module:
```
