### ISSUE TITLE
python2: ctypes.util.find_library is partially broken since gcc10

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#108243]
**Describe the bug**
Can be noticed when building `python2.pkgs.cffi`. Since https://github.com/NixOS/nixpkgs/pull/89793.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Nixpkgs at b9330fe4ebb5f424919a2e88096859742f05954d

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
