### ISSUE TITLE
gdal is broken because optional dependency hdf4 is broken

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#108340]
**Describe the bug**
hdf4 no longer builds in nixpkgs unstable. It looks like something's changed in the compiler or glibc meaning that non-standard types such as `uint32` are no longer available in the global namespace. It is in ['maintenance mode' / deprecated upstream](https://portal.hdfgroup.org/display/HDF4/HDF4). Not sure if this will be fixable or whether we should consider dropping hdf4 / making hdf4 optional for packages such as gdal where it is an optional dependency upstream but a required dependency in nixpkgs.

**To Reproduce**
1. `nix-build '<nixpkgs>' -A gdal`

**Notify maintainers**
@knedlsepp @MarcWeber 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.0-rc5, NixOS, 21.03.git.4648938bb44M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.03.git.0c1c18c"`
 - nixpkgs: `/home/thrall/nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: hdf4 gdal mapnik
# a list of nixos modules affected by the problem
module:
```
