### ISSUE TITLE
nixos.iso_minimal.i686-linux fails to build, blocking nixos-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#108375]
**Describe the bug**
Dependency efivar fails to build.
https://hydra.nixos.org/build/134256319

**To Reproduce**
```
$ nix-build -A pkgsi686Linux.efivar
```

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
