### ISSUE TITLE
cachix does not build (broken dependency) blocking nixpkgs-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#108374]
**Describe the bug**
https://hydra.nixos.org/build/134154387

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
