### ISSUE TITLE
discord: clicking links does not open them in browser

### ISSUE THREAD

**Issue by neonfuz** [NixOS/nixpkgs#108995]
**Describe the bug**
clicking on links posted to discord chats does not open the links in any browser.
Other people on different distros have reported this same bug and some have had success fixing it by installing xdg-utils (see [this issue](https://github.com/snapcrafters/discord/issues/38)).
However installing xdg-utils on nixos does not solve the issue.

**To Reproduce**
1. install discord & firefox
2. click on link in any discord chat, or try to view original image on an image
3. browser does not open

**Expected behavior**
browser opens with clicked link

**Notify maintainers**
@ldesgoui @MP2E @tadeokondrak 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.87, NixOS, 20.09.2538.0cfd08f4881 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(sage): `""`
 - channels(root): `"nixos-20.09.2538.0cfd08f4881, nixos-unstable-21.03pre262471.ad97cdf81d1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: discord
# a list of nixos modules affected by the problem
module:
```
