### ISSUE TITLE
Packages are still built against zfsStable when boot.zfs.enableUnstable

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#109031]
**Describe the bug**

When you set `boot.zfs.enableUnstable`, the zfsUnstable module and userspace packages get installed. Packages that compile against ZFS like Docker and libvirt are still built against zfsStable however.

I am not sure if this would cause issues but it certainly sounds like something that could.

**Expected behavior**

All ZFS-dependant packages should be built with `zfs = zfsUnstable;` when it is enabled.

**Additional context**

Came up while investigating https://github.com/NixOS/nixpkgs/issues/109001

**Notify maintainers**

@Mic92 @globin @wizeman @hmenke @jcumming @fpletz 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
