### ISSUE TITLE
qgpgme fails to build (failing test), blocking nixos-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#109009]
**Describe the bug**
https://hydra.nixos.org/build/134668103

Introduced by gnupg update, updating gpgme did not fix the issue.
https://github.com/NixOS/nixpkgs/pull/108423#issuecomment-757441419

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@primeos

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
