### ISSUE TITLE
nixos/zfs: still pulls in zfsStable when enableUnstable

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#109001]
**Describe the bug**

When you set boot.zfs.enableUnstable, zfsUnstable is used but zfsStable is still put into the system closure. This causes an abort when the kernel is marked as incompatible with zfsStable which is very confusing because it should only be using zfsUnstable.

This only happens on 20.09, not on master.  

**To Reproduce**
1. Mark zfsStable as incompatible with your kernel version
2. Set boot.zfs.enableUnstable
3. Build system closure

**Expected behavior**

**Screenshots**

**Additional context**

https://github.com/NixOS/nixpkgs/pull/108944

**Notify maintainers**

@Mic92 @NeQuissimus 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
