### ISSUE TITLE
uboot-rpi_4_defconfig-2020.10 fails to build, blocking nixos-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#109008]
**Describe the bug**
https://hydra.nixos.org/build/134794636

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@samueldr @bennofs

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
