### ISSUE TITLE
ethminer: CUDA code fails to build

### ISSUE THREAD

**Issue by noneucat** [NixOS/nixpkgs#109283]
**Describe the bug**
I'm not sure what's exactly going on here, but it looks like the build is attempting to use gcc10 includes from somewhere, while the default nvcc from cudatoolkit only supports gcc9 at best. Maybe someone better versed with how cmake works on NixOS could take a look?

```
...
[ 57%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
4 warnings generated.
/nix/store/5wfh94xwg2hd7n82j8klgn4nmf07is24-gcc-10.2.0/include/c++/10.2.0/type_traits(1396): error: type name is not allowed
...
```

**To Reproduce**
1. Try to build `pkgs.ethminer` from nixpkgs (213286bb181c9b6588bb5c4fa130301cefc90dd0).

**Expected behavior**
The package builds successfully with CUDA support.

**Additional context**
Persists after version bump

**Notify maintainers**

cc @nand0p @breakds 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.ethminer
# a list of nixos modules affected by the problem
module:
```
