### ISSUE TITLE
linux-5.4.88-modules (aarch64) fails, blocking nixos-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#109252]
**Describe the bug**
https://hydra.nixos.org/build/135054936

Caused by https://github.com/NixOS/nixpkgs/pull/78430.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

cc @NeQuissimus 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
