### ISSUE TITLE
nixos.tests.docker was broken by docker 19.03.4 → 20.10.2 upgrade

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#109416]
**Describe the bug**
The channel-blocking [`nixos.tests.docker` test](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.docker.x86_64-linux) is failing (hangs forever and times out). I confirmed that the problem was introduced by commit b451286b1f56a65ad37fb606b7a77e73b10911e5 “docker: 19.03.4 -> 20.10.2 (#108960)”.

**To Reproduce**
`nix build -Lf . nixosTests.docker`

**Notify maintainers**
@petabyteboy @offlinehacker @tailhook @vdemeester @periklis @NeQuissimus 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.87, NixOS, 21.03.git.8f43f236a74 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre262347.257cbbcd3ab"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [docker]
# a list of nixos modules affected by the problem
module: [virtualisation.docker]
```
