### ISSUE TITLE
nufraw: segmentation fault

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#109444]
**Describe the bug**
`nufraw` runs into an segmentation fault when the raw image needs to be processed (`--embedded-image` not given).

This is a follow up to #108993 and #108626

**To Reproduce**
`./nufraw-batch --out-type=png --noexif --output=/tmp/preview.png ~/Photos/P1250767.RW2`

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
