### ISSUE TITLE
linuxPackages-libre does not boot

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#109577]
**Describe the bug**
the boot process get stuck at this point

![signal-2021-01-16-231852](https://user-images.githubusercontent.com/91113/104824520-ae506900-5852-11eb-9c13-cffdb10b5ee0.jpeg)

**To Reproduce**
1. Add `boot.kernelPackages = pkgs.linuxPackages-libre;`
2. rebuild
3. reboot

**Expected behavior**
system boots as with default kernel

**Additional context**
Complete config here: https://codeberg.org/davidak/nixos-config/src/commit/26ba1313d71ee74b71058e5d9a472078583b8ccb/machines/gaming/configuration.nix
system has amd gpu, but i think it should be fine since amdgpu driver is open source

**Notify maintainers**
@alyssais 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.7-zen1, NixOS, 20.09.2624.1eff582e7ea (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.2624.1eff582e7ea, nixos-hardware, nixos-unstable-21.03pre262347.257cbbcd3ab"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
