### ISSUE TITLE
deltachat-electron cannot import backup

### ISSUE THREAD

**Issue by cmm** [NixOS/nixpkgs#109557]
**Describe the bug**
Looks exactly like, and probably can be fixed in the same manner as, this one: https://github.com/NixOS/nixpkgs/issues/72901

**To Reproduce**
1. Open deltachat-electron
2. Press "Import backup"
3. The app crashes and prints this to stderr: `"GLib-GIO-ERROR **: <time>: No GSettings schemas are installed on the system"`

**Notify maintainers**
@ehmry 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-38-generic, Ubuntu, 20.10 (Groovy Gorilla)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(nix): `"nixpkgs-20.09pre228453.dcb64ea42e6"`
 - channels(michaell): `"home-manager, nixpkgs-21.03pre263682.bb960171989"`
 - nixpkgs: `/home/michaell/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: deltachat-electron
# a list of nixos modules affected by the problem
module:
```
