### ISSUE TITLE
sway with "exec" command would lost some env variables like GTK_IM_MODULE

### ISSUE THREAD

**Issue by TheKK** [NixOS/nixpkgs#109542]
**Describe the bug**
When running commands using sway's `exec`, you'll notice that some environment variables are missing. For me this make my input method not works on Firefox if I invoke it via `sway bindsym exec > Firefox`

I'm not 100% sure if this a NixOS issue or Sway issue so please forgive me if I'm wrong. It's possible to workaround (?) this issue by using `bindsym $mod+f exec bash --login -c "firefox"`.

**To Reproduce**
1. add `exec_always "env > /tmp/env"` to your `.config/sway/config`
2. enter sway or reload it to invoke the previous command we just added
3. inspect `/tmp/env`
    - you could run `env > /tmp/shell_env && diff /tmp/env /tmp/shell_env` to check the difference

**Expected behavior**
The `sway exec` running environment should contain at least important variable like GTK_IM_MODULE.

**Screenshots**
No snapshot here.

**Additional context**
Nothing special.

**Notify maintainers**
@primeos 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.87, NixOS, 20.09.20210108.0cfd08f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-20.09.2290.647cc06986c, nixos-hardware, nixpkgs-21.03pre258655.00941cd747e"`
 - channels(kk): `"home-manager-20.09, nixos-20.09.2538.0cfd08f4881, nixpkgs-21.03pre262186.e49e3a756b3"`
 - nixpkgs: `/home/kk/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- programs.sway.enable
# a list of nixos modules affected by the problem
module:
- <nixpkgs/nixos/modules/programs/sway.nix>
```

Please feel free to ask me for more information, also I'm willing to help if this is an actual issue of NixOS :)
