### ISSUE TITLE
steam: 'i686-linux' with features {} is required [...] but I am a 'x86_64-linux'

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#109661]
**Describe the bug**

I don't seem able to build Steam on nixpkgs since the last channel update.

```
error: --- Error ------------------------------------------------------------- nix-build
a 'i686-linux' with features {} is required to build '/nix/store/1qn89bbzb84dks24qa8qlnxbm7s5mdlr-steam-runtime-0.20201203.1.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

**To Reproduce**
1. cd ~/nixpkgs
2. nix-build -A steam

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@jagajaga @jonringer

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.1-zen1, NixOS, 21.03.20210109.257cbbc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre260232.733e537a8ad"`
 - channels(bbigras): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
