### ISSUE TITLE
emacs 28: flicker present (extra redraws?) on darwin, not on homebrew

### ISSUE THREAD

**Issue by mjlbach** [NixOS/nixpkgs#109997]
**Describe the bug**
This is a weird one, but I wanted to document it in case others are having the same problem while I try to find a fix.

I'm sorry the reproduction steps are so specific, I'll keep the issue updated as I remove variables.

**To Reproduce**
1. Install native-comp or gitEmacs from the emacs-overlay
2. Install doom-emacs
3. Open an org file
4. Trigger save, or insert-line (o)

**Expected behavior**
The behavior to match across homebrew and nix packaging.

**Screenshots**
Via homebrew:

https://user-images.githubusercontent.com/13316262/105077063-cede1600-5a40-11eb-924d-fb4bf6e32ec7.mov

Via nix: 
https://user-images.githubusercontent.com/13316262/105077085-d7cee780-5a40-11eb-8572-663f40f68745.mov

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
