### ISSUE TITLE
location.provider = "geoclue2" / services.geoclue2 is hitting daily limit exceeted

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixpkgs#110031]
**Describe the bug**
geoclue2 service doesn't work at the moment of writing this. It seems we're hitting the problem of too many requests with default token `geoclue`. (https://location.services.mozilla.com/v1/geolocate?key=geoclue). This also prevents redshift service from starting correctly when location provider is set to geoclue2.

**To Reproduce**
1. set location provider to geoclue
2. `nix-shell -p redshift --run "redshift"`

**Additional context**

```
curl 'https://location.services.mozilla.com/v1/geolocate?key=geoclue' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    151      0  0:00:01  0:00:01 --:--:--   151
{
    "error": {
        "code": 403,
        "errors": [
            {
                "domain": "usageLimits",
                "message": "You have exceeded your daily limit.",
                "reason": "dailyLimitExceeded"
            }
        ],
        "message": "You have exceeded your daily limit."
    }
}
```

**I'm not sure if API is limitting based on api key or something machine specific like IP address**.

**Notify maintainers**
@worldofpeace

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
   - location
   - services.geoclue2
   - services.redshift
```
