### ISSUE TITLE
Android Studio - System fonts can't be chosen in settings

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#110118]
**Describe the bug**
In android studio, you can change the font of the editor for example. It seems that on NixOS, this is not possible.

**To Reproduce**
1. Install android-studio (stable for me)
2. go to File -> Settings -> Editor -> Font
3. System fonts don't appear even if you uncheck "show only monospaced fonts"

**Expected behavior**
System fonts should appear under this menu so that the user can change the font of the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/31109099/105156000-935c4e00-5b0b-11eb-97c1-e94b6152d9c6.png)

**Additional context**
I am on NixOS and I have fonts working everywhere, but not android-studio

**Notify maintainers**

@meutraa

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 20.09.20210118.88f00e7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(narice): `"nixpkgs-21.03pre253014.6625284c397"`
 - channels(root): `"nixos-21.03pre262347.257cbbcd3ab"`
 - nixpkgs: `/home/narice/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: android-studio
# a list of nixos modules affected by the problem
module:
```
