### ISSUE TITLE
Some configuration options for gnome not working

### ISSUE THREAD

**Issue by ishan9299** [NixOS/nixpkgs#110310]
**Describe the bug**
Some options for gnome configuration don't work.

I have disabled xterm and excluded gnome-software in my configuration but it is still installed in my system.

config I am using
```nix
  environment = {
    systemPackages = with pkgs; [
      gnome3.gnome-tweaks
    ];
    # Exclude some gnome packages
    gnome3.excludePackages = with pkgs; [
      gnome3.gnome-music
      gnome3.gnome-contacts
      gnome3.gnome-maps
      gnome3.totem
      gnome3.yelp
      gnome3.epiphany
      gnome3.eog
      gnome3.gedit
      gnome3.geary
      gnome3.gnome-software
      gnome-photos
    ];
  };

  qt5.platformTheme = "gnome";
  programs.dconf.enable = true;
  services.flatpak.enable = true;
  xdg.portal.enable = true;
  xdg.portal.gtkUsePortal = true;
  xdg.portal.extraPortals = with pkgs; [
    xdg-desktop-portal-gtk
    xdg-desktop-portal-wlr
  ];

```

Xterm shouldn't be installed if it is disabled. If gnome-software is installed by default for flatpak then I think that it should be an option and shouldn't override `gnome3.excludePackages`.

```bash
~ 
❯ whereis xterm
xterm: /nix/store/l1y7gc8gjj1h56k16zb7xpxx0q88bzjp-system-path/bin/xterm

~ 
❯ whereis gnome-software
gnome-software: /nix/store/l1y7gc8gjj1h56k16zb7xpxx0q88bzjp-system-path/bin/gnome-software
```

**Notify maintainers**
@jtojnar 
@worldofpeace 
@vcunat 
@r-ryantm 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.7, NixOS, 21.03.20210117.68398d2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
xterm
gnome-software
attribute:
# a list of nixos modules affected by the problem
module:
services.xserver.desktopManager.xterm.enable
environment.gnome3.excludePackages
```
