### ISSUE TITLE
nautilus: webdav share not mounted via point-and-click

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#110477]
**Describe the bug**
I have recently setup a webdav share on a device present on the internal network.
On my NixOS computer, it shows up in Nautilus under "Other Locations" tab and when I click on it I receive the error: "Unable to access location HTTP error: Could not connect: Connection refused"

I can confirm that there is nothing wrong server-side. Nautilus mounts it successfully in Ubuntu 20.04 and 20.10.
I can also mount it under NixOS using the address: dav://192.168.200.214/ or dav://gnubee.local/

**To Reproduce**
1. Use gnome DE
2. Open Nautilus (Files)
3. Go to "Other Locations"
4. Click on a Webdav share

**Expected behavior**
The webdav share should be mounted and the user would be able to browse files.

**Screenshots**

**Additional context**

**Notify maintainers**

cc @hedning @jtojnar @worldofpeace

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
