### ISSUE TITLE
AppImage xdg integration, fonts and cursor

### ISSUE THREAD

**Issue by andresilva** [NixOS/nixpkgs#110636]
**Describe the bug**

Apps packaged as AppImage don't seem to respect the system's fontconfig and cursor. Additionally, opening URLs is broken as it seems that `xdg-open` doesn't work.

**To Reproduce**
1. Run AppImage
2. Click a URL

**Expected behavior**

It should open a browser at the given URL.

**Screenshots**

Proper cursor "outside" AppImage:

![Screenshot_2021-01-23_22-04-53](https://user-images.githubusercontent.com/123550/105615253-1957ed80-5dc7-11eb-80dc-d1e8f66aa7ee.png)

Default X11 cursor "inside" AppImage:

![Screenshot_2021-01-23_22-04-32](https://user-images.githubusercontent.com/123550/105615254-19f08400-5dc7-11eb-9d30-e4d1f74e03ae.png)

**Additional context**

**Notify maintainers**

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.6-zen1, NixOS, 21.03.git.9a6d968f0c0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre265130.f217c0ea7c1"`
 - nixpkgs: `/etc/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: rambox ledger-live-desktop
# a list of nixos modules affected by the problem
module:
```
