### ISSUE TITLE
Assertion failed: (request.expectedETag == res.etag)

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#110734]
**Describe the bug**
on running `nix-channel --update` on macOS 10.15.7, I get this error
```
Assertion failed: (request.expectedETag == res.etag), function downloadFile, file src/libfetchers/tarball.cc, line 64.
fish: “nix-channel --update” terminated by signal SIGABRT (Abort)
```

Here is the result of `nix-channel --list`
```
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable
```

`nix --version` gives me
```
nix (Nix) 3.0pre20200829_f156513
```

I thought it might be a transient error, so I waited a day, but it is still happening today. Not sure how to proceed.

**To Reproduce**
1. run `nix-channel --update`

**Expected behavior**
`nix-channel  --update` does not SIGABRT

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
