### ISSUE TITLE
nixpkgs-review.x86_64-darwin fails to build, blocking unstable

### ISSUE THREAD

**Issue by r-burns** [NixOS/nixpkgs#110750]
**Describe the bug**
Dependency nixUnstable fails to build:
https://hydra.nixos.org/build/135748457

**Notify maintainers**
nixUnstable: @edolstra 
nixpkgs-review: @Mic92 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
