### ISSUE TITLE
broadcom_sta: wifi interface showing up as eth0 since a recent nixos-unstable update

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#110898]
**Describe the bug**

My wifi don't seem to work and I only see a eth0 interface. I don't have an ethernet port on this laptop.

I think eth0 is supposed to get renamed to wlp2s0.

I'm deploying from my desktop to my laptop using deploy.rs. Maybe there's a problem too with my config.

**To Reproduce**
1. install the latest nixos-unstable
2. run `ip a`

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@phreedom

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
