### ISSUE TITLE
nixos-unstable doesn't build on raspberry pi

### ISSUE THREAD

**Issue by dnaq** [NixOS/nixpkgs#110842]
**Describe the bug**

When building a nixos-configuration for the raspberry pi 4, the following error occurs.

```
error: undefined variable 'linux-kernel' at <...>/nixpkgs/nixos/modules/system/boot/loader/raspberrypi/raspberrypi.nix:106:37
```
**To Reproduce**
1. nix-channel --update
2. nixos-rebuild switch
(on a raspberry pi 4)

**Expected behavior**
That the build should succeed.

**Additional context**
Bisecting nixos-unstable gives commit 12881a7aa703beb3fbf2b26f8cfd76e9bd67ae6b as the first bad commit.

**Notify maintainers**
@johnae 

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.79, NixOS, 21.03pre265130.f217c0ea7c1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre253635.2247d824fe0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

(don't trust the channel information, since the machine is deployed by nixops)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
