### ISSUE TITLE
installer.luksroot test failing on master (sometimes)

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#111223]
**Describe the bug**
[nixos.tests.installer.luksroot.x86_64-linux](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.installer.luksroot.x86_64-linux) seems to be failing consistently on master now by timing out.

I wasn’t able to figure out where this problem was introduced, since it fails locally for me in the same way even on commits where Hydra has marked it successful.

**To Reproduce**
`nix build -Lf . nixosTests.installer.luksroot`

**Notify maintainers**
@vcunat?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.92, NixOS, 21.03.git.b6b3d57856c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre265961.891f607d530"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [nixosTests.installer.luksroot]
# a list of nixos modules affected by the problem
module: []
```
