### ISSUE TITLE
`services.xserver.windowManager.xmonad.haskellPackages' is not of type `package'

### ISSUE THREAD

**Issue by wbadart** [NixOS/nixpkgs#111564]
**Describe the bug**
NixOS config fails to build with `services.xserver.windowManager.xmonad` enabled, seemingly due to a breaking change either in its `haskellPackages` option or in `pkgs.haskellPackages` (on unstable):

```
error: A definition for option `services.xserver.windowManager.xmonad.haskellPackages' is not of type `package'. Definition values:
- In `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/window-managers/xmonad.nix'
```

I have a strong feeling this is related to 37f575cd7ea29552f19fbe324973da62fc491dea.

**To Reproduce**
1. `echo "{vm0={pkgs,...}: {services.xserver.windowManager.xmonad.enable = true;};}" > test.nix`
2. `nixos-build-vms test.nix`

**Expected behavior**
I expected the default value to type-check. I tried overriding it with `xmonad.haskellPackages = pkgs.haskellPackages` and `xmonad.haskellPackages = pkgs.haskellPackages.ghc_8_10_2` but got the same error.

**Notify maintainers**
- @Scriptkiddi: do you have any suggestions on a new value here that would type-check?

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.92, NixOS, 21.03pre265961.891f607d530 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(will): `""`
 - channels(root): `"nixos-21.03pre267299.5ff6700bb82, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- haskellPackages
# a list of nixos modules affected by the problem
module:
- services.xserver.windowManager.xmonad
```

Thanks all!
