### ISSUE TITLE
firefox: wayland reports window protocol reports "wayland" instead of "wayland/drm"

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#111520]
**Describe the bug**

Per title, Firefox is reporting `wayland` again, rather than `wayland/drm` as expected.

Last time I fixed this by adding `mesa`. Not sure what it needs this time since I didn't write down *how* I determined what was missing last time.

**To Reproduce**
1. Install firefox from `nixos-unstable`.
2.  Go to `about:support`
3. Look at `window protocol` and see what it says

**Expected behavior**
Since I'm on a drm platform, I expect it to use `wayland/drm` for best performance.

**Notify maintainers**

**Metadata**
as of: 49f5e8799b22319843b8c99105fb267651104ce7

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
