### ISSUE TITLE
Raspberry Pi 4 SD card image broken on master

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#111683]
**Describe the bug**
The build of the RPI4 image has been broken for a few weeks now. See: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.sd_image_raspberrypi4.aarch64-linux

The module closure fails to build with:
```
root module: sun4i_drm
modprobe: FATAL: Module sun4i_drm not found in directory /nix/store/86byp9ixv7yy94vaah92i926ff7i0068-linux-5.4.79-1.20201201-modules/lib/modules/5.4.79
``` 

CC @samueldr  

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module: installer/cd-dvd/sd-image-raspberrypi4.nix
```
