### ISSUE TITLE
hideProcessInformation breaks gdm on Wayland

### ISSUE THREAD

**Issue by benneti** [NixOS/nixpkgs#111629]
**Describe the bug**
enabling `security.hideProcessInformation = true;` and gdm at the same time leads to 
`org.gnome.Shell@wayland.service: Skipped due to 'exec-condition'.`
resulting in gdm falling back to xorg.

**To Reproduce**
1. `enable security.hideProcessInformation = true;` and `services.xserver.displayManager.gdm.enable = true;`
2. enable some wayland DE or WM like `services.xserver.desktopManager.gnome3.enable = true;`
3. reboot
4. Only X11 WM/DMs are available

**Expected behavior**
GDM should be setup according to the security setup or it should be documented that these two settings are incompatible.

**Additional context**
I tried to fix it by adding gdm to the proc group
`users.users.gdm.extraGroups = [ "proc" ];`
which worked half way.
Then gdm starts the wayland session, but I am not able to login.
For now I have disabled the `hideProcessInformation` and wayland works as expected.

Lastly I first thought my problem was related to https://github.com/NixOS/nixpkgs/issues/108672 but this was probably wrong.

**Notify maintainers**
@hedning
@jtojnar
@worldofpeace
@dasj19

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.7, NixOS, 21.03.20210117.68398d2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/nix/store/qh1497vqx38yl6qcpdgf83jd45i96ahi-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: security.hideProcessInformation
# a list of nixos modules affected by the problem
module: services.xserver.displayManager.gdm
```
