### ISSUE TITLE
pkgsStatic.gcc fails to compile

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#111882]
**Describe the bug**

`nix build -L nixpkgs.pkgsStatic.gcc`

https://gist.github.com/Atemu/dbc748ef0cdee57e9ca0dafe74665784

**Additional context**

Also broken on 20.09, 20.03 and even 19.09.

I was trying to build `pkgsStatic.borgbackup` and gcc seems to be a dependency via gdb.

Related but probably separate issue: https://github.com/NixOS/nixpkgs/issues/88956

**Notify maintainers**

@NixOS/exotic-platform-maintainers 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
