### ISSUE TITLE
Docker bypasses NixOS firewall exposing ports on the external interface

### ISSUE THREAD

**Issue by pjones** [NixOS/nixpkgs#111852]
Using `virtualisation.oci-containers.containers.<name>.ports` exposes ports on the external interface regardless of firewall settings.

Docker injects its own firewall rules, bypassing the NixOS firewall.

**To Reproduce**

Configure a container and use the `ports` option:

```nix
{
  virtualisation.oci-containers.containers.foo = {
    # Other settings here ...
    ports = [ "8123:8123" ];
  };

  networking.firewall = {
    enable = true;
    allowedTCPPorts = lib.mkForce [ ];
    allowedUDPPorts = lib.mkForce [ ];
  };
}
```

**Expected behavior**

1. Port 8123 on the host will forward to the same port on the container (this works)
2. Port 8123 on the host blocked from external access via the firewall (Docker is bypassing this)

**Additional context**

My `iptables` skills are lacking, but I think this rule, created by Docker, is the problem:

```
  -A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8123 -j ACCEPT
```

This was brought up in 2018 via #40507 but it looks like GitHub has deleted some comments and it's not clear why the issue was closed.

**Notify maintainers**

@adisbladis

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/store/3p4q8xc5y9kr57ysmd0s2s20s174pg23-a058d005b3cbb370bf171ebce01839dd6ff52222.tar.gz`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - virtualisation.oci-containers.containers
```
