### ISSUE TITLE
nixos-install: add option to *not* add `auto?trusted=1` to extra-substituters

### ISSUE THREAD

**Issue by jakobrs** [NixOS/nixpkgs#111947]
**Describe the ~~bug~~ feature request**
If installing NixOS from a slow installation medium, it can be *much* faster to install by downloading from `cache.nixos.org` even if it's already available in the installation medium's store. (from several minutes to several seconds)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: installer
```
