### ISSUE TITLE
zsh-prezto not building on x86_64-darwin nix-pkgs unstable

### ISSUE THREAD

**Issue by nagromLobo** [NixOS/nixpkgs#112253]
**Describe the bug**

It looks like builds of `zsh-prezto` still expect files to be in the root of `$out` instead of their new location (at least for builds on macOS 10.16).

**To Reproduce**

1. Update nix-channel to latest unstable on macOS 10.16
2. list `zsh-prezto` as a required package
3.  try to build (I noticed this failure when using `home-manager`), and notice that it expects files to be in the root of `$out` instead of the new location. 
I saw: 
```
error: opening file '/nix/store/5asnfm639ywhnycam5m4pcvhrgnkqmjd-zsh-prezto-unstable-2021-01-19/runcoms/zlogin': No such file or directory
```

**Expected behavior**

Install should complete as expected, and not fail on missing expected files. 

**Additional context**

This appears to be related to this change here: https://github.com/NixOS/nixpkgs/pull/111264

**Notify maintainers**

@holymonson 

**Metadata**

- system: `"x86_64-darwin"`
 - host os: `Darwin 20.2.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.9`
 - channels(nagromlobo): `"home-manager, nixpkgs-21.03pre268255.e5b478271ea"`
 - nixpkgs: `/Users/nagromlobo/.nix-defexpr/channels/nixpkgs`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- zsh-prezto
# a list of nixos modules affected by the problem
module:
```
