### ISSUE TITLE
Tickrs fails build on darwin

### ISSUE THREAD

**Issue by daizeng1984** [NixOS/nixpkgs#112338]
**Describe the bug**
Cannot build tickrs on darwin:
```
  cargo:warning=curl/lib/vtls/sectransp.c:45:10: fatal error: 'Security/Security.h' file not found
  cargo:warning=#include <Security/Security.h>
  cargo:warning=         ^~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit code: 1

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
```
**To Reproduce**
1. clone nixpkgs 
2. nix-build . -A tickrs

**Expected behavior**
Success

**Screenshots**
N/A
**Additional context**

**Notify maintainers**

@mredaelli

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.3.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(zdai): `"home-manager, nixpkgs-21.03pre265283.fd0daed2e8d"`
 - nixpkgs: `/Users/zdai/.nix-defexpr/channels/nixpkgs`
 - 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
tickrs
```
