### ISSUE TITLE
build rust package with non crates.io dependencies

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#11237]
@madjar @cstrahan @wizeman @globin @Havvy @wkennington 

I'm trying to use `buildRustPackage` with non crates.io dependencies without success.
In my `Cargo.toml` there are dependencies that point to repositories, e.g.

```toml
[dependencies.rusted_cypher]
version = "0.7.1"
git = "git://github.com/livioribeiro/rusted-cypher.git"
branch = "feature/rustc-serialize"
features = ["rustc-serialize"]  
```
This leads to `fatal: Not a git repository (or any of the parent directories): .git` :(
How can I fix this problem?
