### ISSUE TITLE
ceph: bluestore doesn't work

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#112589]
**Describe the bug**
Using ceph-volume to create a new bluestore-backed OSD doesn't work.

**To Reproduce**
1. ceph-volume lvm create --data /dev/sda --bluestore --no-systemd

**Expected behavior**

A new Bluestore OSD (on LVM) is successfully provisioned.

Switching RocksDB to the Ceph-bundled copy rather than the OS version makes it work. I note that the Ceph NixOS test uses filestore instead.

**Screenshots**

**Additional context**

**Notify maintainers**

@adevress @alexanderkjeldaas @johanot @krav 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/home/lukegb/depot/third_party/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ceph
# a list of nixos modules affected by the problem
module: ceph
```
