### ISSUE TITLE
Gimp fourier plugin is not working

### ISSUE THREAD

**Issue by jsravn** [NixOS/nixpkgs#112545]
**Describe the bug**
I'm adding gimp like this in 20.09:

`(gimp-with-plugins.override { plugins = with gimpPlugins; [ fourier ]; })`

However the fourier plugin is not being recognized. It should add:
* Filters/Generic/Forward FFT
* Filters/Generic/Inverse FFT

But these filters are missing.

**Expected behavior**
FFT plugin should be recognized by gimp.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
