### ISSUE TITLE
nixos/kmscon: services.kmscon.enable does not affect

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#112616]
**Describe the bug**
When `services.kmscon.enable = true;`, the system is expected to use kmscon instead of getty. However, `getty@tty1.service` is activated even if such configuration is deployed. Executing `systemctl start kmsconvt@tty1.service` manually launches kmscon as expected. I confirmed that `services.kmscon.hwRender = true;` does not change the behavior.

**To Reproduce**
1. Append `services.kmscon.enable = true;` to the system configuration.
2. Execute `nixos-rebuild boot`.
3. Reboot the system.

**Expected behavior**
The console is provided by kmscon instead of getty.

**Notify maintainers**
I am the current maintainer of kmscon package, though I have never modified NixOS kmscon module. Any suggestions are highly appreciated.
@xaverdh and @peterhoeg, as authors of non-treewide commits to the module.

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 5.4.95, NixOS, 21.03pre268835.8c8731330b5 (Okapi)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.10`
- channels(root): `"nixos-21.03pre268835.8c8731330b5"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nixpkgs.kmscon
# a list of nixos modules affected by the problem
module:
  - services.kmscon
```
