### ISSUE TITLE
PCIUtils out of date pci.ids

### ISSUE THREAD

**Issue by wiltaylor** [NixOS/nixpkgs#112644]
**Describe the bug**
pciutils is using a really old pci.ids file which doesn't include any definitions for AMD Radeon 6800 XT cards.

When running `lspci | grep VGA` you get the following output

```
0b:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 73bf (rev c1)
```

If you get a newer version of the file from https://pci-ids.ucw.cz/v2.2/pci.ids which update-pciids script in package normally updates (but is disabled in nix package). You get the following:

```
0b:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)
```

**Notify maintainers**
@vcunat

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.13, NixOS, 21.03.20210208.8c87313 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-20.09.1500.edb26126d98"`
 - channels(wil): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- pciutils
- hwdata
# a list of nixos modules affected by the problem
module:
```
