### ISSUE TITLE
Reduce closure size of mkShell

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#112633]
I'm currently in a place with low bandwidth internet and am experimenting with nix inside containers.
I noticed that every mkShell, even with empty buildInputs, pulls in a lot of dependencies which aren't really needed.
gcc for example is always present and bloats up the closure size.
Currently the minimum closure size of mkShell seems to be around 60 MB.

Would a PR be welcomed that reduces the default dependencies, by for example basing mkShell off of stdenvNoCC?

**Notify maintainers**

@zimbatm 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - mkShell
# a list of nixos modules affected by the problem
module:
```
