### ISSUE TITLE
Hydra with 500 Internal Server Error

### ISSUE THREAD

**Issue by bryanasdev000** [NixOS/nixpkgs#112969]
**Describe the bug**

[hydra.nixos.org](hydra.nixos.org) is returning error 500, log on home page:

```
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=hydra;host=10.254.1.9;user=hydra;','',...) failed: could not connect to server: Connection refused
Is the server running on host "10.254.1.9" and accepting
TCP/IP connections on port 5432? at /nix/store/rbx4maml998p56s3ilfwr6xz82bgd3vy-hydra-perl-deps/lib/perl5/site_perl/5.32.0/DBIx/Class/Storage/DBI.pm line 1517. at /nix/store/0k21rc23irjqhn6y8ahjqbb998jdgakh-hydra-0.1.20210202.bc12fe1/libexec/hydra/lib/Hydra/Helper/CatalystUtils.pm line 420
```

**To Reproduce**

1. Acess hydra.nixos.org
2. Profit

**Expected behavior**

A HTTP status code 200 and the list of jobs.

**Screenshots**

![Captura de tela_2021-02-13_03-47-30](https://user-images.githubusercontent.com/53131727/107843982-70d9ef80-6dae-11eb-97da-6d1d87c649cd.png)

**Additional context**

**Notify maintainers**

@grahamc @gilligan @zimbatm 

**Metadata**

Not relevant.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: hydra
```
