### ISSUE TITLE
Rustup reports incorrect version

### ISSUE THREAD

**Issue by iFreilicht** [NixOS/nixpkgs#113124]
**Describe the bug**

Rustup installed via nix reports the version `rustup 1.23.1 (1980-01-01)`, while rustup installed via [the official instructions](https://rustup.rs/) reports the version `rustup 1.23.1 (3df2264a9 2020-11-30)`.

**To Reproduce**
1. Install `rustup` with `nix-env -i rustup`
2. Make sure you're running the version from the store with `which rustup`
3. Run `rustup --version`
4. Output will be `rustup 1.23.1 (1980-01-01)`

**Expected behavior**
Rustup installed via nix should report the same version as rustup installed via rustup.rs.

**Notify maintainers**
@Mic92 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.15-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(felix): `"nixpkgs-21.03pre269202.66e66b9d481"`
 - nixpkgs: `/home/felix/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
