### ISSUE TITLE
NixOS display freezes on tty7 after boot on Dell Vostro 5402

### ISSUE THREAD

**Issue by DrFacepalm** [NixOS/nixpkgs#113196]
**NixOS display freezes on tty7 after boot on Dell Vostro 5402**
Upon entering nixos, (after stage 3 boot has completed with no issue), the tty7 terminal freezes and does not display a graphical user interface. I am attempting to use `gnome`/`plasma5` with `gdm`/`sddm`. I have attempted to load into a graphical user interface on:
* 20.03 graphical installer Plasma
* 20.09 graphical installer Gnome
* 20.09 graphical installer Plasma
* My personal `configuration.nix` using `gdm`, `sddm`, and `lightdm`

I am able to hit <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F1</kbd> to switch to a different terminal that does work however. 

I have used journalctl to try to diagnoise the issue on `gdm` and `sddm` to diagnose the issue as I believe this may be an issue with the X display manager, but I couldn't find anything conclusive. When using `gdm`, the only thing that seemed to bear any significance was the line:
```
systemd-logind: got pause for 13:64
```
I could not find anything too significant on `sddm` and `ligntdm` (and did not want to make this post 10 pages long) 

**To Reproduce**
1. Boot into the installed medium
2. Observe that tty7 is frozen.

**Expected behavior**
tty7 is not frozen, and I can enter a GUI.

**Additional context**
Out of curiosity, I tried to use a typical ubuntu installer to see if a Linux GUI would show up at all and it worked without issue. I had originally attributed my issue to my configuration.nix, but since the issue is occuring on the graphical installers too, I'm not too sure at this point.

**Notify maintainers**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: [
  services.xserver.gdm,
  services.xserver.sddm,
  services.xserver.lightdm
]
```
