### ISSUE TITLE
userActivationScripts do not run on login

### ISSUE THREAD

**Issue by chkno** [NixOS/nixpkgs#113240]
**Describe the bug**
Sometimes users find themselves in an environment where the `userActivationScripts` haven't run yet.

Unless you're doing unusual early boot stuff, the _system_ `activationScripts` have always already run.  It's a simple and useful invariant.  This is implemented by having them run both at startup and on `nixos-rebuild switch`.

The _user_ `userActivationScripts` currently only run at `nixos-rebuild switch`, so users often find themselves in an environment where their `userActivationScripts` haven't run yet — the time between system start-up and the first `nixos-rebuild switch` run — which is typically at least hours and can be indefinite.

`userActivationScripts` should have the same invariant as the system `activationScripts`: unless you're doing unusual early startup stuff, they have always already run.  The same implementation method makes sense: run them both at startup and on `nixos-rebuild switch`.  The user-analogy to startup is login, so userActivationScripts should run at login.

**To Reproduce**
1. Configure a userActivationScript.
2. Restart the machine.
3. Log in.

**Expected behavior**
The userActivationScript has run.

**Additional context**

**Notify maintainers**
@peterhoeg

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
 - system/activation/activation-script.nix
```
