### ISSUE TITLE
mysqltuner: add basic_passwords.txt

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#113517]
**Describe the bug**
When running mysqltuner, it says:

```
-------- Security Recommendations ------------------------------------------------------------------
...
[!!] There is no basic password file list!
```

So i suggest to add `basic_passwords.txt` to the package that in included in the projects repo.

https://github.com/major/MySQLTuner-perl/blob/master/basic_passwords.txt

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Notify maintainers**
@peterhoeg

**Metadata**
used with `nix run -f channel:nixos-unstable mysqltuner -c mysqltuner`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
