### ISSUE TITLE
traefik test warning: The option `docker-containers' defined in `<unknown-file>' has been changed to `virtualisation.oci-containers'

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#113884]
**Describe the bug**
```
[davidak@gaming:~/code/nixpkgs]$ nix-build nixos/tests/traefik.nix
trace: warning: The option `docker-containers' defined in `<unknown-file>' has been changed to `virtualisation.oci-containers' that has a different type. Please read `virtualisation.oci-containers' documentation and update your configuration accordingly.
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
