### ISSUE TITLE
pkgs.adguardhome has wrong platform attribute

### ISSUE THREAD

**Issue by CRTified** [NixOS/nixpkgs#113900]
**Describe the bug**

AdGuardHome has the meta platform `platforms.linux`, but is a [precompiled ELF binary for x86_64](https://github.com/NixOS/nixpkgs/blob/037936b7a307c7399cf0f3d9fabe37ea5b0b8534/pkgs/servers/adguardhome/default.nix#L8).

**To Reproduce**
Try to run `adguardhome` on `aarch64` (or any architecture other than `x86_64`). It will fail with `Exec format error`:

```
# nix-shell --pure -p adguardhome

[nix-shell:~]# adguardhome
bash: /nix/store/c08rij11vr8jcp5v2qcngr0mggzx34q9-adguardhome/bin/adguardhome: cannot execute binary file: Exec format error
```

**Expected behavior**

`adguardhome` should execute, so that it can be used.

**Notify maintainers**

@numkem 

**Metadata**

 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.92, NixOS, 21.03pre265961.891f607d530 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre265961.891f607d530"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - adguardhome
# a list of nixos modules affected by the problem
module:
```
