### ISSUE TITLE
config.wine.build referenced in all-packages but no module for it

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#114279]
**Describe the bug**
`config.wine.build` is referenced in all packages for the wine packages, but there's no way to set it's value

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
