### ISSUE TITLE
Thunderbird is broken

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#114204]
**Describe the bug**
thunderbird exits with

```
[1]    28100 bus error (core dumped)  thunderbird
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0, NixOS, 21.05.20210222.c7d0dbe (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/nix/store/875bj53v8fsaqvvdgfy3pr7l7ws1svdw-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: thunderbird
# a list of nixos modules affected by the problem
module:
```
