### ISSUE TITLE
sage: src/sage/finance/time_series.pyx  # 8 doctests failed

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#114446]
**Describe the bug**

Tests in `src/sage/finance/time_series.pyx` fails since 4082a4e50c7a92a042db9cbe904142a225239170, found by `git bisect` between 7cbec40a09533dd9c525d6ab94dddfe77768101a and 870dbb751f4d851a3dfb554835a0c2f528386982.
```
2 items had failures:
   2 of  16 in sage.finance.time_series.TimeSeries.autoregressive_fit
   6 of  21 in sage.finance.time_series.autoregressive_fit
    [343 tests, 8 failures, 9.75 s]
```

**To Reproduce**
1. `cd path/to/nixpkgs`
2. `nix-build -E 'with (import ./. {}); sage.tests.override { files = [ "src/sage/finance/time_series.pyx" ]; }'`

**Expected behavior**
The tests succeed.

**Notify maintainers**

@7c6f434c, @timokau and @omasanori (sage), @mweinelt (the mentioned commit)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-1160.11.1.el7.x86_64, CentOS Linux, 7 (Core)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ogino): `"nixpkgs-21.05pre272691.04ac9dcd311"`
 - nixpkgs: `/home/ogino/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - sage
# a list of nixos modules affected by the problem
module:
```
