### ISSUE TITLE
python3Packages.pandas: tests fail on master

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#114502]
**Describe the bug**
Build fails with the following single test failure:

```
=================================== FAILURES ===================================
__________________________ TestAccessor.test_from_coo __________________________

self = <pandas.tests.arrays.sparse.test_array.TestAccessor object at 0x7fff6d82a3a0>

    @td.skip_if_no_scipy
    def test_from_coo(self):
        import scipy.sparse

        row = [0, 3, 1, 0]
        col = [0, 3, 1, 2]
        data = [4, 5, 7, 9]
        sp_array = scipy.sparse.coo_matrix((data, (row, col)))
        result = pd.Series.sparse.from_coo(sp_array)

        index = pd.MultiIndex.from_arrays([[0, 0, 1, 3], [0, 2, 1, 3]])
        expected = pd.Series([4, 9, 7, 5], index=index, dtype="Sparse[int]")
>       tm.assert_series_equal(result, expected)
E       AssertionError: Attributes of Series are different
E       
E       Attribute "dtype" are different
E       [left]:  Sparse[float64, nan]
E       [right]: Sparse[int64, 0]

tests/arrays/sparse/test_array.py:1196: AssertionError
```

**Notify maintainers**

@7c6f434c @fridh @knedlsepp

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.pandas
# a list of nixos modules affected by the problem
module:
```
