### ISSUE TITLE
console.earlySetup does not build

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#114698]
**Describe the bug**
The following config fails during build:
```
{ config, lib, pkgs, ... }:
{
        console.earlySetup = true;
        console.keyMap = "de-latin1";
        console.font = "ter-v32b.psf.gz";
        console.packages = [ pkgs.terminus_font ];
}
```
```
'/nix/store/d1isq56iqbwwdj3fpa6clwc23scr1lxa-extra-utils/bin/fsck.ext4' -> 'e2fsck'
cp: missing destination file operand after '/nix/store/d1isq56iqbwwdj3fpa6clwc23scr1lxa-extra-utils/share/consolefonts/font.psf'
Try 'cp --help' for more information.
builder for '/nix/store/5dzsywbjgqzvd5mz6w91drpil7dfh69c-extra-utils.drv' failed with exit code 1
```

I may have a fix that I'm testing locally.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: console.earlySetup
# a list of nixos modules affected by the problem
module:
```
