### ISSUE TITLE
acme nixos test failure in apache httpd test cases

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#114751]
**Describe the bug**

The subtests for apache httpd in `nixosTests.acme` fail:

[i1dqvjb1zxy03kpv29b12bx4c4ay6yph-vm-test-run-acme.drv.log](https://github.com/NixOS/nixpkgs/files/6061849/i1dqvjb1zxy03kpv29b12bx4c4ay6yph-vm-test-run-acme.drv.log):

Removing these subtests makes the test pass:

https://github.com/NixOS/nixpkgs/blob/e72375464b32eac1d749e4905c17baf68320c73b/nixos/tests/acme.nix#L377-L392

**To Reproduce**
1. `nix-build -A nixosTests.acme`

**Expected behavior**

Test success.

**Screenshots**

**Additional context**

**Notify maintainers**

@NixOS/acme 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nixosTests.acme
# a list of nixos modules affected by the problem
module:
```
