### ISSUE TITLE
using Xorg + XFCE + xmodmap + .Xmodmap incurs constant Xserver load

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#114775]
**Describe the bug**
I installed the package `xorg.xmodmap` and populated the file `.Xmodmap` using ``, then modified keycode `107` to `dead_greek`, to use greek alphabet using my `PrtScr` key.

**To Reproduce**
1. Add `xorg.xmodmap` to the installed system packages, run `nixos-rebuild switch`
2. Populate `$HOME/.Xmodmap` using `xmodmap -pke > ~/.Xmodmap`
3. Modify some of the bindings. I modifed the line with `keycode 107` to `keycode 107 = dead_greek dead_greek dead_greek dead_greek`
4. At least after a reboot, and then login, the X server load stays at ~25% on my laptop.

**Expected behavior**
The X server load should not depend on the presence of `.Xmodmap`.

**Screenshots**
None.

**Additional context**
Normally, XFCE greets me with a message "bounced keys are disable", but this doesn't seem to be the case when I use `.Xmodmap`.

**Notify maintainers**
The file which contains the package is automatically generated. And it seems to be caused by a bad interaction between Xorg, XFCE and xmodmap.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 20.09.20210227.d303eee (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-20.09.3281.06b11191834"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  # I'm not sure if the following is correct
  - xfce.xfce4-settings
  - xorg.xmodmap
# a list of nixos modules affected by the problem
module:
```
