### ISSUE TITLE
oci-containers: `podman top` fails to find `nsenter`

### ISSUE THREAD

**Issue by jonas-schievink** [NixOS/nixpkgs#114877]
**Describe the bug**
`podman top` does not work on containers defined via `virtualisation.oci-containers`:

```
# podman top db6d407809d0
Error: error executing "nsenter -U -t 1 cat /proc/1/status": exec: "nsenter": executable file not found in $PATH
```

**To Reproduce**
1. Define any container in `virtualisation.oci-containers.containers` and set `virtualisation.oci-containers.backend = "podman";`
2. Make sure it's running
3. Run `podman top <container-id>` (or `--latest`)

**Expected behavior**
Output similar to this:

```
USER   PID   PPID   %CPU    ELAPSED       TTY   TIME   COMMAND
root   1     0      0.000   7.12211378s   ?     0s     sleep 10 
```

**Notify maintainers**

@NixOS/podman

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.79, NixOS, 21.05pre273435.0aeba64fb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre273435.0aeba64fb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- virtualisation.oci-containers
```
