### ISSUE TITLE
ldc 1.24.0 has stopped building on nixpkgs unstable

### ISSUE THREAD

**Issue by ralph-amissah** [NixOS/nixpkgs#114875]
**ldc 1.24.0 has stopped building on nixpkgs unstable**

the most recent version of ldc made available in nixpkgs fails to build
This version used to build, but has stopped doing so

**To Reproduce**
1. nix-channel --list # unstable https://nixos.org/channels/nixpkgs-unstable
2. nix-channel --update
3. nix-shell -p ldc

**Expected behavior**
ldc should build and be available

**Additional context**
I reproduce this behavior on all my nix boxen;
it is probably easiest to extract extensive build error messages on own system (they should be readily available).
If this assumption is incorrect, I will gladly provide further feedback.

**Notify maintainers**
cc @ThomasMader @lionello 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.1, NixOS, 21.05pre273435.0aeba64fb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(ralph): `"unstable-21.05pre272788.870dbb751f4"`
 - channels(root): `"nixos-21.05pre273435.0aeba64fb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- ldc
# a list of nixos modules affected by the problem
module:
```
