### ISSUE TITLE
D-Bus setup failed: Connection ":1.144" is not allowed to own the service "org.bluez" due to security policies in the configuration file

### ISSUE THREAD

**Issue by mario23174** [NixOS/nixpkgs#114964]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
