### ISSUE TITLE
Unlocking broken on GNOME Wayland

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#114906]
**Describe the bug**
On GNOME Wayland, unlocking the session does not work. I can type in my password and it is accepted, but I get sent back to the screen locker in an infinite loop.

**To Reproduce**
1. Enable the GNOME Wayland session
2. Lock the session
3. Attempt to unlock it by typing your password

**Expected behavior**
The session unlocks.

**Additional context**
[My configuration file](https://github.com/anna328p/configuration.nix)

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.17, NixOS, 21.05pre272646.99ac41b7023 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.05pre272646.99ac41b7023, home-manager"`
 - channels(anna): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
