### ISSUE TITLE
plexamp: no playback

### ISSUE THREAD

**Issue by Synthetica9** [NixOS/nixpkgs#114963]
**Describe the bug**
Plexamp opens fine, can connect to my library fine, but when I try to play anything the playback screen pops up for a second and then goes away again. The following message is printed to console:

```
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
```

Also reported upstream [here](https://forums.plex.tv/t/plexamp-on-linux-no-playback/695711).

**To Reproduce**
1. Open plexamp
2. (login if you haven't, but you need a paid plex pass for this)
3. Try to play anything

**Expected behavior**
Music playing

**Notify maintainers**
@killercup 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(synthetica): `"nixos-19.09pre179307.bc94dcf5002"`
 - nixpkgs: `/nix/store/asgzxf2rs3jv6qpm8fxvssh0zs02ac4k-nixos-unstable-2021-02-24-f6b5bfd`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [plexamp]
# a list of nixos modules affected by the problem
module: []
```
