### ISSUE TITLE
PyCharm is missing gcc

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#115103]
**Describe the bug**
When running PyCharm and you run something in debug mode a popup happens that asks if you want to install [Cython](https://www.jetbrains.com/help/pycharm/2020.3/cython-speedups.html?utm_source=product&utm_medium=link&utm_campaign=PY&utm_content=2020.3). The issue is that when installing the extension the PyCharm package has no gcc which causes it to fail. 

**To Reproduce**
1. Open PyCharm
2. Install Cython extension

**Expected behavior**
The plugin should install with no issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/6047658/109996677-bdf71480-7d0f-11eb-9bb9-4824ee8dca7b.png)

**Notify maintainers**
@edwtjo 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 21.05pre273435.0aeba64fb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre273435.0aeba64fb26, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute:
- jetbrains.pycharm-professional
- jetbrains.pycharm-community # Not sure the extension is available on the community version
module:
```
