### ISSUE TITLE
bash_5 fails on hydra but succeeds locally

### ISSUE THREAD

**Issue by NieDzejkob** [NixOS/nixpkgs#115177]
**Describe the bug**
[The most recent Hydra build of `bash_5`](https://hydra.nixos.org/build/137772726#tabs-summary) failed with

```
configure: WARNING: unrecognized options: --disable-static
building
build flags: -j2 -l2 SHELL=/nix/store/f7jzmxq9bpbxsg69cszx56mw14n115n5-bash-4.4-p23/bin/bash
cd . && autoconf
/nix/store/f7jzmxq9bpbxsg69cszx56mw14n115n5-bash-4.4-p23/bin/bash: autoconf: command not found
make: *** [Makefile:785: configure] Error 127
```

However, running `nix-build -A bash_5` succeeds and produces the store path `/nix/store/yqk7pzd398gxnd7ph6vbka7cm1hvb6ai-bash-5.1-p4` - exactly as listed on the Hydra page.

**Expected behavior**
The results should agree.

**Notify maintainers**
The package is maintained by @peti @dtzWill but I suspect there's something deeper at play here.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05pre272380.f6b5bfdb470 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(kuba): `"nixpkgs-21.05pre272380.f6b5bfdb470"`
 - channels(root): `"nixos-21.05pre272380.f6b5bfdb470"`
 - nixpkgs: `/home/kuba/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: bash_5 bashInteractive_5
# a list of nixos modules affected by the problem
module:
```
