### ISSUE TITLE
nixos-container start fails if tha container was built with flakes

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#115257]
**Describe the bug**
Given
```
#configuration.nix
{lib,pkgs,...}:{
  services.httpd={
    enable=true;
    adminAddr="root@localhost";
    virtualHosts.localhost={
      documentRoot= ./static ;
    };
  };
}

#flake.nix
{
  description = "A very basic flake";

  outputs = { self, nixpkgs }: {

    nixosConfigurations.container=
      nixpkgs.lib.nixosSystem{
        modules=[
          ./configuration.nix
          {boot.isContainer=true;}
        ];
        system = "x86_64-linux";
      };

  };
}
```
`nixos-container start work` will fail if built with `nixos-container create work --flake .` while it will succeed if built with `nixos-container create work --config-file configuration.nix`.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05.20210224.f6b5bfd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `""`
 - nixpkgs: `/nix/store/zfmxqr26bm36kmk22x2zsk0qbcd559qs-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
