### ISSUE TITLE
nextcloud-client: login not saved

### ISSUE THREAD

**Issue by benneti** [NixOS/nixpkgs#115383]
**Describe the bug**
Since https://github.com/NixOS/nixpkgs/pull/113731 nextcloud-client (installed via home-manager) fails to save my login.

**To Reproduce**
1. enable nextcloud service from home-manager
2. login
3. reboot
4. now you have to login again

**Expected behavior**
libsecret should save my credentials.

**Additional context**
adding an override that adds the qtwrapperargs back, fixes the problem for me
``` nix
final: prev: {
  nextcloud-client = (prev.nextcloud-client.overrideAttrs (o: rec {
    # does not find password
    # https://github.com/NixOS/nixpkgs/pull/113731
    # In case nextcloud will not remember passwords...
    qtWrapperArgs = [
      "--prefix LD_LIBRARY_PATH : ${prev.lib.makeLibraryPath [ prev.libsecret ]}"
    ];
  }));
}
```

**Notify maintainers**
@bryanasdev000 @caugner

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.2, NixOS, 21.05.20210306.102eb68 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/nix/store/9h81bjrghwldw5xl5yzdsigcj835c7qz-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nextcloud-client
# a list of nixos modules affected by the problem
module:
```
