### ISSUE TITLE
update to projectm broke clementine

### ISSUE THREAD

**Issue by marius851000** [NixOS/nixpkgs#115772]
**Describe the bug**
The clementine package broke on my system. After bisection, the fault seem to be caused by d035547ffa96f36b4b9685473b5975e2b093153f.

**To Reproduce**
1. ``git checkout d035547ffa96f36b4b9685473b5975e2b093153f``
2. ``nix build .#clementine`` or ``nix-build . -A clementine``
3. The build should fail

**Expected behavior**
Clementine compile successfully.

**Additional context**
I bisected this error. The error is caused by d035547ffa96f36b4b9685473b5975e2b093153f . I tested with the latest version of clementine, but I don't know what I should do: downgrade projectm, fix the clementine code (not sure I have enought knowledge), or open an issue on clementine and let clementine broken until an upstream update.

**Notify maintainers**
The package doesn't have any maintainers.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.18, NixOS, 21.05.20210309.4620b5a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.05pre274994.4d100429b57"`
 - channels(marius): `"home-manager, mariusnur, mlpnur, nur, ricenur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: clementine projectm
# a list of nixos modules affected by the problem
module:
```
