### ISSUE TITLE
PulseEffects on PipeWire frequently crashes when removing input device.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#115988]
**Describe the bug**

**To Reproduce**
1. Insert bluetooth headphones.
2. Start PulseEffects.
3. Disconnect bluetooth headphones.

Other programs also seem a little confused when audio devices appear or disappear however they don't tend to crash, they just don't see new devices generally.

**Additional context**
https://github.com/NixOS/nixpkgs/issues/102547

**Notify maintainers**
@jtojnar 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 21.05pre275232.29b0d4d0b60 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(kevincox): `""`
 - channels(root): `"nixos-21.05pre275232.29b0d4d0b60, nixpkgs-21.05pre271547.a964d7094a3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- pulseeffects-pw
module:
- services.pipewire
```
