### ISSUE TITLE
nixpkgs-unstable: options-docbook fails because of nextcloud18

### ISSUE THREAD

**Issue by clkamp** [NixOS/nixpkgs#116159]
**Describe the bug**
Recently nextcloud 18 was removed from nixpkgs, but it is still present in the related package list of nixos/modules/services/web-apps/nextcloud.nix. These related packages are evaluated when building the nixos-manpages/options-docbook which prevents a system from updating even without using nextcloud

**To Reproduce**
1. Use current nixos-unstable without having nextcloud enabled but have the manpages enabled
2. `nixos-rebuild switch`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nextcloud18
# a list of nixos modules affected by the problem
module: nextcloud
```

cc @Ma27
