### ISSUE TITLE
nix-env can't list out paths for pkgsCross.*

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nixpkgs#116207]
**Describe the bug**
I need to list the out paths of cross compiled packages beforehand which causes an eval error.

**To Reproduce**
```
$ nix-env -f . -qaP --attr pkgsCross.aarch64-multiplatform --out-path
error: attribute 'runtimeShell' missing, at nixpkgs/pkgs/top-level/all-packages.nix:524:7
```

**Expected behavior**
List all out paths like ``nix-env -f . -qaP --out-path``.

**Additional context**
I need this feature for nixpkgs-review when cross compiling.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-44-generic, Ubuntu, 20.10 (Groovy Gorilla)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(user): `"home-manager, nixpkgs-21.05pre273332.5df05c902cd"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
