### ISSUE TITLE
Unable to use a serial bluetooth device

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#116328]
**Describe the bug**
IIUC, one must use the `rfcomm` tool to allocate a serialport for a bluetooth device, for it work. However it seems that said `rfcomm` executable is not available in NixOS.

**Expected behavior**
`rfcomm` is available from the `bluez` package.

**Additional context**
 I suppose that a change in the expression of [`bluez`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/bluez/default.nix) would be sufficient to derive `rfcomm`. However, I'm not certain how this changed would look like. Maybe [this PR](https://github.com/NixOS/nixpkgs/pull/86677) might be a solution?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.18, NixOS, 20.09.3301.42809feaa9f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3301.42809feaa9f, nixos-unstable-21.05pre272380.f6b5bfdb470"`
 - channels(wucke13): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
