### ISSUE TITLE
overridding arguments to cudnn is difficult

### ISSUE THREAD

**Issue by cdepillabout** [NixOS/nixpkgs#116691]
**Describe the bug**

The way the CUDNN packages are defined makes it difficult to override any of the values.  This is due to the slightly weird interaction between how CUDNN uses `callPackages` and `callPackage`.

For instance, even though the CUDNN derivations take `fetchurl` as an argument, you can't override `fetchurl` in the CUDNN derivation:

```console
$ nix-build -E 'with import ./. {}; cudnn_cudatoolkit_11_2.override { fetchurl = fetchurl; }'
error: anonymous function at pkgs/development/libraries/science/math/cudnn/default.nix:1:1 called with unexpected argument 'fetchurl', at lib/customisation.nix:170:63
```

The above is run on commit e3c1c3b.

I explain why this happens, give a workaround, and suggest a fix in this comment: https://github.com/NixOS/nixpkgs/pull/115768#issuecomment-796397428

**Notify maintainers**

@mdaiter

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - cudnn
  - cudnnPackages
  - cudnn_cudatoolkit_11
  - cudnn_cudatoolkit_11_2
# a list of nixos modules affected by the problem
module:
```
