### ISSUE TITLE
murmur does not build

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#116618]
**Describe the bug**
murmur build breaks.

**To Reproduce**
1. nixos-rebuild switch

**Expected behavior**
nixos builds withour error

**Screenshots**
```
/nix/store/cp1sa3xxvl71cypiinw2c62i5s33chlr-binutils-2.35.1/bin/ld: cannot find -lre2
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile.Release:382: ../../release/murmurd] Error 1
make[2]: Leaving directory '/build/source/src/murmur'
make[1]: *** [Makefile:42: release] Error 2
make[1]: Leaving directory '/build/source/src/murmur'
make: *** [Makefile:504: sub-src-murmur-release_ordered] Error 2
builder for '/nix/store/ppdh8mm2xllldk6yw5ffg8xz749w82rr-murmur-1.3.4.drv' failed with exit code 2
```
**Notify maintainers**
@pstn 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre256292.296793637b2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.05pre276379.266dc8c3d05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  murmur
```
