### ISSUE TITLE
Night color is broken after updated to plasma 5.21

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#117036]
**Describe the bug**
Night color cannot be enabled and it shows an error message "Failed to connect to the Window Manager" on the settings panel.

**To Reproduce**
1. enable plasma and use kwin as the window manager (default)
2. open settings -> Display and Monitor -> Night Color

**Expected behavior**
Night color should work

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.7, NixOS, 21.05.20210319.f5e8bdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(root): `""`
 - nixpkgs: `/nix/store/mz372xs1z8r6b3337zs0qxkg0ffrbnn3-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
