### ISSUE TITLE
Vscode fails to install

### ISSUE THREAD

**Issue by miniBill** [NixOS/nixpkgs#117463]
**Describe the bug**
Vscode fails to install because `vscode-update.azurewebsites.net` no longer exists.

**To Reproduce**
1. `nix-shell -p vscode`

**Expected behavior**
Vscode gets downloaded

**Notify maintainers**
@Synthetica9 @eadwu 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 20.09.3398.f26c6ddc472 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(minibill): `"home-manager-20.09, unstable-21.05pre277486.f5e8bdd07d1"`
 - channels(root): `"nixos-20.09.3554.f8929dce13e, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
