### ISSUE TITLE
R fails to build with `fatal error: 'cairo-xlib.h' file not found`

### ISSUE THREAD

**Issue by idontgetoutmuch** [NixOS/nixpkgs#117715]
**Describe the bug**
`nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz -p R`
gives
`fatal error: 'cairo-xlib.h' file not found`

**To Reproduce**
1. See above

**Expected behavior**
I'd expect to get a shell in which I could run R

**Additional context**
https://github.com/NixOS/nixpkgs/issues/105310

**Notify maintainers**

@peti

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:9
 - system: `0`
 - host os: `Darwin 20.1.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(dom): `"nixpkgs-21.05pre278688.c0e88185200"`
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:1
 - nixpkgs: `0`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
