### ISSUE TITLE
If I want to open a Website/no matter what, this happens: Gah. Your tab just crashed.

### ISSUE THREAD

**Issue by SimSon05** [NixOS/nixpkgs#118085]
**Describe the bug**
If I want to open a Website/no matter what, this happens: Gah. Your tab just crashed.

**To Reproduce**
1. open Tor
2. go "in a Website/no matter what (google, yt,...)
3. Then comes the error

**Expected behavior**
That the mistake no longer happens

**Screenshots**
![Screenshot (198)](https://user-images.githubusercontent.com/73385668/113025012-b64c5380-9187-11eb-865e-445d2e9674c0.png)

**Additional context**

**Notify maintainers**

Don't work...

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
