### ISSUE TITLE
sshtunnel fails to build on aarch64-linux

### ISSUE THREAD

**Issue by furrycatherder** [NixOS/nixpkgs#118004]
**Describe the bug**
The Python package sshtunnel fails to build on aarch64-linux systems.

**To Reproduce**
```nix
let
  pkgs = import (builtins.fetchTarball {
    url =
      "https://github.com/NixOS/nixpkgs/archive/eb698b0979fb3e1f24cd85f8caf2b74a52845d8e.tar.gz";
    sha256 = "0c0pzrbqm5ijn36nklwxipg5b26xciqphdbwvlr7hckf90xay26g";
  }) {
    system = "aarch64-linux";
  };

in pkgs.python3Packages.sshtunnel
```

Logs [here](https://gist.github.com/furrycatherder/1ba4617b08a6f079e96d3e5700fc349e).

**Expected behavior**
The package should build successfully on aarch64-linux.

**Notify maintainers**

@jonringer

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-5-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(swim): `"nixos-20.03-20.03.3324.929768261a3, nixpkgs-21.05pre271336.ad4db3f4d8a"`
 - nixpkgs: `/home/swim/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.sshtunnel
# a list of nixos modules affected by the problem
module:
```
