### ISSUE TITLE
nextcloud-client fails to build on nixos-unstable

### ISSUE THREAD

**Issue by ethancedwards8** [NixOS/nixpkgs#118173]
**Describe the bug**
nextcloud-client fails to build.

**To Reproduce**
1. Be on nixos-unstable commit `04a2b269d8921505a2969fc9ec25c1f517f2b307`
2. Install nextcloud-client

**Expected behavior**
It should pull the package from Hydra or build on your machine.

**Additional context**
I'm using Flakes and not channels. My most recent channel update was probably never. I experienced this build upon updating my flake input.

**Notify maintainers**
@caugner @bryanasdev000 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

`nix shell nixpkgs#nix-info -c nix-info -m`

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.8, NixOS, 21.05.20210330.04a2b26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(ece): `""`
 - channels(root): `"nixos-21.05pre278406.d3f7e969b98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nextcloud-client
# a list of nixos modules affected by the problem
module:
```
