### ISSUE TITLE
Plasma Night Color is broken

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#118579]
**Describe the bug**
Plasma's Night Color feature is broken in X11 (and maybe Wayland, too) because the module cannot communicate with the window manager.

**To Reproduce**
1. Open `System Settings`.
2. Navigate to `Display and Monitor > Night Color`.
3. Observe.

**Expected behavior**
The Night Color module connects to the window manager.

**Screenshots**
![Screenshot_20210405_052326](https://user-images.githubusercontent.com/563054/113564620-4bf44280-95cf-11eb-8828-d3398ce24648.png)

**Notify maintainers**
@NixOS/qt-kde 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05.git.0afce22758a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/etc/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
