### ISSUE TITLE
Plasma System Settings does not display the NixOS logo

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#118580]
**Describe the bug**
The `System Information` tab in `System Settings` does not display the NixOS logo.

**To Reproduce**
1. Open `System Settings`.
2. Navigate to `System Information`.
3. Observe.

**Expected behavior**
The NixOS logo appears.

**Screenshots**
![Screenshot_20210405_052652](https://user-images.githubusercontent.com/563054/113564890-b86f4180-95cf-11eb-84a6-f3019f29495d.png)

**Notify maintainers**
@NixOS/qt-kde 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05.git.0afce22758a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/etc/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
