### ISSUE TITLE
Bad Magic bug running  nixos-sd-image-21.05pre279095.31e9d07ed15-aarch64-linux.img onto a Raspberry PI 4

### ISSUE THREAD

**Issue by quantumpotato** [NixOS/nixpkgs#118518]
**Describe the bug**
Bad magic booting up `nixos-sd-image-21.05pre279095.31e9d07ed15-aarch64-linux.img`

**To Reproduce**
sudo dd if=~/Downloads/nixos-sd-image-21.05pre279095.31e9d07ed15-aarch64-linux.img of=/dev/mmcblk0 bs=4096 status=progress
[sudo] password for home: 
2804445184 bytes (2.8 GB, 2.6 GiB) copied, 1 s, 2.8 GB/s
712305+0 records in
712305+0 records out
2917601280 bytes (2.9 GB, 2.7 GiB) copied, 1.05059 s, 2.8 GB/s

**Expected behavior**

**Screenshots**
![badmagic](https://user-images.githubusercontent.com/433852/113524820-3eaf6780-957f-11eb-80f3-0d2e0661c771.jpg)

**Additional context**
`nixos-sd-image-21.03pre262561.581232454fd-aarch64-linux.img of=/dev/mmcblk0` does boot successfully on the Raspberry PI 4.
So possibly this isn't a huge concern since that other build worked.

**Notify maintainers**

**Metadata**
N/A won't boot

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
