### ISSUE TITLE
Plasma Emoji Selector is broken

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#118577]
**Describe the bug**
The Plasma Emoji Selector is missing some components: the window appears "blank" or "empty" when opened:
![Screenshot_20210405_051801](https://user-images.githubusercontent.com/563054/113564142-7265ae00-95ce-11eb-931c-38ec1a2354b5.png)
It does not respond to key presses and the buttons in the side bar are not effective.

**To Reproduce**
1. Open Plasma session
2. Press <kbd>Meta + .</kbd> to open the Emoji Selector.

**Expected behavior**
The Emoji Selector will display and select emoji.

**Screenshots**
See above.

**Notify maintainers**
@NixOS/qt-kde 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05.git.0afce22758a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/etc/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
