### ISSUE TITLE
`electron-cash` failed to build on master

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#118692]
**Describe the bug**
`electron-cash` failed to build on master.

```
ERROR: Could not find a version that satisfies the requirement cryptography>=2.6; extra == "dnssec" (from dnspython[dnssec])
ERROR: No matching distribution found for cryptography>=2.6; extra == "dnssec"
```

**To Reproduce**
1. Checkout nixpkgs master 23f5b0961ec73c0574aa5df09b79e09880d1c7ab
2. `nix build .#electron-cash -L`

**Expected behavior**
It builds.

**Notify maintainers**

@Lassulus @nyanloutre

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.106, NixOS, 21.05.20210319.f5e8bdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(oxa): `"home-manager"`
 - nixpkgs: `/nix/store/mz372xs1z8r6b3337zs0qxkg0ffrbnn3-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- electron-cash
# a list of nixos modules affected by the problem
module:
```
