### ISSUE TITLE
LD_LIBRARY_PATH not set correctly,causing plasmasession to not start

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#118802]
**Describe the bug**
On latest nixos-unstable, the plasma session could not start without the following workaround:
```
environment.sessionVariables.LD_LIBRARY_PATH="/run/current-systyem/sw/lib";
```

**Notify maintainers**
@NixOS/qt-kde 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05.20210405.3d1a771 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `""`
 - nixpkgs: `/nix/store/sz015sc0y6adpacafc4zs35wf8364c6a-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
