### ISSUE TITLE
sayonara: Scripts missing interpreter

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#119420]
**Describe the bug**

The `sayonara-ctl` and `sayonara-query` python scripts in `bin` need their interpreter to be patched (and the `pydbus` module available).

```
[nix-shell:/dev/shm]$ sayonara-ctl 
/usr/bin/env: 'python3': No such file or directory
```

**To Reproduce**
1. `nix-shell -p sayonara --run sayonara-ctl`

**Expected behavior**

They should work :stuck_out_tongue:.

~~**Screenshots**~~
~~If applicable, add screenshots to help explain your problem.~~

~~**Additional context**~~
~~Add any other context about the problem here.~~

**Notify maintainers**

@deepfire 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-139-generic, Ubuntu, 18.04.5 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(bt1cn): `"nixpkgs-21.05pre281670.842f900e73c, nixgl, nixos-21.05pre270709.6b1057b452c"`
 - nixpkgs: `/home/bt1cn/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sayonara
# a list of nixos modules affected by the problem
module:
```
