### ISSUE TITLE
osu-lazer doesn't build on latest unstable

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#119591]
**Describe the bug**
`osu-lazer` refuses to be built on latest unstable, throwing some errors I cannot understand due to not having experience with the build system.

**To Reproduce**
Steps to reproduce the behavior: `NIXPKGS_ALLOW_UNFREE=1 nix build --impure nixpkgs/nixos-unstable#osu-lazer`

**Expected behavior**
obvious

**Screenshots**
n/a

**Additional context**
I am currently in process of bisecting Nixpkgs to see where the error was introduced. I will amend this bug report once I find the commit to blame.

**Notify maintainers**
cc @oxalica

**Metadata**
Latest unstable at the moment of writing was `e019872af81e4013fd518fcacfba74b1de21a50e`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - osu-lazer
# a list of nixos modules affected by the problem
module:
```
