### ISSUE TITLE
ostree errors: TLS support is not available

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#119634]
**Describe the bug**
When I try to pull from a remote repository using ostree, it fails.

Note that flatpak is not affected, just ostree.

**To Reproduce**
```sh
$ nix-shell -p ostree
$ mkdir foo
$ ostree --repo=foo init
$ ostree --repo=foo remote add flathub https://dl.flathub.org/repo/
$ ostree --repo=foo pull flathub org.freedesktop.Sdk/x86_64/20.08
error: TLS support is not available
```
**Expected behavior**
It would download the source files of org.freedesktop.Sdk (actually I'm not sure I'm doing that part right, but the TLS error seems like a Nix problem)

**Notify maintainers**
@copumpkin 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05pre281538.9e377a6ce42 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `"nixos-21.05pre281538.9e377a6ce42, nixos-hardware"`
 - channels(qolen): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ostree
# a list of nixos modules affected by the problem
module:
```
