### ISSUE TITLE
webpack requires webpack-cli and vice-versa

### ISSUE THREAD

**Issue by epigramengineer** [NixOS/nixpkgs#119768]
**Describe the bug**
Given webpack and webpack-cli installed from a synced unstable channel or stable (20.09) both claim to require the other to function.

**To Reproduce**

* Install nodePackages.webpack and nodePackages.webpack-cli from unstable channel. My exact pinned version with niv:

```
❯ niv show unstable
unstable
  homepage: 
  url: https://github.com/NixOS/nixpkgs/archive/f0efbe21f9ae1e17d1aca922708f1bdef605039d.tar.gz
  owner: NixOS
  branch: nixpkgs-unstable
  url_template: https://github.com/<owner>/<repo>/archive/<rev>.tar.gz
  repo: nixpkgs
  type: tarball
  sha256: 0d3xyihm9f7x43vbrs1hi2fxchqi7b5jrwvvc7swhjvva1cyax1n
  description: Nix Packages collection
  rev: f0efbe21f9ae1e17d1aca922708f1bdef605039d
```

**Expected behavior**
webpack and webpack-cli to function correctly

**Screenshots**

```
❯ webpack --version
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): no
You need to install 'webpack-cli' to use webpack via CLI.
You can also install the CLI manually.
❯ webpack-cli --version
[webpack-cli] It looks like webpack is not installed.
✔ Would you like to install 'webpack' package? (That will run 'yarn add -D webpack') (Y/n) · false
```

**Additional context**

* This appears to be the same as https://github.com/NixOS/nixpkgs/issues/42275 Not sure if I should re-open that one instead. If so apologies..

**Notify maintainers**
@dywedir 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 20.09.3719.0c7f43d5917 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels($user): `"nixos-20.09-20.09.2290.647cc06986c"`
 - channels(root): `"nixos-20.09.3719.0c7f43d5917, nixos-unstable-21.05pre279456.04a2b269d89"`
 - nixpkgs: `/nix/store/2ak8av2kbi3cdj1mf5sp9b96y4qr4vyh-unstable-src`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nodePackages.webpack nodePackages.webpack-cli
# a list of nixos modules affected by the problem
module:
```
