### ISSUE TITLE
Clang response files break ccache

### ISSUE THREAD

**Issue by Kha** [NixOS/nixpkgs#119779]
**Describe the bug**
https://github.com/NixOS/nixpkgs/pull/112449 hides clang arguments in a "response file" by default if `isClang` is true, but ccache does not support this and responds with "no input files" instead.

**Additional context**
The following workaround can be used to disable response files in a `ccacheWrapper` result `cc`, fixing the issue:
```nix
  cc.overrideAttrs (old: {
    installPhase = builtins.replaceStrings ["use_response_file_by_default=1"] ["use_response_file_by_default=0"] old.installPhase;
  })
```

**Notify maintainers**
@angerman 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ccacheWrapper ccacheStdenv
# a list of nixos modules affected by the problem
module: programs.ccache
```
