### ISSUE TITLE
bat-extras: fails in checkPhase on Darwin

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#119987]
**Describe the bug**
With the recent `bat-extras` update (#119689), the derivations fail during `checkPhase` on Darwin. This is due to the test framework using `getconf`, which seems to be present in the Linux stdenv but is not present in the Darwin stdenv.

This can be fixed by adding `getconf` to the `checkInputs` of both the `core` derivation and all `script` derivations.

Unfortunately I am not able to submit a PR at this time.

**To Reproduce**
1. On Darwin, run `nix-build --no-out-link -A bat-extras.batgrep '<nixpkgs>'`

**Expected behavior**
It should build

**Notify maintainers**

@bbigras

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre19700101_c235bed`
 - channels(root): `"nixpkgs-21.05pre283554.d9448c95c5d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- bat-extras.batdiff
- bat-extras.batgrep
- bat-extras.batman
- bat-extras.batwatch
- bat-extras.prettybat
# a list of nixos modules affected by the problem
module:
```
