### ISSUE TITLE
Failed to execute: 'mcomix'

### ISSUE THREAD

**Issue by Riey** [NixOS/nixpkgs#119936]
**Describe the bug**
Can't run mcomix3 via desktop file

**To Reproduce**
1. `nix-shell -p "dex" --run "dex $(nix-build -A pkgs.mcomix3)/share/applications/mcomix.desktop"`

**Expected behavior**
mcomix3 application started

**Screenshots**
![20210420184916](https://user-images.githubusercontent.com/14910534/115378455-871b8600-a20b-11eb-88e5-2f18f8ec726e.png)

**Notify maintainers**
@con-f-use 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mcomix3
# a list of nixos modules affected by the problem
module:
```
