### ISSUE TITLE
Qtcreator's clang plugins does not exist in unstable channel.

### ISSUE THREAD

**Issue by Thelta** [NixOS/nixpkgs#119959]
**Describe the bug**
qtcreator from unstable channel doesn't come with clang plugins even though default value of withClangPlugins is true. This problem doesn't exist in 20.09 channel.

**To Reproduce**
1. Download qtcreator from unstable channel. You can look which plugins are loaded from Help -> "About Plugins".

**Expected behavior**
Clang plugins namely ClangCodeModel, ClangFormat and ClangTools should be loaded.

**Notify maintainers**
@akaWolf

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.23-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ati): `"nixgl, nixpkgs-21.05pre283529.8389dcb67d9, nixpkgs-2009-20.09.3866.9a1672105db, nixpkgs-unstable-21.05pre283529.8389dcb67d9"`
 - nixpkgs: `/home/ati/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qtcreator
# a list of nixos modules affected by the problem
module:
```
