### ISSUE TITLE
gnome-terminal doesn't reliably refresh

### ISSUE THREAD

**Issue by eamsden** [NixOS/nixpkgs#120050]
**Describe the bug**
gnome-terminal often fails to refresh on nixos-unstable with nvidia drivers

**To Reproduce**
1. Install nixos-unstable with `boot.kernelPackages = pkgs.linuxPackages_latest` (currently, kernel 5.11.13), gnome/gdm, and nvidia drivers
2. Attempt to use e.g. nvim, but sometimes even `nix repl`, in gnome-terminal
3. The terminal will frequently display stale buffers, making e.g. editing files nearly impossible.

**Expected behavior**
The terminal display reflects the current state of the terminal application/terminal buffer

**Screenshots**

**Additional context**

**Notify maintainers**

@baracoder (nvidia_x11)
@hedning 
@jtojnar 
@worldofpeace 
@dasj19 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
