### ISSUE TITLE
Outputs seem to be writable during installCheckPhase

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#120053]
**Describe the bug**

Badly written packages can modify the outputs during `installCheckPhase`. Packages won't be writable after the derivation completes, so the install check is not representative

**To Reproduce**

1. `nix-build --expr 'with import ./. {}; stdenv.mkDerivation { name = "x"; dontUnpack = true; doInstallCheck = true; installPhase = "mkdir $out"; installCheckPhase = "echo a >$out/a"; }'`
2. observe that it succeeds
3. `cat result/a`
4. observe that the package has a file that _probably_ shouldn't exist

**Expected behavior**

The build fails because the program tried to write to an output.

In `nixpkgs` this could be achieved with `chmod a-w`, except for stubborn packages that try really hard to write to their installation. A paranoid implementation could hash the files and check afterwards. Finally, Nix itself could provide a feature to make an output read-only when the builder requests it. This may not work on all platforms though.

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - stdenv
# a list of nixos modules affected by the problem
module:
```
