### ISSUE TITLE
sshguard is not restarted when services.sshguard.services changes

### ISSUE THREAD

**Issue by pennae** [NixOS/nixpkgs#120282]
**Describe the bug**

sshguard is not restarted when services.sshguard.services changes, instead the old configuration is used until sshguard is restarted through some non-nixos-rebuild means

**To Reproduce**
1. enable services.sshguard with some value for services.sshguard.services
2. change services.sshguard.services
3. nixos-rebuild switch

**Expected behavior**

sshguard is restarted with the new services list passed to journalctl

**Screenshots**

n/a

**Additional context**

since the services list only affects the config file (not the systemd service) and the firewall backend does the same, this should also affect changes in the firewall backend. that probably doesn't matter though.

**Notify maintainers**

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.29, NixOS, 21.05pre282878.652749c4ca7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre282878.652749c4ca7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
