### ISSUE TITLE
Night colors don't work with KDE in NixOS 21.05

### ISSUE THREAD

**Issue by xfix** [NixOS/nixpkgs#120649]
**Describe the bug**
Night colors cannot be configured in KDE in NixOS 21.05. This did work correctly with NixOS 20.09. I'm using an NVIDIA graphics card.

**To Reproduce**
1. Use KDE in NixOS 21.05
2. Enter System Settings
3. Click "Display and monitor"
4. Click "Night color"

**Expected behavior**
Night color should be configurable.

**Screenshots**
![image](https://user-images.githubusercontent.com/1297598/116010077-334ed980-a61d-11eb-9cf9-c07379d6d886.png)

**Additional context**

**Notify maintainers**

@ttuegel

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.30, NixOS, 21.05pre283883.d235056d6d6 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre284379.93de027ee04"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: plasma5
```
