### ISSUE TITLE
Lutris has no icons in minimal DE setups

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#120708]
**Describe the bug**

When running lutris in a minimal DE such as none+i3, lutris has no icons for its various menus. You need to manually add a theme like `gnome3.adwaita-icon-theme` to your `systemPackages` and even then some are missing.

**To Reproduce**
1. Build VM with minimal DE (i.e. just the startx "desktopManager")
2. Run startx in VM
3. Run Lutris from one of the xterms

**Expected behavior**

Some form of icon should display by default.

**Screenshots**

**Additional context**

**Notify maintainers**

@Chiiruno (ミルク🎶)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
