### ISSUE TITLE
mbp2018-bridge build fails

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#120720]
**Describe the bug**

Upstream seem to have removed the release.

I hope they add it again.

```
builder for '/nix/store/i7rqvjkwwbfhrx8fnyip47fakaw9ld1l-source.drv' failed with exit code 1; last 8 log lines:
  
  trying https://github.com/MCMrARM/mbp2018-bridge-drv/archive/0.01.tar.gz
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   132  100   132    0     0    545      0 --:--:-- --:--:-- --:--:--   545
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (22) The requested URL returned error: 404 
  error: cannot download source from any mirror
```

Upstream issue: https://github.com/MCMrARM/mbp2018-bridge-drv/issues/22

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**
@hlolli 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
