### ISSUE TITLE
root coredumps warn "Cannot resolve systemd-coredump user"

### ISSUE THREAD

**Issue by pennae** [NixOS/nixpkgs#120803]
**Describe the bug**
when a root-owned process dumps core (eg recent sshd, due to a known bug) and coredumps are enabled, systemd-coredump warns `Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process` (but proceeds successfully).

**To Reproduce**
1. have systemd coredumps enabled
2. send a SIGABRT to any root-owned process (eg by running `timeout -s ABRT 1s cat`)

**Expected behavior**
coredumps succeeds with proper privsep

**Screenshots**

**Additional context**

**Notify maintainers**
@andir @edolstra @flokli @Kloenk 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.29, NixOS, 21.05pre282878.652749c4ca7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre282878.652749c4ca7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
