### ISSUE TITLE
Nix depends on openssl.bin

### ISSUE THREAD

**Issue by catern** [NixOS/nixpkgs#120948]
**Describe the bug**
openssl.dev depends on openssl.bin which bloats the closure size of Nix among other things.

**To Reproduce**
```
~/.local/src/nixpkgs $ nix-store --query --requisites $(nix-build -A openssl.dev) | grep openssl
/nix/store/5bg9dy337rp8r1mcc4cdrjwhw1kwmppj-openssl-1.1.1k
/nix/store/w99zrfcvxvh0y46sx8p6lbdjla4wdxnj-openssl-1.1.1k-bin
/nix/store/8iyzxj2ysxnknxc7jrldcsk2zzhv7ff1-openssl-1.1.1k-dev
```

**Expected behavior**
Not see -bin in the dependencies of openssl.

**Notify maintainers**
@peti 
@thefloweringash 
I believe this was introduce in https://github.com/NixOS/nixpkgs/commit/ef24a2815

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: openssl
# a list of nixos modules affected by the problem
module:
```
