### ISSUE TITLE
OpenCV with enableCuda and enableUnfree options doesn't build

### ISSUE THREAD

**Issue by Thelta** [NixOS/nixpkgs#121050]
**Describe the bug**
On current unstable branch, when enableCuda and enableUnfree options are true, openCV build fails. There are two reasons why:
1. Current opencv-cuda_opt_flow.patch is for 4.3.0 however since then opencv_contrib/cudaoptflow/CMakeLists.txt has been changed. 
2. In 4.5.2 opencv upped version of optical-flow-sdk to 2.0 which is a breaking change. Current optical-flow-sdk on nixpkgs is 1.0.

**To Reproduce**
1. You can use config below.
``` nix
{
    allowUnfree = true;
    packageOverrides = pkgs: 
    {
        opencv = pkgs.opencv.override {
                enableCuda = true;
                cudatoolkit = pkgs.cudaPackages.cudatoolkit_11_1;
                enableGStreamer = false;
                enableFfmpeg = false;
                enableGtk2 = false;
                enableGtk3 = false;
                enableUnfree = true;
            };
    };
}
```

**Notify maintainers**

@mdaiter @basvandijk

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.32-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ati): `"nixgl, nixpkgs-21.05pre283529.8389dcb67d9, nixpkgs-2009-20.09.3866.9a1672105db, nixpkgs-unstable-21.05pre283529.8389dcb67d9"`
 - nixpkgs: `/home/ati/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ "enableCuda",  "enableUnfree"]
# a list of nixos modules affected by the problem
module: "opencv"
```
