### ISSUE TITLE
Installing neovim with nix-env: Assertion failed: (size_ < capacity_), function push_back, file src/libexpr/attr-set.hh, line 54

### ISSUE THREAD

**Issue by gpanders** [NixOS/nixpkgs#121048]
**Describe the bug**

I'm trying to install `neovim` with `nix-env`:

```
$ nix-env -i neovim
installing 'neovim-0.4.4'
Assertion failed: (size_ < capacity_), function push_back, file src/libexpr/attr-set.hh, line 54.
```

**To Reproduce**
1. Install neovim with `nix-env -i neovim`

**Expected behavior**
Neovim installs successfully.

**Screenshots**
N/A

**Additional context**
I am able to install other packages. This is the first package that I've seen this happen with.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(greande): `"nixpkgs-21.05pre285827.267761cf444"`
 - nixpkgs: `/Users/greande/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: neovim
# a list of nixos modules affected by the problem
module:
```
