### ISSUE TITLE
assaultcube: should be unfree instead of zlib

### ISSUE THREAD

**Issue by yurkobb** [NixOS/nixpkgs#121381]
**Describe the bug**
The [assaultcube package](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/games/assaultcube/default.nix) states the license is zlib, however that seems to apply only to the game engine, not to the whole game. Per [website](https://assault.cubers.net/docs/license.html) (as [linked from the repo](https://github.com/assaultcube/AC#redistribution)) AssaultCube has a custom freeware license, prohibiting, among other things, commercial use. This package should be marked unfree. (Or can non-commercial can be considered `unfreeRedistributable`? I wouldn't risk.)

**Notify maintainers**
@bignaux 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: assaultcube
# a list of nixos modules affected by the problem
module:
```
