### ISSUE TITLE
Dynamically-sized EC2 image exceeds output size limit on Hydra

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#121354]
**Describe the bug**
For aarch64 (only, it seems), the amazonImage exceeds the output size limit on Hydra: https://hydra.nixos.org/build/142425973

This is channel-blocking.

**Notify maintainers**
@samueldr 
@grahamc 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
