### ISSUE TITLE
emacsPackages.* creates internal packages

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#121631]
**Describe the bug**
`emacsPackages.eglot` depends on `emacsPackages.project` (which shouldn't exist in first place, as it's a package shipped with emacs itself).

`emacsPackages.project` got depublished, so an emacs with `eglot` currently fails to build

**To Reproduce**
1. `nix-build -A emacsPackages.eglot`

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
