### ISSUE TITLE
nixos/unbound: Impossible to specify multiple "include" directives.

### ISSUE THREAD

**Issue by pmeiyu** [NixOS/nixpkgs#121878]
**Describe the bug**

Unbound allows the "include" directive to appear more than once. [man5/unbound.conf.5](https://manpages.ubuntu.com/manpages/bionic/man5/unbound.conf.5.html):
```
Files can be included using the include: directive. It can appear anywhere, it  accepts  a single  file name as argument.
```

However the type definition of `services.unbound.settings` is too strict. This code raises an error:
```
services.unbound.settings.include = [ "a" "b" "c"];
```
```
error: A definition for option `services.unbound.settings.include.[definition 1-entry 1]' is not of type `attribute set of signed integer or string or boolean or floating point number or list of signed integer or string or boolean or floating point numberss'.
```

**Notify maintainers**

@rissson 

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.unbound
```
