### ISSUE TITLE
mpich: broken on mac

### ISSUE THREAD

**Issue by nbren12** [NixOS/nixpkgs#121978]
**Describe the bug**
mpich is broken on mac

**To Reproduce**
`nix-build -A mpich`
from nixpkgs root.

**Expected behavior**

mpich installs

**Additional context**

d47f08d78521f0c0bd27e8fbae34590a27fda6af updated mpich, and made it require one of two communication backends (ucw or libfabric). Neither of these are currently successfully building on Darwin. libfabric appears to be the default, but it depends on a Linux-only package `numactl`, I'm not sure why ucw fails.

Maybe mpich builds without either of these?

**Notify maintainers**

@markuskowa

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
