### ISSUE TITLE
scikit: random segmentation faults in hydra (

### ISSUE THREAD

**Issue by nbren12** [NixOS/nixpkgs#121988]
**Describe the bug**

Hydra builds for scikitlearn give a segmentation fault intermittently in [darwin](https://hydra.nixos.org/build/141980325/nixlog/2) and [linux](https://hydra.nixos.org/build/138158666).

The issue happens 100% of the time for Darwin, but only rarely for Linux, and occurs about 72% of the way through the test suite. Since it's a segfault, the offending test is not shown. I suspect we'll need to enable verbose logging to figure out which test to disable.

**To Reproduce**

Unfortunately (?), the builds work locally in a sandbox so this seems specific to the hydra environment, which I have no idea how to debug.

**Expected behavior**

scikitlearn builds in hydra and is in the cache.

**Notify maintainers**

@rmcgibbo 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
