### ISSUE TITLE
Qemu 6.0.0 needs `codesign` on darwin

### ISSUE THREAD

**Issue by layday** [NixOS/nixpkgs#121903]
**Describe the bug**
Qemu 6.0.0 builds fail on darwin because the `codesign` executable is not available in the build environment.  You can observe this on Hydra: https://hydra.nixos.org/build/142456539/nixlog/1

**To Reproduce**
1. `nix-env -i qemu`

**Notify maintainers**
@eelco @alyssais 

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(layday): `"nixpkgs-21.05pre287094.c5173fe2085"`
 - nixpkgs: `/Users/layday/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
