### ISSUE TITLE
XEmbed tray icons on MATE became broken

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#122053]
**Describe the bug**
One of recent packages updates broke XEmbed tray icons on MATE, they lost transparency and have other graphical artifacts. SNI tray icons displayed by the same applet seem to work fine at the same time.

**To Reproduce**
1. Install MATE on NixOS unstable
2. Probably nothing else?

**Expected behavior**
No graphical artifacts

**Screenshots**
![изображение](https://user-images.githubusercontent.com/17829319/117485409-dd9cfa00-af57-11eb-80e1-d2e7909c8ac4.png)

**Notify maintainers**
@romildo

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16-zen1, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/run/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mate.mate-panel
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.mate
```
