### ISSUE TITLE
Document how to use cargo-binutils ?

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#122166]
@Stupremee  sorry to bother you with this. Is there a way to document how to use cargo-binutils ?
I added it to may `buildInputs` inside `mkShell`, but `cargo size` still says
```
Failed to execute tool: size
No such file or directory (os error 2)
```

**To Reproduce**
1. add `cargo-binutils` inside a buildInputs of a mkShell
2. call `cargo size`

**Expected behavior**
no error output

**Screenshots**

**Additional context**
let me know if I'm doing something wrong here.
Maybe the ideal thing would be to add something in the description?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
