### ISSUE TITLE
nixosTests.blockbook-frontend fails to build

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#122215]
nixosTests.blockbook-frontend fails to build

Discovered in https://github.com/NixOS/nixpkgs/pull/122201#issuecomment-835426167

Refs #122042 

**Notify maintainers**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixosTests.blockbook-frontend
# a list of nixos modules affected by the problem
module:
```
