### ISSUE TITLE
nixosTests.privacyidea does not evaluate

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#122250]
**Describe the bug**

```
nix-build -A nixosTests.privacyidea
attribute 'privacyidea' missing, at /home/user/h/nixpkgs/nixos/modules/services/security/privacyidea.nix:10:37
```

**To Reproduce**

```
nix-build -A nixosTests.privacyidea
```

**Expected behavior**

**Screenshots**

**Additional context**

#122042 

**Notify maintainers**

@Ma27 @globin 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixosTests.privacyidea
# a list of nixos modules affected by the problem
module:
```
