### ISSUE TITLE
cypress: EACCESS when running project in browser

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#122425]
**Describe the bug**

**To Reproduce**
1. Have a project with `pkgs.cypress` in its nix-shell
2. Run the `Cypress` executable in the nix-shell
3. Observe error message:

-----

**Title:** Error launching browser

**Message:** EACCES: permission denied, open '/home/user/.config/Cypress/cy/production/browsers/chromium-stable/interactive/CypressExtension/background.js'

**Stack trace:**
```
Error: EACCES: permission denied, open '/home/user/.config/Cypress/cy/production/browsers/chromium-stable/interactive/CypressExtension/background.js'


```

-----

**Expected behavior**

Cypress runs the project without error.

**Screenshots**

**Additional context**

It appears that cypress is copying read-only files from the Nix store.

Normally, it would copy from `node_modules`, which is expected to be ~messy~ writable.

This problem occurs regardless of whether `node_modules` is normal or a symlink to yarn2nix output.

**Notify maintainers**

@thorstenweber83
@mmahut

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cypress
# a list of nixos modules affected by the problem
module:
```
