### ISSUE TITLE
fetchpatch: missing documentation

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#122538]
Currently debugging a failing fetchpatch and noticing that none of the optional arguments like `extraPrefix` or `excludes` are documented.

**Notify maintainers**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
  - fetchpatch
# a list of nixos modules affected by the problem
module:
```
