### ISSUE TITLE
Boinc crashes on startup,too many levels of symbolic links

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#122685]
**Describe the bug**
Boinc crashes on startup with error
`  bind_mount: mount(source, target, NULL, MS_BIND | MS_REC, NULL): Too many levels of symbolic links`

**To Reproduce**
1. `services.boinc.enable=true`
2. reboot
3. `systemctl status boinc`

**Expected behavior**
For the boinc daemon to work as expected

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16, NixOS, 21.05.20210506.6358647 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - nixpkgs: `/nix/store/mzi2dvks0a52mmbhgxc43nlxa4pi6r7p-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
