### ISSUE TITLE
zsh-powerlevel10k does not provide the p10k executable

### ISSUE THREAD

**Issue by devins2518** [NixOS/nixpkgs#122783]
**Describe the bug**
In the instructions for [powerlevel10k](https://github.com/romkatv/powerlevel10k), it says to use `p10k configure` to configure the prompt after installing. The package `zsh-powerlevel10k` doesn't provide this executable.

**To Reproduce**
1. `nix-shell -p zsh-powerlevel10k`
2. `zsh`
3. `p10k configure` <- errors

**Expected behavior**
`p10k configure` should provide the setup for the prompt, but it isn't found even if the package is installed.

**Additional context**
I've tried this on 20.09 and unstable, and neither have worked. I might be doing something wrong, but I can't figure out what.

**Notify maintainers**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.32, NixOS, 21.05pre287596.ae1c8ede09b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre287596.ae1c8ede09b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
