### ISSUE TITLE
extraGSettingsOverridePackages does not work for gnome extensions

### ISSUE THREAD

**Issue by mschuwalow** [NixOS/nixpkgs#123235]
**Describe the bug**
services.xserver.desktopManager.gnome.extraGSettingsOverrides cannot be used to override settings for extensions. When you try to add them to extraGSettingsOverridePackages rebuilding will fail as the schemas are in a different location than assumed here https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/x11/desktop-managers/gnome.nix#L33

**To Reproduce**
1. Add gnome extensions to services.xserver.desktopManager.gnome.extraGSettingsOverridePackages
2. Attempt to rebuild the system configuration

**Expected behavior**
The gsettings schemas of the extension are picked up and I can use extraGSettingsOverrides to configure the defaults.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.20, NixOS, 21.05.20210513.78632af (Okapi)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-20.03.3191.504f993df9a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- services.xserver.desktopManager.gnome
```
