### ISSUE TITLE
OfBorg does not run nix-build -A tests

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#123369]
**Describe the bug**

Problems like #123368 go unchecked.

**NB**: this is _not_ `passthru.tests`, but `pkgs.tests` aka `pkgs/tests`

**To Reproduce**
1. Break a test in pkgs/tests
2. Create a PR
3. Observe that OfBorg does not fail

**Expected behavior**
OfBorg evaluates the `tests` attribute as well.

This *may* be achievable with `recurseIntoAttrs`. I'm not intimately familiar with OfBorg.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tests
# a list of nixos modules affected by the problem
module:
```
