### ISSUE TITLE
julia_10-bin, julia_16-bin: add x86_64-darwin support

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#123394]
**Describe the bug**
Now that https://github.com/NixOS/nixpkgs/pull/123188 has landed, we have derivations for binary releases of julia versions 1.0.x and 1.6.x on x86_64-linux. It would be nice to expand platform support for these derivations, esp. for x86_64-darwin since that's what I have access to and use frequently.

I've taken a hacky first stab at this already: https://gist.github.com/samuela/257b66127bceffcc11453a6992a92d3d. Unfortunately, it gets hung up on test failures bc of nix's strict build environment:
```
        From worker startup:    ERROR: IOError: bind: operation not permitted (EPERM)
```
I'm honestly not sure what the fix for this is. Removing the patch here (https://gist.github.com/samuela/257b66127bceffcc11453a6992a92d3d#file-1-6-bin-nix-L29) doesn't make any difference.

If anyone has any ideas, please do let me know!

**Notify maintainers**

cc @ninjin @raskin

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: julia_10-bin julia_16-bin
# a list of nixos modules affected by the problem
module:
```
