### ISSUE TITLE
Mesa 21.0: VAAPI recording broken

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#123446]
**Describe the bug**

VAAPI records repeated frames (see upstream bug report).

upstream fix: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9995

**To Reproduce**
1. ... open OBS
2. ... try recording using VAAPI (possible AMD hardware required?)
3. ... watch replay

**Expected behavior**
full FPS.

**Notify maintainers**

@primeos @vcunat 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
