### ISSUE TITLE
phosh: PIN unlock issue

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#123435]
**Describe the bug**

The phosh lockscreen will accept any pin.

**To Reproduce**
1. Start phosh
2. Lock screen
3. Unlock with 1 even if it isn't your pin!

**Expected behavior**
Probably use the numeric password of the user

**Notify maintainers**

@zhaofengli 

@NixOS/gnome 

**Solution**

The PAM configuration seems to be at fault.

I can't PAM my way out of a paper bag, but I tried one attempt:

```
auth       include      xscreensaver
account    include      xscreensaver
session    include      xscreensaver
```

Why `xscreensaver`?

Here's why:

 - https://gitlab.manjaro.org/manjaro-arm/packages/community/phosh/phosh/-/blob/master/pam_phosh
 - https://github.com/NixOS/nixpkgs/search?q=system-local-login

That doesn't explain the issue. Only a plausible fix. With this, only the user password is accepted.

We should get someone who understand PAM to look at this.

**Metadata**

Ran on top of 83d907fd760d9ee4f49b4b7e4b1c6682f137b573.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: phosh
# a list of nixos modules affected by the problem
module: phosh
```
