### ISSUE TITLE
pywemo fails to build after libxml2 upgrade

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#124165]
**Describe the bug**
After d01a4e3fe99cdc9f4015e741edfd3c77a5d90a37 pywemo fails a test.

```
_________________________ test_bridge_getdevicestatus __________________________

bridge = <WeMo Bridge "WeMo Device", Lights: 1, Groups: 0>

    @pytest.mark.vcr()
    def test_bridge_getdevicestatus(bridge):
        status = bridge.bridge_getdevicestatus(LIGHT_ID)
        expected = b''.join(
            [
                b'<DeviceStatus>',
                b'<IsGroupAction>NO</IsGroupAction>',
                b'<DeviceID available="YES">0017880108DA898B</DeviceID>',
                b'<CapabilityID>10006,10008,30008,30009,3000A</CapabilityID>',
                b'<CapabilityValue>0,255:0,,,</CapabilityValue>',
                b'<LastEventTimeStamp>0</LastEventTimeStamp>',
                b'</DeviceStatus>',
            ]
        )
>       assert et.tostring(status) == expected
E       AssertionError: assert b'<DeviceStat...ceStatusList>' == b'<DeviceStat...DeviceStatus>'
E         Use -v to get the full diff

tests/ouimeaux_device/test_bridge.py:53: AssertionError
```

**To Reproduce**
1. nix-build -A python3Packages.pywemo

**Notify maintainers**
@fabaff 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.pywemo
# a list of nixos modules affected by the problem
module:
```
