### ISSUE TITLE
weechat-matrix script cannot find `matrix_sso_helper` binary

### ISSUE THREAD

**Issue by arachnist** [NixOS/nixpkgs#124186]
**Describe the bug**
weechat-matrix script cannot find the `matrix_sso_helper` helper binary that's used when logging in to matrix homeservers that require sso

**To Reproduce**
1. Add an override to weechat to add `weechat-matrix` weechat script
```
    (self: super: {
      weechat = super.weechat.override {
        configure = { availablePlugins, ... }: {
          scripts = with super.weechatScripts; [ weechat-otr weechat-matrix multiline ];
        };
      };
    })
```
2. Try logging in to a homeserver that requires SSO

**Actual results**
Weechat prints a message:
```
203055     weechat     │ stderr: Error with command 'matrix_sso_helper'
```

**Expected behavior**
weechat-matrix should print a link that user's supposed to click in browser

**Notify maintainers**
@tilpner @emilazy 
@lovek323 @lheckemann

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05pre291486.900115a4f7f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: weechat weechatScripts.weechat-matrix
# a list of nixos modules affected by the problem
module:
```
