### ISSUE TITLE
ath11k_pci broken on 5.11.21

### ISSUE THREAD

**Issue by krgn** [NixOS/nixpkgs#124340]
**Describe the bug**

The built-in wifi driver
https://bugzilla.redhat.com/show_bug.cgi?id=1960564

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
