### ISSUE TITLE
Some tree-sitter grammars fail to build on darwin

### ISSUE THREAD

**Issue by sandhose** [NixOS/nixpkgs#124396]
**Describe the bug**
`tree-sitter` grammars that have a C++ scanner ([`src/scanner.cc`](https://github.com/tree-sitter/tree-sitter-bash/blob/master/src/scanner.cc)) fail to build on darwin because `$CC` is used to build them instead of `$CXX`. It complains about missing C++ headers like `<string>` and `<vector>`.

**To Reproduce**
1. Try to build `tree-sitter.builtGrammars.tree-sitter-bash` on Darwin
`nix build 'nixpkgs#tree-sitter.builtGrammars.tree-sitter-bash'`

**Expected behavior**
`tree-sitter` grammars should all build on darwin.

**Additional context**

I've fixed the issue in my config by overriding the `buildPhase` in the derivation like this:
https://github.com/sandhose/nixconf/blob/949ed0b6f1b7a1bc8a464105a6dffefbf24d362b/profiles/home-manager/vim/default.nix#L51-L69

Compared to the current `buildPhase`: 
https://github.com/NixOS/nixpkgs/blob/8f5c32af534d299f0ac104495db0aacbdcb2861a/pkgs/development/tools/parsing/tree-sitter/grammar.nix#L34-L46

**Notify maintainers**
@Profpatsch @teto 

**Metadata**

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20201118_79aa7d9`
 - channels(sandhose): `"darwin, home-manager, nixpkgs-21.03pre255596.b6bca3d8061"`
 - channels(root): `"nixpkgs-20.09pre244244.4b30f5ca85d, darwin, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- pkgs.tree-sitter
- pkgs.tree-sitter.builtGrammars.tree-sitter-bash
- pkgs.tree-sitter.builtGrammars.tree-sitter-cpp
- pkgs.tree-sitter.builtGrammars.tree-sitter-html
- pkgs.tree-sitter.builtGrammars.tree-sitter-markdown
- pkgs.tree-sitter.builtGrammars.tree-sitter-php
- pkgs.tree-sitter.builtGrammars.tree-sitter-python
- pkgs.tree-sitter.builtGrammars.tree-sitter-ruby
- pkgs.tree-sitter.builtGrammars.tree-sitter-yaml
# a list of nixos modules affected by the problem
module:
```
