### ISSUE TITLE
virt-install cannot find mkisofs

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#124386]
**Describe the bug**
invoking virt-install with the cloud-init images results in `ENOENT`

a workaround is `nix-shell -p cdrtools`

**To Reproduce**
1. run `virt-install --connect qemu:///system --memory 4000 --cloud-init root-password-generate=on --disk https://cloud.debian.org/images/cloud/bullseye/daily/20210525-648/debian-11-genericcloud-amd64-daily-20210525-648.qcow2`
2. `ERROR    [Errno 2] No such file or directory: 'mkisofs'`

**Expected behavior**
virt-install should proceed

**Screenshots**
NA

**Additional context**
It should probably be enough to add cdrtools to `makeBinPath`

**Notify maintainers**
@qknight @offlinehacker @fpletz @globin 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.20210525.bc71efa (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `""`
 - channels(louis): `""`
 - nixpkgs: `/nix/store/df9dwmlgkx5br42g8md9nfcy6l0cbc57-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
