### ISSUE TITLE
Installation of `pinentry` with "curses" flavour fails with due to missing `cairo-xlib` package

### ISSUE THREAD

**Issue by antoineco** [NixOS/nixpkgs#124753]
**Describe the bug**

While attempting to install `pinentry` with the "curses" flavor, the build fails with

```
configure: error: Package requirements (cairo-xlib >= 1.6) were not met:

No package 'cairo-xlib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CAIRO_BACKEND_CFLAGS
and CAIRO_BACKEND_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**To Reproduce**

1. Set `programs.gnupg.agent.pinentryFlavor = "curses";` in `configuration.nix`
2. Run `sudo nixos-rebuild switch`

**Expected behavior**

The build succeeds.

**Screenshots**

\-

**Additional context**

Side note / question: I'm new to Nix/NixOS, but I'm wondering why a build is required at all, since `nixos.pinentry_curses` is available (`nix-env -iA nixos.pinentry_curses`).

**Notify maintainers**

@ttuegel @fpletz

**Metadata**

```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.128-microsoft-standard, NixOS, 20.09.4209.05f3800b80f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-20.09.4209.05f3800b80f"`
 - channels(acotten): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: <nixpkgs/nixos/modules/programs/gnupg.nix>
```
