### ISSUE TITLE
nixFlakes fails to build on aarch64-darwin

### ISSUE THREAD

**Issue by purcell** [NixOS/nixpkgs#124814]
**Describe the bug**

nixFlakes doesn't build on this system type, which then blocks other dependent tools from building, e.g. the nix-direnv module integration.

**To Reproduce**

1. On an M1 machine using the nixpkgs-unstable channel, check out nixpkgs master (currently 976ee287c863520e0fae4518b51d1e254a732bc2 for me)
2. `nix-build --argstr localSystem aarch64-darwin -A nixFlakes`

**Expected behavior**

Successful build.

**Screenshots**

```
  CXX    src/resolve-system-dependencies/resolve-system-dependencies.o
  GEN    scripts/nix-http-export.cgi
  CXX    src/libcmd/markdown.o
  GEN    scripts/nix-profile.sh
  GEN    scripts/nix-reduce-build
  GEN    doc/manual/nix-env.1
lowdown: sandbox_init: Operation not permitted
make: *** [doc/manual/local.mk:28: doc/manual/nix-env.1] Error 1
make: *** Waiting for unfinished jobs....
builder for '/nix/store/pv51gkfqicxdib8c26plmjg7mphknnbz-nix-2.4pre20210503_6d2553a.drv' failed with exit code 2
```

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nixFlakes
# a list of nixos modules affected by the problem
module:
```
