### ISSUE TITLE
signal-desktop cannot open links in the browser

### ISSUE THREAD

**Issue by jmc-figueira** [NixOS/nixpkgs#124901]
**Describe the bug**
In the latest version (5.3.0) and at least since 5.2.1, I cannot open links in Firefox by clicking them.

This is similar to #78961, however, I have checked that the `nss` packages between Firefox and Signal are the same, using `nix path-info $(which signal-desktop) -r | grep nss-` as described in the wiki article regarding the Discord issue (notably, Discord is also correctly using the same `nss` package and links open properly.

At first I thought it might have been due to using the experimental Wayland support, which also breaks non-text copying and pasting (images, for instance), but running Signal through XWayland results in the same issue.

**To Reproduce**
1. Install `signal-desktop` from the `unstable` channel
2. Try to click a link to open it in the browser
3. The link does not open in the browser

**Expected behavior**
The link should open in the browser

**Screenshots**
N/A

**Additional context**
Running on NixOS 21.11 (unstable), both with the `--enable-features=UseOzonePlatform --ozone-platform=wayland` experimental backend and with the "stable" X backend through XWayland; the result is the same.

**Notify maintainers**
@primeos 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 21.11pre292520.540dccb2aea (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.11pre292520.540dccb2aea, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: <nixpkgs/pkgs/applications/networking/instant-messengers/signal-desktop/default.nix>
# a list of nixos modules affected by the problem
module:
```
