### ISSUE TITLE
Cannot `import lldb` in lldb anymore

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#125183]
**Describe the bug**
After #111487, `import lldb` in lldb results in a ModuleNotFoundError.

`vscode-extensions.vadimcn.vscode-lldb` is affected by this issue (#119945)

**To Reproduce**
1. On current master, `nix-shell -p lldb_12` (Seems all versions of `lldb` are affected, but I only checked 11 and 12.)
2. `lldb`
3. `script import lldb`, see the error.

**Expected behavior**
Module successfully imported.

**Additional context**
Note that in `lldb_12.out`, `lib/python3.8/site-packages/lldb` DOES exist. Not sure why it failed to import.

**Notify maintainers**

@Ericson2314 @lovek323 @7c6f434c @dtzWill @primeos 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.11.20210528.540dccb (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(oxa): `"home-manager"`
 - nixpkgs: `/nix/store/49d2fsjglqa57cca9cwqy1rzgxcanjjl-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- lldb_12
- lldb_11
- vscode-extensions.vadimcn.vscode-lldb
# a list of nixos modules affected by the problem
module:
```
