### ISSUE TITLE
gnome extension "ddterm" does not work

### ISSUE THREAD

**Issue by cmm** [NixOS/nixpkgs#125363]
**Describe the bug**
The "ddterm" extension does not work, because it lacks some NixOS-specific packaging magic having to do with `gjs`, typelibs etc (I don't understand anything about it, just keyword-googled #40474)

**To Reproduce**
1. add `gnomeExtensions.ddterm` to `environment.systemPackages`
2. login into Gnome
3. press F12
4. nothing visible happens.  "/run/current-system/sw/share/gnome-shell/extensions/ddterm@amezin.github.com/com.github.amezin.ddterm: line 5: exec: gjs: not found" appears in the user journal

**Notify maintainers**
@piegamesde  

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.596.3a2e0c36e79 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(cmm): `"home-manager-21.05, nixpkgs-21.05.596.3a2e0c36e79, nixpkgs-unstable-21.11pre292293.84aa23742f6"`
 - channels(root): `"nixos-21.05.596.3a2e0c36e79, nixos-unstable-21.11pre292748.6933d068c5d"`
 - nixpkgs: `/home/cmm/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  gnomeExtensions
  gnome40Extensions
# a list of nixos modules affected by the problem
module:
```
