### ISSUE TITLE
Gnome-terminal does not start

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#125823]
**Describe the bug**
When I run Gnome Terminal, I get `# Error creating terminal: The name org.gnome.Terminal was not provided by any .service files`.

**To Reproduce**
1. `nix-shell -p gnome.gnome-terminal --run "gnome-terminal"`

**Additional context**
I am on Arch Linux and have installed Gnome Terminal via `nix-shell` or home-manager. This may be causing the issue, but I'm not sure.

**Notify maintainers**
@NixOS/gnome 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.9-arch1-1, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(piegames): `"nixpkgs-21.05.740.aa576357673, nixpkgs-unstable-21.11pre293818.afdb5675a18"`
 - nixpkgs: `/home/piegames/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
