### ISSUE TITLE
Prometheus regex substitutions have to be escaped

### ISSUE THREAD

**Issue by sylvainf911** [NixOS/nixpkgs#126083]
**Describe the bug**
After upgrading from 20.09 to 21.05, instances scraped with ec2_sd were having all their "instance" field to ":9100"
instead of the public host name like before.

**To Reproduce**
In your `prometheus.yml`:

```
    relabel_configs:
      - target_label: "__address__"
        source_labels: ["__meta_ec2_public_dns_name"]
        replacement: "$1:9100"
        action: replace
```

When you do a `nixos-rebuild switch`, you can see in `/run/prometheus/prometheus-substituted.yaml`:

```
    relabel_configs:
      - target_label: "__address__"
        source_labels: ["__meta_ec2_public_dns_name"]
        replacement: ":9100"
        action: replace
```

The $1 is missing

If you double the $ sign ($$1 instead of $1), the `/prometheus-substituted.yaml` is containing the
correct value (` replacement: "$1:9100"'`).

This seems to be related to the `envsubst` program called when the service is started.

I did not find any reference to this is the 21.05 change log. Maybe it should be added?

**Expected behavior**
The $1 should be present to make the public host name substitution correctly.

**Notify maintainers**
benley
fpletz
globin
willibutz
Frostman

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.650.eaba7870ffc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.650.eaba7870ffc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
