### ISSUE TITLE
steam: Bind mount for /etc/resolv.conf fails often

### ISSUE THREAD

**Issue by queezle42** [NixOS/nixpkgs#126234]
**Describe the bug**
Starting a game in Steam fails with the following message:
`bwrap: Can't bind mount /oldroot/etc/resolv.conf on /newroot/etc/resolv.conf: No such file or directory`

This does not happen all the time, but quite often (>50%); when it happens once it will happen until I restart Steam.

I'm using systemd-resolved (`services.resolved.enable = true`), so `/etc/resolv.conf` is a symlink to `/etc/static/resolv.conf`, which is a symlink to `/run/systemd/resolve/stub-resolv.conf`.

I assume that `resolv.conf` pointing to `/run` might interfere with the setup of the steam runtime somehow, but that's just a guess.

**Notify maintainers**

@jagajaga
@jonringer

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.7, NixOS, 21.11.20210601.1c2986b (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - nixpkgs: `/nix/store/ypgnj9x286v31wf3061j60vqmyq7pc45-source`
```
I had the problem with that revision; now I'm using steam from `nixpkgs/2033f37fb284bd55159ea1650aa93a635caaffb3` (because of the new runtime version), but the problem persists.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- programs.steam.enable
```
