### ISSUE TITLE
Prometheus node exporter version info not shown

### ISSUE THREAD

**Issue by Dehumanizer77** [NixOS/nixpkgs#126359]
**Describe the bug**
node_exporter_build_info metric showing empty "branch", "revision" and "version" labels

**To Reproduce**
1. enable services.prometheus.exporters.node
2. rebuild
3. check the value of node_exporter_build_info metric at http://localhost:9100/metrics
4. values of branch, revision and version labels are empty strings

**Expected behavior**
correctly populated branch, revision and version labels in the above mentioned metric

**Screenshots**

**Additional context**
It's apparently a build problem, when using a compiled binary from prometheus.io, it shows everything correctly

**Notify maintainers**
@benley @fpletz @globin @Frostman

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-19.09pre191505.7d5375ebf4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
