### ISSUE TITLE
tt-rss: `Schema version is wrong, please upgrade the database.` after upgrade from 20.09 to 21.05

### ISSUE THREAD

**Issue by makefu** [NixOS/nixpkgs#126374]
**Describe the bug**
After upgrading the system to 21.05 the tt-rss update service does not work correctly anymore, it shows `Schema version is wrong, please upgrade the database`

**To Reproduce**
1. configure tt-rss with nixpkgs 20.09 as module
2. perform system upgrade to 21.05
3. `systemctl status tt-rss`

**Expected behavior**
the tt-rss update daemon should work without manual intervention after upgrade. alternatively a workaround is described in the manual on how to perform the upgrade.

**Screenshots**
![image](https://user-images.githubusercontent.com/115218/121371488-e0678200-c93d-11eb-96b1-b5644a6d60b3.png)

**Additional context**

**Notify maintainers**
@symphorien @flokli 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.105, stockholm/NixOS, unknown/21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/var/src/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- services.tt-rss
```
