### ISSUE TITLE
nixosTests.printing failure blocking nixos-unstable

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#126449]
**Describe the bug**

Hydra encountered a problem [here](https://hydra.nixos.org/build/145123871#tabs-summary) blocking the channel.

I've attached the log, because hydra will replace it by a succesful log if the test turns out to be unreliable instead of broken.
[m0xnk96mr6yly0ybva44m9rx4pcgaaln-vm-test-run-printing.drv.txt](https://github.com/NixOS/nixpkgs/files/6628936/m0xnk96mr6yly0ybva44m9rx4pcgaaln-vm-test-run-printing.drv.txt)

**Notify maintainers**

@matthewbauer (cups)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - cups
 - nixosTests.printing
# a list of nixos modules affected by the problem
module:
```
