### ISSUE TITLE
Sweet theme doesn't provide murrine gtk engine

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#126596]
**Describe the bug**
Sweet theme doesn't provide murrine gtk engine compared to other themes:
https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/data/themes/sweet/default.nix
https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/data/themes/materia-theme/default.nix

Apps thus don't detect the murrine engine because it is not installed.
There might also be other problems with the package as I think pixbuf and librsvg are mendatory for themes, I am not sure about that but it could be.

**Expected behavior**
The sweet package should install all necessary dependencies.

**Screenshots**
![image](https://user-images.githubusercontent.com/31109099/121695480-5f3df580-cacb-11eb-83e8-5f86229844c6.png)

**Notify maintainers**

@Fuzen-py

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sweet
# a list of nixos modules affected by the problem
module:
```
