### ISSUE TITLE
Thunar doesn't have Regular Expressions enabled in renamer.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#126618]
**Describe the bug**
The Thunar bulk-rename dialog doesn't support regular expressions.

**To Reproduce**
1. Select multiple files.
2. Right-Click → Rename.
3. Select "Search & Replace"

**Expected behavior**
The "Regular Expression" option can be checked.

**Screenshots**
![image](https://user-images.githubusercontent.com/494012/121731717-4e878280-cabf-11eb-99d3-2543612f3eac.png)

**Additional context**

This appears to be because it is not using PCRE or PCRE doesn't support UTF-8. I support it isn't being built with PCRE at all.

https://sourcegraph.com/github.com/xfce-mirror/thunar@9eb4a40a22e126846793cd6997b0132ed206302a/-/blob/plugins/thunar-sbr/thunar-sbr-replace-renamer.c?subtree=true#L190-194

**Notify maintainers**
Np maintainers, @romildo touched it last.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.11pre293089.1c2986bbb80 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(kevincox): `""`
 - channels(root): `"nixos-21.11pre293089.1c2986bbb80"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- xfce.thunar
# a list of nixos modules affected by the problem
module:
```
