### ISSUE TITLE
update-users-groups.pl malformed JSON string, neither array, object, number, string or atom, at character offset 0

### ISSUE THREAD

**Issue by nixinator** [NixOS/nixpkgs#126971]
**Describe the bug**

update-users-groups.pl fails with malfomed JSON :-(

nixos-rebuild switch

building Nix...
building the system configuration...
activating the configuration...
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "\x{0}\x{0}\x{0}\x{0}...") at /nix/store/iczcvcwxd9pz9agwci6m1f65aywa2jyi-update-users-groups.pl line 294.
Activation script snippet 'users' failed (2)
setting up /etc...
reloading user units for sddm...
reloading user units for user...
setting up tmpfiles
warning: error(s) occurred while switching to the new configuration

**To Reproduce**

nixos-rebuild switch

**Expected behavior**

uid and gid tables to be build successfully.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.11, channels(root): "nixos-20.09.4321.115dbbe82eb", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
system

# a list of nixos modules affected by the problem
module:
```
system
