### ISSUE TITLE
lib.lists.groupBy docs are inaccurate

### ISSUE THREAD

**Issue by whentze** [NixOS/nixpkgs#127227]
**Describe the bug**
This line
https://github.com/NixOS/nixpkgs/blob/5c770035c8fa1e84b1362dc2fe6da30be0eef363/lib/lists.nix#L321
claims that `groupBy` returns a "list of lists", but it actually returns an attribute set whose values are lists.

**To Reproduce**
N/A, this is merely a doc bug.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- lib.lists
# a list of nixos modules affected by the problem
module:
```
