### ISSUE TITLE
PyQt5 fails in nix-shell ("Could not find the Qt platform plugin")

### ISSUE THREAD

**Issue by hlandau** [NixOS/nixpkgs#127277]
**Describe the bug**
When using PyQt5 in Python, Qt cannot load correctly and gives the following error:

>qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
>This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
>
>Available platform plugins are: wayland-org.kde.kwin.qpa.
>
>Aborted (core dumped)

**To Reproduce**
```
$ nix-shell -p 'python38.withPackages(p: with p; [pyqt5])'
$ python -c 'import PyQt5.QtWidgets; PyQt5.QtWidgets.QApplication([])'
```

**Expected behavior**
No error.

**Notify maintainers**
@svanderburg

**Metadata**
Also reproduced on nixpkgs master as of writing.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.83, NixOS, 20.09.4316.85ed11208f8 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-20.09.4316.85ed11208f8"`
 - channels(hugo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pythonPackages.pyqt5
# a list of nixos modules affected by the problem
module:
```
