### ISSUE TITLE
Package Update Segfaults with 21.05 Channel

### ISSUE THREAD

**Issue by herrmoltke** [NixOS/nixpkgs#127211]
**Describe the bug**
After changing my `nixos` channel from 20.09 to 21.05, `nixos-rebuild switch` results in a segmentation fault.

**To Reproduce**
1. Change `nixos` channel from 20.09 to 21.05
2. run `nixos-rebuild switch`

**Expected behavior**
The system successfully upgrades

**Screenshots**

**Additional context**
- My OS is Linux 5.11.21-hardened1

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
- This command results in a segmentation fault, as well.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
