### ISSUE TITLE
amdgpu-pro fails to evaluate

### ISSUE THREAD

**Issue by IvarWithoutBones** [NixOS/nixpkgs#127275]
**Describe the bug**
When adding `"amdgpu-pro"` to `services.xserver.videoDrivers`, the following error occurs:
```
~ > sudo nixos-rebuild switch
building Nix...
building the system configuration...
error: The dpdk driver has been renamed to dpdk-mods.
```

Log with [`--show-trace`](https://gist.github.com/IvarWithoutBones/aac50eefccf4af9c1ffff16aaa2a2abb).

**To Reproduce**
1. Append `amdgpu-pro` to the `services.xserver.videoDrivers` array.
2. Rebuild the system
3. Notice it fail

**Expected behavior**
The system should rebuild.

**Notify maintainers**
@corngood 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.10, NixOS, 21.11pre295280.fa0326ce523 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre295280.fa0326ce523"`
 - channels(ivv): `"home-manager, nixpkgs-21.11pre295670.189a1368878"`
 - channels(ivar): `"home-manager, nixpkgs-21.03pre250049.4b30d5601da, nixos-20.09pre231796.22a81aa5fc1"`
 - nixpkgs: `/home/ivv/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: amdgpu-pro
# a list of nixos modules affected by the problem
module: services.xserver.videoDrivers
```
