### ISSUE TITLE
gegl is broken on aarch64-linux

### ISSUE THREAD

**Issue by L-as** [NixOS/nixpkgs#127347]
**Describe the bug**
I get this:

```
/nix/store/ca148jcwpzjqyasyaqf9l81sndxwgbqn-binutils-2.35.1/bin/ld: gegl-path-smooth.o: undefined reference to symbol 'sqrt@@GLIBC_2.17'
/nix/store/ca148jcwpzjqyasyaqf9l81sndxwgbqn-binutils-2.35.1/bin/ld: /nix/store/z34r7j0ni01ggc7y243114mdyag345xy-glibc-2.32-46/lib/libm.so.6: error adding symbols: DSO missing from command line
```

It can also be seen on hydra: <https://hydra.nixos.org/build/145681632>
Last successful build: <https://hydra.nixos.org/build/86320261> (revision 0b0c67e5378ccc4f4eef3a7e88eb2acb1127d50f)
First unsuccessful build: <https://hydra.nixos.org/build/86773566> (revision 5489e49ebb5cb9b973133fcd70d3196fb12acc0b)

**To Reproduce**
`nix-build '<nixpkgs>' -A gegl`

**Expected behavior**
It should build.

**Notify maintainers**
@jtojnar 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
