### ISSUE TITLE
nextcloud-desktop crashes on startup

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#127324]
**Describe the bug**

`nextcloud` (that is nextcloud-client) crashes on startup

```
$ nextcloud --version
Nextcloud version 3.2.1git
Git revision 5901a0f9835261a640cd8bc9397bcd3068f2acd8
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1k  25 Mar 2021'
Running on NixOS 21.05 (Okapi), x86_64
```

Running in KDE plasma 5.21. Maybe related to #126929 .

**To Reproduce**
1. `nextcloud` in your terminal, results in segfault.

**Notify maintainers**

@caugner 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.125, NixOS, 21.05.git.1f91fd10406 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(m): `""`
 - channels(root): `"nixos-20.03.3269.f05c380a51d"`
 - nixpkgs: `/var/src/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nextcloud-client
# a list of nixos modules affected by the problem
module:
```
