### ISSUE TITLE
Is there suppose to be a dynamic resolved user?

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nixpkgs#127851]
**Describe the bug**

I notice my system has picked up a dynamic `resolved` user. It appears to be due the line
```
users.users.resolved.group = "systemd-resolve";
```
added by commit 2ffb2c0. The description is *add user systemd-resolve to group systemd-resolve*, but my understanding is this creates the user `resolved` by setting the `group` attribute for it.

**To Reproduce**

Set `resolved.enable = true` in your config and rebuild.

**Expected behavior**

Given the commit comment, and the fact that `systemd-resolved` is running as `systemd-resolve` on my machine, I expect what was intended was
```
users.users.systemd-resolve.group = "systemd-resolve";
```

**Notify maintainers**

@WilliButz as the committer.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.93, NixOS, 20.09.git.f18fbc33930 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-19.09.1784.fd4ccdbe3a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - system/boot/networkd.nix
  - system/boot/resolved.nix
```
