### ISSUE TITLE
unbound service broken

### ISSUE THREAD

**Issue by Luis-Hebendanz** [NixOS/nixpkgs#128463]
**Describe the bug**
Unbound fails to start. Or more accurately it starts fine and works for 2 minutes but then  it fails with  `systemd[1]: unbound.service: start operation timed out. Terminating.`

This probably has something to do with the systemd service type beeing `Type=notify` for communication between unbound and systemd. It probably has something to do with unbound not beeing able to access the systemd socket out of some containerization constraints used in the systemd file or because of the option 'chroot: ""' beeing set by default in the unbound.conf

**To Reproduce**
```
  services.unbound = {
    enable = true;
  };
```
**Notify maintainers**
@rissson 
@joachifm 
@ehmry 
**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.122, NixOS, 21.05.1205.b72bde7c4a1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1205.b72bde7c4a1, nixos-unstable-21.11pre297796.e1f8852faac"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.unbound
```
