### ISSUE TITLE
krusader: Can't find kio_krarc module when trying to unzip a file

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#128605]
**Describe the bug**
When I try to unzip a file with krusader, I get this error (on the command line):

```
11:33:11.467-warning kf.kio.core unknown@0 # couldn't create slave: "Meldung von klauncher: Das Modul „kio_krarc“ wurde nicht gefunden.\n"
```

It roughly translates to "Message from klauncher: The module "kio_krarc" was not found."

**Notify maintainers**

@sander

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03pre252083.2deeb58f494 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"musnix, nixos-21.05pre276379.266dc8c3d05, nixos-hardware"`
 - channels(turion): `"nixpkgs-21.11pre297902.e8597594274, home-manager"`
 - nixpkgs: `/home/turion/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - krusader
# a list of nixos modules affected by the problem
module:
```
