### ISSUE TITLE
cloud-init broken on unstable

### ISSUE THREAD

**Issue by Xe** [NixOS/nixpkgs#128783]
**Describe the bug**

cloud-init is broken in nixos-unstable

**To Reproduce**

env NIX_PATH=nixpkgs=channel:nixos-unstable nix-shell -p nixos-generators --run nixos-generate -f qcow -c ./cloud-init-test.nix
```nix
# cloud-init.nix
{ ... }:

{
  services.cloud-init = {
    enable = true;
    ext4.enable = true;
  };
}
```

**Expected behavior**
The build to pull cloud-init from hydra and a qcow2 file gets produced

**Screenshots**
http://sprunge.us/pjgD0S

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.44, NixOS, 21.11pre297098.7e567a3d092 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [cloud-init]
# a list of nixos modules affected by the problem
module: [cloud-init]
```
