### ISSUE TITLE
boot.loader.grub.configurationLimit doesn't work as expected

### ISSUE THREAD

**Issue by psibi** [NixOS/nixpkgs#128956]
**Describe the bug**

I have the following configuration in my `configuration.nix`:

```
  boot.loader.grub.configurationLimit = 25;
```

And with some `nixos-rebuild switch`, I have exceeded more than 30 entries currently.

**To Reproduce**

1. Set a `boot.loader.grub.configurationLimit` to an arbitrary number. (Probably close to your current number of entries)
2. Do some nixos-rebuild switch and your entries would be more than the limit you have specificed.
3. ...

**Expected behavior**

It should be exactly have the n menu entries where `n` is the specified value for `boot.loader.grub.configurationLimit`.

**Notify maintainers**

@rnhmjoj (Pretty sure I'm pinging the wrong person here)

**Metadata**

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.876.60cce7e5e1f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Maintainer information:

```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
