### ISSUE TITLE
firefox-unwrapped times out on Hydra for aarch64-linux

### ISSUE THREAD

**Issue by L-as** [NixOS/nixpkgs#129115]
**Describe the bug**
See https://hydra.nixos.org/job/nixpkgs/trunk/firefox-unwrapped.aarch64-linux and https://hydra.nixos.org/build/146893853

**Expected behavior**
Optimally it would be built by Hydra since it would take ages for most aarch64-linux users to build.

**Notify maintainers**
@edolstra @lovesegfault @mweinelt 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
