### ISSUE TITLE
SDL2 headers are filled with null bytes since d072761

### ISSUE THREAD

**Issue by Uthar** [NixOS/nixpkgs#129226]
**Describe the bug**
Commit https://github.com/NixOS/nixpkgs/commit/d07276113a2a98680777d456dcdc9b24305bb6cf makes some headers in `${pkgs.SDL2.dev}/include/SDL2/` be filled with null bytes and therefore unusable for development.

**To Reproduce**
1. `nix repl`
2. `:l https://github.com/nixos/nixpkgs/archive/d07276113a2a98680777d456dcdc9b24305bb6cf.tar.gz`
3. `:b SDL2`
4. `cat /nix/store/7b02xlaj5wfd2msmlaz6ykgvmlp24cfg-SDL2-2.0.14-dev/include/SDL2/SDL.h`

**Expected behavior**
Every header contains the C code of the SDL API.

**Notify maintainers**

@cpages 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1268.21b696caf39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(kpg): `""`
 - channels(root): `"nixos-21.05.1268.21b696caf39"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: SDL2
# a list of nixos modules affected by the problem
module:
```
