### ISSUE TITLE
sauerbraten can't connect to game servers

### ISSUE THREAD

**Issue by vigilancetech-com** [NixOS/nixpkgs#129366]
**Describe the bug**
Says "illegal network message type" when you try and connect.

**To Reproduce**
1.  install sauerbraten
2.  run it with sauerbraten_client
3.  click server browser
4.  try and connect to one
5.  sometimes it works, but most times it does not (probably needs an upgrade)

**Expected behavior**
connects to server no problem

**Screenshots**
![image](https://user-images.githubusercontent.com/20651234/124516378-596bc500-dd96-11eb-9cb3-811d675d1eb4.png)

**Additional context**

**Notify maintainers**

I don't know how to find this

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.118, NixOS, 20.09.4132.52090c613ad (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
