### ISSUE TITLE
sauerbraten not saving settings

### ISSUE THREAD

**Issue by vigilancetech-com** [NixOS/nixpkgs#129364]
**Describe the bug**

When you fire up sauerbraten, it's supposed to save any options upon exit of the program.   It does not

**To Reproduce**
1. install sauerbraten
2. start the program with $ sauerbraten_client
3. select options from the menu
4. change any setting (e.g. game or music volume, or character name)
5. quit the program
6. restart it
7. check to see if your option is preseved

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
