### ISSUE TITLE
Plasma's Spectacle does not support annotating screenshots

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#129676]
**Describe the bug**
Starting with version 20.12, Spectacle has annotation support, utilizing [kImageAnnotator](https://github.com/ksnip/kImageAnnotator). Most big distributions already ship Spectacle with the feature enabled. I assume kImageAnnotator needs to be packaged and integrated with the existing Spectacle package.

**Screenshots**

Screenshot of the functionality from the official KDE docs:

![Annotate](https://user-images.githubusercontent.com/3802620/124970117-ce096280-e027-11eb-8cf4-a83cee897af1.png)

**Additional context**
- [Request in KDE's Bugzilla](https://bugs.kde.org/show_bug.cgi?id=372464)
- [The commit which added the feature](https://invent.kde.org/graphics/spectacle/-/commit/fa60f99470485143015b547b03ecba7811569480)

**Notify maintainers**

@ttuegel 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
