### ISSUE TITLE
zrepl: ssh connection type not supported

### ISSUE THREAD

**Issue by LennyPenny** [NixOS/nixpkgs#129698]
**Describe the bug**
I wanted to use the `ssh+stdinserver` connection type for a zrepl job like so in my `configuarion.nix`:
```nix
services.zrepl.settings = {
    ...
    jobs = [
      {
        name = "push_backups";
        type = "push";

        connect.type = "ssh+stdinserver";
        ...
```

However the service then fails with this error, saying that ssh is missing from this package. 
```
Jul 09 00:44:53 wyse systemd[1]: Started zrepl daemon.
Jul 09 00:44:54 wyse zrepl[9450]: [push_backups][rpc.ctrl][Uv38$NsJB$NsJB.9wLx.daFR]: cannot connect err="exec: \"ssh\": executable file not found in $PATH"
```

I guess I could fix this with an overlay? I'm new to nixos and don't really know how I would go about doing that. (Would appreciate some pointers to examples where smth similar was done before)

**Notify maintainers**
@cole-h 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05pre290520.a39809ade01 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zrepl
# a list of nixos modules affected by the problem
module:
```
