### ISSUE TITLE
fonts thin and fc-match monospace is wrong

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#129711]
**Describe the bug**
fonts are wrong
9852c9e5b66f33c912b52bbf1e4e1369353ecc50 may be the culprit

**To Reproduce**
1. clone the nixpkgs repo and checkout 036dc0c7096
2. rebuild with `-I nixpkgs=/home/USER/nixpkgs`
3. open a program like wofi or firefox

**Screenshots**
036dc0c7096
```
fc-match monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
```
![screenshot_2021-07-09_05-09-06_761454665](https://user-images.githubusercontent.com/56650223/125015784-d9d14500-e078-11eb-9593-98b5291f6fa9.png)

7229e6d646c
```
fc-match monospace
JetBrains Mono Regular Nerd Font Complete.ttf: "JetBrainsMono Nerd Font" "Regular"
```
![screenshot_2021-07-09_05-44-59_147094303](https://user-images.githubusercontent.com/56650223/125015807-e5bd0700-e078-11eb-9c47-059b1fbfd029.png)

**Additional context**
```git log 7229e6d646c..036dc0c7096```

i've already tried `rm -rf .cache/fontconfig` and `fc-cache -vf` many times

**Notify maintainers**
@NixOS/freedesktop 
@alyssais 

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
