### ISSUE TITLE
GoldenCheetah 3.5 fails to import data while upstream build works

### ISSUE THREAD

**Issue by jpotier** [NixOS/nixpkgs#129926]
**Describe the bug**
In GoldenCheetah 3.5, the current NixOS build segfaults when importing a GPX trace, but the upstream AppImage of the same version succeeds.

**To Reproduce**

1. Create a new athlete profile
2. Click “Import data”
    Use [this GPX file](https://github.com/GoldenCheetah/GoldenCheetah/files/6760374/2021-07-04_17-16_Sun.gpx.zip) (unzip it first)
4. Date is recognized properly, press “Save”
5. The program hangs a few seconds at:
6. The program segfaults.

See https://github.com/NixOS/nixpkgs/pull/121373 and https://github.com/GoldenCheetah/GoldenCheetah/issues/3909 for more details

**Expected behavior**
The import succeeds

**Notify maintainers**

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0, NixOS, 21.11-2021-07-11.45fc7d4 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre301414.45fc7d4a35c, overlay-personal"`
 - channels(eeva): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
