### ISSUE TITLE
cinnamon Menu Editor - Properties, Edit Desktop File dont work

### ISSUE THREAD

**Issue by John-Rodriguez-Git** [NixOS/nixpkgs#129946]
**Describe the bug**
The cinnamon-menu-editor doesn't open the cinnamon-desktop-editor, if I want to change the 'Properties' of a menu Entry.

**To Reproduce**

https://user-images.githubusercontent.com/87267596/125200658-4a8c8300-e26c-11eb-9d7d-beed1428c731.mp4

**Expected behavior**

https://user-images.githubusercontent.com/87267596/125200349-f503a680-e26a-11eb-9a17-c9e6d4c08715.mp4

**Additional context**
Here is the cinnamon-desktop-editor source: https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py

**Notify maintainers**
@mkg20001 thanks for making cinnamon available in NixOS! :)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1408.9376bf7b342 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.1408.9376bf7b342"`
 - channels(linux): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: cinnamon.cinnamon-common
```
