### ISSUE TITLE
virt-manager: Missing toolbar icons

### ISSUE THREAD

**Issue by mz-pdm** [NixOS/nixpkgs#130034]
**Describe the bug**
The toolbar buttons for running, stopping, etc. VMs don't have their normal icons, just some default replacements.

**To Reproduce**
1. Start virt-manager.
2. Look at its toolbar.

**Expected behavior**
All the virt-manager toolbar buttons have their usual icons.

**Screenshots**
[toolbar screenshot](http://www.zamazal.org/wp-content/uploads/sites/3/2021/07/virt-manager-screenshot.jpg)

**Notify maintainers**
@qknight @offline @fpletz @globin

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1408.9376bf7b342 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1408.9376bf7b342, nixos-unstable-21.11pre301414.45fc7d4a35c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
