### ISSUE TITLE
midori: fails to evaluate at nixos-unstable

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#130141]
**Describe the bug**
https://hydra.nixos.org/build/147767715/nixlog/2

```
error: while querying the derivation named 'midori-9.0':
while evaluating the attribute 'buildInputs' of the derivation 'midori-9.0' at /build/source/pkgs/stdenv/generic/make-derivation.nix:203:11:
while evaluating 'getOutput' at /build/source/lib/attrsets.nix:486:23, called from undefined position:
while evaluating anonymous function at /build/source/pkgs/stdenv/generic/make-derivation.nix:154:17, called from undefined position:
attribute 'gtk3' missing, at /build/source/pkgs/applications/networking/browsers/firefox/wrapper.nix:184:23
```

**Notify maintainers**

@ajs124 (I suspect https://github.com/NixOS/nixpkgs/commit/c6e51d03695efa90a8d09b41fe6441953e21d52a)
@7c6f434c @ramkromberg for midori

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - midori
# a list of nixos modules affected by the problem
module:
```
