### ISSUE TITLE
Gollum does not include dependencies for non-default renderers (org-mode etc.)

### ISSUE THREAD

**Issue by wildthyme** [NixOS/nixpkgs#130131]
**Describe the bug**
Gollum [supports a variety of markup languages](https://github.com/gollum/gollum#markups), but the package doesn’t include the relevant gems (notably `org-ruby`).

**To Reproduce**
1. `services.gollum.enable = true;`
2. Make a new page with format set to org-mode
3. `Failed to render page: cannot load such file -- org-ruby`

**Expected behavior**
Ought to render the org markup

**Notify maintainers**
@erictapen 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.11.20210616.0747387 (Porcupine)`
 - multi-user?: `yes`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
