### ISSUE TITLE
xscreensaver warning

### ISSUE THREAD

**Issue by kurnevsky** [NixOS/nixpkgs#130218]
**Describe the bug**
When xscreensaver is launched it prints the following warning:
```
xscreensaver-auth: 22:54:53: OOM: /proc/1919/oom_score_adj: Permission denied
xscreensaver-auth: 22:54:53:   To prevent the kernel from randomly unlocking
xscreensaver-auth: 22:54:53:   your screen via the out-of-memory killer,
xscreensaver-auth: 22:54:53:   "xscreensaver-auth" must be setuid root.
```

**Expected behavior**
xscreensaver-auth is wrapped to suid and this wrapper is used by xscreensaver so that it can set oom score.

**Notify maintainers**
@7c6f434c 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.14-zen1, NixOS, 21.05.20210713.2a96414 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.1486.2a96414d7e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
