### ISSUE TITLE
qt5base: apple silicon: fails to build

### ISSUE THREAD

**Issue by hexagonal-sun** [NixOS/nixpkgs#130240]
**Describe the bug**
Bulding `qt5.qtbase` fails on apple silicon.  [See the hydra log](https://nix-cache.s3.amazonaws.com/log/jcbh3gkvm043q9xjvdz6rj57nwz53mrr-qtbase-5.12.10.drv). It looks as though the `x86_64` linker is being invoked, see the bottom of the log.  Specifically `clang` is being passed `-triple x86_64-apple-macosx11.0.0`.

**To Reproduce**
Build `qt5.qtbase` on apple silicon.

**Expected behavior**
it builds.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qt5.qtbase
# a list of nixos modules affected by the problem
module:
```
