### ISSUE TITLE
Midnight Commander can't connext to x11

### ISSUE THREAD

**Issue by kurnevsky** [NixOS/nixpkgs#130353]
**Describe the bug**
Midnight Commander can't connext to x11, and because of that `ctrl+enter` hotkey to paste selection doesn't work.
I debugged it a bit and it can't open x11 library (here)[https://github.com/MidnightCommander/mc/blob/fa9ea0d61cc2a5f4a839fc1969da5416ab38ba98/lib/tty/x11conn.c#L136-L139] and returns `false` (here)[https://github.com/MidnightCommander/mc/blob/fa9ea0d61cc2a5f4a839fc1969da5416ab38ba98/lib/tty/x11conn.c#L144]
Should it be patched somehow?

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**
@svanderburg 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.14-zen1, NixOS, 21.05.20210713.2a96414 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.1486.2a96414d7e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
