### ISSUE TITLE
Midnight Commander references to an unexistent store path

### ISSUE THREAD

**Issue by kurnevsky** [NixOS/nixpkgs#130471]
**Describe the bug**
Execute action in midnight commander doesn't work (when enter is pressed).

**To Reproduce**
Press enter on any video or audio file, you will see something like:
```
/tmp/mc-kurnevsky/mcextDPGN60: line 13: /nix/store/j3qxj7x680qf7l7y7hqkl8fajfpyj894-mc-4.8.26/libexec/mc/ext.d/video.sh: No such file or directory
```
Midnight commander has different store path. My store doesn't have this hash at all, so don't know where is it taken from.

**Expected behavior**
Midnight commander is able to open audio/video files.

**Notify maintainers**
@svanderburg 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.14-zen1, NixOS, 21.05.20210713.2a96414 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.1486.2a96414d7e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
