### ISSUE TITLE
No disk space in 21.05 VirtualBox OVA

### ISSUE THREAD

**Issue by Infinisil** [NixOS/nixpkgs#131128]
**Describe the bug**
In the 21.05 VirtualBox OVA you can download from https://nixos.org/download.html#nixos-virtualbox there is no disk space available, making it impossible to use for almost anything:

```
[demo@nixos:~]$ df .
Filesystem               1K-blocks    Used Available Use% Mounted on
/dev/disk/by-label/nixos   7698852 7286112       172 100% /
```

**To Reproduce**
1. Download the VirtualBox OVA from https://nixos.org/download.html#nixos-virtualbox, [persistent link from Hydra](https://hydra.nixos.org/build/148271506/download/1/nixos-21.05.1590.63ee5cd99a2-x86_64-linux.ova)
2. Follow the instructions on above page to import and start it (although the instructions are a bit outdated too, no need to log in manually)
3. Run `df .` in a Konsole window

**Expected behavior**
I expect to have disk space. Here's the same for a NixOS 20.09 OVA:
```
[demo@nixos:~]$ df .
Filesystem               1K-blocks    Used Available Use% Mounted on
/dev/disk/by-label/nixos  51341792 6938872  41765200  15% /
```

**Screenshots**
![2021-07-22_22-00](https://user-images.githubusercontent.com/20525370/126702057-b77dd9bc-b954-4e67-b90a-c63f4614e92f.png)

**Notify maintainers**
@Lassulus @samueldr @dfordivam 

**Metadata**
Bad nixpkgs version (21.05): 63ee5cd99a2e193d5e4c879feb9683ddec23fa03
Good nixpkgs version (20.09): 068984c00e0d4e54b6684d98f6ac47c92dcb642e

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - virtualisation/virtualbox-image.nix
```
