### ISSUE TITLE
iterm2: builds as x86_64 on apple silicon

### ISSUE THREAD

**Issue by hexagonal-sun** [NixOS/nixpkgs#131269]
### Describe the bug
The iterm2 attribute builds as an x86_64 binary on apple silicon.

### Steps To Reproduce
Steps to reproduce the behavior on an apple silicon machine:
`nix-env -i iterm2`

The resulting binary will be built for x86_64:

```
matthew@matthews-air ~ [1]> file .nix-profile/Applications/iTerm.app/Contents/MacOS/iTerm2 
.nix-profile/Applications/iTerm.app/Contents/MacOS/iTerm2: Mach-O 64-bit executable x86_64
```

### Expected behavior
It is built for `arm64`.

### Additional context
It maybe that we can't produce native `arm64` apps until  #101229 is fixed.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: iterm2
# a list of nixos modules affected by the problem
module:
```
