### ISSUE TITLE
earthly: maintainer disappeared and license became unfree

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#131308]
### Describe the bug
https://github.com/NixOS/nixpkgs/pull/131169#issuecomment-886007895

### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
