### ISSUE TITLE
helvum: build broken on unstable

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#131498]
### Describe the bug
Helvum build is broken on unstable

### Steps To Reproduce
1. Checkout master
2. Build helvum

### Expected behavior
Build suceeds.

### Screenshots
https://hydra.nixos.org/build/148449711/nixlog/1

### Additional context
Since it's pipewire-sys crate that fails, I suspect it was a pipewire upgrade that broke it

### Notify maintainers
@fufexan 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
