### ISSUE TITLE
Python3 fails to build with musl

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#131557]
### Describe the bug

`pkgsMusl.python3` fails to build: <https://hydra.nixos.org/build/148241699>

### Notify maintainers

cc @FRidh 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsMusl.python3, pkgsMusl.python39, pkgsMusl.python38
# a list of nixos modules affected by the problem
module:
```
