### ISSUE TITLE
qt5ct should be a part of libsForQt5, like kvantum

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#131751]
### Describe the bug
qt5ct is not a part of libsForQt5, what means it's not built for other Qt versions (like 5.14) and apps using these Qt versions (e.g. virtualbox) aren't themed

### Steps To Reproduce
1. Set `programs.qt5ct.enable = true;`
2. Install virtualbox and run it

### Expected behavior
VirtualBox is themed

### Screenshots
![изображение](https://user-images.githubusercontent.com/17829319/127241837-47ea8e79-9b3b-4ea7-a081-eeec3fe25e44.png)

### Notify maintainers
@ralith

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.14-zen1, NixOS, 21.11.20210709.45fc7d4 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qt5ct
# a list of nixos modules affected by the problem
module: programs.qt5ct
```
