### ISSUE TITLE
Emacs service

### ISSUE THREAD

**Issue by dan4ik605743** [NixOS/nixpkgs#131771]
### Describe the bug
After updating glibc > 2.33. Emacs has no service. Although service.emacs.enable = true;

### Steps To Reproduce
1. emacs.service.enable = true;
2. systemctl --user restart emacs.service
3. systemctl --user start emacs.service

### Expected behavior
Failed to restart emacs.service: Unit emacs.service not found
Failed to start emacs.service: Unit emacs.service not found.

### Screenshots
![image](https://user-images.githubusercontent.com/86075850/127265718-1f007ef6-8531-4e85-b400-b58566ea1d2c.png)
![image](https://user-images.githubusercontent.com/86075850/127265755-dbfa9f40-e769-4e77-8e99-7e399a9642bf.png)

### Additional context
Before updating GLIBC-2.33, the module worked properly. I tried without install = true; No effect. And without package. The same..

### Notify maintainers
@lovek323 @peti @jwiegley @adisbladis

### Metadata
```console
λ ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.134, NixOS, 21.11.20210724.dd14e5d (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.11pre299299.3a8d7958a61"`
 - nixpkgs: `/nix/store/3iw3gnv08yaz0v5qjhmv6g4dlj7pirfz-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: emacs
# a list of nixos modules affected by the problem
module: services.emacs
```
