### ISSUE TITLE
Latest stable and unstable sees sporadic reboots with watchdog enabled

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#131920]
### Describe the bug

For the longest time we've been running both physical and virtual instances with the systemd watchdog enabled

```
  systemd.extraConfig = ''
    RuntimeWatchdogSec=1m
    ShutdownWatchdogSec=1m
  '';
```

*However*, since b361dcf0bd3610d1fea6b44d72404add188da51d was merged and made it into both unstable as well as 21.05 through a subsequent backport, *something* goes wrong with systemd that makes it not send the watchdog keep-alives and the machines as a consequence get force rebooted after a period of time.

Without the mentioned commit on both unstable and 21.05, the configuration above works as expected.

*With* the commit and the watchdog enabled, machines will reboot anywhere between after 2 and 8 minutes after boot.

### Steps To Reproduce
1. Run latest 21.05 or unstable
2. Activate the `RuntimeWatchdog`
3. Reboot
4. Wait a few minutes for the machine to force reboot

We *really* should pin this issue.

### Notify maintainers
@dasJ @eelco @andir @flokli @kloenk

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - systemd
# a list of nixos modules affected by the problem
module:
 - systemd
```
