### ISSUE TITLE
MultiMC package violates trademark requirements

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#131983]
### Describe the bug
The "MultiMC" name cannot be used when redistributing MultiMC, according to [its README](https://github.com/MultiMC/MultiMC5#forkingredistributing).

Based on discussion on their Discord server, Nixpkgs should either patch MultiMC to change the name or package the official binaries without redistributing them.

From my understanding, while granting explicit permission to use the name similar to Firefox would be fine in the short term, MultiMC will require OAuth credentials in the future and they're reluctant to give distributions permission to use them.

### Notify maintainers
@cleverca22 @starcraft66 

### Metadata
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: multimc
# a list of nixos modules affected by the problem
module:
```
