### ISSUE TITLE
broken application icon on Plasma task bar

### ISSUE THREAD

**Issue by hyperfekt** [NixOS/nixpkgs#132477]
### Describe the bug
By default the KDE Plasma task bar seems to come with several application shortcuts, amongst them KDE Discover.
The icons displayed by default are defined in `${plasma-desktop}/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml`, where `org.kde.discover.desktop` is listed.
This entry corresponds with a missing (default blank page) icon in the task bar, that when clicked shows an error of `Unknown application folder`.
Presumably this is because the corresponding 'Discover' application is not installed by default, and so the desktop file the icon is supposed to refer to is missing from the system.

The solution would be to either install 'Discover' by default or to remove it from the default task bar applications.

### Screenshots
![image](https://user-images.githubusercontent.com/9434715/127934694-5c813f8e-d948-475e-8f6a-627e98625c3f.png)

### Notify maintainers
@ttuegel
@nyanloutre

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.5, NixOS, 21.11pre304626.8ecc61c91a5 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixos-21.11pre304626.8ecc61c91a5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - plasma-desktop
# a list of nixos modules affected by the problem
module:
  - services/x11/desktop-managers/plasma5.nix
```
