### ISSUE TITLE
Remove minergate?

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#133127]
### Describe the bug

The minergate and minergate-cli packages were packaged by @bfortz in April/May 2018. They haven't been updated since.
It has had an [unsolved problem](https://github.com/NixOS/nixpkgs/pull/132541#discussion_r683353419), presumably for a long time, which hinders maintenance.

Meanwhile, the minergate website has an invalid certificate (lack of maintenance? mitm seems unlikely) so I base my info off https://nl.trustpilot.com/review/minergate.com which notes a minimum 250USD withdrawal rate. Let's say this software is supposed to be used for non-trivial amounts of money, yet it has been unmaintained for over three years.

It seems reasonable to conclude that it isn't used anymore, and can be removed. Note that such a decision does not imply that the software can't be re-added and it is not a judgement of quality or anything like that. Unless the maintainer @bfortz would like to resolve the problem and commits to maintaining the package going forward, I suggest we remove it after 2021-09-07 (a month from now).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - minergate
 - minergate-cli
# a list of nixos modules affected by the problem
module:
```
