### ISSUE TITLE
pinentry: excessive derivation closure size

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#133156]
### Describe the bug

Pinentry is causing more rebuilds than necessary because it depends on many desktop environments for apparently no good reason.

The unnecessary dependencies also make the package more fragile, as observed in https://github.com/NixOS/nixpkgs/issues/124753 

### Steps To Reproduce

1. change qt
2. build the `pinentry-gnome`
3. observe a rebuild

This applies to all combinations of variants.

### Expected behavior

Distinct derivations for each variant cause no unnecessary derivation dependencies and therefore no unnecessary rebuilds.

The problem in https://github.com/NixOS/nixpkgs/issues/124753 is fixed.

### Additional context

This is not about the (byte) size of an output closure, but rather about rebuilding too often and depending on too many other packages.

The problem was introduced with https://github.com/NixOS/nixpkgs/commit/cb0adc11ffb0926adae7aa2ed22835c4f9ea971c

### Notify maintainers

@ttuegel @fpletz 

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - pinentry
 - pinentry-curses
 - pinentry-emacs
 - pinentry-gtk2
 - pinentry-qt
 - pinentry-gnome
# a list of nixos modules affected by the problem
module:
```
