### ISSUE TITLE
Plasma system monitor bot showing any measurements

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#133782]
### Describe the bug
System monitor shows list of apps but not graphs of resource usage

### Steps To Reproduce
1. Update to Plasma 5.22
2. Run `systemmonitor`

### Expected behavior
CPU, memory and other resource usage graphs are shown

### Screenshots
![image](https://user-images.githubusercontent.com/6931743/129385552-27a925e0-8806-43d1-9aee-0c7c4b21e112.png)

### Notify maintainers
@ttuegel @nyanloutre

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - nixpkgs: `/nix/store/v7g142952hmz1ss1cpbp38n6xp6q28jk-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: plasma-systemmonitor
# a list of nixos modules affected by the problem
module:
```
