### ISSUE TITLE
Scrooge does not run woob command on Import with engine

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#134054]
### Describe the bug
If I do File > Import > Import with engine in Skrooge it gives me a error command, even through the same command pasted in a command terminal gives me  the correct informations

### Expected behavior
Import succeeds without errors.

### Screenshots
![immagine](https://user-images.githubusercontent.com/6931743/129452904-012aa388-e80a-4982-9b2b-e9933d5ef1fd.png)

### Notify maintainers
@joko 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - nixpkgs: `/nix/store/9h6hsbq8qc7h51wnk88j39kyh3zihqz5-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: skrooge
# a list of nixos modules affected by the problem
module:
```
