### ISSUE TITLE
buildEnv fails when one of the paths to link is a symlink to a directory

### ISSUE THREAD

**Issue by ggPeti** [NixOS/nixpkgs#134103]
### Describe the bug
As per title. Check the example at https://gitlab.com/ggpeti/buildEnv-sscce. There are 2 top level directories, `a` and `b`. `b` has an empty file called `c` in it. `a` has a symlink to `b` in it. When one tries to create a trivial `buildEnv` like:
```nix
buildEnv {
  name = "test";
  paths = [ ./a ];
  pathsToLink = [ "/b" ];
}
```
the following, weird error message surfaces:
```
> collision between `/nix/store/sv597kz16cwk4g15w4665w6alj9na81q-a/b' and `'
```

### Steps To Reproduce
`nix build gitlab:ggpeti/buildenv-sscce`

### Expected behavior
buildEnv should treat symlinks to directories just like directories. It should not fail but create the environment.

### Additional context
This issue probably underlies https://github.com/LnL7/nix-darwin/issues/320 and https://github.com/nix-community/home-manager/issues/1994.

### Notify maintainers
@edolstra
@urkud
@aszlig
@Ma27
@MarcWeber
@vcunat
@rasendubi
@romildo
@lheckemann
@abbradar

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ buildEnv jdk zulu ]
# a list of nixos modules affected by the problem
module: []
```
