### ISSUE TITLE
Thunderbird cannot install any extension

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#134433]
### Describe the bug
As explained also here:
https://www.reddit.com/r/Thunderbird/comments/p5jffe/cannot_install_any_extensions/

### Steps To Reproduce
1. Open Thunderbird 91
2. Try to install any extensions
3. Install fail with "Thunderbird has prevented this site from installing an unverified add-on"

### Expected behavior
Add on is instaalled successfully

### Notify maintainers
@eelco @lovesegfault @pierron @vcunat

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - nixpkgs: `/nix/store/02kpag0vgfj1qi7bfwkipp74f1svzag0-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: thunderbird
# a list of nixos modules affected by the problem
module:
```
