### ISSUE TITLE
networkd network module's linkConfig is missing the ActivationPolicy option

### ISSUE THREAD

**Issue by berbiche** [NixOS/nixpkgs#134919]
### Describe the bug

https://www.freedesktop.org/software/systemd/man/systemd.network.html#ActivationPolicy=

The `ActivationPolicy` option is missing from the possible options for `systemd.network.networks.<name>.linkConfig`.

https://github.com/NixOS/nixpkgs/blob/2a205b0cdb744bc134134f82f3e9129ac3d7e981/nixos/modules/system/boot/networkd.nix#L376-L405

### Steps To Reproduce
N/A

### Expected behavior
Being able to use `linkConfig.ActivationPolicy = "manual"` on a wireguard network.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@flokli @rnhmjoj 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
Irrelevant
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- systemd.network.networks
```
