### ISSUE TITLE
cryptsetup cannot be built statically

### ISSUE THREAD

**Issue by alyssais** [NixOS/nixpkgs#134948]
```sh
nix-build -A pkgsStatic.cryptsetup
```

This would be useful for reducing initramfs size.  cryptsetup has a `--enable-static-cryptsetup` configure flag, so it should be possible!

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cryptsetup
# a list of nixos modules affected by the problem
module:
```
