### ISSUE TITLE
gnomeExtensions.arcmenu fails with a hash mismatch

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#134936]
### Describe the bug

```
nix-build -A gnomeExtensions.arcmenu.src
these derivations will be built:
  /nix/store/jin0n8f9vlvfac2zj1zsxwh7yp05z6df-source.drv
building '/nix/store/jin0n8f9vlvfac2zj1zsxwh7yp05z6df-source.drv'...

trying https://gitlab.com/api/v4/projects/arcmenu%2FArcMenu/repository/archive.tar.gz?sha=v12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1175k    0 1175k    0     0  1242k      0 --:--:-- --:--:-- --:--:-- 1241k
unpacking source archive /build/archive.tar.gz?sha=v12
hash mismatch in fixed-output derivation '/nix/store/8k7nq03khj5nrh2mr08mqzdyp2yw55zj-source':
  wanted: sha256:0h12ks0rvbs75d4qi8f4c6x0zaxddjrzdk05qwjj6cyqzw6r8ls7
  got:    sha256:097sm9w08mbh5p09zp26x27dsi909ydajx9f6mvg9wrz4yx6pv0w
error: build of '/nix/store/jin0n8f9vlvfac2zj1zsxwh7yp05z6df-source.drv' failed
```

Someone should investigate this (maybe the release was re-tagged?) and fix the hash mismatch in nixpkgs.

### Notify maintainers

cc @dkabot

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnomeExtensions.arcmenu
# a list of nixos modules affected by the problem
module:
```
