### ISSUE TITLE
ZFS kernel panic in 21.05

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#134914]
### Describe the bug

My NAS runs `21.05.20210721.63ee5cd (Okapi)`, with the stable ZFS package (version `2.0.5-1`). Yesterday, it kernel-panicked in ZFS block management code.

I traced the panic back to openzfs/zfs#11531, which was fixed by https://github.com/openzfs/zfs/commit/a81b812495a20623a49c797d255ee5d89fc38790 and released in ZFS 2.1.0, but not backported to 2.0.x.

I filed https://github.com/openzfs/zfs/issues/12494 to request a backport + 2.0.6 release upstream, so that downstream distros can pull the fix without having to upgrade a stable OS release to ZFS 2.1. I have no idea if the OpenZFS project continues maintaining prior minor releases for a while, or if they'll say that downstream distros should import the patch if they care.

Filing this bug to track either importing ZFS 2.0.6 if such a release happens, or to consider backporting the panic fix into NixOS as a downstream patch on 2.0.5.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - linuxPackages.zfs
  - linuxPackages.zfsStable
# a list of nixos modules affected by the problem
module:
```
