### ISSUE TITLE
Yubikey Luks encryption salt should be stored in the initramfs instead of a separate filesystem

### ISSUE THREAD

**Issue by dedsm** [NixOS/nixpkgs#135462]
### Describe the bug
Right now the only option for storing the salt of the challenge for yubikey+luks encrypted devices is in another filesystem, I've been using the EFI partition for this and in less than a week of using NixOS I've been locked out of the system because of a corruption in the vfat partition due to (I think) hibernation.

Coincidentally, the only file that gets corrupted is the one with the salt for the decryption of the device.

### Steps To Reproduce
1. Use the yubikey + luks encryption as described in the wiki https://nixos.wiki/wiki/Yubikey_based_Full_Disk_Encryption_(FDE)_on_NixOS
2. damage (or change) the salt in the storage path
3. reboot and suffer

### Expected behavior
If we can include the salt in the configuration.nix itself and use it to store it in the initrd instead of having to mount a filesystem in the boot process, we could skip this issue, with the bonus that everything could be handled inside nix files.

An example of this working is how Archlinux handles it: https://github.com/agherzan/yubikey-full-disk-encryption

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
boot.initrd.luks
```
