### ISSUE TITLE
avr-gcc isn't built on Hydra due to exceeding the log limit

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#135605]
### Describe the bug

`pkgsCross.avr.buildPackages.binutils` and `pkgsCross.avr.buildPackages.gcc` fail in this fashion: <https://hydra.nixos.org/build/150135872>. This seems to have started to happen in December of last year (see <https://hydra.nixos.org/job/nixpkgs/cross-trunk/avr.buildPackages.gcc.x86_64-linux/all>).

This effectively means that using the avr toolchain in nixpkgs means re-compiling gcc on every channel update.

Not sure what is causing the log size, unfortunately there's no special hydra meta attr to change the log limit.

cc @matthewbauer @Ericson2314 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsCross.avr.buildPackages.binutils pkgsCross.avr.buildPackages.gcc 
# a list of nixos modules affected by the problem
module:
```
