### ISSUE TITLE
Run passthru.tests on hydra

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#136026]
Run passthru.tests on hydra, so we can spot failures there and make the [fetchgit tests](#136022) a channel blocker.

This adds approximately 400 derivations for `x86_64-linux` and presumably slightly smaller amounts for other `systems`. The tests are usually sanity checks written by us, so they are generally quick. Their outputs are virtually empty.

This could work like `packageTests` in #136022 but with special handling of
 - license, to avoid uploading illegal deps
 - hydraPlatforms, to avoid attempts to build on unsupported `system`s
 - more?

Possible solutions:
 a. copy the relevant meta stuff while constructing `pkgs.packageTests`. Add `recurseIntoAttrs`.
 b. use the same traversal but apply it to all of `release.nix` instead of using `recurseIntoAttrs`.

The latter seems more elegant, as it reuses existing hydra-adjacent logic.

### Notify maintainers

@edolstra @grahamc

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: packageTests
# a list of nixos modules affected by the problem
module:
```
