### ISSUE TITLE
wafHook does not correctly honor NIX_BUILD_CORES

### ISSUE THREAD

**Issue by panicgh** [NixOS/nixpkgs#136368]
### Describe the bug
`wafHook` does not correctly honor `NIX_BUILD_CORES`. `wafHook` assumes `waf`, like `make`,  builds single jobs, unless parallel build is enabled with `-j <NUM>`. However, `waf` **by default** builds in parallel using all available CPU cores, unless overridden with `-j <NUM>`.

This leads to the unexpected situation where `enableParallelBuilding=false`, but the build is actually parallel using all available cores. All CPU cores are used, even when `NIX_BUILD_CORES=1` (e.g. via `nix-build --cores 1 ...`). Only when `enableParallelBuilding=true` and `NIX_BUILD_CORES=1`, the build is sequential using only 1 CPU core. This is counter-intuitive.

### Steps To Reproduce
1. Choose a package that uses `wafHook`, for example `hamster`.
2. Open `top`/`htop` in another terminal to observe CPU usage.
2. Build the package: `nix-build '<nixpkgs>' -A hamster --max-jobs 1 --cores 1 --check`
3. Observe that all CPUs are fully used and that there is no `-j 1` option among the reported `build flags`:
```console
$ nix-build '<nixpkgs>' -A hamster --max-jobs 1 --cores 1 --check
...
'configure' finished successfully (0.173s)
building
build flags: build
Waf: Entering directory `/build/source/build'
[  1/310] Compiling help/cs/cs.po
[  2/310] Compiling help/da/da.po
...
``` 

### Expected behavior
If `enableParallelBuilding=false`, the build shall use only 1 core and `-j 1` shall be among the build flags.

If `enableParallelBuilding=true`, the build shall use `NIX_BUILD_CORES` cores and `-j ${NIX_BUILD_CORES}` shall be among the build flags.

Packages that use `wafHook` probably should also set `enableParallelBuilding=true`.

### Notify maintainers
@vrthra 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.05.2717.bc1a0f56812 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2717.bc1a0f56812"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - gaia
  - blockhash
  - glmark2
  - patchage
  - saldl
  - weighttp
  - clasp-common-lisp
  - semantik
  - aubio
  - ndn-cxx
  - ganv
  - ldb
  - non
  - ntk
  - raul
  - lilv
  - lv2
  - lvtk
  - serd
  - sord
  - sratom
  - suil
  - talloc
  - ntdb
  - tdb
  - tevent
  - ams-lv2
  - ardour
  - ardour_5
  - guitarix
  - fomp
  - hamster
  - jalv
  - kupfer
  - mda_lv2
  - mpv-unwrapped
  - pflask
  - xiphos
  - ingen
  - ns-3
  - jack2
  - wxmupen64plus
# a list of nixos modules affected by the problem
module:
```
