### ISSUE TITLE
nixos/modules/system/boot/binfmt: systemd-binfmt does not have a reload trigger on /etc/binfmt.d/nixos.conf

### ISSUE THREAD

**Issue by kittywitch** [NixOS/nixpkgs#136499]
### Describe the bug
The systemd service "systemd-binfmt" does not have a reload trigger on `/etc/binfmt.d/nixos.conf`.

### Steps To Reproduce
1. Add additional architectures to `boot.binfmt.emulatedSystems` after having a first one already in your config.
2. Apply the new config.
3. Registrations do not get created, run `ls /proc/sys/fs/binfmt_misc/` to confirm.
4. Run `systemctl restart systemd-binfmt`
5. Re-run the ls command in step 3.
6. You should now see your new architecture.

### Expected behavior
When new emulatedSystems are added, systemd-binfmt should be restarted automatically with a trigger.

### Additional context
This means that builds for a new architecture will fail despite you adding the entry to emulatedSystems.

### Notify maintainers

@ngkz was the last person who touched this module. That might make them a maintainer?

### Metadata

```console
nixfiles on  main [$!+?] via ❄️  impure (nix-shell) 
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.11, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-20.09.2555.41dddb12837"`
 - channels(kat): `""`
 - nixpkgs: `/nix/store/cbhmgg1x1gsha7l1wf9yhpvxj6mv2pw2-nixpkgs-src`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - nixos/modules/system/boot/binfmt.nix
```
