### ISSUE TITLE
gitlab: Does not rotate log files

### ISSUE THREAD

**Issue by yayayayaka** [NixOS/nixpkgs#136723]
### Describe the bug
The gitlab service does rotate its log files which has potential of filling up the partition. 

### Steps To Reproduce
1. `services.gitlab.enable = true;`
2. Do something that causes a lot of logs to be written.
3. Eventually the partition runs full.

### Expected behavior
Rotation of the logs similar to [omnibus](https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/files/gitlab-cookbooks/gitlab/attributes/default.rb#L754)

### Notify maintainers

@fpletz @globin @krav @talyz @yu-re-ka

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - nixpkgs: `/etc/src/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: gitlab
```
