### ISSUE TITLE
python37.pkgs.pyroma: test fails with segmentation fault

### ISSUE THREAD

**Issue by charlieshanley** [NixOS/nixpkgs#136901]
### Describe the bug
A test for the python package `pyroma` produces a segmentation fault under Python 3.7.

### Steps To Reproduce
```
nix-shell -p python37.pkgs.pyroma -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/9fe0b74ae40c4e83552aed1df137e379e64b3680.tar.gz
```
Use `--check` if somehow it is already in your nix store.
By comparison, building succeeds if I change `37` to `38` or `39`.

### Expected behavior
Successfully builds and tests, or problematic tests disabled.

### Additional context
I encountered this because `pyroma` is a transitive dependency of `python37.pkgs.google-api-python-client`, via this path:
`pyroma -> Pillow -> faker -> pytest-randomly -> httplib2 -> google-api-python-client`

### Notify maintainers

@fabaff -- not listed in maintainers but recently worked on `pyroma`s nixpkgs expression.

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.05.2680.871e8c4d585 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.05.2796.110a2c9ebbf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python37.pkgs.pyroma
# a list of nixos modules affected by the problem
module: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pyroma/default.nix
```
