### ISSUE TITLE
gitlab: Does not render `.rst` files

### ISSUE THREAD

**Issue by tomprince** [NixOS/nixpkgs#137021]
### Describe the bug
The gitlab services does not render `.rst` files by defaullt

### Steps To Reproduce
1. `services.gitlab.enable = true;`
2. Look at a `.rst` file in a repository
3. Notice that the output is plain text

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
