### ISSUE TITLE
metasploit no longer builds on unstable

### ISSUE THREAD

**Issue by buckley310** [NixOS/nixpkgs#137125]
### Describe the bug
Metasploit no longer builds when pulled from unstable branch.

### Steps To Reproduce
`nix run nixpkgs/nixos-unstable#metasploit`

### Additional context
The commit https://github.com/NixOS/nixpkgs/commit/ee79ba102299e06b0b3d2cde443c85282a6a8588 seems to be the point at which it stops building.
[Example of failing build](https://github.com/NixOS/nixpkgs/files/7131266/build.txt)

This fails for me:
`nix run nixpkgs/ee79ba102299e06b0b3d2cde443c85282a6a8588#metasploit`
This runs as expected:
`nix run nixpkgs/c0e1f01e435e69be409a98d92934a51495ceb2c4#metasploit`

### Notify maintainers
@makefu

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.61, NixOS, 21.05.20210902.6bfe71f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    metasploit
# a list of nixos modules affected by the problem
module:
```
