### ISSUE TITLE
NixOS always imports all modules

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#137168]
### Describe the bug

NixOS always imports all modules, leading to degrading performance as NixOS grows.

### Steps To Reproduce
1. Add many modules
2. Watch performance drop

But to really see the potential:

1. Make significant cuts in `modules-list.nix` and fix a few broken options references
2. Watch instantiation of `toplevel` go down from 4.0 to 1.4 seconds.

### Expected behavior

New modules don't reduce NixOS evaluation performance. NixOS can scale in complexity.

### Additional context

I'll probably write an RFC suggesting the required refactorings and module authoring guidelines. This can all be achieved in a backcompatible manner, but the performance gains may be require some opting in.

### Notify maintainers

@Infinisil 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nixos
 - lib.nixosSystem
# a list of nixos modules affected by the problem
module: # most of them
```
