### ISSUE TITLE
jdk16: No release version is packaged

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#138219]
### Describe the bug
jdk16 packages tag jdk-16+36 which is not a released version. Latest released version is 16.0.2+7

/cc @petabyteboy @taku0 @edwtjo , can you comment on that?

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
* jdk16
# a list of nixos modules affected by the problem
module:
```
