### ISSUE TITLE
libinput configuration not respected

### ISSUE THREAD

**Issue by eadwu** [NixOS/nixpkgs#138437]
### Describe the bug
Tap-to-click becomes more like tap-and-drag.

### Steps To Reproduce
Enable tap-to-click on libinput and witness tap-and-drag like behavior without enabling it. Tap-and-drag no longer works for highlighting.

### Expected behavior
Tap-to-click is tap-to-click, not tap-and-drag.

### Additional context
Same as https://github.com/NixOS/nixpkgs/issues/138435, appeared at the same time.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
