### ISSUE TITLE
Broken 8021x auth with iwd (eduroam)

### ISSUE THREAD

**Issue by eadwu** [NixOS/nixpkgs#138435]
### Describe the bug
Unable to connect to eduroam after a recent upgrade. Errors out with `key addition failed`, no other useful information, even with `IWD_TLS_DEBUG`.

Sadly I probably will be very slow to respond to any testing, simply don't have the time to worry about this, I'm sticking with the generation that works.

### Steps To Reproduce
```bash
iwctl
> station ... connect eduroam
>> username
>> password
Operation failed
```

### Expected behavior
To connect.

### Additional context
Use to work on 177c0befbce07b4a7d7471628f4c6d2f3a2f4262, broke on the next upgrade (I don't have exact commit anymore but it should have been somewhere near the 1000 commits pushed to master.

This is not due to a iwd upgrade (1.17), since I had it working with that so at least that variable is gone.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
