### ISSUE TITLE
smokeping: service can't find `fping6`, fails to build system

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#138581]
### Describe the bug
On a system with `services.smokeping.enable = true;` enable build now fails as:

```
nixpkgs-master $ nix build --no-link -f nixos system --keep-going
...
Checking that Nix store paths of all wrapped programs exist... FAIL
The path /nix/store/kr2sr80g9ny74im6m6dyh9v44hnzm261-fping-5.0/bin/fping6 does not exist!
Please, check the value of `security.wrappers."fping6".source`.
```

I suspect it started happening after `fping` package stopped providing `fping6` binary.

### Notify maintainers

@erictapen 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fping
# a list of nixos modules affected by the problem
module: services.smokeping
```
