### ISSUE TITLE
azure-functions-core-tools unable to interface with azure

### ISSUE THREAD

**Issue by bluescreen303** [NixOS/nixpkgs#139102]
### Describe the bug

Azure Functions Core Tools in nixpkgs is great for developing Functions locally, however all functionality to get/publish settings from a Function running on Azure or to publish an app itself doesn't seem to work.

### Steps To Reproduce
```
$ az functionapp show --resource-group foobar --name foobar
```
_output that shows that azure cli is logged in and able to see the functionapp resource_
```
$ func azure functionapp fetch-app-settings foobar
```
_No such ffile or directory_

### Expected behavior

this should have responded with the app settings for the _foobar_ function

### Notify maintainers

@jshcmpbll 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - nixpkgs: `/home/mathijs/Projects/nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- azure-functions-core-tools
# a list of nixos modules affected by the problem
module:
```
