### ISSUE TITLE
networking.tempAddresses = "disabled" and networking.networkmanager

### ISSUE THREAD

**Issue by benneti** [NixOS/nixpkgs#139306]
### Describe the bug
When setting `networking.tempAddresses = "disabled"` I would expect this to be respected even when enabling networkmanager.
But I think the 
```
[connection]
ipv6.ip6-privacy=2
```
in the default networkmanager configuration overrides this

### Steps To Reproduce
1. networking.tempAddresses = "disabled";
2. networking.networkmanager.enable = "true";
3. check ip

### Expected behavior
respect global setting

### Additional context
manually adding 
```
[connection]
ipv6.ip6-privacy=0
```
to networking.networkmanager.extraConfig works
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: networking.networkmanager.enable networking.tempAddresses
```
