### ISSUE TITLE
Pantheon: Session Crash when i try to take a screenshot

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#139404]
### Describe the bug
When i try to take a screenshot of an area (STRG + PRINT), i hear the bell notification sound (that also comes when the disk is full) and nothing more happens (no screenshot). The third time i tried, the whole session crashed!

I actually have a video of it: https://www.youtube.com/watch?v=uSOar6HBNTs

### Steps To Reproduce
1. take screenshot with STRG + PRINT (not tested other methods)
2. ???
3. session crash

### Expected behavior
actually taking screenshot

### Screenshots
that's  the issue ;)

### Additional context
Issue appeared after https://github.com/NixOS/nixpkgs/pull/139163

### Notify maintainers
@bobby285271 

can you reproduce or should i get a log?

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"home-manager-21.05, nixos-21.05.1574.4181644d09b, nixos-hardware, nixos-unstable-21.11pre302615.967d40bec14"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
