### ISSUE TITLE
split python packages install more outputs than requested

### ISSUE THREAD

**Issue by pennae** [NixOS/nixpkgs#139756]
### Describe the bug

when installing only one output of a python package, eg with `environment.systemPackages = [ kitty.terminfo ]`, all output of the package are installed. this seems to be limited to python packages (and possibly other users of `lib.extendDerivation`?) and can be fixed by overriding the output in question to set `outputUnspecified = false` so that buildEnv does not ignore the request, so it seems that maybe installing everything all the time is not entirely expected behaviour?

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre318500.51bcdc4cdaa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
