### ISSUE TITLE
dockerTools: prune and improve examples

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#139895]
### Describe the bug

The dockerTools examples are bad.

 - It has too many examples that are really only test cases and
 - it abuses `contents` in one or more instances. It is for adding to the filesystem root, not for adding/combining packages. Use `buildEnv` for that.

### Expected behavior

Examples are correct, representative and focused.
Test cases are in a separate file.
The examples are still tested.

### Notify maintainers

@roberth @utdemir 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - dockerTools
 - dockerTools.examples
# a list of nixos modules affected by the problem
module:
```
