### ISSUE TITLE
Poetry source link on https://search.nixos.org is pointing to poetry2nix

### ISSUE THREAD

**Issue by imincik** [NixOS/nixpkgs#139951]
### Describe the bug
"Source" link in search result on https://search.nixos.org for Poetry package is pointing to poetry2nix source code instead of poetry.

### Steps To Reproduce
1. [Search for poetry](https://search.nixos.org/packages?channel=21.05&from=0&size=50&sort=relevance&type=packages&query=poetry)
2. Click on "Source" link in "poetry" package. This will point you to [poetry2nix](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/development/tools/poetry2nix/poetry2nix/default.nix#L344) instead of [poetry](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/poetry/default.nix)

### Expected behavior
When clicking on "Source" link in "poetry" package search results I want to get to "poetry" source code

### Notify maintainers

@adisbladis

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
