### ISSUE TITLE
nginx: lua can't run with the current hardening

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#140655]
### Describe the bug

I'm using lua with `services.nginx.package = pkgs.openresty;` and after updating to 21.05 I got:

```
oct 05 13:22:09 nixos nginx[652194]: nginx: lua atpanic: Lua VM crashed, reason: runtime code generation failed, restricted kernel?
```

### Notify maintainers

@mweinelt 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.70, NixOS, 21.05.3513.d550d4ebd5f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3513.d550d4ebd5f"`
 - channels(bbigras): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
