### ISSUE TITLE
rocm-opencl-runtime: broken patch URL

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#140674]
### Describe the bug

The patch URL introduced in https://github.com/NixOS/nixpkgs/commit/2549800a1a83c7fa6f639e915545042667c98789#diff-d7683eb7d8a667d71db5ab39a89a1330d04f1d6c67898983903a4a64e698a7d4R36 is broken (404 Not Found).

The patch is of https://reviews.llvm.org/rG884040db086936107ec81656aa5b4c607235fb9a
but the diff URL seems to be unstable. Maybe consider adding the patch to nixpkgs?

### Steps To Reproduce
1. Checkout nixpkgs master 807370df9481804598f06c9e17020cdb7f974a18
1. `nix-build . -A rocm-opencl-runtime`

```
trying https://reviews.llvm.org/file/data/nrhbpc5axblqwx2xyyzv/PHID-FILE-wwcpjvquusomoddmqcwo/file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```

### Expected behavior

It builds.

### Notify maintainers

@Princemachiavelli 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - rocm-opencl-runtime
# a list of nixos modules affected by the problem
module:
```
