### ISSUE TITLE
apache-airflow fails to build with python-slugify >=5.0

### ISSUE THREAD

**Issue by r-burns** [NixOS/nixpkgs#141213]
### Describe the bug
As of https://github.com/NixOS/nixpkgs/pull/126255, apache-airflow fails to build due to the constraint here:

https://github.com/apache/airflow/blob/2.1.4/setup.cfg#L143

### Notify maintainers
@bhipple @costrouc @ingenieroariel

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: apache-airflow
# a list of nixos modules affected by the problem
module:
```
