### ISSUE TITLE
nixosTest closure too big for headless tests

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#142036]
### Describe the bug

NixOS tests include graphical bells and whistles by default.
When the vm testing infrastructure is used out-of-tree, this causes more "build" dependencies to be downloaded than necessary.
This pain is mostly felt in external projects, but will also speed up non-graphical tests within NixOS.

### Steps To Reproduce
1. Invoke `nixosTest` in an external project which uses its own commit of nixpkgs
2. Observe that a bunch of graphical libs and tools are downloaded

### Expected behavior

NixOS tests are non-graphical by default. Only graphical use results in download of graphical dependencies.

### Notify maintainers

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nixosTest
 - nixosTests
# a list of nixos modules affected by the problem
module:
```
