### ISSUE TITLE
`nginx` test failing

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#142184]
### Describe the bug

A failure in NixOS test `nginx`.

https://github.com/NixOS/nixpkgs/pull/140792/checks?check_run_id=3936367258

### Steps To Reproduce
1. `nix-build -A nixosTests.nginx`

### Notify maintainers

@thoughtpolice @7c6f434c @fpletz @globin @ajs124 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nixosTests.nginx
# a list of nixos modules affected by the problem
module:

```
