### ISSUE TITLE
phpstorm: Doesnt uses Jetbrains JRE

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#142550]
### Describe the bug
PhpStorm warns about that the Jetbrains JRE is not used

### Steps To Reproduce
- Install jetbrains.phpstorm
- Open it
- See the warning

### Screenshots
![image](https://user-images.githubusercontent.com/6224096/138425158-9110a12b-635c-43bf-b70b-e46352d1f11b.png)

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.12, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11pre323790.5f0194220f2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: jetbrains.phpstorm
# a list of nixos modules affected by the problem
module:
```
