### ISSUE TITLE
shogun fails to build on master

### ISSUE THREAD

**Issue by r-burns** [NixOS/nixpkgs#142811]
### Describe the bug
shogun fails to build since the eigen 3.4.0 bump: https://hydra.nixos.org/build/155318500

### Additional context
The package is a likely candidate for removal. Upstream is unresponsive and development has halted. 

Removed from debian: https://tracker.debian.org/news/1087653/removed-320-9-from-unstable/
Removed from fedora: https://src.fedoraproject.org/rpms/shogun/c/fad4614ae86b308901a0e670ffbeaeb9267af569?branch=rawhide
Blocking vcpkg update: https://github.com/microsoft/vcpkg/pull/19665#issuecomment-938021896 https://github.com/shogun-toolbox/shogun/issues/4870#issuecomment-936086582

### Notify maintainers
@edwtjo

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: shogun
# a list of nixos modules affected by the problem
module:
```
