### ISSUE TITLE
mingw cross compilation is broken

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#144126]
### Describe the bug
Attempting to use `pkgsCross.mingwW64.stdenv.cc` to cross-compile a simple Hello World program fails with a linker error.

### Steps To Reproduce
1. Write a simple C program, `hi.c`
2.  `nix run -f ~/nixpkgs pkgsCross.mingwW64.stdenv.cc -c x86_64-w64-mingw32-cc hi.c
2. Observe that it fails:
   ```
   /nix/store/40hb0cp3xl4cr14zxdp8lr5kf9lb594w-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: cannot find -lmcfgthread
   collect2: error: ld returned 1 exit status
   ```

### Expected behavior
It should produce an executable

### Additional context
Tested with `nixpkgs` from late September (7728136201023022493e85e790ccc719516aab3c).

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
