### ISSUE TITLE
python3Packages.blspy: broken

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#144209]
### Describe the bug
Since #141684, the package cannot build.

### Steps To Reproduce
1. `nix build nixpkgs#python3Packages.blspy`
2. `importsCheckPhase` fails with
```
ImportError: /nix/store/cc6vwnq87hpgywihdn55ajf96lhwfqvi-python3.9-blspy-1.0.6/lib/python3.9/site-packages/blspy.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3bls9GTElement4SIZEE
```

### Expected behavior
Package builds

### Additional context
I believe this is just a matter of definition-vs-declaration semantics in different versions of the C++ standard. I will submit a patch upstream and backport

### Notify maintainers
@lourkeur @Atemu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/nix/store/8m51fq11k6nrgvqiphjxrdgy701bmpzm-source`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - python3Packages.blspy
  - chia
# a list of nixos modules affected by the problem
module:
```
