### ISSUE TITLE
Unknown group Controller in /etc/bluetooth/main.conf

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#144457]
### Describe the bug
Bluez complains on startup as visible in `systemctl status bluetooth`:

```
src/main.c:check_config() Unknown group Controller in /etc/bluetooth/main.conf
```

### Steps To Reproduce
1. Restart bluez with `sudo systemctl restart bluetooth`
2. Notice the error in `systemctl status bluetooth`

### Expected behavior
There should be no error

### Additional context
Looks like the `Controller` group comes from

https://github.com/NixOS/nixpkgs/blob/9355b0fd0c7e2d5d7b777516f9fecbd219118785/nixos/modules/services/hardware/bluetooth.nix#L18

It has been introduced in https://github.com/NixOS/nixpkgs/commit/1a4c039432f742be58d400dd596eacad8cb2348b.

Apparently, the group has been removed in bluez 5.56: https://github.com/bluez/bluez/commit/8c6373667aebae94722eb1960434231528b51f3f#diff-0563b576b81c9cf4e2f2e53e4290b2a8434484de67677c8b30c3b4fcd048188c

### Notify maintainers
cc @peterhoeg 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: bluez
# a list of nixos modules affected by the problem
module: bluetooth
```
