### ISSUE TITLE
guitarix messes up system fonts

### ISSUE THREAD

**Issue by YodaEmbedding** [NixOS/nixpkgs#144595]
### Describe the bug
Some fonts are no longer detected by `alacritty` when `guitarix` is installed to system.

### Steps To Reproduce

1. Install `guitarix` and `alacritty`

Alternatively, clone from this `/etc/nixos` commit:
https://github.com/YodaEmbedding/nixos/commit/43e58103cece8c58470bc295bfa43a8fc4dabe9e

2. Change `~/.config/alacritty/alacritty.yml` to:
```yaml
font:
  normal:
    family: Iosevka
```

3. Start a new alacritty terminal and see that the font is wrong.

### Expected behavior
Correct fonts.

### Screenshots
N/A

### Additional context
https://github.com/NixOS/nixpkgs/blob/9d7df9dcc33a497e840062bb989962d5135d7aa5/pkgs/applications/audio/guitarix/default.nix#L102-L109

Potentially problematic lines:
```nix
    "--no-font-cache-update"
    "--install-roboto-font"
```

### Notify maintainers
@astsmtl, @cillianderoiste (goibhniu)

### Metadata
```console
λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.73, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11pre323790.5f0194220f2"`
 - channels(mulhaq): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: guitarix
# a list of nixos modules affected by the problem
module:
```
