### ISSUE TITLE
nixosTest testScript could be typechecked

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#144876]
### Describe the enhancement

More programming mistakes in `nixosTest` `testScript` can be caught early.

### Steps To Reproduce
1. Make a typo in a machine method name near the end of a long test, e.g. `machine.succed`
2. Run the test
3. Wait for the test to complete
4. Discover the silly mistake and reflect on the way you're spending your life

### Expected behavior

We already run mypy but it appears that we don't have enough types or the machine variables aren't typed.

### Notify maintainers

Not sure, maybe @tfc @andir

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nixosTest
 - nixosTests
# a list of nixos modules affected by the problem
module:
```
