### ISSUE TITLE
Gitea module creates system user and group without reproducible UID/GID

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nixpkgs#145014]
### Describe the bug
Gitea module creates system user and group without reproducible UID/GID.

### Expected behavior
Every user and group should be created with a statically defined UID/GID.

### Additional context
Unfortunately, defining a value now would result in a breaking change. What would be the best way to handle this?

### Notify maintainers

@srhb @ma27 @disassembler @bjornfor 

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.gitea
```
