### ISSUE TITLE
Screen sharing does not work on kde wayland + pipewire

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#145174]
### Describe the bug
When in a KDE wayland session with pipewire enabled nor firefox nor OBS' pipewire screen sharing does not show.
Weirdly only Spectacle works for screen capture.

### Steps To Reproduce
1. Open KDE plasma session
2. https://mozilla.github.io/webrtc-landing/gum_test.html
3. Try and fail to screen capture

### Expected behavior
![image](https://user-images.githubusercontent.com/6931743/140888617-48c6a4a3-86b0-41c1-b8ce-722d1626125f.png)

### Additional context

https://bugs.kde.org/show_bug.cgi?id=437529 suggest "compiling in an environment with pipewire" but adding pipewire to `xdg-desktop-portal-kde.buildInputs` does not fix this

### Notify maintainers
@peterhoeg  @jtojnar @kranzes @ttuegel @nyanloutre

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.77, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"nixos-21.05.3801.83667ff60a8"`
 - nixpkgs: `/nix/store/94hsmqk3nrx26yd46crlw5aygiya6pj4-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
 - xdg-desktop-portal-kde
 - obs
 - pipewire
# a list of nixos modules affected by the problem
module:
 - services.pipewire
 - services.xserver.desktopManager.plasma5
```
