### ISSUE TITLE
cinnamon settings gnome-online-accounts is broken

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#146507]
### Describe the bug
Adding an account crashes cinnamon-settings with

```
** (cinnamon-settings.py:34700): ERROR **: 17:57:40.026: GApplication is required for xdg-desktop-portal access in the WebKit sandbox.
```

### Steps To Reproduce
1. cinnamon-settings online-accounts
2. Click on any account that requires a web sign in (google for ex)
3. crash

### Expected behavior
No crash

### Notify maintainers
@ myself

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- cinnamon.cinnamon-settings
# a list of nixos modules affected by the problem
module:
```
