### ISSUE TITLE
fuloongminipc cross stdenv fails to build

### ISSUE THREAD

**Issue by r-burns** [NixOS/nixpkgs#146842]
Since https://hydra.nixos.org/build/109284492, `pkgsCross.fuloongminipc.buildPackages.gccCrossStageStatic.cc` has failed during the gcc testsuite build with:
```
cc1: error: no include path in which to search for stdc-predef.h
```

The regression bisected to the gcc 8 ->  9 bump (more specifically, https://github.com/gcc-mirror/gcc/commit/8ae8bad7e558ce916c52e91a4e1879557f287bbc)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gcc
# a list of nixos modules affected by the problem
module:
```
