### ISSUE TITLE
Sway refuses to start

### ISSUE THREAD

**Issue by cid-chan** [NixOS/nixpkgs#146912]
### Describe the bug
I am using LightDM as a Display Manager.  When I try to log in, I get a black screen before being dropped back into LightDM.

I can see this in the log after I selected a previous generation:
```
Nov 21 19:04:28 cid-chan xsession[3074]: 00:00:00.283 [ERROR] [sway/config/output.c:417] Failed to commit output eDP-1
```

Known Working Commit:
> e544ee88fa4590df75e221e645a03fe157a99e5b

First known Broken Commit:
(Earlier commits might be broken, too)
> c935f5e0add2cf0ae650d072c8357533e21b0c35

### Expected behavior
I log in and sway starts.

### Notify maintainers
@primeos 
@colemickens 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.3, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/run/current-system/sw/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- sway
# a list of nixos modules affected by the problem
module:
```
