### ISSUE TITLE
wpa_supplicant: wpa_dbus_property_changed errors

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#147219]
### Describe the bug
wpa_supplicant produces the following errors:

```
dbus: wpa_dbus_property_changed: no property RoamTime in object /fi/w1/wpa_supplicant1/Interfaces/0
dbus: wpa_dbus_property_changed: no property RoamComplete in object /fi/w1/wpa_supplicant1/Interfaces/0
```

### Steps To Reproduce
IDK how to reliably reproduce this behavior cause it's definitely dependent on the wireless environment.

### Expected behavior
There should be no errors logged

### Notify maintainers
cc @globin @rnhmjoj

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.20, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/nix/store/ixpnxqyishs7xp7sz2dpjx960pszpfwc-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: networking.wpa_supplicant
```
