### ISSUE TITLE
nixos/virtualisation.vmware-guest: automatic resolution switching not working

### ISSUE THREAD

**Issue by krav** [NixOS/nixpkgs#147261]
### Describe the bug

The `vmtoolsd` service seems to be executed before the `vmwgfx` module is loaded, causing automatic modeswitching not to be enabled.

The following is seen in the `vmware-vmsvc-root.log`:

```
[ warning] [resolutionCommon] [719] resolutionCheckForKMS: No system support for resolutionKMS.
```

Restarting `vmware.service` after login resolves the problem, as does adding the following to the guest's configuration:
 
`systemd.services.vmware.after = lib.mkForce [ "display-manager.service" ];`

### Steps To Reproduce
1. Start a nix guest with X11 enabled in vmware fusion
2. In windowed mode, resize window by dragging
3. Window appears stretched/blurry or centered in window (dependent on host configuration).

### Expected behavior
Display resolution is automatically switched to match dimensions of window.

### Notify maintainers

@joamaki 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.80, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11pre333218.263ef4cc414"`
 - channels(krav): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.open-vm-tools
# a list of nixos modules affected by the problem
module: nixos.virtualisation.vmware-guest
```
