### ISSUE TITLE
`yescrypt` user passwords do not function

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#147312]
### Describe the bug
When setting roots `hashedPassword` to a `yescrypt` hash, login becomes seemingly impossible even with the correct password. All else being equal, sha512crypt does not exhibit this problem.

### Steps To Reproduce
1. build this virtual machine: https://gist.github.com/lourkeur/771d190aeb026dba2a60897eab90de57
2. log in as root with password test
3. Womp womp

### Expected behavior
Access should be granted iff the password is correct.

### Additional context
This is a bit concerning given that yescrypt is now the `mkpasswd` default since #143661.

Should `pam` be built with the `withLibxcrypt` flag? If so how?

### Notify maintainers

For `pam`+`libxcrypt` interaction @dottedmag 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
