### ISSUE TITLE
unbound-full is broken on unstable

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#147358]
### Describe the bug
unbound-full cannot be built on the unstable channel
error message:

```
/nix/store/js66s0xwjnzg0ggi2lq9bcvlk6x2za13-binutils-2.35.2/bin/ld: /build/testbound.vQYPwg.ltrans11.ltrans.o: in function `dtio_output_cb':
/build/unbound-1.13.2/dnstap/dtstream.c:1488: undefined reference to `dtio_disable_brief_write'
```

### Steps To Reproduce
1. nix build .#unbound-full

### Expected behavior
It should obviously build

### Notify maintainers
cc @ehmry @fpletz @globin

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: unbound-full
# a list of nixos modules affected by the problem
module:
```
