### ISSUE TITLE
networking.hostFiles not working

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#147589]
### Describe the bug
In my config I have `networking.hostFiles=[ ./mvn.hosts ];` and when building it gives me the following error:
```
nix log /nix/store/xsg1gi465km5l6zv0z32m8q8m137q818-hosts.drv
cat: /nix/store/1dmmrmi6yncn4j2ymmqziag8fflq8jiw-source/mvn.hosts: No such file or directory
```

However if I replace it with `networking.extraHosts = builtins.readFile ./mvn.hosts;` it builds without errors.

Even weirder, If I do `cat /nix/store/1dmmrmi6yncn4j2ymmqziag8fflq8jiw-source/mvn.hosts` it works without problems.

### Expected behavior
The configuration builds normally

### Notify maintainers
@Infinisil 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - nixpkgs: `/nix/store/8gnhm8ws354wzqd1mkapra14qk7bnc40-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
 - networking.hostFiles
```
