### ISSUE TITLE
Issue with discord on firefox

### ISSUE THREAD

**Issue by baronleonardo** [NixOS/nixpkgs#147687]
### Describe the bug
I tried discord web version on `firefox`, `firefox-wayland` and `firefox-bin`
- firefox-waylan:
    - no voice, no camera, no audio and no screen sharing
    - it stuck with `RTC connecting`
- firefox:
    - voice only works in `test voice`
    - camera only works in `test camera`
    - no audio and no screen sharing
    - it stuck with `RTC connecting`
-firefox-bin:
    - everything works fine

### Steps To Reproduce
1. open firefox
2. login to you discord account
3. start voice/video calls with/without screensharing

### Expected behavior
I expect that both firefox, and firefox-wayland to work the same like firefox-bin

### Additional context
- I disabled firewall but that didn't solve anything

### Notify maintainers
@hexa @taku0 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.3, NixOS, 21.05.4349.09650059d7f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
firefox
firefox-wayland
attribute:
# a list of nixos modules affected by the problem
module:
```
