### ISSUE TITLE
Adding a ZFS ZPool to a system can drop you to an emergency shell unexpectedlty

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#147783]
### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
