### ISSUE TITLE
basename of writeFile does not equal passed name

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#147769]
### Describe the bug

```
runCommand "test" {} ''
  cp ${writeText "foo.bar" ""} .
  mkdir -p $out
  mv foo.bar $out/
''
```

The above doesn't work because the basename of `outPath` includes the hash.

### Steps To Reproduce

Build the snippet above.

### Expected behavior

- `writeText` creates a directory in the store with the file inside
- `writeText` returns an `outPath` attr that is set to `"${old.outPath}/${name}"`
  This can be done with #119942

### Additional context

This function has siblings that behave the same.

Also mentioned in ##147690 

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - writeText
 - writeScript
 - concatText 
# a list of nixos modules affected by the problem
module:
```
