### ISSUE TITLE
dbus-python build missing python3 during build

### ISSUE THREAD

**Issue by dadada** [NixOS/nixpkgs#148195]
### Steps To Reproduce
1. nix build github:nixos/nixpkgs/nixos-unstable#legacyPackages.x86_64-linux.python27Packages.dbus-python 

### Expected behavior
Nix builds the derivation.

### Additional context
```
checking for python3... no
configure: error: Cannot find python3 in your system path
```

### Notify maintainers

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python27Packages.dbus-python
# a list of nixos modules affected by the problem
module:
```
