### ISSUE TITLE
Ceph Tests are broken on release-21.11 and master

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#148233]
### Describe the bug
All ceph tests are currently broken on release-21.11 and master.

https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.ceph-multi-node.x86_64-linux

First broken in https://hydra.nixos.org/build/158336811 (0a580f to 931ab0), likely due to a snappy update, like ededca048a93974703a77b4bae84e4fc9f509580). @Artturin 

```
load failed dlopen(): "/nix/store/kxkj80fiwbq2fsaps7dm98mp3wq87aw7-ceph-16.2.6-lib/lib/ceph/compressor/libceph_snappy.so: undefined symbol: _ZTIN6snappy6SourceE" or "/nix/store/kxkj80fiwbq2fsaps7dm98mp3wq87aw7-ceph-16.2.6-lib/lib/ceph/libceph_snappy.so: cannot open shared object file: No such file or directory"
create cannot load compressor of type snappy
```

### Steps To Reproduce
1. nix-build -A nixosTests.ceph-multi-node etc.

### Expected behavior
Tests should complete.

### Notify maintainers

@srhb 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nixosTests.ceph-multi-node, nixosTests.ceph-single-node, nixosTests.ceph-single-node-bluestore
```
