### ISSUE TITLE
appimage-run:  Could not initialize GLX (only in 21.11)

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#148377]
### Describe the bug

I just built a new 21.11 derivation using the same `configuration.nix` as my prior 21.05 derivations, with the exception of a few minor updates required by 21.11 patch notes.

I'm trying to run an AppImage using appimage-run (the [Blockstream Green](https://blockstream.com/green/) desktop Bitcoin wallet).  It never had problems in 21.05, but is failing to start in 21.11, with the error "Could not initialize GLX" (full logs linked below).

Reverting to a 21.05 derivation solves the problem and allows it to run.

This may be a problem with the app itself not being compatible with 21.11's GLX, not sure, but reporting just in case.

### Steps To Reproduce

1. In NixOS 21.11:
2. Install [appimage-run](https://search.nixos.org/packages?channel=21.11&show=appimage-run&from=0&size=50&sort=relevance&type=packages&query=appimage)
3.  Download the [Blockstream Green](https://blockstream.com/green/) app.
4. Run `appimage-run BlockstreamGreen-x86_64.AppImage`

### Expected behavior

The Blockstream Green GUI app should start in its own window.

### Screenshots

1. [console error log](https://pastebin.com/1CJu66py)
2. [full error log](https://pastebin.com/L88esReC)

### Notify maintainers

@symphorien
@prusnak 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

(submitting this bug report on 21.05, will add the 21.11 info shortly)

```
> nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.07 MiB download, 0.34 MiB unpacked):
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.20, NixOS, 21.05.4349.09650059d7f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.333896.a640d8394f3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/appimage/
https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/package-management/appimage-run
```
