### ISSUE TITLE
Wxpython fails to build

### ISSUE THREAD

**Issue by jakobneufeld** [NixOS/nixpkgs#148300]
### Describe the bug
When I use mach-nix to package a python app, wxWidgets fails to build.
### Steps To Reproduce
1. package a python app with mach-nix.
2. nix-build default.nix

### Expected behavior
wxWidgets works
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
