### ISSUE TITLE
lttng-modules broken on latest kernel

### ISSUE THREAD

**Issue by arkivm** [NixOS/nixpkgs#148558]
### Describe the bug

lttng-modules is broken on latest kernels due to deprecated API.
`get_online_cpus` and `put_online_cpus` were deprecated for a while and is finally removed in v5.15.
It is fixed upstream https://github.com/lttng/lttng-modules/commit/ffcc873470121ef1ebb110df3d9038a38d9cb7cb

I am avoiding the fix of pulling in as a patch just to remove it once we upgrade the version.
Hopefully, a new release is coming soon (They usually do one every 3-4 months).

Just keeping this issue here for now.

### Steps To Reproduce
1. Fails on hydra (https://hydra.nixos.org/build/159376052)

### Notify maintainers

@bjornfor

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
