### ISSUE TITLE
pcsclite ships a systemd service unit with an unreplaced ${prefix} variable

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#148538]
### Describe the bug

The `pcsclite` package installs `pcscd.service` that contains an unconfigured `prefix` variable:

```text
$ cat /etc/systemd/system/pcscd.service | grep EnvironmentFile
EnvironmentFile=-${prefix}/etc/default/pcscd
```

This results in the following message in system journal:

```text
systemd[1]: /etc/systemd/system/pcscd.service:9: EnvironmentFile= path is not absolute, ignoring: ${prefix}/etc/default/pcscd
```

Obviously, not critical, but still this doesn’t sound right.

The [upstream file](https://salsa.debian.org/rousseau/PCSC/-/blob/e1b1590c7f32e0353404967f457643d122367772/etc/pcscd.service.in#L9) contains `EnvironmentFile=-@sysconfdir@/default/pcscd`, so it looks like `@sysconfdir@` gets replaced by literal `${prefix}/etc/`, but I am not sure where this happens or why.

### Steps To Reproduce
1. `nix build nixpkgs#pcsclite`
2. `grep EnvironmentFile result-bin/lib/systemd/system/pcscd.service`

### Expected behavior
There should be no unsubstituted variables in the installed unit.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ pcsclite ]
# a list of nixos modules affected by the problem
module:
```
