### ISSUE TITLE
DBeaver cannot show spatial data

### ISSUE THREAD

**Issue by zarelit** [NixOS/nixpkgs#148631]
### Describe the bug
DBeaver has support to show spatial data on a map when the database is capable (e.g. postgres + postgis) but opening "spatial" tab gives this error:

```
Can't switch presentation

Reason:
No more handles because there is no underlying browser available.
Please ensure that WebKit with its GTK 3.x bindings is installed (WebKit2 API level is preferred). Additionally, please note that GTK4 does not currently have Browser support.
```

### Steps To Reproduce
1. open dbeaver
2. navigate to a table that has a geometry, show data
3. click "Spatial" on the left

### Expected behavior
A map should be shown

### Notify maintainers
@jojosch @mkg20001 

### Metadata
This happens on master and 21.05-release, didn't test on 21.11 but I suppose it's the same

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
