### ISSUE TITLE
`pkgs.formats.json` alters integers in options due to use of `jq`

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#148824]
### Describe the bug

```
$ nix-build -E '((import <nixpkgs> {}).formats.json {}).generate "file.json" 165998239273844736'
/nix/store/c4qchpr6bi0yk168gaj1k1fv9lkqx3p6-file.json
$ cat /nix/store/c4qchpr6bi0yk168gaj1k1fv9lkqx3p6-file.json
165998239273844740
```

### Expected behavior

I expected the file to contain the integer given as input.

### Additional context

https://github.com/NixOS/nixpkgs/blob/master/pkgs/pkgs-lib/formats.nix#L46

```
$ jq . <<< "165998239273844736"
165998239273844740
```

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.21, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: formats.json
# a list of nixos modules affected by the problem
module:
```
