### ISSUE TITLE
Midnight Commander Editor syntax highlighting appears to be broken

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#149099]
### Describe the bug
A few months before today, mcedit's (pulled from nixpkgs-unstable) syntax highlighing just worked, but at least at nixpkgs commit b9982bcba7b0a54e004f73ece06743768c1781cd, syntax highlighing doesn't appear to work at all. Unluckily I don't have a system profile available anymore where it works...

### Steps To Reproduce
Unknown.

### Expected behavior
Syntax highlighting should work.

### Screenshots
![Choose Syntax Highlighting](https://user-images.githubusercontent.com/1618343/144902894-e8ba1993-54e4-404b-9054-4b902355df53.png)

### Additional context
config repo: https://github.com/zseri/nixos-configs

### Notify maintainers
@trofi @svanderburg

## Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211202_3f3561f`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - mc
# a list of nixos modules affected by the problem
module:
```
