### ISSUE TITLE
Android MTP doesn’t work with NixOS 21.11

### ISSUE THREAD

**Issue by linsui** [NixOS/nixpkgs#149789]
### Describe the bug
Since I upgraded my machines, they doesn’t work with my Android anymore. What should I do? Thanks for any help!

### Steps To Reproduce
1. Connect to an Android device
2. Nothing happens
3. ...

### Expected behavior
MTP storage is detected

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
