### ISSUE TITLE
Emacs with nativecomp fails to build

### ISSUE THREAD

**Issue by ckiee** [NixOS/nixpkgs#150085]
### Describe the bug
Running `nix-build -E '(import ./. {}).emacs.override {nativeComp = true;}'` in nixpkgs fails.

### Steps To Reproduce
1. Fetch a recent nixpkgs
2. `nix-build -E '(import ./. {}).emacs.override {nativeComp = true;}'`
3. Observe

### Expected behavior
I wanted Emacs to build and hopefully be a bit faster (:

### Additional context
[Log for `/nix/store/pwn94hy09nv9rgg40b1hgy1fhw984w8l-emacs-27.2.drv`](https://i.ckie.dev/VrMwrej.txt)

### Notify maintainers
I don't see a `meta.maintainers` so @adisbladis 

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: emacs
# a list of nixos modules affected by the problem
module:
```
