### ISSUE TITLE
nyxt: inability to load URLs

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#150412]
### Describe the bug
Package `nyxt` is essentially unusable: basic actions like attempting to open a new tab (`C-l`) fail.

### Steps To Reproduce
1. Open `nyxt` version 2.0.0
2. Press `C-l` to load URL

Observe error message "Warning: Javascript error: invalid number of arguments: 2".

If you ignore the error message and enter a URL, and press enter, the URL is ignored and your default search engine loads.

### Expected behavior
No error message, and the ability to load particular URLs.

### Additional context
I recall nyxt not having this issue a few months ago. Perhaps this was a recent common lisp library update?

### Notify maintainers
@nlewo 

### Metadata

I'm running commit 1dfc4c3edfde08c9a449bbf3eadcf0abe243ca6c.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
