### ISSUE TITLE
please don't strip symbols for zrythm

### ISSUE THREAD

**Issue by alex-tee** [NixOS/nixpkgs#150403]
### Describe the bug
The package for zrythm strips symbols so bug reports (which are supposed to include backtraces) don't include backtraces and make it impossible to debug/fix most reported bugs

### Steps To Reproduce
1. Install zrythm

### Expected behavior
Have proper backtraces. According to https://nixos.wiki/wiki/Debug_Symbols, `dontStrip = true;` should be added

### Additional context
Example offending bug report: https://todo.sr.ht/~alextee/zrythm-bug/759

Example bug report with proper backtrace: https://todo.sr.ht/~alextee/zrythm-bug/575

The content of the bug reports is generated automatically by the software and it looks like it fails to generate a backtrace for NixOS

### Notify maintainers
@tshaynik  @magnetophon 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

I don't use nixos so I can't do this sorry
