### ISSUE TITLE
fbgrab: no PPM -> PNG conversion tool found.

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#150505]
### Describe the bug

```
[davidak@gaming:~]$ fbgrab testx.png
fbgrab: no PPM -> PNG conversion tool found.
Please install Netpbm or GraphicsMagick, or ImageMagick.
```

### Steps To Reproduce
1. `nix run nixpkgs.fbcat`
2. `fbgrab testx.png`

### Expected behavior
working program

### Notify maintainers
@matthiasbeyer

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.11, nixos-21.11.334139.1bd4bbd49be, nixos-hardware, nixos-unstable-22.05pre337103.581d2d6c9cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
