### ISSUE TITLE
youtube-dl: some YouTube videos fail w/ `AttributeError: 'NoneType' object has no attribute 'group'`

### ISSUE THREAD

**Issue by YoshiRulz** [NixOS/nixpkgs#150843]
### Describe the bug
Attempting to download seemingly any video with music fails with `AttributeError: 'NoneType' object has no attribute 'group'`.

### Steps To Reproduce
1. `nix-env -f https://github.com/NixOS/nixpkgs/archive/nixos-21.11.tar.gz -iA youtube-dl`
2. `youtube-dl https://www.youtube.com/watch?v=mgsayvglv5o`

Examples of videos which cause the error: mgsayvglv5o EFEmTsfFL5A
Example of a working video: WLIfbiTUMiU

### Expected behavior
Video downloads in best format (w/o flags) / a list of formats is printed (w/ `-F`).

### Notify maintainers
@bluescreen303 @phreedom @AndersonTorres @fpletz @ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.0-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(yoshi): `"nixpkgs-21.11.333823.96b4157790f"`
 - nixpkgs: `/home/yoshi/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: youtube-dl
# a list of nixos modules affected by the problem
module:
```
