### ISSUE TITLE
nixos-install --flake misbehaves with nix 2.3 in PATH

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#151129]
### Steps To Reproduce
1. Boot a 21.11 installer
2. Attempt to install a flake-based system using e.g. `nixos-install --flake .#system`

### Expected behavior
Either the flake is built and installed, or the command errors out.

### Actual behaviour
Building the flake fails, and **/etc/nixos/configuration.nix in the target system is used instead**.

```
nixos-install --flake .#test
error: unrecognised flag '--experimental-features'
Try 'nix --help' for more information.
building the configuration in /mnt/etc/nixos/configuration.nix..
```

### Additional context
As a workaround, the nixos-install command can be run in `nix-shell -p nixUnstable`.

### Notify maintainers
Not sure who maintains this?

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.21, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.03pre246062.420f89ceb26"`
 - channels(linus): `""`
 - nixpkgs: `/var/lib/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

cc @grahamc @samueldr with whom I discovered this
