### ISSUE TITLE
'Teamviewer' terminated by Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by khrj** [NixOS/nixpkgs#151784]
### Steps To Reproduce
1. Launch teamviewer
2. Connect to NixOS using a remote computer
3. Teamviewer exits on NixOS machine with `Segmentation fault (core dumped)`

### Expected behavior
Teamviewer doesn't quit after 20 seconds of remote access

### Screenshots

![image](https://user-images.githubusercontent.com/44947946/147124643-6c7567b8-ac05-4ac9-a89c-0aa2268568ad.png)

### Additional context
Possibly fixed in next minor version 15.25.5 (unstable is on 15.24.5)

### Notify maintainers
@jagajaga
@jraygauthier

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"nixos-21.05.4481.c5f1ee98224"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: teamviewer
# a list of nixos modules affected by the problem
module: teamviewer
```
