### ISSUE TITLE
github-runner fails with "Could not find a part of the path '/proc/1/cgroup'"

### ISSUE THREAD

**Issue by grische** [NixOS/nixpkgs#191358]
### Describe the bug
Github Action fails with:
```
Error: Could not find a part of the path '/proc/1/cgroup'.
```
Even though the path exists (and unified cgroups are enabled):
```
# ls -ald / /proc/ /proc/1/ /proc/1/cgroup
drwxr-xr-x  18 root root 4096 Sep 15 16:19 /
dr-xr-xr-x 215 root root    0 Sep 12 19:32 /proc/
dr-xr-xr-x   9 root root    0 Sep 12 19:32 /proc/1/
-r--r--r--   1 root root    0 Sep 15 16:47 /proc/1/cgroup
```

### Steps To Reproduce
The NixOS configuration parts:
```nix
{
  services.github-runner = {
      enable = true;
      replace = true; 
      name = "my-runner";
      tokenFile = "/etc/nixos/github-runner/nixos.token";
      url = "https://github.com/xxx/yyy"; # your repo
      extraPackages = with pkgs; [ config.virtualisation.docker.package ];
    };
  };
  systemd.services.github-runner.serviceConfig.SupplementaryGroups = [ "docker" ];
}
```

And the Github Action workflow:
```yml
on:
  workflow_dispatch:
  push:

jobs:
  test_arm64_runner:
    runs-on: "ARM64"
    container:
      image: ubuntu:20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
```

### Expected behavior
Start Docker container and run checkout

### Notify maintainers
@veehaitch @newAM @kfollesdal 

### Context
Probably relevant upstream code:
https://github.com/actions/runner/blob/v2.296.2/src/Runner.Worker/ContainerOperationProvider.cs#L503

### Metadata
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.64, NixOS, 22.05 (Quokka), 22.05.3010.dd1f4d98244`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
