### ISSUE TITLE
systemd-oomd has failed start conditions on recent nixos-unstable

### ISSUE THREAD

**Issue by tazjin** [NixOS/nixpkgs#195085]
Since our [last NixOS bump](https://cl.tvl.fyi/c/depot/+/6874) we're getting alerts from the Prometheus systemd exporter for `systemd-oomd` having failed. It seems like it's not the unit itself that fails, but some kind of start condition:

```
tazjin@whitby ~ [4]> sudo systemctl status systemd-oomd.service 
○ systemd-oomd.service - Userspace Out-Of-Memory (OOM) Killer
     Loaded: loaded (/etc/systemd/system/systemd-oomd.service; enabled; preset: enabled)
    Drop-In: /nix/store/yfh0vbha84j23kwpxgxblvyj5mjbj884-system-units/systemd-oomd.service.d
             └─overrides.conf
     Active: inactive (dead)
TriggeredBy: × systemd-oomd.socket
  Condition: start condition failed at Thu 2022-10-06 23:23:07 UTC; 1 day 12h ago
             └─ ConditionControlGroupController=v2 was not met
       Docs: man:systemd-oomd.service(8)

Oct 06 23:23:07 whitby systemd[1]: Userspace Out-Of-Memory (OOM) Killer was skipped because of a failed condition check (ConditionControlGroupController=v2).
Oct 06 23:23:07 whitby systemd[1]: Userspace Out-Of-Memory (OOM) Killer was skipped because of a failed condition check (ConditionControlGroupController=v2).
# ... this line just keeps repeating
```

We don't have any custom config (that we're aware of) that could influence this. The system configuration for whitby at this commit [lives here](https://cs.tvl.fyi/depot@4d19955580427165a86e82f2ff5c5d04fc34b467/-/blob/ops/machines/whitby/default.nix).

### Prometheus exporter

It seems that there might be a separate issue in here about the Prometheus exporter alerting for this at all, not sure what the behaviour should be there - the unit is _skipped_ and not _failed_ technically, but we also wouldn't have noticed that something is not working without this alert. Alert we're getting from Prometheus for completeness' sake:

```
**Firing**

    Value: [ var='B0' metric='systemd-oomd.socket'
    labels={__name__=node_systemd_unit_state, instance=localhost:9100,
    job=node, name=systemd-oomd.socket, state=failed} value=1 ]
    Labels:
     - alertname = Failed Systemd Units
     - grafana_folder = Whitby
    Annotations:
    Source: https://status.tvl.su/alerting/grafana/Un0G8Pbnk/view
    Dashboard: https://status.tvl.su/d/6OdL_VXMz
    Panel: https://status.tvl.su/d/6OdL_VXMz?viewPanel=14
```

### Notify maintainers

@flokli 

This seems related to the fairly recent #169613, so also @dasJ and @lovesegfault.

### Metadata

```console
tazjin@whitby ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.17pre0_46a91f2`
 - channels(root): `"nixos-20.03.3269.f05c380a51d"`
 - nixpkgs: `/nix/store/zkvfribqrgi75gbny9bsflqjd9vn3v6b-nixpkgs-src`
```
