### ISSUE TITLE
Rustup not patching bin/gcc-ld/ld.lld

### ISSUE THREAD

**Issue by witchof0x20** [NixOS/nixpkgs#220717]
### Describe the bug
[The patchelf patch](https://github.com/NixOS/nixpkgs/blob/35871b088320c61a961ca4dedd2304e67b04f440/pkgs/development/tools/rust/rustup/0001-dynamically-patchelf-binaries.patch) seems to miss certain executables, such as one ending `bin/gcc-ld/ld.lld`

### Steps To Reproduce
1. Go into directory with a `rust-toolchain.toml` containing
```toml
[toolchain]
channel = "nightly-2022-11-01"
targets = [ "thumbv6m-none-eabi", "thumbv7em-none-eabihf", "thumbv8m.main-none-eabihf" ]
profile = "minimal"
components = [ "rustfmt" ]
```
2. `rustup show` to download the toolchain
3. Run `~/.rustup/toolchains/nightly-2022-11-01-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/ld.lld`
```
bash: ~/.rustup/toolchains/nightly-2022-11-01-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/ld.lld: No such file or directory
```
```
file ~/.rustup/toolchains/nightly-2022-11-01-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/ld.lld
~/.rustup/toolchains/nightly-2022-11-01-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/ld.lld: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, with debug_info, not stripped
```

### Expected behavior
`ld.lld` executes properly

### Notify maintainers
@Mic92 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.15, NixOS, 22.11 (Raccoon), 22.11.20230310.824f886`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/dhdakb68bvihwrfvimwifm295qzycmrm-source`
```
