### ISSUE TITLE
Pool not being exported properly when using ZFS

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#24556]
## Issue description

I am running ZFS on root and i'm sharing a pool dual-booting between NixOS and arch. Whenever I go from NixOS to arch I get a failed boot and i'm told the pool wasn't exported properly.

### Steps to reproduce

Share a ZFS pool between Nix and Arch.

## Technical details

* System: (NixOS: nix-env (Nix) 1.11.8 )
* ZFS version:  0.6.5.9-1
* spl version:   0.6.5.9-1
* Arch linux:    4.10.6-1-ARCH x86_64

Thought the problem might be that I didn't have the same hostid between the two installs so I set them to be the same. Even with them set the same the pool won't import going from NixOS to Arch.

**Comment by wizeman** [comment]
As far as I know, a ZFS pool is not supposed to be exported on shutdown or reboot. I believe it's supposed to be exported only when you need to move it between different machines.

See for example, the following email: http://git.net/ml/zfs-discuss/2011-06/msg00227.html

I suspect your problem may be that the host id is not properly set on the Arch Linux side when booting.

Specifically, when you set the host id on your Arch installation, are you sure that your new host ID has been copied into the initramfs?

Alternatively, you may try specifying the host ID as a kernel parameter, as specified in the link below.

See https://wiki.archlinux.org/index.php/ZFS#Incorrect_hostid

**Comment by johnramsden** [comment]
I'm pretty sure it's set correctly. I set my host ID on Arch by [writing the host ID into the initramfs](https://ramsdenj.com/2016/06/23/arch-linux-on-zfs-part-2-installation.html#first-tasks). 

I also don't have any problems when I go from an arch machine to an arch machine. I have multiple installs of arch on my system that I used the same pool on with no problems. 

I also made sure that I was using the same hostid on NixOS and Arch. 

Part of the reason I think it's a problem with how Nix is finishing with the pool is when I go from Arch -> Nix there is no issue on boot, but there is going in the other direction. 

The only way I can fix the problem after going from NixOS to Arch is to rebuild my initramfs on Arch again with  ```mkinitcpio -p linux```, until then every time I reboot there will be an issue. I'm running root on ZFS on both systems.

**Comment by wizeman** [comment]
@johnramsden Your observations are still consistent with my diagnosis.

Let's assume that your Arch systems are not being initialized with a host id (which I think is what's happening).

Here's what happens when you move a ZFS pool from Arch to NixOS:

1. Your Arch system has not been initialized with a host id, so it will be equal to zero
2. Your Arch system sets the owner of the ZFS pool to have a host id equal to zero
3. You "move" the ZFS pool to NixOS
4. Since the pool has an owner with a host id set to zero, NixOS will skip the host check (see code here: https://github.com/zfsonlinux/zfs/blob/87f9371aefca857e7091dfdee3ec2d36b0de54c4/lib/libzfs/libzfs_status.c#L222) and therefore will not complain about opening the ZFS pool.

Here's what happens when you move a ZFS pool from NixOS to Arch:

1. Your NixOS system has been initialized with a host id, so it will be **not** be equal to zero
2. Your NixOS system sets the owner of the ZFS pool to have a host id (different than zero)
3. You "move" the ZFS pool to Arch
4. Since the pool has an owner with a host id different than zero, Arch will do the host check, which will fail because Arch doesn't have the host id equal to the one written in the ZFS pool.

Here's what happens when you move a ZFS pool from one Arch system to another Arch system:

1. Your Arch system has not been initialized with a host id, so it will be equal to zero
2. Your Arch system sets the owner of the ZFS pool to have a host id equal to zero
3. You "move" the ZFS pool to the other Arch system
4. Since the pool has an owner with a host id set to zero, the new Arch system will skip the host check and therefore will not complain about opening the ZFS pool.

This is the only explanation I can think of that seems to fit what you are observing.

Here are the problems with the other possible explanations:

1. If you were initializing the host id in your Arch systems, but they would have a different host id than the NixOS system, you would experience a problem moving the ZFS pool from Arch to NixOS.
2. If the host id was not being initialized in NixOS (i.e. it would be equal to zero), but it would be set correctly in your Arch systems, you would experience a problem moving from Arch to NixOS.
3. If the host id was not being initialized either in NixOS or your Arch systems, you would not experience a problem moving from Arch to NixOS or vice-versa. However, this way of working around the problem is severely discouraged because the host check is important to avoid ZFS pool corruption in certain scenarios.
4. If the host id was being initialized and set to the same value in both Arch and NixOS systems, you would not experience a problem moving from Arch to NixOS or vice-versa. This is what we want!

Where's what you can do to make sure Arch has set host id set correctly:
1. The `/etc/hostid` file in your Arch systems must have exactly the same contents as the `/etc/hostid` file in NixOS. Specifically, it must be a binary file (not a hexadecimal string), with exactly 4 bytes and exactly the same contents as the one in NixOS.
2. That `/etc/hostid` file must also be inside Arch's initramfs (always! Even if you upgrade the kernel).
3. If you checked the above and it still doesn't work, try setting the host ID via a kernel parameter in your Arch system. Make sure to do the following:
    1. Go to your NixOS system and run the command `hostid`. This will output a host id in hexadecimal like `b06a2bf1`.
    2. Go to your Arch system and add the kernel parameter `spl.spl_hostid=0xb06a2bf1` to your boot loader configuration. Make sure to add the `0x` prefix before the host id, and of course, setting the same host id as what the `hostid` command returned in NixOS.
    3. The added kernel parameter must be persistent. Here are some tips for how to add it persistently to your boot loader: https://wiki.archlinux.org/index.php/kernel_parameters#Configuration

If it still doesn't work, we will need more information, specifically you will need to show me:

1. What `hostid` returns in NixOS
2. What `hostid` returns in your Arch systems
3. Inside NixOS, run `zdb -l /dev/sda1` (replace /dev/sda1 by whatever partition your ZFS pool is stored in). This will output some information about your ZFS pool, including a line that starts with "hostid:" followed by the host id stored in the ZFS pool in decimal. I will need this number.
4. The same as in point 3, but do it inside the Arch system.

**Comment by johnramsden** [comment]
Very interesting @wizeman.

So if I want to as you said, put the `/etc/hostid` file "_in the /etc directory inside Arch's initramfs (always! Even if you upgrade the kernel)_". Can I just copy the binary file on NixOS to `/etc/hostid` on arch and re-run `mkinitcpio -p linux`?

**Comment by wizeman** [comment]
@johnramsden I'm not exactly an Arch Linux expert, but according to [1]... yes, I believe that should work! The difference being that you are creating `/etc/hostid` yourself (by copying the value from NixOS), instead of calling `sethostid()` in a C program, like they suggest in the guide (of course, that wouldn't work in your case, because the hostid must be equal to the one you set in your NixOS configuration).
Presumably, `mkinitcpio -p linux` will then copy the `/etc/hostid` file into the initramfs, so you should be good to go after that.

[1] https://wiki.archlinux.org/index.php/Installing_Arch_Linux_on_ZFS#After_the_first_boot

**Comment by johnramsden** [comment]
So, I mounted the nix store on arch and did a binary diff 

`
cmp -l /mnt/nix/store/k9h2zrdchfq84adjqcpdbl76cjxzq12x-gen-hostid /etc/hostid
`
I got no output so apparently the files are the same.

I also ran `zdb -l /dev/sda1` within arch and got the following, stand by for the same on nix:

```
zdb -l /dev/sda1
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 500291
    pool_guid: 1357041183262611022
    errata: 0
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 1
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 500291
    pool_guid: 1357041183262611022
    errata: 0
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 2
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 500291
    pool_guid: 1357041183262611022
    errata: 0
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 3
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 500291
    pool_guid: 1357041183262611022
    errata: 0
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data

```

**Comment by johnramsden** [comment]
Here's NixOS, it looks like the hostid IS being set.

```
zdb -l /dev/sda1                                              ~
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 504216
    pool_guid: 1357041183262611022
    errata: 0
    hostid: 346817044
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 1
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 504216
    pool_guid: 1357041183262611022
    errata: 0
    hostid: 346817044
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 2
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 504216
    pool_guid: 1357041183262611022
    errata: 0
    hostid: 346817044
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 3
--------------------------------------------
    version: 5000
    name: 'vault'
    state: 0
    txg: 504216
    pool_guid: 1357041183262611022
    errata: 0
    hostid: 346817044
    hostname: '(none)'
    top_guid: 10203073494137127831
    guid: 14736833795846691026
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 10203073494137127831
        metaslab_array: 38
        metaslab_shift: 32
        ashift: 12
        asize: 480088948736
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 14736833795846691026
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_152271401093-part1'
            whole_disk: 1
            DTL: 4433
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13496783181990707449
            path: '/dev/disk/by-id/ata-SanDisk_SDSSDXPS480G_154501401266-part1'
            whole_disk: 1
            DTL: 4432
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```
