### ISSUE TITLE
TexText: does not work with Inkscape

### ISSUE THREAD

**Issue by taha-yassine** [NixOS/nixpkgs#270509]
### Describe the bug
When launching the extension through Inkscape, the application freezes.
```
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = [
    (pkgs.inkscape-with-extensions.override {
      inkscapeExtensions = [
        pkgs.inkscape-extensions.textext
      ];
    })
  ];
}
```

### Steps To Reproduce
1. Open Inkscape
2. Launch the extension under Extensions > Text

### Expected behavior
Launch TexText

### Additional context
Maybe linked to https://github.com/NixOS/nixpkgs/pull/121711#issuecomment-1728483237

### Notify maintainers
@raboof @jtojnar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.20231007.5a237ae`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/store/bxrxl669b0ylvd02bbsdymbh9i2fm0s5-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by raboof** [comment]
hmm, it opens pretty much instantly for me on current nixos-unstable (5a09cb4b393d58f9ed0d9ca1555016a8543c2ac8). Do you see any error messages in the terminal where you opened Inkscape?

**Comment by taha-yassine** [comment]
> hmm, it opens pretty much instantly for me on current nixos-unstable ([5a09cb4](https://github.com/NixOS/nixpkgs/commit/5a09cb4b393d58f9ed0d9ca1555016a8543c2ac8)). Do you see any error messages in the terminal where you opened Inkscape?

No error message is reported on the terminal. Is there a flag I should add to the command for verbosity?
I had someone else test this and they reported the same behavior.
Something else I noticed is that Inkscape returns to normal if I let it hang for 1 or 2 minutes, but no sign of the extension's window.

**Comment by taha-yassine** [comment]
@raboof sorry for the ping again, but I just noticed that trying to launch TexText results in a ~/.config/inkscape/extension-errors.log file with this content:
```
Extension "Export to PDF via Scribus" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: scribus

Extension "EPS Input" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: /nix/store/63wa96v23j67f1l4pfn0v81bpdsx1q02-ghostscript-with-X-10.02.1/bin/ps2pdf

Extension "Optimized PNG" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: optipng

Extension "PostScript Input" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: /nix/store/63wa96v23j67f1l4pfn0v81bpdsx1q02-ghostscript-with-X-10.02.1/bin/ps2pdf

Extension "XFIG Input" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: fig2dev

Extension "GIMP XCF" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: gimp
```
