### ISSUE TITLE
pkgs.overcommit fails to run as a hook and doesn't find files

### ISSUE THREAD

**Issue by lukash** [NixOS/nixpkgs#280916]
### Describe the bug
When `overcommit` hooks are installed in a git repo, the pre-commit hook fails:
```
$ git commit -am "test"
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
```

When running `overcommit --run`, it runs, but it fails to process any files in the repo.
```
git rev-parse --show-toplevel
EXIT STATUS: 0
STDOUT: "/home/lu/dev/test\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "87144b2a9223a4252b8b2091d4432f9b82847dab1afaf00438f69c877a5f1074\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "87144b2a9223a4252b8b2091d4432f9b82847dab1afaf00438f69c877a5f1074\n"
STDERR: ""
git ls-files /home/lu/dev/test/clang-format --error-unmatch
EXIT STATUS: 1
STDOUT: ""
STDERR: "error: pathspec '/home/lu/test/clang-format' did not match any file(s) known to git\nDid you forget to 'git add'?\n"
git config --local --get overcommit.PreCommit.ClangFormat.signature
EXIT STATUS: 0
STDOUT: "f36c7a2348262635a4e22c619af14e54689a02f397bed3245378132cacb7205d\n"
STDERR: ""
Running pre-commit hooks
clang-format --verbose
EXIT STATUS: 0
STDOUT: "\n"
STDERR: ""
Run ClangFormat.........................................[ClangFormat] OK
```

My `.overcommit.yml`:
```
PreCommit:
  ALL:
    problem_on_unmodified_line: warn
    requires_files: true
    required: false
    quiet: false

  AuthorEmail:
    enabled: false
  AuthorName:
    enabled: false
  BrokenSymlinks:
    enabled: false
  MergeConflicts:
    enabled: false
  CaseConflicts:
    enabled: false

  ClangFormat:
    enabled: true
    command: [ 'clang-format' ]
    flags: [ '--verbose' ]
    parallelize: false
    include:
      - '**/*.c'
      - '**/*.h'
```
(There are `.c` and `.h` files in the repo)

 I've been trying to find out what's going on but so far unsuccessfully. Upstream documentation fails to mention how exactly the files are passed to hooks, to me it seems to be over `stdin`. If I add `flags: [ '--verbose', '-i' ] to the `ClangFormat` hook, this is the output, the STDERR confirms the theory:
```
...
Running pre-commit hooks
clang-format --verbose -i
EXIT STATUS: 0
STDOUT: ""
STDERR: "error: cannot use -i when reading from stdin.\n"
Run ClangFormat.........................................[ClangFormat] OK
```
Tried to put `cat` instead of `clang-format`, printed nothing.

### Expected behavior
`overcommit` runs without error when executed from a `git` hook.

`overcommit --run` operates on all repository files (matching the `include` patterns).

### Notify maintainers
@Br1ght0ne
@anthonyroussel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20240103.b0b2c54`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
