### ISSUE TITLE
Ansible missing (optional) dependency boto3/botocore

### ISSUE THREAD

**Issue by BlessJah** [NixOS/nixpkgs#28171]
## Issue description

Ansible is missing boto3 and botocore dependency.

### Steps to reproduce

Execute following playbook (script). The keys does not matter, play will fail before keys are validated.
```
#!/usr/bin/env ansible-playbook
---
- hosts:
    - localhost
  tasks:
    - cloudformation:
        aws_access_key: abc
        aws_secret_key: wxyz
        stack_name: test
        state: absent
```

```
~/minimal-aws.playbook.yml 
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available
...
TASK [cloudformation] ********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "boto3 and botocore are required for this module"}
...
```

## Technical details

* System: (NixOS: 17.03, also unstable)
* Nixpkgs version:
    - nixos/unstable nixos-17.09pre111447.a7c8f5e419
    - nixos/17.03 nixos-17.03.1665.055e5c3578

**Comment by BlessJah** [comment]
I've tried but it still fails to find those: https://github.com/NixOS/nixpkgs/compare/master...BlessJah:ansible/add-boto?expand=1

**Comment by copumpkin** [comment]
IIRC there was an ansible bug where it would use the wrong python when executing modules. I think we had a patch in there for 1.9 but I don't know what happened with 2, since I stopped using it around then. Here's some context from back then: https://github.com/ansible/ansible/issues/13421

**Comment by BlessJah** [comment]
I have workaround:
```
#!/usr/bin/env ansible-playbook
---
- hosts:
    - localhost
  vars:
    ansible_python_interpreter: /home/blessjah/python-with-boto3.sh
  tasks:
    - cloudformation:
        aws_access_key: AK
        aws_secret_key: gB
        stack_name: testtest
        state: absent

```

```
#!/usr/bin/env nix-shell
#! nix-shell -p python27Packages.boto3 python27Packages.botocore ansible -i bash
python2 "${*}"
```

Unfortunately this is not valid:
```
  vars:
    ansible_python_interpreter: |
      /usr/bin/env nix-shell
      #! nix-shell -p python27Packages.boto3 python27Packages.botocore ansible -i bash
```

Because ansible will try to execute:
```
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/env nix-shell
#! nix-shell -p python27Packages.boto3 python27Packages.botocore ansible -i python2.7 /home/blessjah/.ansible/tmp/ansible-tmp-1511186904.35-62479818495972/setup.py && sleep 0'
```

Executed manually it fails due to syntax error: `ansible_shell_interpreter` is split on spaces and put into list with single `'` around (thus having newline in `'nix-shell\n#!'` argument, which is invalid).
