### ISSUE TITLE
k3s: GPU Passthrough for Nvidia / AMD / Intel

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#288037]
This issue is for tracking GPU pass through in K3s. [Please do not close it. I will be updating it soon.]

As it is right now it is an unsolved issue. Problem with nix paths and ldcache in Nvidia driver is one.

References:
* https://discourse.nixos.org/t/using-nvidia-container-runtime-with-containerd-on-nixos/27865/30

**Comment by SomeoneSerge** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/278969 https://github.com/NixOS/nixpkgs/pull/284507

**Comment by OlfillasOdikno** [comment]
I was unable to get the official NVIDIA device plugin to work, since all the heavy lifting is already done in containerd and generating cdi json, I created a device plugin that uses the cdi json and instructs kubernetes to inject the device. 
Tested it on a NVIDIA 3060.
https://github.com/OlfillasOdikno/generic-cdi-plugin

**Comment by ahirner** [comment]
@OlfillasOdikno thanks, I use your plugin as well for now. I had problems that some containers didn't see libnvml.so.1, nor the generated CDIs.

> GPU pass through is:

Question regarding scope: does this issue inlcude shared GPU use? I'm not sure how involved it is.

**Comment by Goorzhel** [comment]
After four months of dead ends and failed hacks, I've arrived at this configuration for my k3s node and its GeForce 3070:

#### In NixOS
1. [Bodge](https://git.sr.ht/~goorzhel/nixos/tree/a806b38a14361e0eab2b1aca23f0b7d54e4c50f8/item/profiles/k3s/common/nvidia.nix#L25) `LD_LIBRARY_PATH` into the CDI generator's environment.
2. [Ensure](https://git.sr.ht/~goorzhel/nixos/tree/a806b38a14361e0eab2b1aca23f0b7d54e4c50f8/item/profiles/k3s/common/nvidia.nix#L15-18) `/run/opengl` is available.
3. [Enable](https://git.sr.ht/~goorzhel/nixos/tree/a806b38a14361e0eab2b1aca23f0b7d54e4c50f8/item/profiles/k3s/common/nvidia.nix#L27-40) CDI in `k3s`' bundled `containerd`.

#### In Kubernetes

1. [Install](https://git.sr.ht/~goorzhel/kubernetes/tree/a768e68e8beae68543821840f15b9696688da322/item/pkgs/generic-cdi.nix) @OlfillasOdikno's CDI server (thank you!)
2. [Add](https://git.sr.ht/~goorzhel/kubernetes/tree/a768e68e8beae68543821840f15b9696688da322/item/services/6-services/svc/jellyfin.nix#L22) `spec.resources.limits."nvidia.com/gpu-0"=1` to the relevant pod specs.
3. Enjoy massively-improved video transcoding, etc.

#### Stray notes

- containerd/containerd@c8e8a093c will remove the need for NixOS step 3 whenever k3s bundles a version with that commit.
- Like OlfillasOdikno, I hit a [dead end](https://git.sr.ht/~goorzhel/kubernetes/commit/a768e68e8beae68543821840f15b9696688da322) with Nvidia's device plugin.
- Relevant software versions:
  - k3s 1.30.2+k3s2,
  - NixOS 24.05, and
  - Nvidia 550.78.

Nvidia monoculture aside, I also have a Radeon RX 7800 in my desktop. A brief web-search reveals [a plugin for AMD GPUs](https://github.com/ROCm/k8s-device-plugin), but I need more time to look into that.

**Comment by Goorzhel** [comment]
> A brief web-search reveals [a plugin for AMD GPUs](https://github.com/ROCm/k8s-device-plugin), but I need more time to look into that.

Little did I know that _is_ the official AMD plugin. I made a one-node `k3s` cluster of my desktop and installed the plugin's Helm chart—and that's all I needed. One unit of `amd.com/gpu` became available, without any abstruse hacks like my Nvidia odyssey above.

Some caveats:
1. Like the Nvidia device plugin, the AMD one hands out whole-GPU leases by default. Unlike the Nvidia plugin, [this is non-configurable](https://github.com/ROCm/k8s-device-plugin/issues/66). 
2. No news on [CDI support](https://github.com/ROCm/ROCm/issues/3029) yet.
3. On a Jellyfin pod, [with VAAPI selected](https://jellyfin.org/docs/general/administration/hardware-acceleration/amd/), I got ~20 fps transcoding 2160p HEVC to AVC—in memory. The same video on a magnetic ZFS pool in my main cluster went through NVENC at ~200 fps.

**Comment by bornav** [comment]
> 3. [Enable](https://git.sr.ht/~goorzhel/nixos/tree/a806b38a14361e0eab2b1aca23f0b7d54e4c50f8/item/profiles/k3s/common/nvidia.nix#L27-40) CDI in `k3s`' bundled `containerd`.


been struggeling the entire time with and this was it https://git.sr.ht/~goorzhel/nixos/tree/a806b38a14361e0eab2b1aca23f0b7d54e4c50f8/item/profiles/k3s/common/nvidia.nix#L37

**Comment by Goorzhel** [comment]
> > 3. [Enable](https://git.sr.ht/~goorzhel/nixos/tree/a806b38a14361e0eab2b1aca23f0b7d54e4c50f8/item/profiles/k3s/common/nvidia.nix#L27-40) CDI in `k3s`' bundled `containerd`.

If you use `k3s` from unstable and pull in 1.31.6, delete that hack or `containerd` will wordlessly exit 1. The newest 1.31 and 1.32 versions [bundle `containerd` 2.0](https://docs.k3s.io/release-notes/v1.32.X), which has CDI enabled by default.

**Comment by yellowhat** [comment]
Hi,

I am on:

```
$  k3s --version
k3s version v1.32.3+k3s1 (079ffa8d)
go version go1.24.2

$ sudo crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  2.0.4+unknown
RuntimeApiVersion:  v1
```

but the `nvidia-device-plugin` fails:

```
main.go:356] Retrieving plugins.
factory.go:112] Incompatible strategy detected auto
factory.go:113] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
factory.go:114] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
factory.go:115] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
factory.go:116] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
main.go:173] error starting plugins: error getting plugins: unable to create plugins: failed to construct resource managers: invalid device discovery strategy
```

How did you manage to make it work?

**Comment by thedaringdev** [comment]
> Hi,
> 
> I am on:
> 
> ```
> $  k3s --version
> k3s version v1.32.3+k3s1 (079ffa8d)
> go version go1.24.2
> 
> $ sudo crictl version
> Version:  0.1.0
> RuntimeName:  containerd
> RuntimeVersion:  2.0.4+unknown
> RuntimeApiVersion:  v1
> ```
> 
> but the `nvidia-device-plugin` fails:
> 
> ```
> main.go:356] Retrieving plugins.
> factory.go:112] Incompatible strategy detected auto
> factory.go:113] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
> factory.go:114] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
> factory.go:115] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
> factory.go:116] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
> main.go:173] error starting plugins: error getting plugins: unable to create plugins: failed to construct resource managers: invalid device discovery strategy
> ```
> 
> How did you manage to make it work?

What worked for me is:

1. Install the [generic-gpu-plugin](https://github.com/OlfillasOdikno/generic-cdi-plugin).
2.  Configure nix
  ```nix
    services.k3s.enable = true;
    services.k3s.role = "server";
    services.k3s.extraFlags = toString [
      # "--debug" # Optionally add additional args to k3s
    ];

    hardware.graphics.enable = true;
    hardware.graphics.enable32Bit = true;
    nixpkgs.config.nvidia.acceptLicense = true;
    hardware.nvidia.datacenter.enable = true;
    hardware.nvidia-container-toolkit.enable = true;
  ```
3.  Restart `k3s service` and validate drivers have been detected
  ```bash
  systemctl restart k3s
  grep nvidia /var/lib/rancher/k3s/agent/etc/containerd/config.toml
  # Output:
  # [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
  # BinaryName = "/nix/store/avkjvrcmac3qbw015k65bglg8wz4jmq7-nvidia-dc-565.57.01-6.12.33/lib/nvidia"
  ```
4. Label nodes
```bash
 kubectl label nodes node_name nixos-nvidia-cdi=enabled
```
I was able to validate by launching a hashcat pod as detailed in [generic-gpu-plugin](https://github.com/OlfillasOdikno/generic-cdi-plugin).

**Comment by kbrowder** [comment]
Hi, so this may not be the best place for this but I've gotten the basic k3s nvidia runtime support with nixos 25.05-ish (such that nbody works); there's few issues compared to the wiki, but here's the jist outside of the basic k3s setup (and the runtime class configuration on the wiki):
```nix
  hardware.nvidia-container-toolkit = {
    enable = true;
    package = unstable.nvidia-container-toolkit;
  };
  
  services.k3s.containerdConfigTemplate = ''
{{ template "base" . }}

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
  privileged_without_host_devices = false
  runtime_engine = ""
  runtime_root = ""
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
  BinaryName = "${lib.getOutput "tools" config.hardware.nvidia-container-toolkit.package}/bin/nvidia-container-runtime"
'';

systemd.services.k3s.path = [ "${lib.getBin unstable.libnvidia-container}" "${lib.getBin config.hardware.nvidia-container-toolkit.package}" ];
```

So the first issue is that the container config template's BinaryName for nvidia-container-runtime is not located in /run/current-system/sw/bin, i don't think libnvidia-container's tools are either (at least not on unstable).  It actually may not need to be set given...

The second issue is that libnvidia-container needs to be added to the k3s services path, may as well ad nvidia-container-toolkit there as well.

The third issue is that in nixos 25.05 libnvidia-container and nvidia-container-toolkit don't match; unstable seems to have this resolved, so i swapped to using that (on 25.05 you get `Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli configure: unrecognized option '--cuda-compat-mode=ldconfig'
Try `nvidia-container-cli configure --help' or `nvidia-container-cli configure` in the container)

Anyways with the bit of nix code above nvcr.io/nvidia/k8s/cuda-sample:nbody gives:
```
NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Turing" with compute capability 7.5

> Compute 7.5 CUDA device: [NVIDIA GeForce RTX 2080 Ti]
69632 bodies, total time for 10 iterations: 133.596 ms
= 362.931 billion interactions per second
= 7258.618 single-precision GFLOP/s at 20 flops per interaction
```
I'll do some more testing soon but it looks kindof good so far.

**Comment by bornav** [comment]
> [@bornav](https://github.com/bornav) didn't come to that point where i need multiple pods.
> 
> But you do that then with a patched runtime? or with CDI approach? If CDI approach, can you share complete pod/deployment example?
```

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
helmCharts:
- name: nvidia-device-plugin
  repo: https://nvidia.github.io/k8s-device-plugin
  version: 0.17.3
  releaseName: nvdp
  namespace: nvidia-device-plugin
  includeCRDs: true
  valuesInline:
    runtimeClassName: nvidia
---
apiVersion: node.k8s.io/v1
handler: nvidia
kind: RuntimeClass
metadata:
  name: nvidia
  labels:
    app.kubernetes.io/component: gpu-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-test
  labels:
    app: gpu-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gpu-test
  template:
    metadata:
      labels:
        app: gpu-test
    spec:
      restartPolicy: Always
      runtimeClassName: nvidia
      containers:
      - name: gpu-test
        image: nvidia/cuda:12.6.3-base-ubuntu22.04
        command: ["nvidia-smi"]
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
```

**Comment by Xnyle** [comment]
@bornav I don't know why you were not able, I just created two hashcat containers in different namespaces plus had ollama generate some tokens all at the same time. Albeit slow it worked as expected.

**Comment by bornav** [comment]
@Xnyle  i tried the steps you described above with generic cdi plugin, but it's not assigning it at all, did you miss a step of what you did, or do you have your nix repo public, since ether the generic plugin does not work or 
something else is missing here
```
{ config, lib, host, inputs, pkgs, pkgs-unstable, ... }:
{
  hardware.nvidia = {
    open = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    nvidiaSettings = true;
  };
  services.xserver = {
    enable = false;
    videoDrivers = [ "nvidia" ];
  };
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "nvidia-x11"
    "nvidia-settings"
  ];
  hardware.nvidia-container-toolkit.enable = true;
  hardware.nvidia-container-toolkit.mount-nvidia-executables = true; 
  environment.systemPackages = with pkgs; [
    nvidia-container-toolkit 
  ];
}
```
ps the generic-cdi is assigning gpu limits but with request/limit on a pod it is not mapped to the pod, had the same behaviour year ago when i tryed the gpu passtrough first time

**Comment by Xnyle** [comment]
No the above is my config, nothing else, container limits have to be set though as well:

```
apiVersion: v1
kind: Pod
metadata:
  name: hashcat-benchmark-pod
spec:
  containers:
  - name: hashcat-benchmark-container
    image: dizcza/docker-hashcat
    command: ["hashcat", "-d", "2" , "-b"]
    resources:
      requests:
        nvidia.com/gpu-all: "1"
      limits:
        nvidia.com/gpu-all: "1"

```
Actually I reinstalled the whole system again so there can't be anything old hanging around that's not in my config.
What is your log from the daemonset? mine is constantly creating and removing devices, not sure what that s about, but is also reacting to pod creation with extra logs.

**Comment by bornav** [comment]
>What is your log from the daemonset?

same for me, every few seconds it is logging device change, guess only diff is im on rke2 and not k3s

that pod in particular, is complaining no cuda is installed, the nvidia-smi container does not see the nvidia-smi in the path

running it manually using podman by speciftying gpu works, so yeah, no clue

**Comment by Run1e** [comment]
Is a consequence of this setup that you can't have multiple gpus in a cluster, each assigned to its own pod like this?
```yaml
  resources:
    limits:
      nvidia.com/gpu: 1
```
The above setup is how I'm doing it today with the NVIDIA gpu operator (not on NixOS). I'm not able to find any information about the `nvidia.com/gpu-all` resource, only `nvidia.com/gpu=all`, but not really in kubernetes contexts.

**Comment by dcdq** [comment]
It seems they are enumerated by bios (which implies you might not have stable pinning over time with bios updates/hw changes?). In other words, instead of requesting one gpu, you are requesting one gpu id 1 (nvidia.com/gpu-1: 1), or all of the gpus available on a node (nvidia.com/gpu-all: 1), which I'm assuming means you need an additional tagging strategy for your nodes to further segment your deployments if you are going to run several models on several machines. At least this is how I understand it so far.

If I have two machines with two sets of different gpus, where one machine parallelizes all gpus with vllm to serve a big model and another serves two endpoints of small models running of a single gpu each for load balanced high throughput, I would want to request nvidia.com/gpu-all: 1 (as well as some other tag like `gpu=reasoning` that I would mark the former node with) and separately nvidia.com/gpu-0: 1 in one pod and nvidia.com/gpu-1: 1 in another destined for the latter node (say, `gpu=routing`). Coming completely out of the left field but scouring everything I could to try feeling less stupid, and doing a bit of a rubberducky here so please correct me if I'm wrong and it'll probably save more than just me < 3

**Comment by dcdq** [comment]
> [@dcdq](https://github.com/dcdq) Massive thanks for the investigation! Likewise I don't entirely understand how it all glues together but at least this seemingly answers my questions.
> 
> I have multiple nodes with one gpu each, so afaict I can simply request `nvidia.com/gpu-0: "1"` or `nvidia.com/gpu-all: "1"` and I should be good.

So far so good here!
I've also tried the official nvidia cdi, and after mounting /nix/store and a few other iterative things, I got it working for vllm using the regular `nvidia.com/gpu: <count>` labeling:

```yml
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: nvidia
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nvidia-device-plugin
    spec:
      nodeSelector:
        gpu: "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: nvidia-device-plugin-ctr
          image: nvcr.io/nvidia/k8s-device-plugin:v0.17.4
          args:
            - --fail-on-init-error=false
          securityContext:
            privileged: true
          terminationMessagePath: /tmp/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: LD_LIBRARY_PATH
              value: /run/opengl-driver/lib
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: nvidia-libs
              mountPath: /run/opengl-driver
              readOnly: true
            - name: nix-store
              mountPath: /nix/store
              readOnly: true
            - name: host-dev
              mountPath: /dev
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
        - name: nvidia-libs
          hostPath:
            path: /run/opengl-driver
            type: Directory
        - name: nix-store
          hostPath:
            path: /nix/store
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
            type: Directory
```

This is of course in no way a recommendation, just some additional lore for anybody that finds it useful that has no prior experience with any of this. This exposes the gpu capabilities in k9s and such but of course you then have to manage gpu pinning with the usual `<CUDA/NVIDIA>_VISIBLE_DEVICES` per pod to get the same `gpu-<id>` functionality given by the `generic-cdi-plugin`. This goes against a lot or all of the purpose behind the nixos-related work on exposing the gpus and drivers deterministically and I'm sure other implications. But it was neat to see and plays along with broader tooling that expects this standard labeling strategy.
