### ISSUE TITLE
ntfy-sh is missing settings to run securely

### ISSUE THREAD

**Issue by tcurdt** [NixOS/nixpkgs#294637]
## Issue description

The current configuration implementation does not allow for running ntfy-sh in a secured way.
The default access is "open" and there is no way set some of the configuration options.

https://github.com/NixOS/nixpkgs/blob/ad12944445f0b09737a1592fbd256bfbade7e790/nixos/modules/services/misc/ntfy-sh.nix#L75

### Steps to reproduce

This installs the packages

```
  services.ntfy-sh = {
    enable = true;

    settings = {
      base-url = "https://example.org";
      listen-http = "127.0.0.1:8080";

      # missing settings:
      # auth-default-access = "deny-all";
      # behind-proxy = true;
      # enable-login = false;

    };
  };
```

But the package is missing three important configuration settings that are mentioned in the original documentation:

## Technical details

https://docs.ntfy.sh/docs/config/#__tabbed_2_1

```
version: '3'
services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    environment:
      NTFY_BASE_URL: http://ntfy.example.com
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
    volumes:
      - ./:/var/lib/ntfy
    ports:
      - 80:80
    command: serve
```

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.72-hardened1, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
 ```
