### ISSUE TITLE
Can't find crystal dependency.

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#31844]
## Issue description
```
Error in /nix/store/9ll7lq3n05rimy44llaih52wc33hy1g6-test.cr:1: while requiring "msgpack": can't find file 'msgpack' relative to '/nix/store'

require "msgpack"
```

What is the right way to build crystal package with dependency, that installed with shards manager.

### Steps to reproduce
1. Install `crystal` & `shards`
2. Create shard.yml
```Yaml
name: test
version: 0.1.0

authors:
  -  <>

targets:
  test:
    main: src/test.cr

crystal: 0.23.1

license: MIT

dependencies:
  msgpack:
    github: crystal-community/msgpack-crystal
```
3. Install dependencies with `crystal deps init`
4. Create test.cr
```Crystal
require "msgpack"
```
5. Create default.nix
```Nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "test";
	src = ./test.cr;

  buildInputs = [
		crystal
		openssl
		zlib
  ];

	buildCommand = ''
		crystal build $src -o $out
	'';
}
```
6. Build it.
`nix-build`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 18.03pre120540.b8f7027360 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
