### ISSUE TITLE
Replacing ofBorg with Github actions

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#355847]
This is one of the two plans to ensure we can also perform github evaluation checks in the future.

See https://discourse.nixos.org/t/infrastructure-announcement-the-future-of-ofborg-your-help-needed/56025
for more information.

To replace OfBorg’s functions with GitHub Actions the following tasks need to be implemented:

- [ ] Running evaluation checks on Nixpkgs/Manual/NixOS.
- [ ] Identifying package rebuilds and adding appropriate labels to the repository.
- [ ] (Optional) Rebuilding selected packages for Linux/macOS.

I already created a proof of concept pull request here: https://github.com/NixOS/nixpkgs/pull/352808

**Comment by Mic92** [comment]
@Bot-wxt1221 I managed to run it in 5 minutes for naive nix-env evaluation based on the default.nix entry point and 15 minutes using the same logic that ofborg uses: https://github.com/Mic92/nixpkgs/actions/workflows/eval.yml

Also this is not yet the end of the line of optimizations. We still have https://github.com/Mic92/nixpkgs/blob/main/pkgs/top-level/release-attrpaths-superset.nix to split evaluation in smaller parts that can run even in parallel.

**Comment by JohnRTitor** [comment]
https://github.com/NixOS/nixpkgs/pull/352808#issuecomment-2475893708 and

I worry that bot accounts like ryantm-r can easily hit the limit of CI. CC @ryantm

**Comment by Mic92** [comment]
@JohnRTitor

Yes it's possible:

```
name: Trigger on PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  run-on-comment:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
```
