### ISSUE TITLE
Plasticity unusably slow (Wayland)

### ISSUE THREAD

**Issue by NicoleKai** [NixOS/nixpkgs#362248]
## Describe the bug

Plasticity underrperforms on my computer (with an NVIDIA 4080) on Wayland.

## Steps To Reproduce

1.  `NIXPKGS_ALLOW_UNFREE=1 nix run 'github:nixos/nixpkgs?ref=21de726c192ca9e7cc02a376dda62070272e1046#plasticity' --impure`
2. Do some basic movements / editing
3. It is slow (drops regularly to 11 FPS). Also seems to display geometry incorrectly. (See fig 1.)

## Expected behavior

Should be able to run >=60 FPS & correctly display cylinder & top geometry.

## Screenshots

![image](https://github.com/user-attachments/assets/236a130c-2efa-4e45-a648-422acde3ddb8)
_fig 1_

## Additional context

```
✨ ❯ inxi -G                                       2024-12-05 (Dec, Thu) 16:49:14 
Graphics:
  Device-1: NVIDIA AD103 [GeForce RTX 4080] driver: nvidia v: 560.35.03
  Device-2: AMD Raphael driver: amdgpu v: kernel
  Device-3: Netchip Nuroum V11
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.14 with: Xwayland v: 24.1.4
    compositor: kwin_wayland driver: gpu: nvidia,nvidia-nvswitch resolution:
    1: 3440x1440~60Hz 2: 2400x1350~60Hz
  API: Vulkan v: 1.3.296 drivers: N/A surfaces: xcb,xlib,wayland
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
```

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS 24.11 (Vicuna), 24.11.20241203.b681065`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/etc/nixPath`
 
## Notify maintainers

@imadnyc

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
