### ISSUE TITLE
nixos's clangd don't respect -nostdinc

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#363479]
## Describe the bug

`.clangd`:

```yaml
---
CompileFlags:
  Add:
    - -undef
    - -D__TI_COMPILER_VERSION__=7.4.24
    - -nostdinc
    - -nostdinc++
    - -isysroot/home/wzy/.local/share/c6000_7.4.24
    - -iwithsysroot/include
```

It still search `file:///nix/store/lw21wr626v5sdcaxxkv2k4zf1121hfc9-glibc-2.40-36-dev/include/stdio.h`,
not `/home/wzy/.local/share/c6000_7.4.24/stdio.h`.

For other OS (ArchLinux), it will work normally.

## Steps To Reproduce

1. Download a C runtime and put them to a path, such as /home/wzy/.local/share/c6000_7.4.24
2. edit `.clangd`
3. use editor to edit a C file, `#include <stdio.h>`
4. search its path and find it is incorrect.

## Expected behavior

Arch Linux,
![Screenshot_20241209_150253](https://github.com/user-attachments/assets/5b2b200f-d6bd-461f-8749-9d32d7fbce5b)

## Screenshots

![Screenshot_20241209_150222](https://github.com/user-attachments/assets/f312136a-f1f5-4a13-9757-652502c1142d)

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

maintainer: @patryk27
last modifier: @JohnRTitor @ShamrockLee

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
