### ISSUE TITLE
nixos/hardware.nvidia-container-toolkit: Missing nvidia_icd.json in docker

### ISSUE THREAD

**Issue by arakan94** [NixOS/nixpkgs#383085]
### Nixpkgs version

- Stable (24.11)

### Describe the bug

Not sure if this is the correct place to report this, but docker images run with nvidia-container-toolkit are missing the `/etc/vulkan/icd.d/nvidia_icd.json` file leading to `vulkaninfo` and `vkcube` not seeing Nvidia GPU.

### Steps to reproduce

Add container with vulkan support:
Dockerfile
```
FROM ubuntu:latest

ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV NVIDIA_VISIBLE_DEVICES=all

RUN apt-get update && \
    apt-get -y install \
    libxext6 \
    libvulkan1 \
    libvulkan-dev \
    libgl1 \
    vulkan-tools
```

docker-compose.yml
```
services:
  vulkan-docker:
    build: .
    command: sh -c "vulkaninfo --summary && vkcube"
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              capabilities: [all]
              device_ids: [nvidia.com/gpu=all]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- /home/david/vulkan_test/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json
    environment:
      - DISPLAY=${DISPLAY}
```

Build and run:
```
docker compose build
xhost +local:docker # allow access to X11 server
docker compose run vulkan-docker
```

Vkcube will be using CPU (llvm) and vulkaninfo won't see Nvidia GPU at all.

Manually map nvidia_icd.json to `/etc/vulkan/icd.d/nvidia_icd.json`:
```
{
    "file_format_version" : "1.0.1",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.289"
    }
}
```
(_versions taken from `/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.x86_64.json`)_

Now, running the container shows vkcube using Nvidia GPU correctly.

### Expected behaviour

The ICD file should be available automatically when deploying with Nvidia support.

### Relevant log output

```console

```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.76, NixOS, 24.11 (Vicuna), 24.11.20250215.a60651b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.12`
 - nixpkgs: `/nix/store/k5m013s96104sv1fl3awxn83l57j9dpm-source`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
