### ISSUE TITLE
nixos/kanidm: unixd support v2 config

### ISSUE THREAD

**Issue by samos667** [NixOS/nixpkgs#391080]
### Nixpkgs version

- Unstable (25.05)

### Describe the bug

Kanidm unixd have a new format version that provide more capabilities (notably map_group). But come with a breaking change on v1 config (pam_allowed_login_groups)

v1:
```toml
gid_attr_map = "name"
home_alias = "name"
hsm_pin_path = "/var/cache/kanidm-unixd/hsm-pin"
uid_attr_map = "name"
pam_allowed_login_groups = ["posix-users"]
```
v2:
```toml
version = "2"
gid_attr_map = "name"
home_alias = "name"
hsm_pin_path = "/var/cache/kanidm-unixd/hsm-pin"
uid_attr_map = "name"

[kanidm]
pam_allowed_login_groups = ["posix-users"]
[[kanidm.map_group]]
local = "wheel"
with = "posix-admins"
```

The issue is that nixos module explicity require services.kanidm.unixSettings.pam_allowed_login_groups to be set. Making no compatible to v2 format

### Steps to reproduce

```nix
services.kanidm.unixSettings = {
        version = "2";
        hsm_pin_path = "/var/cache/kanidm-unixd/hsm-pin";
        uid_attr_map = "name";
        gid_attr_map = "name";
        home_alias = "name";
        kanidm = {
          pam_allowed_login_groups = ["posix"];
          map_group = [
            {
              local = "wheel";
              "with" = "sudo";
            }
          ];
        };
      };
```
result in something like "require services.kanidm.unixSettings.pam_allowed_login_groups to be set" due to https://github.com/NixOS/nixpkgs/blob/c80f6a7e10b39afcc1894e02ef785b1ad0b0d7e5/nixos/modules/services/security/kanidm.nix#L371-L375

### Expected behaviour

Should support either v1 or v2 config

### Relevant log output

```console

```

### System metadata

 - system: `"aarch64-linux"`
 - host os: `Linux 6.13.6, NixOS, 25.05 (Warbler), 25.05.20250318.f5d806a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.5`
 - nixpkgs: `/nix/store/i6ihdhrnw5viahvr04wadyjsq12l1bln-source`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
