### ISSUE TITLE
incus: Nvidia passthrough support

### ISSUE THREAD

**Issue by rajil** [NixOS/nixpkgs#400096]
### Nixpkgs version

- Unstable (25.05)

### Describe the bug

Incus has a bug in version 6.11, nvidia passthrough doesnt work. It is fixed by patches as mentioned [here](https://github.com/zabbly/incus/issues/81#issuecomment-2780357391).

### Steps to reproduce

Incus fails to start if nvidia.runtime is set to "true".

Incus flake has the following,

```
  virtualisation.incus.package = pkgs.incus;
  virtualisation.incus.enable = true;
  systemd.services.incus.environment.INCUS_LXC_HOOK =
    "${config.virtualisation.incus.lxcPackage}/share/lxc/hooks";
```

Here is a test container config which fails to start,
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu noble amd64 (20250405_07:42)
  image.os: Ubuntu
  image.release: noble
  image.requirements.cgroup: v2
  image.serial: "20250405_07:42"
  image.type: squashfs
  image.variant: default
  nvidia.driver.capabilities: all
  nvidia.runtime: "true"
  volatile.base_image: 69d2c4b732067bd2ca820d84786c4532f95dfb206afe6c452953178a5052fe19
  volatile.cloud-init.instance-id: c80f6af8-1f83-4e9d-9f61-f8110dd5f292
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: 220547a0-939d-402e-a850-9d0737d49a25
  volatile.uuid.generation: 220547a0-939d-402e-a850-9d0737d49a25
devices:
  gpu:
    id: "0"
    type: gpu
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Error is,
```
$incus start test1
Error: Failed to run: /nix/store/g8a7p5s8221g3wgfpzgghymxvzamsn2w-incus-6.11.0/bin/incusd forkstart test1 /var/lib/incus/containers /run/incus/test1/lxc.conf: exit status 1
Try `incus info --show-log test1` for more info

$incus info --show-log test1
Name: test1
Description: 
Status: STOPPED
Type: container
Architecture: x86_64

Log:

lxc test1 20250419152106.913 ERROR    utils - ../src/lxc/utils.c:run_buffer:571 - Script exited with status 1
lxc test1 20250419152106.913 ERROR    conf - ../src/lxc/conf.c:lxc_setup:3948 - Failed to run mount hooks
lxc test1 20250419152106.913 ERROR    start - ../src/lxc/start.c:do_start:1268 - Failed to setup container "test1"
lxc test1 20250419152106.914 ERROR    sync - ../src/lxc/sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 4)
lxc test1 20250419152106.914 ERROR    lxccontainer - ../src/lxc/lxccontainer.c:wait_on_daemonized_start:837 - Received container state "ABORTING" instead of "RUNNING"
lxc test1 20250419152106.914 ERROR    start - ../src/lxc/start.c:__lxc_start:2114 - Failed to spawn container "test1"
lxc test1 20250419152106.914 WARN     start - ../src/lxc/start.c:lxc_abort:1037 - No such process - Failed to send SIGKILL via pidfd 17 for process 2155833
lxc 20250419152106.960 ERROR    af_unix - ../src/lxc/af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20250419152106.960 ERROR    commands - ../src/lxc/commands.c:lxc_cmd_rsp_recv_fds:128 - Failed to receive file descriptors for command "get_init_pid"
```

### Expected behaviour

Incus container should start

### Relevant log output

```console

```

### System metadata

nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.23, NixOS, 25.05 (Warbler), 25.05.20250412.2631b0b`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
