### ISSUE TITLE
Steam unable to detect OS (NixOS)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#63839]
## Issue description

For visibility of our project it would be good if Steam can detect NixOS.

Then it might appear in their stats: https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=linux

Error on console:

`sh: lsb_release: command not found`

Related to https://github.com/NixOS/nixpkgs/issues/22729

Currently detected system informations:

```
Betriebssystem:
    Linux 4.x (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.19.47
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 12004000
    X-Fenstermanager: Mutter(Gala)
    Steam-Runtime-Version: <Runtime enabled>
```

### Steps to reproduce

1. open steam
2. view system informations

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.47, NixOS, 19.03.172783.a0b7a7913c4 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.172783.a0b7a7913c4, nixos-hardware, nixos-unstable-19.09pre181392.4ab1c14714f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
