### ISSUE TITLE
xpra does not build

### ISSUE THREAD

**Issue by cdyson37** [NixOS/nixpkgs#65272]
**Describe the bug**
xpra fails to build in unstable.

**To Reproduce**
```
$ nix-build -E 'import <nixpkgs> {}' -A xpra
error: opencv-2.4.13 not supported for interpreter python3.7
(use '--show-trace' to show detailed location information)
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-957.el7.x86_64, CentOS Linux, 7 (Core)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(nix): `"nixpkgs-19.09pre186326.62cb4f72282"`
 - nixpkgs: `/home/nix/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: xpra
# a list of nixos modules affected by the problem
module:
```
