### ISSUE TITLE
Chicken scratch doesn't work out of the box

### ISSUE THREAD

**Issue by mjgpy3** [NixOS/nixpkgs#65270]
**Describe the bug**
Running `csc` to compile chicken scratch programs breaks.

The specific error follows, asking for `types.db`

> Error: default type-database `types.db' not found
> 
> Error: shell command terminated with non-zero exit status 256: '/nix/store/xfbnnk4rkgakc3sahn5h9q3g47iy7p91-chicken-5.0.0/bin/chicken' 'hello.scm' -output-file 'hello.c'

**To Reproduce**
1. Install the `chicken` package
2. Create `hello.scm` with the contents `(display "Hello world!\n")`
3. Run `csc hello.scm`

**Expected behavior**
Outputs
> Hello world!

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.46, NixOS, 19.03.172754.0728c3e026e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: chicken
# a list of nixos modules affected by the problem
module:
```
