### ISSUE TITLE
qutebrowser doesn't start

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#65290]
**Describe the bug**
qutebrowser doesn't start

**To Reproduce**
1. Use the latest nixos-unstable
2. Start qutebrowser

**Expected behavior**
qutebrowser starts

**Screenshots**
![2019-07-23_08-27](https://user-images.githubusercontent.com/178496/61687960-fce77a80-ad23-11e9-929a-58c8d7719cf6.png)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.60, NixOS, 19.09pre186326.62cb4f72282 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(philipp): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/82bi282j8b6xx1gksqxjvrmwqh1mzwh4-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
