### ISSUE TITLE
QT_QPA_PLATFORM=xcb not available?

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#65355]
**Describe the bug**
I had previously been running `obs` with the `xcb` backend.

I don't think I've changed anything relevant, but `xcb` is no longer available?

```
env QT_QPA_PLATFORM=xcb obs
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

Aborted (core dumped)
```

I know the wayland backends are provided by getting `qt5.qtwayland` into my environment. Is something now necessary in the same fashion for the `xcb` backend to be available?

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
