### ISSUE TITLE
haskellPackages.servant: wrong hash for docs

### ISSUE THREAD

**Issue by yurrriq** [NixOS/nixpkgs#65400]
**Describe the bug**
The hash for `docs` under `servant` in `common-configuration.nix` is `0kqglih3rv12nmkzxvalhfaaafk4b2irvv9x5xmc48i1ns71y23l` when it should be `0n9xn2f61mprnvn9838zbl4dv2ynnl0kxxrcpf5c0igdrks8pqws`, according to my system.

**To Reproduce**
```sh
nix-build -p pkgs.haskellPackages.servant
```

**Expected behavior**
I expect `servant` (and thus `cachix`) to be buildable on my system.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03pre-git (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(yurrriq): `"nixos-19.03-19.03.173098.88cb463a3b9"`
 - nixpkgs: `/nix/store/h656xbkp5x3q44snnz16l7rykfacj1dg-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- haskellPackages.servant
# a list of nixos modules affected by the problem
module:
```
