### ISSUE TITLE
lutris-free: GOG integration broken due to missing dependency

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#65416]
**Describe the bug**

Trying to install a GOG game yields just the following window:

![Selection_078](https://user-images.githubusercontent.com/1663259/61954045-3506eb80-afb8-11e9-9bd8-374a5d9d3b5c.png)

**To Reproduce**
1. Add a GOG game to your library (eg. via the website)
2. Double-click it in the Lutris interface
3. Click the "Install" button for GOG
4. Click "Install" in the installation directory window

**Expected behavior**

Presumably, some sort of login popup is supposed to appear, that enables the integration.

**Screenshots**

See above.

**Additional context**

I'm using `lutris-free` due to an unrelated installation issue with Steam, but I suspect that the main `lutris` attribute suffers from the same issue.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.56, NixOS, 19.03.173182.96151a48dd6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173182.96151a48dd6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

(Note: Lutris installed from `unstable`)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ lutris-free ]
# a list of nixos modules affected by the problem
module:
```
