### ISSUE TITLE
e2fsprogs 1.45.2 transient failures

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#65471]
**Describe the bug**
Since we have e2fsprogs version 1.45.2 I've noticed transient failures of certain tests when building e2fsprogs. 

https://hydra.nixos.org/build/97065990

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: e2fsprogs
# a list of nixos modules affected by the problem
module:
```
