### ISSUE TITLE
openscad: fails to start

### ISSUE THREAD

**Issue by c00w** [NixOS/nixpkgs#65514]
**Describe the bug**

**To Reproduce**
1. Run openscad

**Expected behavior**
Openscad opens

**Screenshots**
```
 % openscad                                                                              ~/brood/src/data
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      openscad
```

**Additional context**
I'm using nvidia graphics drivers

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
nix run nixpkgs.nix-info -c nix-info -m                     ~/brood/src/ml

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.60, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(colin): `""`
 - channels(root): `"nixos-19.09pre186563.b5f5c97f7d6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

I don't use nix-channels to manage my version - I'm at commit b5f5c97f7d67a99b67731a8cfd3926f163c11857

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- openscad
# a list of nixos modules affected by the problem
module:
```
