### ISSUE TITLE
Nikola build fails

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#65527]
**Describe the bug**
build fails on stable, unstable works

so backporting https://github.com/NixOS/nixpkgs/pull/56305 should fix it

**To Reproduce**
1. nix run -f channel:nixos-19.03 python3Packages.Nikola

**Expected behavior**
working build

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173165.55b8860aa20 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.173198.aeeb30a3b29, nixos-hardware, nixos-unstable-19.09pre186563.b5f5c97f7d6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.Nikola
# a list of nixos modules affected by the problem
module:
```
