### ISSUE TITLE
VirtualBox: Virtual machines fail to start.

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#65564]
**Describe the bug**

On the latest nixos-unstable (b5f5c97f7d67a99b67731a8cfd3926f163c11857), starting any virtual machine gives me error:
```
The virtual machine 'Fedora' has terminated unexpectedly during startup because of signal 6.
Result Code: | NS_ERROR_FAILURE (0x80004005)
Component: | MachineWrap
Interface: | IMachine {5047460a-265d-4538-b23e-ddba5fb84976}
```

**To Reproduce**
1. Use VirtualBox on nixos-unstable
2. Start a virtual machine

**Screenshots**
![Screenshot_2019-07-29_20-11-34](https://user-images.githubusercontent.com/2626481/62071575-23824580-b23d-11e9-8d49-6e9e90856eb0.png)

**Additional context**
Seems to have been caused by updating.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: linuxPackages.virtualbox
# a list of nixos modules affected by the problem
module: virtualbox
```
