### ISSUE TITLE
zoom-us fails to build correctly

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#65562]
**Describe the bug**

zoom-us appears to be broken. Caused by a change between b5f5c97f7d67a99b67731a8cfd3926f163c11857...239fffc90d792b5362a20ec1a009978de7b8f91a.

**To Reproduce**
1. ```nix build -f channel:nixos-unstable zoom-us```

**Expected behavior**
Success

**Additional context**
Logs:

```
/nix/store/01xalm9xmzv24s6hwr4l6pp71cz67rsx-stdenv-linux/setup: line 1289: /nix/store/mfm8p0n326fzfa8iiihq32qb78sbym9s-zoom-us-qt-5.9.7/bin/qt.conf: Permission denied
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173201.defa89ffaef (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173201.defa89ffaef"`
 - channels(mbauer): `"nixpkgs-19.09pre186857.239fffc90d7"`
 - nixpkgs: `/home/mbauer/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zoom-us
# a list of nixos modules affected by the problem
module:
```

/cc @ttuegel
