### ISSUE TITLE
Please increment Jupyterlab

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#65586]
**Describe the bug**
Jupyterlab is on version 1.0.4 now, it looks like, but the Nixpkgs version is 0.35 or so. The problem is, the visualization library Altair requires Jupyterlab >1.0, and I don't have the wherewithall with Nix to increment this version myself. 

**To Reproduce**
1. Try to use Altair to produce a chart (i.e. with Jupyterlab)
2. Note that it requires Jupyterlab 1.0 or greater
3. Try to install Jupyterlab 1.0 or greater????

**Expected behavior**
Jupyterlab should be up to date. 

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
- python37Packages.jupyterlab
module:
```
