### ISSUE TITLE
Mixxx fails to open

### ISSUE THREAD

**Issue by sam-willis** [NixOS/nixpkgs#65667]
**Describe the bug**
When running the Mixxx package it fails to open and prints:

> Warning [Main]: Could not find the Qt platform plugin "xcb" in ""
> Fatal [Main]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 

**To Reproduce**
Steps to reproduce the behaviour:
1) Run `nix-env -iA nixos.mixxx`
3) Run `mixxx` from the command line.

**Expected behavior**
Mixxx opens its GUI

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.09pre186857.239fffc90d7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"home-manager, nixos-19.09pre186857.239fffc90d7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mixxx
# a list of nixos modules affected by the problem
module:
```
