### ISSUE TITLE
zoom-us: Missing desktop icon

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#65678]
**Describe the bug**

`zoom-us` is missing its icon, because it does not appear in the source tarball.

I see a couple of options to fix:

1. Fetch the icon separately, perhaps from https://github.com/flathub/us.zoom.Zoom
2. Change the source to one of the packaged releases for another distro that includes the icon

cc @danbst 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zoom-us
# a list of nixos modules affected by the problem
module:
```
