### ISSUE TITLE
vscode: integrate vscode with libdbusmenu

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#65680]
**Describe the bug**
Allow vscode and firefox support for libdbusmenu,like with libreoffice

**To Reproduce**
1. Install `vscode` in KDE
2. Run `code` with ` "window.titleBarStyle": "native"`

**Expected behavior**
The title bar integrated in KDE's menu button

**Screenshots**
![Desktop 2_001](https://user-images.githubusercontent.com/6931743/62236426-9a931780-b3be-11e9-95d2-7cfbceac6855.png)

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.16, NixOS, 19.09pre186408.3d84cffe955 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre20190712_aa82f8b`
 - channels(root): `"nixos-19.09pre186408.3d84cffe955"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
- vscode
- vscode-with-extensions
- vscodium
# a list of nixos modules affected by the problem
module:
```
