### ISSUE TITLE
nix.maxJobs is broken with "auto"

### ISSUE THREAD

**Issue by c00w** [NixOS/nixpkgs#65708]
**Describe the bug**

setting 
  nix.maxJobs = "auto";
Causes
    nix.nrBuildUsers = mkDefault (lib.max 32 cfg.maxJobs);
to fail.

**To Reproduce**
1. set nix.maxJobs ="auto" in you nixos config
2. build it
3. ...

**Expected behavior**
You should be able to set nix.maxJobs to auto to saturate your cpu cores.

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(colin): `""`
 - channels(root): `"nixos-19.09pre186563.b5f5c97f7d6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
nix
```
