### ISSUE TITLE
Segmentation fault while installing NixOS on travis

### ISSUE THREAD

**Issue by vedhavyas** [NixOS/nixpkgs#65717]
**Describe the bug**
NixOS installation fails randomly with a seg fault
```
$ bash <(curl https://nixos.org/nix/install)
downloading Nix 2.2.2 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-2.2.2/nix-2.2.2-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.EKUWFTKp9k'...
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown travis /nix' using sudo
copying Nix to /nix/store.................................
initialising Nix database...
Nix: creating /home/travis/.nix-profile
installing 'nix-2.2.2'
building '/nix/store/2c4l83wkdfrj7ra9k07l0aqvym1d5z20-user-environment.drv'...
created 6 symlinks in user environment
Segmentation fault (core dumped)
```

**To Reproduce**
fails randomly

**Expected behavior**
Installation should not fail

**Screenshots**

**Additional context**
We observed this on TravisCI

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
