### ISSUE TITLE
Bacula module doesn't allow Autochanger

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#65805]
**Describe the bug**

 `services.bacula-sd` doesn't have an attribute set for `Autochanger` or an `extraConfig` option to add it by hand - so AFAIK it's not possible to configure an `Autochanger` for `bacula-sd` using the nixos config. 

**Expected behavior**
Being able to add my autochanger to the `bacula-sd` config, so that I can use a tapelibrary with bacula on a nixos system.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.61, NixOS, 19.03.173193.112f522d48c (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173193.112f522d48c"`
 - channels(wucke13): `"nixos-unstable-19.09pre185259.362be9608c3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
