### ISSUE TITLE
rustc: hydra build failed

### ISSUE THREAD

**Issue by matthias-t** [NixOS/nixpkgs#66120]
**Describe the bug**
https://hydra.nixos.org/job/nixpkgs/trunk/rustc.x86_64-linux

***

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- rustc
# a list of nixos modules affected by the problem
module:
```
