### ISSUE TITLE
qbittorent fails to run

### ISSUE THREAD

**Issue by sam-willis** [NixOS/nixpkgs#66339]
**Describe the bug**
Running qbittorrent causes the following error
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

```
**To Reproduce**
Install qbittorrent and run

**Expected behavior**

**Screenshots**

**Additional context**
Another example of:
https://github.com/NixOS/nixpkgs/issues/65399

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qbittorrent
# a list of nixos modules affected by the problem
module:
```
