### ISSUE TITLE
tinc: Service fails to restart on host configuration changes

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#66431]
**Describe the bug**

When modifying a host configuration in ones `services.tinc` config (stored in `/etc/tinc/<name>/hosts`), the relevant tinc service does not restart. This is because only the main `tinc.conf` has been added to `restartTriggers`.

[This post](https://github.com/NixOS/nixpkgs/pull/27660#issuecomment-321419593) appears to include a solution, but has not actually been merged into nixpkgs for some reason that is unclear to me. (cc @volth)

**To Reproduce**
1. Create a `services.tinc` network.
2. Rebuild/deploy system.
3. Change configuration for one specific host in `hosts`.
4. Rebuild/deploy system again. Tinc service fails to restart/reload.

**Expected behavior**

Tinc service should restart/reload on host configuration changes.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.56, NixOS, 19.03.173251.56d94c8c69f (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173251.56d94c8c69f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.tinc
```
