### ISSUE TITLE
samba smbd started before network is ready

### ISSUE THREAD

**Issue by sweber83** [NixOS/nixpkgs#66520]
**Describe the bug**
We have setup samba to bind to specific ip addresses only.
When the machine boots, smbd is unable to bind to the ip address of the ethernet adapter (localhost works fine).
Restarting smbd solves the problem temporarily.
When we add "After=network.target" to the samba-smbd service, it fixes the problem.
We are not sure, why samba-nmbd does not suffer from this problem.

**To Reproduce**
1. Configure samba like so:
```
bind interfaces only = yes
interfaces = 192.168.0.1 127.0.0.1
```
2. reboot machine
3. Check if smbd is listening on 192.168.0.1:
```
netstat -lnp | grep 192\.168\.0\.1 | grep smbd
```

**Expected behavior**
Expected smbd to be listening on 192.168.0.1 after reboot.

**Additional context**
The affected machines are deployed via nixops.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.65, NixOS, 19.03pre-git (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-17.03.889.9626bc7db7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: samba
```
