### ISSUE TITLE
`kitty` term info copy does not work

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#66583]
**Describe the bug**
Kitty has a shortcut to copy terminfo to target server

**To Reproduce**
1. ... kitty +kitten ssh root@x.x.x.x
2. ... error FileNotFoundError: [Errno 2] No such file or directory: 'infocmp': 'infocmp'

**Expected behavior**
Connected to the server

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.8, NixOS, 19.09pre188690.8746c77a383 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre188690.8746c77a383"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: kitty
# a list of nixos modules affected by the problem
module:
```
