### ISSUE TITLE
erlang fails to build on macOS

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#66644]
**Describe the bug**
The current version of `erlang` fails to build on macOS. From the error message it sounds like it believes the current macOS version is 10.10. The error message in question, from the configure phase:

```
  You are natively building Erlang/OTP for a later version of MacOSX
  than current version (10.10). You either need to
  cross-build Erlang/OTP, or set the environment variable
  MACOSX_DEPLOYMENT_TARGET to 10.10 (or a lower version).
```

I suspect this was caused by https://github.com/NixOS/nixpkgs/pull/64458 which bumped our `MACOSX_DEPLOYMENT_TARGET` to 10.12. I have no idea why Erlang thinks the current macOS version is 10.10 (I'm running macOS 10.14).

**To Reproduce**
1. On macOS, run `nix-env -iA nixpkgs.erlang`, or from a nixpkgs checkout run `nix-build -A erlang .`

**Expected behavior**
It should build.

**Additional context**

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(lily): `"nixpkgs-19.09pre188239.c0e56afddbc"`
 - nixpkgs: `/Users/lily/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: erlang
# a list of nixos modules affected by the problem
module:
```
