### ISSUE TITLE
home-assistant failing to build on 19.03

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#66674]
**Describe the bug**

**To Reproduce**
`nix build -f channel:nixos-19.03 home-assistant`

**Expected behavior**
home-assistant builds

**Additional context**
Hydra log:
https://hydra.nixos.org/build/98271775

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.58, NixOS, 19.03.173251.56d94c8c69f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173251.56d94c8c69f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: home-assistant
# a list of nixos modules affected by the problem
module: home-assistant
```
