### ISSUE TITLE
hardware.pulseaudio.enable conflicts with sound.mediaKeys.enable

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nixpkgs#66854]
**Describe the bug**
I was using ALSA just fine but recently enabled PulseAudio for bluetooth support and noticed my media keys on my laptop no longer work. I checked the output of `nixos-option services.actkbd.bindings` to ensure that the key bindings were still set and indeed they are. In fact if I run the amixer commands manually from the cmdline they still work just fine. Somehow PulseAudio is interfering in a way I don't quite understand. I tried to fix myself but cannot pinpoint the issue.

**To Reproduce**
1. enable sound.mediaKeys.enable
2. open alsamixer from command line and use your media keys on your keyboard and ensure they work to manipulate the volume
3. enable hardware.pulseaudio.enable
4. repeat step 2 and notice that the media keys no longer manipulate the alsamixer volume

**Expected behavior**
I checked the module declarations for PulseAudio and it does not set or declare actkbd in any way shape or form so it should not interfere with its operation when set by sound.mediaKeys.enable. In other words, the media keys option should work with or without PulseAudio

**Screenshots**
N/A

**Additional context**
if I run the commands `amixer set Master 1%- unmute` manually it works fine even with PulseAudio enabled. This is the same command set by actkbd through the sound.mediaKeys options binded to the media keys. Seeing this I am a little perplexed as to why there is an issue at all.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.9-rt3, NixOS, 19.09.git.a2bd8da (Loris)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(<user>): `""`
 - channels(root): `""`
 - nixpkgs: `/home/<user>/git/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- sound.mediaKeys.enable
- hardware.pulseaudio.enable
# a list of nixos modules affected by the problem
module:
- alsa
- pulseaudio

```
