### ISSUE TITLE
No module named 'wheel.install'

### ISSUE THREAD

**Issue by smurfless1** [NixOS/nixpkgs#67122]
**Describe the bug**
Unable to use pants on OS X with error "No module named 'wheel.install'"

**To Reproduce**
Install pants 1.8 using home page curl, chmod +x instructions.
./pants generate-pants-ini

**Expected behavior**
generate a pants ini

**Screenshots**
```$ ./pants generate-pants-ini
timestamp: 2019-08-20T13:44:53.734968
Exception caught: (builtins.ModuleNotFoundError) (backtrace omitted)
Exception message: No module named 'wheel.install'
```

**Additional context**
I cleared the ~/.cache directory and get the same problem every time. 
Homebrew installations of python3 are present, but not active at the time of pants install.
Trying with homebrew python3 was no different.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
"command not found"

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
