### ISSUE TITLE
Tensorflow crashes on GPU

### ISSUE THREAD

**Issue by jyp** [NixOS/nixpkgs#67257]
**Describe the bug**

When trying to run a tensorflow program on GPU, I get the following error:
```
tensorflow/stream_executor/cuda/cuda_driver.cc:175] Check failed: err == cudaSuccess || err == cudaErrorInvalidValue Unexpected CUDA error: unknown error
Aborted (core dumped)
```
**To Reproduce**
- Using nix-shell master from today:
- LD_PRELOAD=/lib64/libcuda.so.1:/lib64/libnvidia-fatbinaryloader.so.418.74 python
- run tensorflow program

**Expected behavior**
No crash.

**Additional context**
This was tested on master from yesterday.

The machine is not a nixos machine, see below.

I am also seeing the same behaviour with pytorch. I am expecting that somehow a wrong version of a library is loaded. But I do not know how to figure out the mismatch.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.17-200.fc29.x86_64, Fedora, 29 (Server Edition)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`

(Not copying the irrelevant nix channels).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
