### ISSUE TITLE
clucene_core_2 fails to cross-compile

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#67505]
**Describe the bug**
clucene_core_2 fails to cross-compile with some weird errors. 

**To Reproduce**
`nix-build '<nixpkgs>' --arg crossSystem '{ system = "armv7l-linux"; }' --arg system builtins.currentSystem -A clucene_core_2 `

**Expected behavior**
clucene_core_2 builds

**Screenshots**
n/a

**Additional context**
It's a dependency of dovecot, though an optional one. I was able to compile dovecot without it by using overrideAttrs. The library seems to provide full-text search capabilities to Dovecot.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.09pre190102.8b56d205b2e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"cleveca22, nixos-19.09pre190102.8b56d205b2e"`
 - channels(kisik21): `"home-manager"`
 - nixpkgs: `/home/kisik21/Projects/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - clucene_core_2
 - dovecot
# a list of nixos modules affected by the problem
module:
```
