### ISSUE TITLE
judy fails to cross-compile

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#67619]
**Describe the bug**
judy (a dependency of mariadb) fails to cross-compile.

**To Reproduce**
`nix-build '<nixpkgs>' --arg crossSystem '{ system = "armv7l-linux"; }' --arg localSystem '{ system = "x86_64-linux"; }' -A judy`

**Expected behavior**
Judy should build correctly

**Screenshots**
A build log from my (currently private) Hydra instance shall be attached to this issue: 
[3lfa35d6rq50pghkp6rmp6iwnh1v65qw-judy-1.0.5-armv7l-unknown-linux-gnueabihf.drv.log](https://github.com/NixOS/nixpkgs/files/3550869/3lfa35d6rq50pghkp6rmp6iwnh1v65qw-judy-1.0.5-armv7l-unknown-linux-gnueabihf.drv.log)

**Additional context**
This is another of my issues about cross-compiling. I discovered by setting up a (currently private) Hydra instance that tries to cross-compile things.

**Metadata**
I have tested it on my Hydra and on my laptop, and it's consistent between Nixpkgs revisions right now. Here's metadata from my laptop:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.09pre190102.8b56d205b2e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"cleveca22, nixos-19.09pre190102.8b56d205b2e"`
 - channels(kisik21): `"home-manager"`
 - nixpkgs: `/home/kisik21/Projects/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - judy
 - mariadb
# a list of nixos modules affected by the problem
module:
```
