### ISSUE TITLE
services.postfix.{aliasFiles/mapFiles} fails if the file is not owned by root

### ISSUE THREAD

**Issue by d3rped** [NixOS/nixpkgs#67630]
**Describe the bug**
Running postmap/postalias on a linked file that is not owned by root fails with:
`postalias: fatal: open aliases.db: Permission denied`

**To Reproduce**
1. `echo "postmaster: root" > aliases`
2. `chown SOME_USER aliases`
3. `ln -s aliases aliases_linked`

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
