### ISSUE TITLE
Manual fails to build from master

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#67726]
**Describe the bug**
From revision `604b7c139f4d44d9fb0e84d812efdfcf5dda3448` to the current master (` f86bbb218cacd968aecdd1374a42d23262c23d3b`) the documentation fails to build
**To Reproduce**
1. `git clone https://github.com/NixOS/nixpkgs`
2. `git checkout 604b7c139f4d44d9fb0e84d812efdfcf5dda3448`
3. `nixos-rebuild build` (I used `nixops deploy --build-only` because I found out the bug when deploying nixops deployment from master)

**Expected behavior**
Manual should build.

**Screenshots**
A build log shall be attached to this issue: [failure.log](https://github.com/NixOS/nixpkgs/files/3557195/failure.log)

**Additional context**
The revisions mentioned earlier were determined using `git bisect` on the master branch.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
 - nixos/doc/manual/default.nix
```
