### ISSUE TITLE
virt-manager doesn't save config

### ISSUE THREAD

**Issue by MoritzFago** [NixOS/nixpkgs#67736]
**Describe the bug**

**To Reproduce**
1. $ nix-env -iA nixos.virtmanager
2. change some config, for example add a connection
3. close virt-manager
4. reopen virt-manager

**Expected behavior**
config is preserved through restarts of application

**Additional context**
Fix: $ nix-env -iA nixos.gnome3.dconf

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.57, NixOS, 19.03.173389.51e1e3ceaf0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173389.51e1e3ceaf0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs/pkgs/applications/virtualization/virt-manager/default.nix
# a list of nixos modules affected by the problem
module:
```
