### ISSUE TITLE
Installer ISO stuck in stage1 when booted from (micro) SD card

### ISSUE THREAD

**Issue by andir** [NixOS/nixpkgs#67821]
**Describe the bug**
When an installer image is copied onto a SD card and booted on hardware supporting boot from SD cards (e.g. my XP13 9380) the boot loader loads fine, the stage1 boot starts but fails to find the root device (the SD card). It seems that we are just missing drivers for those devices within the initramfs / stage1.

**To Reproduce**
1. create an ISO installer from master
2. copy / dd it to a (micro) SD card
3. boot from the SD card
4. stage1 fails to find the root device.
5. launch the interactive shell and verify that `/dev/mmcblkX` isn't present.

**Expected behavior**
We should be able to boot x86_64-linux installer from SD cards. Many devices support booting from them and it is a nice alternative to USB sticks (mostly because they disappear into their slot and you do not have to care about them much).

**Additional context**

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.10, NixOS, 19.09pre190978.8d1510abfb5 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6779_324a5dc9`
 - channels(root): `"nixos-19.09pre190978.8d1510abfb5"`
 - channels(andi): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  probably some of the installer profiles. I am not sure what is the best place to add the module. Also not sure what the entire landscape of drivers requried for most current systems is.
```
