### ISSUE TITLE
vim quickfix window closing broken in vim-8.1.0146+

### ISSUE THREAD

**Issue by m-scr** [NixOS/nixpkgs#67998]
**Describe the bug**
Vim quickfix window is opened with ":copen" and closed with ":cclose". ":cclose" fails to close the quickfix window in recent builds of nixpkg's vim-8.1.

vim-7.4 (fksd49gk2dgq23j64237gvjgqyp77rpl-vim-7.4.2367) works as expected, as well as 8.1 in other distro's releases (tested archlinux and ubuntu).

This is one of the oddest bugs I've ever encountered. I am open to any suggestion on how to debug the issue. Vim debug mode does not help, cclose is a single instruction.  

**To Reproduce**
1. Start vim skipping all initializations: "vim -u NONE" 
2. ":copen" will open the quickfix window
3. ":cclose" will fail to close the quickfix window

**Expected behavior**
":cclose" should close the quickfix window.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.5, NixOS, 19.09pre187507.525eaf407d4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre191505.7d5375ebf4c, nixos-stable-18.09.2574.a7e559a5504, old-16.09.1943.25f4906da6"`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: vim
# a list of nixos modules affected by the problem
module:
```
