### ISSUE TITLE
Dolphin "Unable to create io-slave. klauncher said: Unknown protocol 'baloosearch'."

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#68174]
**Describe the bug**

When running dolphin on plasma5, getting this error:

```
Unable to create io-slave. klauncher said: Unknown protocol 'baloosearch'.
```

/cc @ttuegel

**To Reproduce**
1. Open dolphin
2. Select "Search for -> Document"
3. Observe error

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.09pre191505.7d5375ebf4c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre191505.7d5375ebf4c"`
 - channels(mbauer): `"nixpkgs-19.09pre191265.c4adeddb5f8"`
 - nixpkgs: `/home/mbauer/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dolphin
# a list of nixos modules affected by the problem
module:
```
