### ISSUE TITLE
zfs-user doesn't cross-compile because of Python usage

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#68251]
**Describe the bug**
ZFS userspace packages don't cross-compile on ARM - configurePhase "can't find python in PATH". I tried to read the Nix expression - Python is placed in buildInputs. Can it be moved to nativeBuildInputs? where is it used?

**To Reproduce**
`nix-build '<nixpkgs>' --arg crossSystem '{ system = "armv7l-linux"; }' --arg system builtins.currentSystem -A zfsStable`

**Expected behavior**
zfs builds normally

**Screenshots**
n/a

**Additional context**
This may be a major blocker for cross-compiling NixOS on ARM.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.68, NixOS, 19.09.git.9e90586 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre188690.8746c77a383"`
 - nixpkgs: `/home/vika/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - zfsStable
 - zfsUnstable
# a list of nixos modules affected by the problem
module:
```
