### ISSUE TITLE
`nc` doesnt' find system certificate store anymore

### ISSUE THREAD

**Issue by andir** [NixOS/nixpkgs#68286]
**Describe the bug**
The `nc` attribute (provided by LibreSSL) is no longer able to find the system certificates on NixOS. It seems like with the change to the CMake build system / with the switch to libressl 2.9 the feature broke.

**To Reproduce**
1. `nix-shell --pure -p nc` with a current master / recent unstable channel.
2. `nc -cvz google.com 443`
3. See `nc: failed to open CA file '/etc/ssl/cert.pem': No such file or directory`

**Expected behavior**
`nc` should have been able to connect to find the local system certificates and connect successfully.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.11, NixOS, 19.09.git.920dd87 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6895_84de821`
 - channels(root): `"nixos-19.09pre190978.8d1510abfb5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nc
  - libressl_2_9.nc
  - libressl_3_0.nc
# a list of nixos modules affected by the problem
module: []
```
cc libressl maintainers @fpletz @thoughtpolice
