### ISSUE TITLE
manual build fails because of jing-trang blocking channels

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#68307]
**Describe the bug**
The jing-trang package fails to build. This blocks channels from advancing.

https://nix-cache.s3.amazonaws.com/log/7mvnpavvh5gcsprijv3ax1hz7m14m621-jing-trang-20151127.drv

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: jing-trang
# a list of nixos modules affected by the problem
module:
```
