### ISSUE TITLE
Can't automatically login to KDE wallet

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#68316]
**Describe the bug**
After upgrading to 19.09pre, I am always asked for a password to unlock from . I don't recall this happening in 19.03

Some more info on how to set this up:

https://wiki.archlinux.org/index.php/KDE_Wallet#Unlock_KDE_Wallet_automatically_on_login

**To Reproduce**
1. Configure KDE with KWallet enabled
2. Log out and back in
3. Try to launch chromium
4. Notice that a password is needed

**Expected behavior**
Password used for login is used to unlock kwallet.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.09pre191617.4e60699fa72 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre191617.4e60699fa72"`
 - channels(mbauer): `"nixpkgs-19.09pre192076.4179ba049cf"`
 - nixpkgs: `/home/mbauer/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
