### ISSUE TITLE
Creation date not shown in Dolphin file manager

### ISSUE THREAD

**Issue by digitalsignalperson** [NixOS/nixpkgs#68334]
**Describe the bug**

In Dolphin, adding a column for "Created" date does not show anything in the column.

This is supposed to be fixed as of KDE Frameworks 5.58: 

> With KDE Frameworks 5.58, the Dolphin file manager and other KDE applications will finally begin displaying file creation dates/times as a long sought after feature on Linux systems. 
(https://www.phoronix.com/scan.php?page=news_item&px=KDE-Finally-File-Creation-Times)

KInfoCenter indicates KDE Frameworks Version 5.61.0. 

**To Reproduce**
1. Use nixos-unstable channel
2. Enable plasma5 desktop and sddm

**Expected behavior**
Creation date should be shown. Can confirm it works as expected on an Arch Linux install since 5.58

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.09pre191617.4e60699fa72 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre191617.4e60699fa72"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ plasma5 dolphin kdeFrameworks ]
# a list of nixos modules affected by the problem
module:
```
