### ISSUE TITLE
qtwebkit build is aborted because of log size

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#68341]
**Describe the bug**
qtwebkit fails to build. This impacts the whole of KDE.

**Metadata**
https://hydra.nixos.org/build/100190178

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qt5.qtwebkit
# a list of nixos modules affected by the problem
module:
```
