### ISSUE TITLE
nixos/nginx: Don't have restart=always by default, can cause issues with letsencrypt ratelimits

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#68415]
**Describe the bug**
I had an error in my `nginx` config causing `nginx` to crash and restart,
but `nginx` has a `Wants` dependency on `acme-${cert}.service`.  which caused the cert renewal process to start over and over and over again until my IP block got blacklisted with Letsencrypt and now my website is down :)

**To Reproduce**
1. Get an nginx config with a syntax error and set `enableACME=true;`
2. Wait for you to hit the rate limits of Letsencrypt
3. Profit

**Expected behavior**
Nginx shouldn't restart automatically unless I configure it to do so. Or have rate limits on the restarts that are in line with the rate limits of letsencrypt

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nginx
# a list of nixos modules affected by the problem
module:
  - nginx
  - acme
```
