### ISSUE TITLE
nixos/taskserver: Firewall is opened on all interfaces

### ISSUE THREAD

**Issue by tilpner** [NixOS/nixpkgs#68839]
**Describe the bug**

If `services.taskserver.listenHost` is changed from its default value of `localhost`, the module sets

```
networking.firewall.allowedTCPPorts = [ cfg.listenPort ];
```

This option is interface-agnostic, and doesn't allow the user to restrict access to a single
interface easily.

**Expected behavior**

There should be a way to allow access on only some interfaces, even if `listenHost` was set.

Some modules have an `openFirewall` option, which would solve this nicely. With a default of true, backwards compatibility would be kept.

I'll send a PR if that sounds good.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.taskserver.listenHost
```

cc @aszlig
