### ISSUE TITLE
Cannot configure systemd sleep settings

### ISSUE THREAD

**Issue by svalaskevicius** [NixOS/nixpkgs#68974]
**Describe the bug**

Cannot configure systemd sleep settings.

After my last upgrade my laptop started poweroff at nights.. where I only wanted it to suspend. I suspect this is because of the default systemd settings... but I cannot change them?

**To Reproduce**

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/systemd.nix#L853
https://github.com/systemd/systemd/blob/master/src/sleep/sleep.conf

**Expected behavior**
I should be able to set config values

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
