### ISSUE TITLE
buildRustCrate does note set CARGO_FEATURE_<name>

### ISSUE THREAD

**Issue by danieldk** [NixOS/nixpkgs#68978]
**Describe the bug**

Cargo sets `CARGO_FEATURE_<name>`, as described in:

https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

Some crates uses these environment variables in their build scripts, such as `openblas-src`:

https://github.com/blas-lapack-rs/openblas-src/blob/4e22901068851a7db29550ae6886d0948fc30c2a/build.rs#L7

**Expected behavior**

`CARGO_FEATURE_<name>` is set in the same manner as in Cargo.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: buildRustCrate
# a list of nixos modules affected by the problem
module:
```
