### ISSUE TITLE
"man lsof" says can't open /run/current-system/sw/share/man/./version: No such file or directory

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#69225]
**Describe the bug**

```
# man lsof
/run/current-system/sw/bin/man: can't open /run/current-system/sw/share/man/./version: No such file or directory
No manual entry for lsof
```

**To Reproduce**
1. Run release-19.09 branch
2. Add lsof to systemPackages
3. `man lsof`

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.72-hardened, NixOS, 19.09.git.b981b1c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/var/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

cc @dezgeg
