### ISSUE TITLE
networking.firewall.extraCommands: should run before all drop/reject

### ISSUE THREAD

**Issue by eyJhb** [NixOS/nixpkgs#69265]
**Describe the bug**
`networking.firewall.extraCommands` should run before any drop/reject is specified, so that the user is allowed to input firewall rules before that.
Currently I need to add a rule before `iptables -t raw -A nixos-fw-rpfilter -j DROP`, but I am not allowed to do so, as it is added before `extraCommands` run.

Currently I remove and add it again.

**To Reproduce**
1. Try to add someting before the above specified
2. See it is added after
3. ...

**Expected behavior**
Should be added before the rule e.g.

```
-A nixos-fw-rpfilter -i tun0 -j RETURN
-A nixos-fw-rpfilter -j DROP
```

not

```
-A nixos-fw-rpfilter -j DROP
-A nixos-fw-rpfilter -i tun0 -j RETURN
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.72, NixOS, 19.03.173481.8a30e242181 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: networking.firewall
# a list of nixos modules affected by the problem
module: networking.firewall
```
