### ISSUE TITLE
Bonded network not working on Packet.net

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#69360]
**Describe the bug**
It takes ages for the routing table to come up

See https://github.com/NixOS/nixpkgs/issues/49534#issuecomment-528516916 for original thread.   
**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
