### ISSUE TITLE
ghc-8.6.5 fails to install on aarch64 (Ubuntu 18.04.2 LTS) 

### ISSUE THREAD

**Issue by sebeaumont** [NixOS/nixpkgs#69372]
**Describe the bug**
attempt to install ghc (ghc-8.6.5) fails with:

rts/Libdw.c: error "Please implement set_initial_registers() for your arch"

**To Reproduce**
1. nix-env -i ghc-8.6.5
2. ...
3. ...

**Expected behavior**
Expected ghc-8.6.5 to be built and available

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 nix run nixpkgs.nix-info -c nix-info -m
error: attribute 'nixpkgs' in selection path 'nixpkgs.nix-info' not found

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
