### ISSUE TITLE
Virtualbox: Unable to do a "Detachable" or "Headless" start of the first VM

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#69408]
**To Reproduce**
1. Start the Virtualbox GUI
2. Select a VM, ensure no other VM is running
3. Select Start -> "Detachable Start"

**Expected behavior**
VirtualBox is able to start the VM

**Additional context**
It fails to start the VM and spits out the following error message:

```
The VM session was aborted.

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | SessionMachine
Interface: | ISession {c0447716-ff5a-4795-b57a-ecd5fffa18a4}
```

Interestingly, it starts up just fine if there's another machine currently running (which was not started in headless or detatchable mode).

It might be another invocation of https://github.com/NixOS/nixpkgs/issues/65564.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.1, NixOS, 20.03.git.4fffa413869 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/home/flokli/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: virtualbox
# a list of nixos modules affected by the problem
module:
 - virtualbox
```

cc @ambrop72 @B4dM4n @jcumming
