### ISSUE TITLE
Installing teamspeak not working because of license agreement showing up

### ISSUE THREAD

**Issue by VanCoding** [NixOS/nixpkgs#69415]
**Describe the bug**
When adding `teamspeak_client` to `environment.systemPackages` and then running `nixos-rebuild switch`, at some point the license agreement of teamspeak shows up in the console and I couldn't find a way to accept it. Because of this, the installation is stuck forever at this point with no instructions how to continue.

**To Reproduce**
- add `teamspeak_client` to `environment.systemPackages`
- run `nixos-rebuild switch`

**Expected behavior**
The last command should complete and teamspeak should be installed on my system.

**Screenshots**
![image](https://user-images.githubusercontent.com/595361/65596681-a56dc100-df97-11e9-8667-1c6600c14449.png)

**Additional context**
I've tried both stable and unstable, but got the same result for both.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.71, NixOS, 19.09pre192418.e19054ab3cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(patrik): `"nixos-19.09pre190978.8d1510abfb5"`
 - channels(root): `"nixos-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - teamspeak_client
```
