### ISSUE TITLE
nix search doesn't give any results

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#70054]
**Describe the bug**
`nix search` doesn't give any results even when called with the `-u` flag

**To Reproduce**
```
nix-channel --list                                                                
nixos https://nixos.org/channels/nixos-unstable
 nix-channel --update                                                              
unpacking channels...
nix search -u gcc                                                                  
error: no results for the given search term(s)!
```

**Expected behavior**
`nix search` gives a list of packages

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.17, NixOS, 20.03pre194293.2436c27541b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20190922_382aa05`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - channels(paki): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nix
# a list of nixos modules affected by the problem
module:
```
