### ISSUE TITLE
Qdigidoc not probably wrapped with qt

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#70145]
**Describe the bug**
```
[nix-shell:~/.cache/nix-review/pr-69651]$ ./results/qdigidoc/bin/qdigidoc4
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
Aborted

**To Reproduce**
nix-shell -p qdigidoc4
qdigidoc4

**Expected behavior**
opens application

**Screenshots**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
$ nix run nixpkgs.nix-info -c nix-info -m
[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 19.03.173522.021d733ea3f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173549.ebdc4419310"`
 - channels(jon): `"home-manager, nixpkgs-20.03pre194293.2436c27541b"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
@yegortimoshenko (maintainer)

cc #65399
