### ISSUE TITLE
Reliable and trustworthy mirror for Epson artifacts (and maybe others)

### ISSUE THREAD

**Issue by d-goldin** [NixOS/nixpkgs#70155]
**Describe the bug**

Epson seems to be particularly aggressive about removing old versions of their drivers and utilities from their mirrors. This leads to build failures appearing for packages that have been building and working just fine for months, if not longer, when they are suddenly removed. This forces version updates, where maybe other thing would take priority. It also hurts reproducibility.

It would be great if we could figure out a way to host a mirror for such artifacts, ideally ensuring authenticity and integrity. 

I briefly looked into the source RPMs, and unfortunately they are not signed with Epson's PGP key, while the binary artifacts are. This makes it a bit iffy to just host them in some arbitrary github repo. I reached out to their `linux-printer` e-mail address provided in the README, but so far no response. 

If we can't get a signed archive from the vendor, then maybe trusted core members could sign the artifacts establishing some trust that way.

**To Reproduce**
1. package version
2. wait a few months
3. watch build failure due to 404

**Expected behavior**
We should be able to build packages for specific versions as long as we require the version.

**Additional context**

https://github.com/NixOS/nixpkgs/pull/69376
https://github.com/NixOS/nixpkgs/pull/69894#issuecomment-536577580

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
  - pkgs.epson-201106w
  - pkgs.epkowa
  - pkgs.epson-workforce-635-nx625-series
  - pkgs.epson-alc1100
  - pkgs.epson-escpr
  - pkgs.epson-escpr2
  - pkgs.epson_201207w
# a list of nixos modules affected by the problem
module:
```
