### ISSUE TITLE
chef-dk is broken and missing some utils

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#70171]
**Describe the bug**

**To Reproduce**
1. nix-build -A chefdk
2. ./result/bin/chef
3. ./result/bin/knife

**Expected behavior**
The chef executable is there but is broken, the knife executable isn't even present. 

**Additional context**
7136e0d0a6f61734994c566e2cc72fd75733b873 broke chef, it worked before that commit. I've bisected it down to that changeset.

Problem for me is that I don't know ruby or the ruby ecosystem...

This is a problem in 19.09 as well.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03pre193829.f0fec244ca3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre193829.f0fec244ca3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: chefdk
# a list of nixos modules affected by the problem
module:
```
