### ISSUE TITLE
Add JSON Support to universal-ctags

### ISSUE THREAD

**Issue by tredontho** [NixOS/nixpkgs#70191]
universal-ctags is not built with jansson, which means that universal-ctags does not have support for outputting JSON files.

1. Install universal-ctags
2. Run `ctags` with `--output-format=json`
3. Observe error: `ctags: unknown output format name supplied for "output-format=json"`

Expected: Tags file created with json format.

**Additional context**
I think this can be resolved by simply adding `jansson` to the `buildInputs`, but I've never written a nix package before so I'm not certain.  I did this locally and it seemed to work, but I don't know if there's a better way to do it.

**Metadata**
```yaml
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3`
 - channels(tredontho): `"nixpkgs-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/Users/tredontho/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: universal-ctags
# a list of nixos modules affected by the problem
module:
```
