### ISSUE TITLE
raspberry pi doesn't boot without monitor attached

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#70230]
**Describe the bug**
The 19.09 and unstable aarch64 sd images won't boot on the raspberry pi 3A+ (checked myself) and 3B+ (I think I heard this) if no monitor is connected to its HDMI port.

**To Reproduce**
1. Write 19.09 or unstable sd image to SD card
2. Insert SD card in raspberry pi
3. Power up with no monitor attached

**Expected behavior**
Boots.

**Actual behaviour**
Boot loop, where u-boot repeatedly resets when trying to initialise the graphical console.

**Additional context**
This works if the firmware in the pi boot partition is replaced with raspberrypifw from 19.03.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: raspberrypifw
# a list of nixos modules affected by the problem
module:
```

cc @mmahut who I believe had this issue too.
