### ISSUE TITLE
Running a command with sudo after sshing into any user causes the ssh session to hang 

### ISSUE THREAD

**Issue by ljdwigney** [NixOS/nixpkgs#70418]
**Describe the bug**
Running a command with sudo after sshing into any user causes the ssh session to hang 
Ctrl-c doesn't even kill the ssh session, a new terminal followed by pkill ssh is needed. Subsequent attempts at sshing allow me to enter the password and then do nothing and time out. If sudo is not run the session doesn't hang.

**To Reproduce**
The relevant part of my config:
`A clean install with just the following changed from a default config also has the issue.

services.openssh.enable = true;
users.users.liam = {
	isNormalUser = true;
	extraGroups = [ "wheel" ];
};
security.sudo = {
	enable = true;
	wheelNeedsPassword = true; 
};
`

Steps to reproduce the behaviour:
1. ssh user@hostname
2. run something with sudo, i.e. sudo nixos-rebuild switch or sudo vim configuration.nix
3. watch it freeze

**Expected behavior**
To not freeze

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.75, NixOS, 20.03pre194293.2436c27541b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - channels(liam): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: security users services
# a list of nixos modules affected by the problem
module: ssh openssh sudo
```
