### ISSUE TITLE
surf: dmenu and xprop missing from PATH

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#70410]
**Describe the bug**

`surf` doesn't have `xprop` and `dmenu` in PATH. This makes `surf` unusable because `dmenu` is needed for entering URLs. It works if I also install `dmenu` myself, but I'd expect `surf` to have all dependencies properly in PATH.

**To Reproduce**

Launch surf and try to enter URLs with `Ctrl+g`. Nothing happens and you'll see the following errors in the terminal:

```
$ nix-shell --pure -p surf

[nix-shell:~]$ surf
_SURF_URI: xprop: command not found
_SURF_URI: dmenu: command not found
_SURF_URI: xprop: command not found
_SURF_URI: dmenu: command not found
```

**Expected behavior**

`surf` should find `dmenu` and `xprop`.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03.git.44efee1 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: surf
# a list of nixos modules affected by the problem
module:
```
