### ISSUE TITLE
nixos-rebuild fails on i3 config on nixos-unstable channel

### ISSUE THREAD

**Issue by philroberts** [NixOS/nixpkgs#70436]
**Describe the bug**
I have the following option set in configuration.nix:

`services.xserver.windowManager.i3.configFile = ~/.config/i3/config;`

on nixos-unstable, a nixos-rebuild fails:

```
# nixos-rebuild dry-build
building the system configuration...
error: getting attributes of path '/root/.config/i3/config': No such file or directory
```

**To Reproduce**
1. set `services.xserver.windowManager.i3.configFile` to some path involving ~ that doesn't exist for root.
2. nixos-rebuild

**Expected behavior**
Successful rebuild.

**Additional context**
It works if I manually substitute the ~ with my fully qualified home directory.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.17, NixOS, 19.03.173552.bd5e8f35c2e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
services.xserver.windowManager.i3
```
