### ISSUE TITLE
vixie crontab(5) man page does not mention @reboot

### ISSUE THREAD

**Issue by rbrewer123** [NixOS/nixpkgs#70906]
**Describe the bug**
The man page for vixie cron's crontab format in nixos 19.03 does not mention the `@reboot` frequency directive, even though cron supports it.

**To Reproduce**
1. man 5 crontab
2. Search for reboot
3. Nothing found

**Expected behavior**
The man page should document `@reboot` and any other `@` frequency directives that are supported by the underlying cron.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- cron
```

cc @aanderse
