### ISSUE TITLE
nginx's enableACME fails because of ACMEv1 EOL

### ISSUE THREAD

**Issue by multun** [NixOS/nixpkgs#70966]
When enabling a new ACME site:

```
{
  "type": "urn:acme:error:unauthorized",
  "detail": "Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.",
  "status": 403
}
```

I *think* it would be fixed by an upgrade of simp_le

**To Reproduce**
1. add a new acme domain
2. nixos-rebuild switch

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nginx
# a list of nixos modules affected by the problem
module: nginx
```
