### ISSUE TITLE
plymouthd consumes 60% CPU on one core

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#71034]
**Describe the bug**
`plymouthd` seems to be confused.
I see a `@lymouthd --mode=boot --pid-file=/run/plymouth/pid --attach-to-session"` process constantly burning at around 60% of one cpu core - quite unpleasant on a laptop ;-)

`strace` suggests its polling excessively, with some "A start job is running for Hold until boot process finishes up" messages in between. This seems to be `plymouth-quit-wait.service`.

I'm not sure why the waiting service doesn't finish waiting (the system is powered on for quite some time), and also not why `@lymouthd` is handling this so badly

**To Reproduce**
```
services.xserver = {
  enable = true;
  desktopManager = {
    gnome3.enable = true;
  };
  windowManager = {
    default = "i3";
    i3.enable = true;
  };
};
boot.plymouth.enable = true;
```

**Additional context**
possibly related: https://github.com/NixOS/nixpkgs/pull/70357

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - host os: `Linux 5.3.5, NixOS, 20.03.git.e24526 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: plymouth
# a list of nixos modules affected by the problem
module: plymouth
```

cc @worldofpeace @jtojnar @hedning
