### ISSUE TITLE
not all gitea options can be customized

### ISSUE THREAD

**Issue by BrianHicks** [NixOS/nixpkgs#71116]
**Describe the bug**
If you provide gitea options (`services.gitea.extraConfig`) which have the same INI section as one already provided by the package, `gitea` will start in the install wizard instead of booting properly.

**To Reproduce**
1. set `services.gitea.extraConfig` to

       [server]
       LANDING_PATH = explore

2. apply the configuration
3. gitea starts up and redirects to /install

**Expected behavior**
I expected to be able to change arbitrary config parameters using `extraConfig`. With this bug in place, I can't…

- enable SSH
- enable LFS
- change the landing path
- change security settings

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.789.7952807791d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.gitea
```
