### ISSUE TITLE
pipenv: do not export PYTHONPATH in wrapper

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#71110]
**Describe the bug**
The `pipenv` wrapper exports `PYTHONPATH` which is passed on to virtualenv shells.

**To Reproduce**
1. `nix run nixpkgs.pipenv`
2. `pipenv install attrs`
3. `pipenv shell`
4. `env | grep PYTHONPATH`

**Expected behavior**
Our `PYTHONPATH` should not be passed through, but that of a user should (if they want to break things, let them).

**Additional context**
Generally, we should get rid of the `export PYTHONPATH` in wrappers. Either we should use `NIX_PYTHONPATH` (~although that would not solve the issue here~) or we should rely only on the magical sed expression (the `rpath` like substitution in the Python code).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `pipenv`
# a list of nixos modules affected by the problem
module:
```
