### ISSUE TITLE
GitLab backups fail

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#71124]
**Describe the bug**
When running a gitlab backup with gitlab-rake according to the documentation, it fails with the following log output:
https://termbin.com/ugqb

**To Reproduce**
1. enable the gitlab module
3. ???, causing /var/gitlab/state/config/initializers to disappear
2. sudo -u gitlab -H gitlab-rake gitlab:backup:create RAILS_ENV=production

**Expected behavior**
A backup is created in /var/gitlab/state/backup/

**Screenshots**
https://termbin.com/ugqb

**Additional context**

**Metadata**
[mil@lab:~]$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.5, NixOS, 20.03pre196725.94500c93dc2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre196725.94500c93dc2"`
 - channels(mil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- gitlab-ee
# a list of nixos modules affected by the problem
module:
- gitlab
```
