### ISSUE TITLE
scribusUnstable: PDF import fails

### ISSUE THREAD

**Issue by liamdiprose** [NixOS/nixpkgs#71154]
**Describe the bug**
Scribus allows PDF's to be imported into image frames, but running inside `nix-shell --pure` leads to no PDF appearing.

**To Reproduce**
1. `nix-shell --pure -p scribusUnstable`
2. `scribus`
3. Create a new 'Single Page'
4. Create an image frame (Next to 'T' on top toolbar, `i` on the keyboard)
5. Double click the empty Image frame
6. Select any PDF
7. Image frame remains blank

**Expected behavior**
The top left portion of the imported PDF should appear in Image frame.

**Workaround**
- Copying the PATH variable from an impure scribusUnstable shell on Ubuntu to the pure shell fixes the problem. 

**Metadata**

```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-62-generic, Ubuntu, 18.04.3 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(liam): `"nixpkgs-20.03pre196811.7818f30cc4b"`
 - nixpkgs: `/home/liam/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: scribusUnstable
# a list of nixos modules affected by the problem
module:
```
