### ISSUE TITLE
runInLinuxVM fails since username can't be detected

### ISSUE THREAD

**Issue by eadwu** [NixOS/nixpkgs#71157]
**Describe the bug**
Specifically through nixops creating `libvirtd-image`, it fails with `error: cannot figure out user name` around `chroot /mnt ${config.nix.package.out}/bin/nix-store --load-db` [2]. `whoami` outputs `whoami: cannot find name for user ID 0: No such file or directory`.

**To Reproduce**
Any nixops machine deployed through libvirtd.
1. `nixops create -d a ./.`
2. `nixops deploy -d a`

**Expected behavior**
Create a QEMU image successfully.

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.6-hardened, NixOS, 20.03.git.c6d74dc (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6895_84de821`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `$HOME/Projects/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

https://github.com/nix-community/nixops-libvirtd/issues/5

[2] https://github.com/nix-community/nixops-libvirtd/blob/master/nix/libvirtd-image.nix#L67
