### ISSUE TITLE
nginx-prometheus-exporter.service should depend on nginx.service

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#71187]
**Describe the bug**
The default configuration for services.prometheus.exporters.nginx generates a systemd service that does not depend on nginx to be up. However, the nginx prometheus exporter fails at startup if nginx is not running:

```
nginx-prometheus-exporter[21526]: 2019/10/15 11:56:04 Could not create Nginx Client: failed to get http://localhost/nginx_status: Get http://localhost/nginx_status: dial tcp [::1]:80: connect: connection refused
```

**To Reproduce**
1. systemctl restart nginx nginx-prometheus-exporter
2. Get unlucky with restart parallelism

**Expected behavior**
Proper dependencies are required.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nixos/modules/services/monitoring/prometheus/exporters.nix
```
