### ISSUE TITLE
rrsync doesn't hardcode perl's path

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#71198]
**Describe the bug**

The rrsync script recently stopped having a full path to perl in its shebang. This happend to me on my server since the 19.09 upgrade.

The weird thing is that the rrsync package doesn't seem to have changed much since NixOS 19.03. Maybe it comes from a change in `mkDerivation`?

**To Reproduce**

From the unstable or 19.09 channel.

```sh
nix build nixpkgs.rrsync
head -1 ./result/bin/rrsync
```

**Expected behavior**

The script should have a full path to perl, because `/usr/bin/perl` doesn't exist ^^

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.09.794.28d2548a03f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.794.28d2548a03f, home-manager, nixpkgs-unstable-20.03pre196752.a8b2e302c66"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - rrsync
# a list of nixos modules affected by the problem
module:
```
