### ISSUE TITLE
mergerfs crashes when deleting a file on nixos 19.09

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#71272]
**Describe the bug**
mergerfs crashes when deleting a file

**To Reproduce**
1. Install mergerfs
2. Create a mergerfs file system, e.g. by
```
mkdir -p /mnt/dir1 /mnt/dir2 /mnt/merged
mergerfs /mnt/dir1:/mnt/dir2 /mnt/merged
```
3. Create and remove a file in the mergerfs, e.g.
```
cd /mnt/merged
touch foo
rm foo
```
4. `rm: cannot remove 'foo': Software caused connection abort` should be displayed, mergerfs process stops. fs is now unreachable, trying to access in now gives `Transport endpoint is not connected`.

**Expected behavior**
mergerfs should not crash, file should be deleted

**Additional context**
Observed on two systems running on 19.09, worked correctly on 19.03. Current workaround is to downgrade mergerfs to v2.25.1 (used in 19.03). All versions mergerfs newer than this appear to have this issue.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79-hardened, NixOS, 19.09.852.0f9b2d9c860 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.852.0f9b2d9c860"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mergerfs
# a list of nixos modules affected by the problem
module:
```
