### ISSUE TITLE
Redis module fails to disable Transparent Huge Pages (THP) in container

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#71414]
**Describe the bug**
Since 19.09 redis ships a unit called `disable-transparent-huge-pages.service` this oneshot unit fails on every start of a container with redis, because containers have a read-only sysfs.

**To Reproduce**
1. Enable `redis` in nixos-container
2. start container

See something like
`Oct 20 03:14:11 chor-cloud wivy2sp6fn5bwj8q7b92w2d6wbhx606l-unit-script-disable-transparent-huge-pages-start[660]: /nix/store/wivy2sp6fn5bwj8q7b92w2d6wbhx606l-unit-script-disable-transparent-huge-pages-start: line 2: /sys/kernel/mm/transparent_hugepage/enabled: Read-only file system`
in the journal of the container.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module: services.redis.enable
```
