### ISSUE TITLE
MATE is partially broken

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#71427]
**Describe the bug**
Using services.xserver.desktopManager.session for some reason breaks the normal launch of caja, using services.xserver.displayManager.extraSessionFilePackages and environment.extraInit solves the problem, but that’s not all.
This condition https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/mate.nix#L58 prevents from adding all packages with gsettings schemas to XDG_DATA_DIRS, as a result it is impossible to change a lot of settings.
Turning the block into ${concatMapStrings (p: addToXDGDirs p) config.environment.systemPackages} solves the problem... almost: settings appear in the dconf-editor, but, for example, in the appearance settings it is still impossible to change the font size on the desktop, and in the settings of the workspace widget - to change the number of workspaces.

**To Reproduce**
1. services.xserver.enable = true;
2. services.xserver.displayManager.sddm.enable = true;
3. services.xserver.desktopManager.mate.enable = true;

**Expected behavior**
Fully working MATE with desktop icons

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 20.03pre196836.1c40ee6fc44 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre196836.1c40ee6fc44"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.mate
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.mate
```
