### ISSUE TITLE
python package box2d is not working for python 3

### ISSUE THREAD

**Issue by StillerHarpo** [NixOS/nixpkgs#71435]
**Describe the bug**
When i try to install box2d i got the following error

`error: Box2D-2.3.2 not supported for interpreter python3.7`

**To Reproduce**
1. run `nix-shell -p python3Packages.box2d`

**Expected behavior**
box2d is installed

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.03.173592.e758436f986 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173592.e758436f986, nixos-unstable-19.09pre183832.20b993ef2c9"`
 - channels(florian): `"home-manager, nixos-19.03.173489.af5481e9b77, nixos-unstable-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3.box2d
# a list of nixos modules affected by the problem
module:
```
