### ISSUE TITLE
On NixOS 19.09, users cannot log into gnome wayland session via GDM if user shell is zsh

### ISSUE THREAD

**Issue by kyren** [NixOS/nixpkgs#71688]
**Describe the bug**
Enable GDM and gnome, and set `users.users.<user>.shell` to `pkgs.zsh` and on a *fresh boot* with this configuration, try to log in with the "Gnome" session, not the "Gnome on Xorg" session.

Something goes wrong and the session ends and the user is kicked back to the GDM login screen.

The one thing that sticks out to me that occurs when using zsh but not bash is this error: `.gnome-shell-wr[2466]: Could not find cursor. Perhaps set XCURSOR_PATH?`.  Other than that, there are a lot of logs and a lot of errors and I'm not entirely sure which ones are harmless and which ones aren't.

**To Reproduce**
1. Enable the gnome desktop, GDM, and a fresh user, and set that user's `users.users.<user>.shell` to `pkgs.zsh`.
2. Do a fresh boot and try to log in.  GDM or the user's session or something seems to maintain a lot of state if there is not a fresh boot (I'm not totally sure what it is), and it will either succeed due to having succeeded once on the same boot, or fail because it has previously failed on the same boot.  I am very unsure what's happening here but the only reliable way I know of to test it is to reboot :/

**Expected behavior**
A successful login

**Screenshots**

**Additional context**

**Metadata**
nixpkgs version is 80b42e630b23052

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.gnome3.gdm
# a list of nixos modules affected by the problem
module: services.xserver.displayManager.gdm
```
