### ISSUE TITLE
pkgs.i686Linux.openssl_1_0_2 does not build

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#71786]
**Describe the bug**
The Linux i686 version of openssl does not build on the `staging-next` branch.

**To Reproduce**
1. `nix-build -A pkgsi686Linux.openssl_1_0_2`

Caused by 703e44675c5e62b0dbbd37b76153383fc0b5ee47, https://github.com/NixOS/nixpkgs/pull/71457 cc @dingxiangfei2009 

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:  `pkgsi686Linux.openssl_1_0_2`
# a list of nixos modules affected by the problem
module:
```
