### ISSUE TITLE
wrong merging  of kernel "optional" setting

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#71803]
**Describe the bug**

The `optional` character of a kernel configuration is set to true upon merging instead of false.

The fix is to update kernel_config.nix to:
```
  mergeFalseByDefault = locs: defs:
    if defs == [] then abort "This case should never happen."
    else if any (x: x.value == false) defs then false
    else true;
```
I need to update/check the tests too

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
