### ISSUE TITLE
Samsung M2070 still not working

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#71815]
**Describe the bug**
@tohl 
Even with the following in `configuration.nix`:
```
{config,pkgs,...}:{
  imports=[
    <nixpkgs/pkgs/misc/cups/drivers/samsung/1.00.36/module.nix>
  ];
  services.printing.enable=true;
  hardware.sane.enable=true;
  services.samsung-unified-linux-driver_1_00_36.enable=true;
}
```
scanning still doesn't work and `scanimage -L` still doesn't give me any scanner

**To Reproduce**
1. Add the above to `configuration.nix`
2. `nixos-rebuild switch`
3. `scanimage -L`

**Expected behavior**
`scanimage -L` recognize the Samsung M2070 as scanner 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.20, NixOS, 20.03pre197685.f35f0880f2c (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20190922_382aa05`
 - channels(root): `"nixos-20.03pre197685.f35f0880f2c"`
 - channels(paki): `"nixos-20.03pre196201.07d4df59626"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.samsung-unified-linux-driver_1_00_36
```
