### ISSUE TITLE
nix run nixpkgs.nix-info -c nix-info -m: Assertion `size_ < capacity_' failed

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#72034]
**Describe the bug**

`nix run nixpkgs.nix-info -c nix-info -m` crashes.

**To Reproduce**
1. run `nix run nixpkgs.nix-info -c nix-info -m`

**Expected behavior**
no crash

**Screenshots**
![image](https://user-images.githubusercontent.com/24027/67623138-06cfbc80-f7f0-11e9-84d6-864e02ad6c18.png)

**Additional context**
running `nix-info -m` directly is fine.

#71770 had the same error msg

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 20.03pre197685.f35f0880f2c (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(bbigras): `"home-manager, unstable-20.03pre197685.f35f0880f2c"`
 - channels(root): `"nixos-20.03pre197685.f35f0880f2c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
