### ISSUE TITLE
stress-ng: fails to build on missing strlcat

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#72292]
**Describe the bug**
stress-ng fails to build with
`stress-str.c:605:33: error: 'strlcat' undeclared here (not in a function);`. This looks like a missing libbsd include, but I don't know why it would miss it. Removing the libbsd dependency allows it to build without the strlcat stress test.

**To Reproduce**
1. `nix-build '<nixpkgs>' -A stress-ng`

**Expected behavior**
Package builds

**Metadata**
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: stress-ng
# a list of nixos modules affected by the problem
module:
```
