### ISSUE TITLE
munin-node hardcoded host *

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#72308]
**Describe the bug**

it should be possible to change the listening address

now it is hardcoded to host * which means:

$ sudo netstat -ntlpu | grep perl
tcp6       0      0 :::4949                 :::*                    LISTEN      1027/perl

**To Reproduce**

services.munin-node.enable = true;

**Expected behavior**

i would like for example host 127.0.0.1

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.03.173624.b6cfdceb7f9 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09.840.8bf142e001b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  munin-node
```
