### ISSUE TITLE
best64.rule missing in pkgs.john

### ISSUE THREAD

**Issue by fabianbuettner** [NixOS/nixpkgs#72327]
**Describe the bug**
johntheripper can not be started because of missing file "best64.rule"

**To Reproduce**
1. Install pkgs.john
2. Start john

**Expected behavior**
The program should start without error messages.

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.7, NixOS, 20.03pre198214.4cd2cb43fb3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(fab): `"home-manager-19.09, nixos-20.03pre198214.4cd2cb43fb3"`
 - channels(root): `"nixos-20.03pre198214.4cd2cb43fb3, home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
