### ISSUE TITLE
nix is not in binary cache for aarch64

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nixpkgs#72717]
**Describe the bug**

When building `nix` on aarch64, it should be fetched from binary cache. Instead I need to rebuild it, which is really time consuming because of recompiling `nlohmann_json`.

**To Reproduce**
1. Run `nix-build test.nix` with `test.nix`:
```nix
with import <nixpkgs> { };

stdenv.mkDerivation {
  name = "test";

  buildInputs = [
    nix
  ];
}
```
2. I see the following output which shows that the packages are going to be rebuilt.
```
these derivations will be built:
  /nix/store/cnfnd4dm74i4cydcsqchs0plc74b56hf-nlohmann_json-3.6.1.drv
  /nix/store/qdhngkjj1lb9589dwa9psvfbqzyy3dfx-nix-2.3.drv
  /nix/store/pzz87q87cwwc357wm1ikf9q5jihjabjy-test.drv
building '/nix/store/cnfnd4dm74i4cydcsqchs0plc74b56hf-nlohmann_json-3.6.1.drv'...
unpacking sources
unpacking source archive /nix/store/5xagvh9xb69njglwpdbzq814l4dv6xgi-source
```

**Expected behavior**

`nix` and all its dependencies should always be fetchable via the official binary cache.

**Additional context**

`nlohmann_json` is failing sometimes in hydra, which might cause the issue, see https://hydra.nixos.org/job/nixos/release-19.09-aarch64/nixpkgs.nlohmann_json.aarch64-linux. But as `nix` depends on it, we should provide more stability in its build.

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.3.7, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"home-manager, nixos-19.09.1046.a1b46bd1252, nur-gerschtli, unstable-20.03pre199897.471869c9185"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nix
  - nlohmann_json
  # probably all versions of the nix derivation
# a list of nixos modules affected by the problem
module:
```
