### ISSUE TITLE
Non of the grafana provisioning nixos options get type-checked

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#72732]
**Describe the bug**
It seems type-checking isn't working for the
```
grafana.provisioning.dashboards
grafana.provisoning.datasources
``` 
modules

**To Reproduce**

```
      grafana.provision.datasources = [
        {
          # name = "hello"; # name is mandatory but I can leave it out
          editable = "hello i should be a boolean but i made it a string";
          type = "prometheus";
          url = "http://127.0.0.1:9090"; # TODO make configurable
        }
      ];
```

**Expected behavior**
I expected it to complain that `name` is required but not set,
and give a type error that `editable` is not a boolean

**Additional context**
I have a feeling this line causes this behaviour:
https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/modules/services/monitoring/grafana.nix#L336

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
