### ISSUE TITLE
Hydra fails at runtime due to buildPerlPackage changes

### ISSUE THREAD

**Issue by lopsided98** [NixOS/nixpkgs#72783]
**Describe the bug**

Hydra fails at runtime due to missing transitive dependencies. This occurs because https://github.com/NixOS/nixpkgs/commit/9e60fefc349c9aa52927546e575889615b0f5ed5 removed `nix-support/propagated-user-env-packages` from all Perl packages. Hydra uses `buildEnv` to create an environment with all its Perl packages, and `propagated-user-env-packages` used to cause all the transitive dependencies to be pulled into the environment, but this no longer happens.

As suggested by @conferno, I tried replacing `buildEnv` with `perl.withPackages`, but this does not work because the Perl wrapper clobbers `PERL5LIB`, which [prevents Hydra from adding its own Perl files to `PERL5LIB`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/hydra/default.nix#L122).

**To Reproduce**
```
nix-build nixos/tests/hydra
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - hydra
# a list of nixos modules affected by the problem
module:
  - hydra
```

cc @volth @Ma27
