### ISSUE TITLE
nlohmann_json build timed out and blocking stable channel

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#72890]
**Describe the bug**

The stable channel was last updated 5 days before.
The blocking issue seems to be the build of nlohmann_json timing out.
https://hydra.nixos.org/build/105868032

**To Reproduce**
1. go to local nixpkgs repo: `cd code/nixpkgs/`
2. get latest changes: `git fetch upstream`
3. checkout stable channel: `git checkout release-19.09`
4. build: `nix-build . -A nlohmann_json`

That works, so there is no actual issue with the build.

The problem is that a test times out on the CI:
```
The following tests FAILED:
         80 - test-unicode_all (Timeout)
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
