### ISSUE TITLE
micro: can't copy text

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#72905]
**Describe the bug**
I can select text in the micro editor, but i can't copy it.

**To Reproduce**
1. open some textfile with micro
2. select text
3. press CTRL + C
4. press CTRL + V

**Expected behavior**
The selected text should have been copyed and pasted like with any GUI text editor.

**Additional context**
the program supports it https://github.com/zyedidia/micro#features

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.1019.c5aabb0d603 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1019.c5aabb0d603, nixos-hardware, nixos-unstable-20.03pre200231.7827d3f4497"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Using inside pantheon terminal.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: micro
# a list of nixos modules affected by the problem
module:
```
