### ISSUE TITLE
Screens went dark for a second

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#72989]
**Describe the bug**
Shortly after i logged in, 2 of my 3 screens went dark for a second. It happens 2-3 times, then never again. But after every boot.

These entries appear in the syslog when it happens:

```
Nov 07 16:17:49 ethmoid kernel: [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe C FIFO underrun
Nov 07 16:18:59 ethmoid kernel: [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe B FIFO underrun
```

**To Reproduce**
1. 
2. ...
3. ...

**Expected behavior**
constant picture on screens

**Additional context**

I'm using Pantheon desktop with X11 on a Thinkpad L470 with integrated Intel GPU in a docking station.

I noticed it only on this system, so might be hardware/driver related.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.81, NixOS, 19.09.1019.c5aabb0d603 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1019.c5aabb0d603, nixos-hardware, nixos-unstable-20.03pre200231.7827d3f4497"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Host: 20J4000XGE ThinkPad L470
CPU: Intel i7-7500U (4) @ 3.500GHz 
GPU: Intel HD Graphics 620 
GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520 
Memory: 5567MiB / 32054MiB

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.pantheon
```

cc @worldofpeace
