### ISSUE TITLE
Impossible to override libxml2 and libxslt with pythonSupport = false

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#73102]
**Describe the bug**
It appears that there is no simple way to override libxml2 and libxslt with pythonSupport = false

**To Reproduce**
```nix
with import <nixpkgs> {
  overlays = [
    (self: super: {
      libxslt = super.libxslt.override { pythonSupport = false; };
      libxml2 = super.libxml2.override { pythonSupport = false; };
    })
  ];
};

libxslt
```

```
# nix-instantiate test.nix --show-trace
error: while evaluating the attribute 'libxslt.override' at nixpkgs/pkgs/top-level/all-packages.nix:12864:3:
while evaluating 'callPackageWith' at nixpkgs/lib/customisation.nix:117:35, called from /home/veprbl/nixpkgs/pkgs/top-level/all-packages.nix:12864:13:
while evaluating 'makeOverridable' at nixpkgs/lib/customisation.nix:67:24, called from /home/veprbl/nixpkgs/lib/customisation.nix:121:8:
while evaluating anonymous function at nixpkgs/pkgs/development/libraries/libxslt/default.nix:1:1, called from /home/veprbl/nixpkgs/lib/customisation.nix:69:16:
assertion failed at nixpkgs/pkgs/development/libraries/libxslt/default.nix:7:1
```

**Expected behavior**
Straightforward override should work

**Metadata**
 - version: `nix-env (Nix) 2.3`
 - channels(veprbl): `"nixpkgs-20.03pre194957.bef773ed53f"`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - libxml2
  - libxslt
# a list of nixos modules affected by the problem
module:
```
