### ISSUE TITLE
travis: console command needs 'pry'

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#73238]
**Describe the bug**

The `travis console` command doesn't work, as the 'pry' dependency is missing.

I don't know how to add a dependency to a ruby package. If someone can point me in the right direction, I would be happy to work on a PR.

**To Reproduce**
```
> nix run nixpkgs.travis -c travis console
You need to install pry to use Travis CLI console. Try

$ (sudo) gem install pry
````

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.8, NixOS, 19.09.1019.c5aabb0d603 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"home-manager, nixos-unstable-20.03pre198214.4cd2cb43fb3, nixpkgs-19.09.976.c75de8bc12c"`
 - channels(addy): `"home-manager, nixos-unstable-20.03pre200231.7827d3f4497, nixpkgs-19.09.1019.c5aabb0d603"`
 - nixpkgs: `/home/addy/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: travis
# a list of nixos modules affected by the problem
module:
```
