### ISSUE TITLE
Chromium hangs in Vmware Guest

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#73294]
**Describe the bug**
Very often every 2-5 minutes chrome hangs inside the vmware box. This issue does not happen without open-vm-tools. Maybe just open-vm-tools is outdated? 🤔 

**To Reproduce**
1. Create a VM in VMware Workstation
2. Install nixos with chrome and open chrome and surf
3. After short time it hangs. (Happends on everything that depends on chromium)

**Expected behavior**
Not haning

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.8, NixOS, 20.03pre200231.7827d3f4497 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre200231.7827d3f4497"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: open-vm-tools
```
