### ISSUE TITLE
SteamPlay Compatibility Tools: Proton-GE, Boxtron, Roberta, Luxtorpeda

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#73323]
**Project description**
As many of you already know, Steam has a built in compatibility tool for playing Windows games on Linux called Proton. In addition there's several other compatibility tools that have been made by the community.

Recently Steam has officially added the ability for distributions to package their own compatibility tools: https://github.com/ValveSoftware/steam-for-linux/issues/6310

I propose packaging the following known projects:
* Proton-GE: https://github.com/GloriousEggroll/proton-ge-custom
* Boxtron: https://github.com/dreamer/boxtron
* Roberta: https://github.com/dreamer/roberta
* Luxtorpeda: https://github.com/dreamer/luxtorpeda

Some of the projects listed above have NixOS specific issues, for example: https://github.com/dreamer/roberta/issues/6

**Comment by yusdacra** [comment]
Still important to me

**Comment by MetaDark** [comment]
I think steam hard-codes the global compatibility tool search paths to `/usr/share` & `/usr/local/share`, but also allows configuration with `STEAM_EXTRA_COMPAT_TOOLS_PATHS`:  https://github.com/ValveSoftware/steam-for-linux/issues/6310#issuecomment-511630263.

If steam doesn't follow the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (which seems very likely), then we will have to emulate it through a wrapper that defines `STEAM_EXTRA_COMPAT_TOOLS_PATHS`. Without this, steam won't pick up Nix-built compatibility tools.

**Comment by TheOddler** [comment]
No stale bot, I'd like to keep this fresh a bit longer. Still important to me.

**Comment by alanjjenkins** [comment]
This is also something I am interested in. I would have a go at creating this myself but I do not yet have a proper grasp on how to make my own derivations.

**Comment by benneti** [comment]
Assuming you use nvfetcher and home-manager it is reasonably straight forward to have a semi automatic process:
nvfetcher sources.toml
``` toml
[luxtorpeda]
src.github = "luxtorpeda-dev/luxtorpeda"
src.from_pattern = "v(\\d*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/luxtorpeda-dev/luxtorpeda/releases/download/v$ver/luxtorpeda-$ver.tar.xz"

[proton-ge]
src.github = "GloriousEggroll/proton-ge-custom"
fetch.url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/$ver/Proton-$ver.tar.gz"
```
then you can have simple derivations for those releases
``` nix
{ lib, stdenv, sources }:
stdenv.mkDerivation rec {
  inherit (sources.luxtorpeda) pname src version;

  nativeBuildInputs = [ ];

  installPhase = ''
    mkdir -p $out
    mv * $out/
  '';
}
```
and the same for proton-ge
and to automatically put them in the correct folder you can use
```
  # proton is very large and slows down the boot when linking, therefore only copy the files when necessary
  home.activation = lib.mkIf global-config.programs.steam.enable
    {
      proton-ge = (lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        target="${xdgData}/Steam/compatibilitytools.d/Proton-${pkgs.proton-ge.version}"
        if ! [ -d "$target" ]; then
          cp -R ${pkgs.proton-ge} "$target"
          chmod -R u+w "$target" # not strictly necessary...
        fi
      '');
    };

  # luxtorpeda has another kind of versioning and is much smaller we can safely link it
  xdg.dataFile = lib.mkIf global-config.programs.steam.enable {
    luxtorpeda = {
      recursive = true;
      source = "${pkgs.luxtorpeda}";
      target = "Steam/compatibilitytools.d/luxtorpeda";
    };
  };
```
in you home-manager configuration.
In total this puts the prebuilt releases in the correct place for steam to detect and thanks to the steam-run environment they simply work.
For nixpkgs I think this solution is not suitable at all but for a selfrolled config it fits the bill.
