### ISSUE TITLE
flatpak-builder rofiles-fuse not available, doing without

### ISSUE THREAD

**Issue by piotr-szegda** [NixOS/nixpkgs#73325]
**Describe the bug**
flatpak-builder for some reasons can't use rofiles-fuse

**To Reproduce**
1. Try build any app using flatpak-builder

**Expected behavior**
flatpak-builder should use rofiles-fuse.

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.10, NixOS, 19.09.1208.ef8c34c4721 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1208.ef8c34c4721"`
 - channels(piotrek): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
