### ISSUE TITLE
kwallet complain about pinetry not installed when trying to open it

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#73332]
**Describe the bug**
When trying to open kwallet instead a dialouge pop up that complain about pinetry not installed
Of note that I have `programs.gnupg.agent.enable=true`

**Expected behavior**
kwallet open up as normal and give me the password

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.21, NixOS, 20.03pre200231.7827d3f4497 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20191022_9cac895`
 - channels(root): `"nur, nixos-20.03pre200231.7827d3f4497, home-manager"`
 - channels(paki): `"nixos-20.03pre196201.07d4df59626"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  -programs.gnupg.agent
  -services.xserver.plasma5
```
