### ISSUE TITLE
mpv: Killed by SIGABRT because of missing libsndio.7.0.dylib

### ISSUE THREAD

**Issue by toonn** [NixOS/nixpkgs#73367]
**Describe the bug**
`mpv` crashes with a `SIGABRT`:

```
dyld: Library not loaded: libsndio.7.0.dylib
  Referenced from: /nix/store/ci6zs90d2mpdd3pczlani1kmyw4ai5kn-mpv-0.30.0/bin/.mpv-wrapped
  Reason: image not found
```

This happens regardless of what file I try to play, even a bare `mpv` invocation without arguments.

**To Reproduce**
1. Install `mpv` from `nixpkgs-unstable` on macOS
2. Run (or attempt to) `mpv` with or without arguments.

**Expected behavior**
I expected all dependencies, including this `libsndio` to be installed in the nix store.

**Additional context**
Running on macOS, using nix-darwin and home-manager.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Will do when I get access to the machine again.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mpv
# a list of nixos modules affected by the problem
module:
```
