### ISSUE TITLE
USB sound card is not detected after updating 19.09 channel

### ISSUE THREAD

**Issue by wedens** [NixOS/nixpkgs#73531]
**Describe the bug**
I tried upgrading from 19.09.1172.2d896998dc9 to more recent 19.09.1254.9104be2ee08, but after the upgrade my usb sound card (EMU 0404) is not being detected as sound device. 

It shows in `dmesg` and `lsusb` as USB device, but not as a sound device in `/dev/snd/`, `/sys/class/sound`, `aplay -l`, `pactl list sinks`.

Plugging it in to other USB port doesn't help.

I downgraded the kernel to LTS (4.19) to check if upgrade from 5.3.9 to 5.3.11 caused the problem, and the problem is still there with LTS kernel.

I've checked `dmesg`/`journalctl -b` and there are no obvious errors.

Rolling back to 19.09.1172.2d896998dc9 makes the sound card work again.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.11, NixOS, 19.09.1254.9104be2ee08 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1019.c5aabb0d603"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
