### ISSUE TITLE
skypeforlinux: prevent constant breakage using web.archive.org

### ISSUE THREAD

**Issue by jamescostian** [NixOS/nixpkgs#73597]
**Describe the bug**

One cannot install skypeforlinux on nixos at this time

**To Reproduce**

1. Install skypeforlinux

**Expected behavior**

It should install properly - at the very least, it should not download from a dead (404) URL

**Additional context**

Similar to #31047

But, I have a suggestion to put an end to this cat-and-mouse game: Instead of downloading directly from skype, download from the web archive, e.g. http://web.archive.org/web/20191118025647/https:/repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.51.0.92_amd64.deb

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.82, NixOS, 19.09.1258.07e66484e67 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1258.07e66484e67"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
