### ISSUE TITLE
bitlbee does not build

### ISSUE THREAD

**Issue by terlar** [NixOS/nixpkgs#73747]
**Describe the bug**
Bitlbee does not build on master.

**To Reproduce**
1. `nix-build --no-build-output -A bitlbee`

```
these derivations will be built:
  /nix/store/2a69lfr8r6zh6d20nwvqyxcd6p9yii05-bitlbee-3.6.drv
building '/nix/store/2a69lfr8r6zh6d20nwvqyxcd6p9yii05-bitlbee-3.6.drv'...
builder for '/nix/store/2a69lfr8r6zh6d20nwvqyxcd6p9yii05-bitlbee-3.6.drv' failed with exit code 2; last 10 log lines:
              ^~~~~~~~~~~~~~~~~
  check_util.c:27:12: warning: 'test_strip_newlines' defined but not used [-Wunused-variable]
   START_TEST(test_strip_newlines)
              ^~~~~~~~~~~~~~~~~~~
  check_util.c:11:12: warning: 'test_strip_linefeed' defined but not used [-Wunused-variable]
   START_TEST(test_strip_linefeed){
              ^~~~~~~~~~~~~~~~~~~
  make[1]: *** [Makefile:27: check_util.o] Error 1
  make[1]: Leaving directory '/build/bitlbee-3.6/tests'
  make: *** [Makefile:65: check] Error 2
error: build of '/nix/store/2a69lfr8r6zh6d20nwvqyxcd6p9yii05-bitlbee-3.6.drv' failed
```

**Expected behavior**
The bitlbee derivation should build without errors.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.11, NixOS, 20.03.git.6be20178f08 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - nixpkgs: 25fc378642e

Maintainer information:
```yaml
attribute:
- bitlbee
- bitlbee-steam
- bitlbee-mastodon
- bitlbee-facebook
- bitlbee-discord
# a list of nixos modules affected by the problem
module:
- services/networking/bitlbee
```

@pSub
