### ISSUE TITLE
git fails to build on darwin

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#73806]
**Describe the bug**
git fails to build on darwin

https://hydra.nixos.org/build/106951796

**Metadata**
nixpkgs at ec9cf578e56ff7c3045878f86506338b0112777d

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
