### ISSUE TITLE
Composer needs more ram

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#73816]
**Describe the bug**
Composer needs more ram. With projects with 180 packages it out of ram

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///nix/store/6my0l3i8q6bddp7fky4cpv8wrdkxv6fd-php-composer-1.9.0/libexec/composer/composer.phar/src/Composer/Repository/ComposerRepository.php on line 340

**To Reproduce**
Have a project with much dependencies

**Expected behavior**
It works

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.11, NixOS, 20.03pre201791.c1966522d7d (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre201791.c1966522d7d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: composer
```
