### ISSUE TITLE
rainloop-standard: wrong licence and package name

### ISSUE THREAD

**Issue by c0bw3b** [NixOS/nixpkgs#73956]
**Describe the bug**

Both `rainloop-community` and `rainloop-standard` are listed as being licensed under AGPLv3 but only the community edition actually is :
* https://www.rainloop.net/licensing/
* https://www.rainloop.net/purchase/

Moreover, the _package name_ for the standard variant is invalid as it contain two dashes between name and version. Some tools ([for example Repology](https://repology.org/log/1648667)) can't parse it properly.

**To Reproduce**
Consult https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=rainloop-standard

**Expected behavior**
`rainloop-standard` license should be unfree and its package name should not contain two consecutive dashes between name and version.

**Screenshots**
N/A

**Additional context**
N/A

**Metadata**
N/A

**Maintainer information:**
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: rainloop-standard
# a list of nixos modules affected by the problem
module:
```

Friendly ping to @dasJ as maintainer.
