### ISSUE TITLE
Arduino: binaries installed through Boards Manager fail to run

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#73965]
**Describe the bug**
Binaries installed through the Boards Manager in Arduino IDE
fail to run due to missing shared libraries.

A solution to this is to `patchelf` them manually after installation.

**To Reproduce**
1. Tools > Boards > Boards Manager
2. install Arduino SAM Boards
3. Verify/Compile

**Expected behavior**
Code is compiled using the installed binaries

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.03.173660.3f92c2124a5 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03.173660.3f92c2124a5, nixos-unstable-20.03pre201791.c1966522d7d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
