### ISSUE TITLE
joplin-desktop: can't start from gnome menu

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#73981]
**Describe the bug**
I can't start joplin-desktop from the Gnome menu but I can start it from the command line.

**To Reproduce**
1. try to run it from the menu
2. nothing happens

**Expected behavior**

**Screenshots**

**Additional context**
installed with home-manager.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 20.03pre202088.e89b21504f3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(bbigras): `"home-manager, unstable-20.03pre202088.e89b21504f3"`
 - channels(root): `"nixos-20.03pre202088.e89b21504f3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

cc @rafaelgg @raquelgb
