### ISSUE TITLE
The undervolt module needs warnings

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixpkgs#74029]
**Describe the bug**
The undervolt module is potentially damaging to hardware when misconfigured.
The module description needs an appropriate warning informing users that they are taking a risk when enabling it (even though I think it's fairly obvious that's the case).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: undervolt
# a list of nixos modules affected by the problem
module: services.undervolt
```

cc @Vodurden
