### ISSUE TITLE
nix-shell with coq+compcert will not start

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#74083]
**Describe the bug**
Shell with `coq` and `compcert` will fail to start with a following message:
```
bash: COQPATH: unbound variable
```
This is an issue because `compcert` depends on `coq` so they would be always included to the shell started by nix-review. I noticed this issue while reviewing #73958.

I suspect this is caused by #72347.

**To Reproduce**
```
NIXPKGS_ALLOW_UNFREE=1 nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/814f9104d721dcbf267720d8964095626b45321b.tar.gz -p compcert -p coq
```
This does not reproduce on release-19.09

**Expected behavior**
Shell will start, shell prompt will appear.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

cc @Ericson2314  @thoughtpolice @jwiegley @vbgl
