### ISSUE TITLE
qtpass can't use qrencode

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#74220]
**Describe the bug**
Clicking the QR code icon on a password entry does nothing.

**To Reproduce**
1. Enable the **Use qrencode** option in preferences
2. Click the QR code icon on a password entry

**Expected behavior**
A QR code is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/166791/69589050-e68a4d80-0fa7-11ea-9708-13be0a40a127.png)
The QR code icon is the righthand one. Clicking it doesn't display anything.

**Additional context**
`qtpass` [hardcodes](https://github.com/IJHack/QtPass/blob/d242041c3efdba43b037ef3f8fb9f526a46173a9/src/qtpass.cpp#L412) the location of the `qrencode` executable.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 19.09.1326.382f0951a9f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1326.382f0951a9f"`
 - channels(user): `"nixpkgs-20.03pre199833.6b463388478"`
 - nixpkgs: `$HOME/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
