### ISSUE TITLE
Anydesk package fails to install: Source 404

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#74248]
**Describe the bug**
Anydesk package fails to install

https://download.anydesk.com/linux/anydesk-4.0.1-amd64.tar.gz is missing (404)

**To Reproduce**
1. nix-env -iA anydesk

**Expected behavior**
It installs.

**Screenshots**
Log: https://paste.mkg20001.io/emuvozijon.sql

**Additional context**
Likely just outdated version, using the latest version tarball should fix it.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-23-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-19.09.1300.08e503bac6d"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

NOTE: also tested on master in VM, same result

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.anydesk
# a list of nixos modules affected by the problem
module:
```
