### ISSUE TITLE
Slic3r does not build

### ISSUE THREAD

**Issue by marcus7070** [NixOS/nixpkgs#74250]
**Describe the bug**
On master (ba85932bae15a6e44bfe30c9cb9d5368f55d1574) Slic3r fails during build with 
```
src/libslic3r/GCodeSender.hpp:17:48: error: expected class-name before ‘{’ token
17 | class GCodeSender : private boost::noncopyable {
   |                                                ^
```

**Additional context**
The problem is due to a bump in Boost version, and a file now needs the noncopyable header included. 

I've applied this patch on my NixOS machine and it fixes the problem: https://bugs.gentoo.org/689804

The slic3r devs fixed in https://github.com/slic3r/Slic3r/commit/90f108ae8e7a4315f82e317f2141733418d86a68, but unfortunately there are no new releases since that to use in nixpkgs.

I'm unsure how to fix. Patch in nixpkgs, even though the problem not due to nix? Or use a non-release version of Slic3r?

Maintainer information: @bjornfor @the-kenny 
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: slic3r
# a list of nixos modules affected by the problem
module:
```

@grahamcofborg build slic3r
