### ISSUE TITLE
Neovim Segmentation Fault

### ISSUE THREAD

**Issue by iclanzan** [NixOS/nixpkgs#74286]
**Describe the bug**
Neovim crashes when resizing windows under some circumstances.

**To Reproduce**
There are many different ways to repro, these are some reliable steps to reproduce the behavior:
1. `nvim -u NORC`
2. Press `<C-W> S` to create a split
3. `:te` to open a terminal
4. `<C-W> J` to go to other window
5. `<C-W> _` to maximize window

**Expected behavior**
Windows should resize and there should be no crash.

**Additional context**
Originally filed at https://github.com/neovim/neovim/issues/11458 but it seems to only be affecting NixOS. The crashes only started since I upgraded from NixOS _19.03_ to _19.09_.

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.3.9, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: neovim
# a list of nixos modules affected by the problem
module: applications/editors/neovim/default.nix
```

cc @rvolosatovs @manveru
