### ISSUE TITLE
Initrd vs predictable interface names

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#74328]
**Describe the bug**
Initrd networking does not use predictable interface names, but does enable DHCP on the interfaces that are specified by the normal (networking.) configuration. 

**To Reproduce**
1. Enable boot.initrd.network
2. Enable predictable interface names (default)
3. Enable useDHCP on one interface
4. Boot to initrd

**Expected behavior**
DHCP should be used on all interfaces that have DHCP enabled.

**Screenshots**
![photo_2019-11-27_13-30-49](https://user-images.githubusercontent.com/3250809/69723553-22ddbb00-111a-11ea-9eec-f3a66f16d3a4.jpg)

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
I can't because I can not unlock the root drive without networking ;)
But here's the info from another computer running the same channel and kernel:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0, NixOS, 20.03.20191125.89b2c0b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20191022_9cac895`
 - channels(root): `"nixos-20.03pre202991.57cf4eb83bc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- boot.initrd.network
```

CC @edolstra
