### ISSUE TITLE
networkmanager does not set pkgconfig path

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#74349]
**Describe the bug**
The networkmanager does not expose it's header files via the PKG_CONFIG_PATH

**To Reproduce**
1. Run `nix-shell -p networkmanager --run 'echo $PKG_CONFIG_PATH'`

**Expected behavior**
It should print something including a path from networkmanager, instead it just prints nothing

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-23-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-19.09.1320.4ad6f1404a8"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: networkmanager
# a list of nixos modules affected by the problem
module:
```
