### ISSUE TITLE
tt-rss should be less verbose by default

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#74427]
**Describe the bug**

tt-rss produces an unreasonable amount of logs by default, on the order of 200 lines of info and lower priority, when refreshing 75 feeds.

**To Reproduce**
1. Enable the tt-rss service

**Expected behavior**
Like most services, only warnings and higher priorities should go into the logs by default.

**Additional context**

It seems tt-rss does not have options to configure this, and based on [this discussion](https://community.tt-rss.org/t/systemd-daemon-is-too-verbose-in-syslog/757) it seems unlikely that there is willingness to change that. But one [solution](https://community.tt-rss.org/t/systemd-daemon-is-too-verbose-in-syslog/757/4) would be to set the following in the service file:

```
StandardOutput=null
StandardError=syslog
```

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 19.09.1434.ca9f709fd0b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(username): `""`
 - channels(root): `"nixos-19.09.1434.ca9f709fd0b, nixos-unstable-20.03pre200231.7827d3f4497"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: services.tt-rss
# a list of nixos modules affected by the problem
module:
```
