### ISSUE TITLE
btrfs raid rootfs timing problem leads to mount fail

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#74468]
**Describe the bug**
I see "btrfs device scan" in my stage 1 script. When I boot, it fails to mount the rootfs. When I drop into the initrd shell, run btrfs device scan and repeat the exact mount command that failed, it works.

**To Reproduce**
1. install a system with btrfs raid as root
2. have specific hardware I guess?
3. see it fail to boot

**Expected behavior**
File system should be mounted

**Screenshots**
https://img.pbb.lc/id/Nk95LNx7nWQT623A

**Metadata** 
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.0, NixOS, 20.03.20191125.89b2c0b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20191022_9cac895`
 - channels(root): `"nixos-20.03pre202991.57cf4eb83bc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- boot.initrd
```
