### ISSUE TITLE
Fix far2l version

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#74490]
**Describe the bug**

Repology reports:

>far2l: WARNING: "far2l-2.1.unstable-2018-07-19.gitdceaa39": suspicious version "2.1.unstable-2018-07-19.gitdceaa39", worth rechecking

**Expected behavior**

Please follow the naming convention:

>If a package is not a release but a commit from a repository, then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also append "unstable" to the name - e.g., "pkgname-unstable-2014-09-23".

https://nixos.org/nixpkgs/manual/#sec-package-naming

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: far2l
# a list of nixos modules affected by the problem
module:
```
