### ISSUE TITLE
qtbase darwin build failure

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#74770]
**Describe the bug**
A patch does not apply to qtbase for darwin

https://hydra.nixos.org/build/107289685

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
