### ISSUE TITLE
k3d does not build

### ISSUE THREAD

**Issue by ahiaao** [NixOS/nixpkgs#74809]
**Describe the bug**
k3d does not build. I ran a bisect and found that k3d stopped building after 29d40ef73562f0a2180dbdf56ad2960824bd7791 (imagemagick: 6.9.9-34 -> 6.9.10-68 (security))

Build failure from hydra https://hydra.nixos.org/build/107206939

>Module k3d-imagemagick-io.module: /nix/store/fs6wdhwi4rfiyc62w94wdf9bzmwa9hzd-gcc-6.5.0-lib/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /nix/store/xani7qx16vwl3hn1n8x0a8dimrzcp76i-libheif-1.5.0/lib/libheif.so.1)

**To Reproduce**
1. nix-build -A k3d

**Expected behavior**
To build

Maintainer information: 
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: k3d
# a list of nixos modules affected by the problem
module: @7c6f434c 
```
