### ISSUE TITLE
prometheus: error reading base template: open templates/_base.html: no such file or directory

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#74844]
**Describe the bug**
prometheus doesn't seem to find some template file.

**To Reproduce**
1. use `services.prometheus.enable = true;`
2. run `curl localhost:9090/graph`

get
`error reading base template: open templates/_base.html: no such file or directory`

**Expected behavior**
no error

**Screenshots**

**Additional context**

**Metadata**
❯ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 20.03pre203917.0106804da3f (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(bbigras): `"home-manager"`
 - channels(root): `"nixos-20.03pre203917.0106804da3f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

cc @benley @fpletz @globin @willibutz
