### ISSUE TITLE
Spectacle isn't working

### ISSUE THREAD

**Issue by jamescostian** [NixOS/nixpkgs#74926]
**Describe the bug**
One cannot install `kdeApplications.spectacle` using NixOS 19.09

**To Reproduce**
1. In `environment.systemPackages`, add `kdeApplications.spectacle`
2. `nixos-rebuild build`
3. Error!

**Expected behavior**
Package should get installed/upgraded/whatever

**Additional context**
I use KDE. I already had the package installed (via `environment.systemPackages`) for quite a while now, but today I ran `nixos-rebuild switch` and discovered this error, which is now preventing me from upgrading and installing other packages

Full logs from the `nixos-rebuild switch` are [here](https://gist.github.com/jamescostian/037751a05424ced5146737c83964c878)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.86, NixOS, 19.09.1457.dae3575cee5 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1476.72a2ced2523"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
