### ISSUE TITLE
kodiPlugins not working

### ISSUE THREAD

**Issue by vdot0x23** [NixOS/nixpkgs#74937]
**Describe the bug**
I've attempted to intall kodiPlugins.advanced-emulator-launcher kodiPlugins.inputstream-adaptive but neither of them appear in kodi "my Add-ons" or `~./kodi/addons/`

**To Reproduce**
1. Install kodi (i used `desktopManager.kodi.enable = true;`)
2. Install kodiPlugins
3. Run kodi, look for plugins

**Expected behavior**
I would expect kodiPlugins to appear in kodi my Add-ons and `~./kodi/addons/`, though i am not sure if it is strictly necessary to have them in  `~./kodi/addons/`.

**Additional context**
I suspect this might be related to the line `pluginDir = "/share/kodi/addons";` in https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/kodi/plugins.nix though i am a nix beginner.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 20.03pre203904.bb1013511e1 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre203904.bb1013511e1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- kodiPlugins.advanced-emulator-launcher
- kodiPlugins.inputstream-adaptive
# a list of nixos modules affected by the problem
module:
```
