### ISSUE TITLE
JDK issues

### ISSUE THREAD

**Issue by Dil3mm4** [NixOS/nixpkgs#75055]
**Describe the bug**
Build halt.

**To Reproduce**
1. get an Android ROM source (LineageOS/PixelExperience whatever) 
2. . build/envsetup.sh && breakfast
3.. select your target 
4.. make otapackage 

**Expected behavior**
Build should complete.

**Additional context**
Current nix script used https://pastebin.com/xT7YNUvj 
Error:https://hastebin.com/pecaporapi.bash 
NixOS version: 19.09.1487.1be199f0594

Tried to switch to other versions of jdk as well, oracle's and open, headless and non-headless, no change.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, NixOS, 19.09.1487.1be199f0594 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1487.1be199f0594"`
 - channels(linuxct): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
