### ISSUE TITLE
GTK pantheon-filechooser-module cannot be loaded

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#75244]
**Describe the bug**
(java:34937): Gtk-WARNING **: 13:33:12.201: GTK+ module /run/current-system/sw/lib/gtk-3.0/modules/libpantheon-filechooser-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 13:33:12.202: Failed to load module "pantheon-filechooser-module"

**To Reproduce**
1. Start a Jetbrains product

**Expected behavior**
No error

**Screenshots**

**Additional context**
That file exists

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.1, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
--



# a list of nixos modules affected by the problem
module:
```
