### ISSUE TITLE
PHP 7.4 zip extension missing

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#75427]
**Describe the bug**
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - shopware/platform dev-master requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - shopware/platform dev-master requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - shopware/platform dev-master requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - Installation request for shopware/platform dev-master -> satisfiable by shopware/platform[dev-master].

**To Reproduce**
1. Install symfony using php74Packages.comoser

**Expected behavior**
Just works like in other versions

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: php74 php74Packages.composer
# a list of nixos modules affected by the problem
module: 
```
