### ISSUE TITLE
nixos: vm-test-run-natStandalone fails on master

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#75760]
**Describe the bug**
vm-test-run-natStandalone fails on master, blocking nixos.

https://hydra.nixos.org/build/108241462

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
