### ISSUE TITLE
Newer version of pango seems to have broken a few packages

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#75790]
**Describe the bug**
Seems like some updates to pango broke a few packages

Among the broken ones:
 - ettercap (see #75789)
 - pangox-compat (which anydesk needs)
 - probably a few more

**To Reproduce**
1. Try to build ettercap or anydesk from master
2. It will fail to build with some pango-related errors

**Expected behavior**
It should work

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-24-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pango
# a list of nixos modules affected by the problem
module:
```
