### ISSUE TITLE
thunderbird: It's branded as thunderbird daily, although it's a release version

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#75904]
**Describe the bug**
Seems like it really does use release source code, so it should be branded as that

**To Reproduce**
1. Open thunderbird

**Expected behavior**
Should be branded as thunderbird _release_ not _daily_

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.89, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre205780.d942688fc13"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: thunderbird
# a list of nixos modules affected by the problem
module:
```
