### ISSUE TITLE
zoom-us: "Sign in with google" causes browser to open, without any link

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#75903]
**Describe the bug**
SSO login in zoom just opens the default browser that loads the default homepage

**To Reproduce**
1. Open zoom-us
2. Click sign-in
3. Click sign in with google

**Expected behavior**
A browser should open _pointed at the Google SSO page_

**Screenshots**

**Additional context**
Seems like the argument isn't passed properly to the browser. Possibly wrapper issue or the default-browser-command-thing is somehow swallowing the parameter.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.89, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre205780.d942688fc13"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zoom-us
# a list of nixos modules affected by the problem
module:
```
