### ISSUE TITLE
python38Packages.bleach build broken

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#76093]
**Describe the bug**
2012dd5734ef0f15a68794020283b112625b3f95 broke the build of python38Packages.bleach, see [here](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python38Packages.bleach.x86_64-linux), python37 is still [fine](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python37Packages.bleach.x86_64-linux).
This is probably an upstream issue in either bleach or python.
bleach [master](https://github.com/mozilla/bleach/commit/27bac8e7c00f8a15dc2a80f19e592e2fe98bbc93) still has this behavior, though.
They do [test on 3.8](https://github.com/mozilla/bleach/pull/490), that is however 3.8.0, not 3.8.1 as of writing this.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python38Packages.bleach
# a list of nixos modules affected by the problem
module:
```

cc @FRidh
