### ISSUE TITLE
VirtualBox "Kernel driver not accessible" 

### ISSUE THREAD

**Issue by iterprise** [NixOS/nixpkgs#76108]
**Describe the bug**
I have the same problem as here
https://github.com/NixOS/nixpkgs/issues/75808
But I don't have virtualbox in my user environment 

type VirtualBox
VirtualBox /run/current-system/sw/bin/VirtualBox

**To Reproduce**

1. Install virtual box. My cfg is it attach.

2. Try to run VirtualBox and start VM in non root user

if run VBox from root user it works fine.

[configuration.txt](https://github.com/NixOS/nixpkgs/files/3989635/configuration.txt)

**Expected behavior**
Start VM

**Additional context**
type VirtualBox
VirtualBox /run/current-system/sw/bin/VirtualBox

groups
users wheel networkmanager libvirtd vboxusers kvm

id
uid=1000(user) gid=100(users) группы=100(users),1(wheel),57(networkmanager),67(libvirtd),72(vboxusers),302(kvm)

ls -l /dev/vbox*
crw-rw---- 1 root vboxusers 10, 58 дек 20 19:59 /dev/vboxdrv
crw-rw-rw- 1 root root 10, 57 дек 20 19:59 /dev/vboxdrvu
crw-rw---- 1 root vboxusers 10, 56 дек 20 19:59 /dev/vboxnetctl

/dev/vboxusb:
итого 0
drwxr-x--- 2 root vboxusers 100 дек 20 19:59 002
drwxr-x--- 2 root vboxusers 60 дек 20 19:59 003

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.90, NixOS, 19.09.1629.ce54d9601ea (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1629.ce54d9601ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.virtualbox
# a list of nixos modules affected by the problem
module: virtualisation/virtualbox-host
```
