### ISSUE TITLE
python.withPackages does not honor lowPrio

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#76135]
**Describe the bug**
When calling python.withPackages with multiple packages that collide, setting lowPrio on one of those packages does not change anything

**To Reproduce**
1. Add the expression `(python3.withPackages(ps: with ps; [ (lib.lowPrio pyqt5) dbus-python sip ]))` to buildInputs of any derivation
2. Build that derivation

**Expected behavior**
.withPackages should detect pyqt5 being lowPrio and resolve the collision with sip's `sipconfig.py`

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.90, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-20.03pre205792.fb1bc1b891f"`
 - channels(root): `"nixos-20.03pre205780.d942688fc13"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - python3
 - python
# a list of nixos modules affected by the problem
module:
```
