### ISSUE TITLE
please update typora to 0.9.80

### ISSUE THREAD

**Issue by sharuzzaman** [NixOS/nixpkgs#76249]
**Describe the bug**
Typora have released version 0.9.80

**To Reproduce**
1. nix-env -i typora
2. Got old version compared to the latest version in their website
3. Sad :(

**Expected behavior**
The latest version should be installed

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: typora
# a list of nixos modules affected by the problem
module:
```
