### ISSUE TITLE
teamspeak: missing icon

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#76326]
**Describe the bug**
The desktop icon for teamspeak is missing

**To Reproduce**
1. Install teamspeak
2. Open any app listing which shows the application icoons

**Expected behavior**
It should display the teamspeak icon

**Additional context**
I noticed there is `/run/current-system/sw/share/icons/teamspeak.png/: directory`, which isn't a .png file as expected so this means the icon is where it shouldn't be or wasn't even moved with the proper install command

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-20.03pre205792.fb1bc1b891f"`
 - channels(root): `"nixos-20.03pre206331.eeaf1f702d4"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- teamspeak
# a list of nixos modules affected by the problem
module:
```
