### ISSUE TITLE
remmina RDP plugin does not load

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#76350]
**Describe the bug**
Remmina can not be used as an RDP client due to a packaging bug in NixOS.

**To Reproduce**
1. start remmina
2. notice in your terminal: `Error: /nix/store/5jwjz069s0b8dvqkh6lmp5vd8fdsjhzd-remmina-1.3.7/lib/remmina/plugins/remmina-plugin-rdp.so: undefined symbol: freerdp_settings_set_string`

**Expected behavior**
The RDP plugin should work.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.5-hardened, NixOS, 20.03.git.ed57285 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(delroth): `""`
 - nixpkgs: `/etc/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: remmina
# a list of nixos modules affected by the problem
module:
```
