### ISSUE TITLE
ROOT 6.18.04 requires clang++?

### ISSUE THREAD

**Issue by yipengsun** [NixOS/nixpkgs#76365]
**Describe the bug**
I just installed `root` on my macOS 10.15. when launching `root` from the command line, I got a pop-up window:

```
The "clang++" command requires the command line developer tools. Would you like to install the tools now?
```

But `root` itself seems to be launching fine. I'm using `nixpkgs-unstable` channel.

In my nix configuration, I listed `gcc` but not `clang` (they seems to be mutually exclusive). @veprbl any ideas?

**To Reproduce**
1. `nix-env -i gcc root`
2. `root -b`

**Expected behavior**
`root` launch properly without the pop-up window.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
