### ISSUE TITLE
Pencil does not start due to "pango: Harfbuzz version too old" 

### ISSUE THREAD

**Issue by robaca** [NixOS/nixpkgs#76403]
**Describe the bug**
Pencil does not start. When executed from the terminal, I get the following output:

```
Hardware acceleration disabled for Linux.

(pencil:17950): Pango-ERROR **: 15:20:19.627: Harfbuzz version too old (1.2.7)

[1]    17950 trace trap (core dumped)  pencil
```

**To Reproduce**
1. Install pencil from the nixos-unstable channel 
2. Run `pencil` 

**Expected behavior**
Pencil starts without errors

**Screenshots**

**Additional context**
System with "nixos-unstable" standard channel, xfce-i3wm

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.3, NixOS, 20.03pre206331.eeaf1f702d4 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206331.eeaf1f702d4, nixpkgs-unstable-20.03pre205792.fb1bc1b891f"`
 - channels(carsten): `"nixos-19.09.1292.e1843646b04"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
