### ISSUE TITLE
trilium: has two desktop files

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#76567]
**Describe the bug**
The Trilium Desktop App has two desktop files

**To Reproduce**
1. Install trilium
2. Open the menu

**Expected behavior**
There should be one

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/7735145/71497794-1c964800-285a-11ea-8f48-90d34ca9619c.png)

**Additional context**
/nix/store/y961ny44rfl33ismx3njads6y224lj7g-trilium-desktop-0.38.2
latest master

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-20.03pre205792.fb1bc1b891f"`
 - channels(root): `"nixos-20.03pre206438.a06925d8c60"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - trilium
# a list of nixos modules affected by the problem
module:
```
