### ISSUE TITLE
earlyoom: Option -k is ignored since earlyoom v1.2

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#76570]
**Describe the bug**
The option services.earlyoom.useKernelOOMKiller appends the -k flag, which has been deperacted upstream. The module should reflect this

**To Reproduce**
1. `services.earlyoom = { enable = true; useKernelOOMKiller = true; }`
2. Build config

**Expected behavior**
Module should tell option is deperacted

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-20.03pre205792.fb1bc1b891f"`
 - channels(root): `"nixos-20.03pre206438.a06925d8c60"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
 - services.earlyoom
```
