### ISSUE TITLE
pyramid: make the dependency on Sphinx optional

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#76593]
**Describe the bug**
As of now the pyramid package depends on the package `Sphinx` which is originally on the `docs_extras`  section of the package definition: https://github.com/Pylons/pyramid/blob/1.10.4/setup.py#L46

This brings in a big chunk of dependencies that are added on the `propagatedBuildInputs` for an unclear advantage. As of now the dependency on `Sphinx` brings in also a dependency on `SQLAlchemy` making it very difficult to override it for a database applications that uses pyramid.

Would it be possible/feasible to duplicate the package building one without all that chunk of doc-only dependencies? 

Should I propose a PR?

Maintainer information:
```yaml
attribute:
  - python27Packages.pyramid
  - python37Packages.pyramid
  - python38Packages.pyramid  
module: []
```
