### ISSUE TITLE
sphinx: make the dependency on SQLAlchemy optional and don't propagate it

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#76602]
**Describe the bug**
The package lists `sqlalchemy` package among its dependencies even if it's missing from the original `setup.py` (See https://github.com/sphinx-doc/sphinx/blob/v2.2.0/setup.py#L18 ). It's  unclear why this needs to be done and the fact that it's in  the `propagatedBuildInputs` means that will be impossible for any python application that has this package in its closure to  use a custom/different version of sqlalchemy.

A solution to this problem could be to:

- remove it together with other unexpected dependencies (like `whoosh`);
- as sphinx is mostly used as a standalone application, move them to the `buildInputs`;
- replace this with two packages, one `slim` that only lists dependencies in accordance with the original package and one `fat` that has more features at the expense of a bigger closure and more difficult management.

Maintainer information:
```yaml
attribute:
  - python27Packages.sphinx
  - python37Packages.sphinx
  - python38Packages.sphinx 
# a list of nixos modules affected by the problem
module: []
```

See also #76593 

cc @nand0p
