### ISSUE TITLE
Can't install a new KDE theme

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#76615]
**Describe the bug**

Downloading and installing KDE look-and-feel themes fails silently.

**To Reproduce**
1. Open System Settings -> Look and Feel
2. Click "get new look and feel themes" 
3. Click "install" on any theme. Wait for installation to finish.
4. Notice that no new theme has actually been installed. 

**Expected behavior**

The theme would be installed.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.18, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(jon): `"home-manager, nixpkgs-20.03pre203529.e8f2764fe8d"`
 - channels(root): `"nixos-20.03pre206632.b0bbacb5213"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
