### ISSUE TITLE
users-groups.pl: Ignores skelDirectory

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#76657]
**Describe the bug**

**To Reproduce**
1. Set security.pam.makeHomeDir.skelDirectory
2. Add a user
3. Start the config as VM

**Expected behavior**
It should copy the files from the skelDirectory into the new $HOME if the $HOME didn't already exist

**Additional context**
https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/modules/config/update-users-groups.pl#L214-L218

It doesn't do that

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-20.03pre205792.fb1bc1b891f"`
 - channels(root): `"nixos-20.03pre206632.b0bbacb5213"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
