### ISSUE TITLE
xserver.{desktopManager,windowManager}.default configuration breaks after upgrade to master

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#76684]
**Describe the bug**
I have a NixOS installation with a very simple xserver configuration:
```nix
services.xserver.enable = true;
services.xserver.windowManager.default = "fluxbox"; 
services.xserver.windowManager.fluxbox.enable = true;
```
When trying to rebuild with master I get an error:
```
trace: Default graphical session, 'fluxbox', not found.
Valid names for 'services.xserver.displayManager.defaultSession' are:
  xterm
  xterm+fluxbox
  none+fluxbox

error: The option value `services.xserver.displayManager.defaultSession' in `/home/veprbl/nixpkgs/nixos/modules/services/x11/display-managers/default.nix' is not of type `session name'.
```

**To Reproduce**
1. Use my configuration.nix lines from the above
2. Do `nixos-rebuild build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e1ee43f514fa8b510d8d3d142dc1ae83dee7716d.tar.gz`

**Expected behavior**
The old configuration should continue to work unless I opt into `system.stateVersion = "20.03";`

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.xserver
```

This has to do with #53843
cc @hedning @jtojnar
