### ISSUE TITLE
[19.09] piper version incompatible with libratbag

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#76695]
**Describe the bug**

Supported devices do not show up in piper's GUI.

**To Reproduce**

1. Enable `ratbagd` service - `services.ratbagd.enable = true;`
2. Connect a supported device
3. Run `piper`

**Expected behavior**

The device shows up in piper GUI.

**Screenshots**

N/A

**Additional context**

Running compatible version of piper fixes the issue:

```
$ nix-shell -p "piper.overrideAttrs(_: { src = fetchTarball "https://github.com/libratbag/piper/archive/0.2.904.tar.gz"; })" --run piper
```

19.09 currently ships with piper 0.2.903.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 19.09.1690.0d9055a2ac2 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1690.0d9055a2ac2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: piper
# a list of nixos modules affected by the problem
module: services.ratbagd
```
