### ISSUE TITLE
libwebsockets: libuv, openssl should be propagated?

### ISSUE THREAD

**Issue by furrycatherder** [NixOS/nixpkgs#76714]
**Describe the bug**
Building with libwebsockets leads to errors like
```
/nix/store/kr9ivkvs7vy6bvwskf7cdh4r4f3kn64m-libwebsockets-3.2.0/include/libwebsockets.h:244:10: fatal error: openssl/ssl.h: No such file or directory
   #include <openssl/ssl.h>
            ^~~~~~~~~~~~~~~
  compilation terminated.
```
and
```
/nix/store/vmjqcmsd72sfps818p01iv9bj5kz3rgd-libwebsockets-3.2.0/include/libwebsockets.h:174:10: fatal error: uv.h: No such file or directory
   #include <uv.h>
            ^~~~~~
  compilation terminated.
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.86-gentoo, Gentoo, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixpkgs-20.03pre205780.d942688fc13"`
 - channels(swim): `"nixpkgs-19.09.1682.bfdae0860e4, nixpkgs-unstable-20.03pre206331.eeaf1f702d4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
