### ISSUE TITLE
gcloud-sdk missing path of /usr/lib/google-cloud-sdk/bin/gcloud

### ISSUE THREAD

**Issue by chrissound** [NixOS/nixpkgs#76737]
**To Reproduce**

```
nix-env -i kubectl
nix-env -i google-cloud-sdk

gcloud auth activate-service-account --key-file=/var/my-k8s-secrets/gcp.json
gcloud container clusters get-credentials  --region europe-west2-a    standard-cluster-1

kubectl get pods
```

The above generates a kubernetes kubectl config file with:
```
...
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

but /usr/lib/google-cloud-sdk/bin/gcloud does not exist

An error occurs when using `kubectl`:
```
error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr= 
```

---
