### ISSUE TITLE
Fish does not tab complete man pages

### ISSUE THREAD

**Issue by JustinLovinger** [NixOS/nixpkgs#76745]
**Describe the bug**
Tab completion for man pages does not work in the fish shell.

**To Reproduce**
1. Enter a fish shell
2. Type "man " followed by the first few letters of an installed package command
3. Press tab

**Expected behavior**
Fish should complete the man page command.

**Additional context**
This appears related to #14472.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.14, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(jlove): `""`
 - channels(root): `"nixos-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fish, man-db
# a list of nixos modules affected by the problem
module:
```
