### ISSUE TITLE
ssb-patchwork crashes when trying to change profile picture

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixpkgs#76743]
**Describe the bug**
When clicking on "Profile > Edit your profile > Choose profile image", `ssb-patchwork` crashes.

**To Reproduce**
1. `nix-env -iA nixpkgs.ssb-patchwork`
2. Profile > Edit your profile > Choose profile image
3. :boom: 

**Expected behavior**
A file browser window shows up

**Screenshots**
x.

**Additional context**
* I'm running i3.
* ssb-patchwork 3.17.1
* This is not a regression, it has been broken for a wihle

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 19.09.1484.84586a4514d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1484.84586a4514d, nixos-hardware"`
 - channels(asymmetric): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
