### ISSUE TITLE
writers.writeC: can't use libraries

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#76761]
**Describe the bug**

As described [in the wiki](https://nixos.wiki/wiki/Nix-writers) the writers.writeC don't work. I know the wiki does not hold the truth, but it seems using libs with `writers.writeC` and `writers.writeCBin` don't work at all.

**To Reproduce**
This `shell.nix`
```nix
{ pkgs ? import <nixpkgs> { } }:
pkgs.mkShell {
  buildInputs = with pkgs;
    [
      (pkgs.writers.writeC "hello-world-ncurses" {
        libraries = [ pkgs.ncurses ];
      } ''
        #include <ncurses.h>
        int main() {
          initscr();
          printw("Hello World !!!");
          refresh(); endwin();
          return 0;
        }
      '')
    ];
}
```

produces : 

```
/nix/store/3g2pkmc1s9ycjaxaqc5hrzmq05r5ywbi-stdenv-linux/setup: line 1293: find: command not found
Must specify package names on the command line
/build/.attr-0:1:10: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
          ^~~~~~~~~~~
compilation terminated.
builder for '/nix/store/n9lj0aw48rwrp8sqc6b3cl2vivd2w59m-hello-world-ncurses.drv' failed with exit code 1
error: build of '/nix/store/n9lj0aw48rwrp8sqc6b3cl2vivd2w59m-hello-world-ncurses.drv' failed
```

**Expected behavior**
You want to have a shell with a `hello-world-ncurses` binary.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
error: attribute 'nixpkgs' in selection path 'nixpkgs.nix-info' not found
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - writers.writeC
  - writers.writeCBin
# a list of nixos modules affected by the problem
module:
```
