### ISSUE TITLE
Google Play Music Desktop Player not loading, fixed in new release

### ISSUE THREAD

**Issue by dkudriavtsev** [NixOS/nixpkgs#76864]
**Describe the bug**

Google Play Music Desktop Player does not finish loading.

**To Reproduce**
1. Start GPMDP
2. Log in
3. Attempt to load the music page

**Expected behavior**
Page loads

**Screenshots**

![image](https://user-images.githubusercontent.com/9790772/71711488-2d910d00-2db6-11ea-8f2b-fbf6b36cc136.png)

**Additional context**

This is fixed in new nightly builds of GPMDP.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206693.b38c2839917 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre207243.be3f887ac40"`
 - channels(dmitry): `"nixos-20.03pre206486.a8fc904c7c0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: google-play-music-desktop-player
# a list of nixos modules affected by the problem
module:
```
