### ISSUE TITLE
Ship libykpers udev rules in NixOS

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#76874]
**Describe the bug**
We're missing some udev rules that allow you to set `otp` settings on yubikey without root.
Original issue: https://github.com/Yubico/yubikey-manager/issues/287

Just leaving this here so I don't forget to fix this. Happy to self-assign

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
