### ISSUE TITLE
XFCE Display settings are crashing

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#76888]
**Describe the bug**
fish: “xfce4-display-settings” terminated by signal SIGSEGV (Address boundary error)

**To Reproduce**
1. Install xfce

**Expected behavior**
Its just working

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(shyim): `"nixos-20.03pre205780.d942688fc13"`
 - channels(root): `"nixos-20.03pre206632.b0bbacb5213"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: xfce.xfce4-settings
# a list of nixos modules affected by the problem
module:
```
