### ISSUE TITLE
tensorflow: build fails with cuda 10.2

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#76935]
**Describe the bug**

python3Packages.tensorflowWithCuda build fails with:

```
ERROR: /build/output/external/nccl_archive/BUILD.bazel:53:1: fatbinary external/nccl_archive/device_dlink_hdrs.fatbin failed (Exit 1)
fatbinary fatal   : Unknown option '-bin2c-path'
```

**To Reproduce**

1. `nix-shell -p python3Packages.tensorflowWithCuda`
2. observe build failure

**Expected behavior**

Build is successful.

**Additional context**

Might be related to https://github.com/tensorflow/tensorflow/issues/34429

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: jyp abbradar
# a list of nixos modules affected by the problem
module:
```

cc @timokau
