### ISSUE TITLE
Firefox plugins don't work anymore

### ISSUE THREAD

**Issue by petercommand** [NixOS/nixpkgs#76943]
**Describe the bug**

A recent commit to firefox (https://hg.mozilla.org/integration/autoland/rev/9b4e603eb86a ) removed support for loading extensions with the environment variable MOZ_PLUGIN_PATH, and the firefox wrapper in nixpkgs uses this environment variable to load plugins.

**To Reproduce**
1. install firefox
2. set nixpkgs.config.firefox.enableAdobeFlash = true
3. execute firefox

**Expected behavior**

The flash plugin should load

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.89, NixOS, 19.09.1625.0dc46b0e1c8 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1625.0dc46b0e1c8, nixos-unstable-20.03pre205710.352f030b715"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
@edolstra 
@andir
