### ISSUE TITLE
pipenv doesn't work anymore

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#76965]
**Describe the bug**
`pipenv sync` fails with 
```
[pipenv.exceptions.InstallError]: ['Traceback (most recent call last):', '  File "~/.local/share/virtualenvs/lavoro-fabio-n0pBXid0/bin/pip", line 6, in <module>', '    from pip._internal.main import main', "ModuleNotFoundError: No module named 'pip._internal.main'"]
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"home-manager, nixos-20.03pre207998.e0470e11c7a"`
 - channels(paki): `"nixos-20.03pre206632.b0bbacb5213"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- pipenv
# a list of nixos modules affected by the problem
module:
```
