### ISSUE TITLE
Reimplement lib.types.path.check

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#76977]
**Describe the bug**

 - it adds source paths to the store https://github.com/NixOS/nixpkgs/pull/64691
 - it is partial https://github.com/NixOS/nixpkgs/pull/76861#issuecomment-570593060

**To Reproduce**

Partiality:
```
nix-repl> lib.types.path.check {}
error: cannot coerce a set to a string, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:246:42
```

Adding sources to store:
1. write a module with a `types.path` option
2. make the module use that path by further filtering the source
3. use it
4. intermediate source will be in the store (nb can be huge)

**Expected behavior**

No side effects, so also no exceptions.

**Additional context**

`path.check` will need to understand when string coercion is possible to avoid both exceptions and adding sources to the store.

toString implementation:
https://github.com/NixOS/nix/blob/f800d450b78091835ab7ca67847d76e75d877a24/src/libexpr/primops.cc#L1762

string coercion:
https://github.com/NixOS/nix/blob/f800d450b78091835ab7ca67847d76e75d877a24/src/libexpr/eval.cc#L1593-L1648

**Metadata**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
