### ISSUE TITLE
bash is built without ​PGRP_PIPE

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#77055]
**Describe the bug**
The version of bash 4.4 built by hydra does not enable `PGRP_PIPE`. According to e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=224543 this can lead to problems.

Interestingly, just rebuilding (`nix-build '<nixpkgs>' -A bash --check`) on my machine seems to enable `PGRP_PIPE` in `/include/bash/config.h`. I'm not sure what determines `PGRP_PIPE`, but perhaps we should consider enabling it consistently.

**To Reproduce**
1. `nix-build '<nixpkgs>' -A bash --check`

**Expected behavior**
Succeed, enabling `PGRP_PIPE` consistently

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: bash
# a list of nixos modules affected by the problem
module:
```
