### ISSUE TITLE
KDE wallet crashes on start (plasma5)

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#77290]
**Describe the bug**
During boot, kwalletd5-wrap dumps core: `systemd-coredump[1204]: Process 1095 (.kwalletd5-wrap) of user 1000 dumped core.`
This prevents kde wallet to authenticate together with my session, and I need to re-enter the password after logging in.

**To Reproduce**
1. Configure system with kde plasma5 and sddm
2. Boot it

**Expected behavior**

kdewallet should not crash on boot

**Additional context**

Probably related to #68316.
@tenaf0 in that thread seems to have the same issue.

Display manager info:

- sddm
- plasma5

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.8-hardened, NixOS, 20.03pre208261.9beb0d1ac2e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(rick): `""`
 - channels(root): `"nixos-20.03pre208261.9beb0d1ac2e, nixpkgs-20.03pre207249.7e8454fb856"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
