### ISSUE TITLE
Please update Firefox to 72.0.1, Firefox ESR to 68.4.1 to fix a security vulnerability exploited in the wild (CVE-2019-17026)

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#77361]
**Describe the bug**

It would be great it this could be fixed in 19.03 too.

https://www.mozilla.org/en-US/security/advisories/mfsa2020-03/

> Mozilla Foundation Security Advisory 2020-03
Security Vulnerabilities fixed in Firefox 72.0.1 and Firefox ESR 68.4.1
> Announced January 8, 2020
> Impact   critical
> Products   Firefox, Firefox ESR
> Fixed in  Firefox 72.0.1, Firefox ESR 68.4.1
> CVE-2019-17026: IonMonkey type confusion with StoreElementHole and FallibleStoreElement
> Reporter    Qihoo 360 ATA
> Description
> Incorrect alias information in IonMonkey JIT compiler for setting array elements could lead to a type confusion. We are aware of targeted attacks in the wild abusing this flaw.

**To Reproduce**
N/A
**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Metadata**
N/A

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - firefox
  - firefox-esr
# a list of nixos modules affected by the problem
module:
```
