### ISSUE TITLE
geary crashes on startup

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#77397]
**Describe the bug**
When geary is run in an environment other than Gnome (in my case it's sway), it crashes with various errors.
When using gnome3 or having a gdm running in the background, it works. Enabling various gnome3 services (gnome-settings-daemon and gnome-accounts-daemon, dconf) on my machine did not help.

**To Reproduce**
1. Set up a host or VM without gdm and gnome3
2. Start geary
3. See it crash

**Expected behavior**
Geary should be usable in environments other than Gnome3. If additional services have to be configured on the machine to be able to start the application, I would expect there to be a `programs.geary` nixos module, which configures those.

**Screenshots**

**Additional context**
The wrapGAppsHook does not seem to work properly, or it is not sufficient for geary. 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.8, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(pbb): `""`
 - nixpkgs: `/var/src/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnome3.geary
# a list of nixos modules affected by the problem
module:
```

CC gnome3 applications maintainers @lethalman @jtojnar @hedning @worldofpeace
