### ISSUE TITLE
Krita does not build on hydra because of 'Log limit exceeded'

### ISSUE THREAD

**Issue by Flakebi** [NixOS/nixpkgs#77509]
**Describe the bug**
The krita build on hydra fails since gcc 9.0 was introduced, because of the log size.

**Expected behavior**
Krita should be available on cache.nixos.org

**Additional context**
Krita builds: https://hydra.nixos.org/job/nixpkgs/trunk/krita.x86_64-linux
First failing build: https://hydra.nixos.org/build/109444445
Last log line: `building of '/nix/store/41r8djyn9xccqkjj95i4azlia8985wrr-krita-4.2.7.1' killed after writing more than 67108864 bytes of log output`
Probably introduced through these commits (use gcc 9 by default): https://hydra.nixos.org/api/scmdiff?type=git&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev2=0fb7ae83ade88abd3af3f6969796909499b2bc2a&branch=&rev1=7e8454fb856573967a70f61116e15f879f2e3f6a

I guess silencing some warnings could fix this.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: krita
# a list of nixos modules affected by the problem
module:
```

cc @abbradar
