### ISSUE TITLE
Firefox puts store paths into extensions.json and breaks when they are GCd

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#77514]
**Describe the bug**
I've just had Firefox updated from 72.0 to 72.0.1 (nixos-unstable), and I did a garbage collect, and Firefox failed to start with many errors (in the console) about /nix/store/ files not found (I don't have the errors available any more). I found store paths in ".mozilla/firefox/<profile>/extensions.json" that did not exist any more. I was able to get Firefox to run again by deleting that file.

**To Reproduce**
1. Update the system such that Firefox goes from 72.0 to 72.0.1.
2. nix-collect-garbage --delete-old
3. Try to start Firefox.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: firefox
# a list of nixos modules affected by the problem
module:
```
