### ISSUE TITLE
patchShebangs doesn't handle /usr/bin/env -S

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#77539]
**Describe the bug**
patchShebangs doesn't handle /usr/bin/env -S command args... shebangs

**To Reproduce**
1. Download https://github.com/mkg20001/nix/blob/master/pkgs/kseistrup-filters/default.nix
2. Remove the sed command in the install phase that drops the -S flag
3. Build it

**Expected behavior**
Should patch shebangs as it would with the sed command

(The -S flag just allows multiple arguments which are already handled)

**Additional context**
Fails with exit 1 and no output

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(maciej): `"nixpkgs-20.03pre207249.7e8454fb856"`
 - channels(root): `"nixos-20.03pre208857.e4134747f56"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
