### ISSUE TITLE
Gparted unable to use exfat filesystem

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#77599]
System: NixOS 19.09

Problem:
The exfat option is not available when creating/formatting a partition with gparted even though the exfat filesystem is enabled in /etc/nixos/configuration.nix via `boot.supportedFilesystems = [ "ntfs" "exfat" ];` 

Additionally I tried  installing the `exfat` package from nixpkgs but that didn't help.

Manually executing mkfs.exfat works

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - gparted
# a list of nixos modules affected by the problem
module:
```
