### ISSUE TITLE
Bookworm doesnt compile

### ISSUE THREAD

**Issue by fionera** [NixOS/nixpkgs#77681]
**Describe the bug**
The current version of bookwork doesnt compile and cancels with:

"configure: error: C compiler cannot create executables"

**To Reproduce**
1. nix-env -iA bookworm

**Expected behavior**
It should compile and work

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.92, NixOS, 20.03pre209245.f9c81b5c148 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre209091.100012e55bc, nixos-hardware, nixpkgs-20.03pre209245.f9c81b5c148"`
 - channels(fionera): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
