### ISSUE TITLE
Tensorflow: command line flags not recognized by Bazel 2.0

### ISSUE THREAD

**Issue by GeorgeFlerovsky-Canada** [NixOS/nixpkgs#77771]
**Describe the bug**
Build fails because Bazel rejects the `--incompatible_no_support_tools_in_action_inputs` command line flag. This flag used to exist in Bazel 0.27, but no longer exists in Bazel 2.0, which is what the nixpkgs tensorflow package currently uses.

```
    bazelFlags = [
      # temporary fixes to make the build work with bazel 0.27
      "--incompatible_no_support_tools_in_action_inputs=false"
      "--incompatible_use_native_patch=false"
    ];
```

**To Reproduce**
nix-shell -p python37 -p "pkgs.lib.callPackageWith pkgs python37Packages.tensorflowWithCuda { cudaSupport = true; }" -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/60d72d12dea298599f497865fa83b5188ff7e467.tar.gz

**Expected behavior**
Tensorflow build works.

**Screenshots**
```
Configuration finished
building
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Unrecognized option: --incompatible_use_native_patch=false
builder for '/nix/store/0ab1jbzhm43zi2rkwkbipr949qr7vm9d-tensorflow-gpu-1.15.0-deps.drv' failed with exit code 2
cannot build derivation '/nix/store/nwirkpa9xz6xpnv5ac7d4z2kmmkpfz33-tensorflow-gpu-1.15.0.drv': 1 dep
```

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- python37Packages.tensorflowWithCuda
# a list of nixos modules affected by the problem
module:
```
