### ISSUE TITLE
Dino: Crash when trying to select file do send

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#77774]
**Describe the bug**
Dino crashes when trying to select file do send.

Might be an upstream bug.

**To Reproduce**
1. open dino
2. click on file chooser icon in a chat

![Screenshot from 2020-01-15 17-46-42](https://user-images.githubusercontent.com/91113/72453208-07f50200-37bf-11ea-87a5-ab21777ef0d9.png)

3. the program crash

```
(dino:13779): GLib-GIO-ERROR **: 17:05:10.780: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped
```

**Expected behavior**
being able to send files

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.89, NixOS, 19.09.1861.eb65d1dae62 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1861.eb65d1dae62, nixos-hardware, nixos-unstable-20.03pre209091.100012e55bc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dino
# a list of nixos modules affected by the problem
module:
```

cc @Mic92
