### ISSUE TITLE
Document nixos/virtualisation/docker-image.nix

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#77816]
**Describe the bug**
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/docker-image.nix
I only stumbled by accident on this file while looking for the profile `docker-image.nix`.This file explains in its comments how to run a NixOS-based docker image.

Please move the explanation to the NixOS manual.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
-nixos/modules/virtualisation/docker-image.nix
-manual
```
