### ISSUE TITLE
Installing any libcontainer related software (runc, podman, cri-o) bricks nixos-container

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#77925]
**Describe the bug**
NixOS Containers expect `/etc/containers` to be used by it. but this is a directory that is used by `libcontainer`-compatible systems like podman. More specifically it creates a file `/etc/containers/registries.conf`

`nixos-container.pl` then hard-crashes as it expects its own `*.conf` files to live there on the following line: https://github.com/NixOS/nixpkgs/blob/a0a3f5c86ce04a820035855a081d3acb7f353201/pkgs/tools/virtualization/nixos-container/nixos-container.pl#L153  but that file but it dies instead

**To Reproduce**
Install something `libcontainer`-y and use it
nixos-container is now broken

**Expected behavior**
nixos-container should not namesquat `/etc/containers`

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
