### ISSUE TITLE
GNOME 3 crashes on startup when AppArmor is enabled

### ISSUE THREAD

**Issue by emilazy** [NixOS/nixpkgs#77968]
**Describe the bug**
I was futzing for a while trying to figure out why GNOME crashed on startup until I realized that disabling AppArmor fixed it.

**To reproduce**
1. Turn on the `hardened.nix` profile.
2. Turn on `services.xserver.desktopManager.gnome3.enable`.
3. `$ XDG_SESSION_TYPE=wayland dbus-run-session gnome-session`

**Expected behaviour**
GNOME doesn't crash on startup, even with hardening features enabled.

**Metadata**
```
 - host os: `Linux 5.4.12-hardened, NixOS, 20.03.git.0436ef7 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - nixpkgs: `/home/emily/etc/nixos/extern/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

(not sure how to fill this part out, sorry)
