### ISSUE TITLE
python3.7-aiohttp-3.6.2 fails installtests on arm

### ISSUE THREAD

**Issue by bqv** [NixOS/nixpkgs#78016]
**Upstream bug**

https://github.com/aio-libs/aiohttp/issues/4515

**Metadata**
 - system: `"armv7l-linux"`
 - host os: `Linux 4.19.75, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre209226.d7627dd2df9"`
 - channels(leaf): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information: @dotlambda
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.pythonPackages.aiohttp
# a list of nixos modules affected by the problem
module:
```
