### ISSUE TITLE
python: gunicorn: 19.9.0 -> 20.0.4 upgrade broke apache-airflow

### ISSUE THREAD

**Issue by arnoldfarkas** [NixOS/nixpkgs#78084]
**Describe the bug**
apache-airflow requires gunicorn at or above 19.5 and below 20.0, therefore the upgrade of gunicorn broke apache-airflow build:

```
ERROR: Could not find a version that satisfies the requirement gunicorn<20.0,>=19.5.0 (from apache-airflow==1.10.5) (from versions: none)
ERROR: No matching distribution found for gunicorn<20.0,>=19.5.0 (from apache-airflow==1.10.5)
```

**To Reproduce**
Attempt to use apache-airflow package. E.g.:

```
nix-shell -p python37Packages.apache-airflow
```

This triggers a re-build of apache-airflow which will finally fail because of unsatisfied version requirement.

**Expected behavior**
apache-airflow package is usable (in the particular example, shell opens and apache airflow can be imported in python).

**Screenshots**

**Additional context**
The same issue can be observed in hydra  builds, e.g.:
https://hydra.nixos.org/build/110444491/nixlog/1

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
