### ISSUE TITLE
pick-colour-picker: icon missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#78484]
**Describe the bug**
the color picker icon on the main button is missing

**To Reproduce**
1. `nix run -f channel:nixos-unstable pick-colour-picker`
2. `pick-colour-picker`
3. see button

**Expected behavior**
buttons should have the proper icon and not a placeholder

**Screenshots**
![Screenshot from 2020-01-25 22-34-43](https://user-images.githubusercontent.com/91113/73127616-43fc4400-3fc3-11ea-8f83-078652a03bbc.png)

**Additional context**
I use the Pantheon Desktop (GTK based).

https://github.com/davidak/nixos-config/blob/master/machines/thinkpad_X230/configuration.nix

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 19.09.1815.caad1a78c47 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.09.1815.caad1a78c47, nixos-hardware, nixos-unstable-20.03pre208413.e1eedf29e5d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pick-colour-picker
# a list of nixos modules affected by the problem
module:
```
