### ISSUE TITLE
in zsh with command-not-found, missing programs return null error 

### ISSUE THREAD

**Issue by thblt** [NixOS/nixpkgs#78568]
**Describe the bug**

with `programs.command-not-found.enable = true;` and `programs.zsh.enable = true;`, attempting to run a non-existing program doesn't return an error code.

```
root@maladict> whatever
whatever: command not found
root@maladict> echo $?
0
``` 

it works with bash:

```
[root@maladict:/home/thblt]# whatever
whatever: command not found

[root@maladict:/home/thblt]# echo $?
127
```

**To Reproduce**

 1. Type gibberish at zsh prompt, press return.
 2. `$? == 0`

**Expected behavior**

`$? != 0`

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(thblt): `""`
 - channels(root): `"nixos-20.03pre208857.e4134747f56"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ "zsh" ]
# a list of nixos modules affected by the problem
module:
```
