### ISSUE TITLE
Calibre 4.x requires PyQtWebEngine for ebook reader

### ISSUE THREAD

**Issue by malSet** [NixOS/nixpkgs#78642]
**Describe the bug**
The ebook reader in Calibre 4.0 and above requires PyQtWebEngine for the ebook reader, as it will otherwise throw an ImportError.

**To Reproduce**
1. Install `calibre` from latest unstable `nixpkgs`.
2. Run calibre from terminal.
3. Attempt to open an ebook in the viewer (the quick start guide included should work fine for this example)
4. View the error in the terminal.

**Expected behavior**
The ebook reader to open properly.

**Additional context**
On my system, I have made an overlay which adds `python27.pyqtwebengine` to the `buildInputs` of `calibre`, and in the resulting derivation the ebook reader works perfectly fine. This seems just to be a missing dependency issue.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.97, NixOS, 19.09.1957.57c35c63004 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1957.57c35c63004, home-manager-19.09, nixos-unstable-20.03pre210078.90441b4b47f, nur"`
 - channels(malset): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ calibre ]
# a list of nixos modules affected by the problem
module:
```
