### ISSUE TITLE
python3Packages.imbalanced-learn requires scikit-learn>=0.22, fails to install

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#78788]
**Describe the bug**
python3Packages.imbalanced-learn requires scikit-learn>=0.22 but nixpkgs currently has 0.21.3:

```
ERROR: Could not find a version that satisfies the requirement scikit-learn>=0.22 (from imbalanced-learn==0.6.1) (from versions: none)
ERROR: No matching distribution found for scikit-learn>=0.22 (from imbalanced-learn==0.6.1)
```
**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-957.21.2.el7.x86_64, Red Hat Enterprise Linux Server, 7.6 (Maipo)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(user): `"nixpkgs-20.03pre203317.8bb98968edf"`
 - nixpkgs: `/u/user/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.imbalanced-learn
# a list of nixos modules affected by the problem
module:
```
