### ISSUE TITLE
x2goclient: fails to find sftp binary

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#78907]
**Describe the bug**
The x2goclient client fails to find the SFTP binary

```
x2go-ERROR-31> Unable to find the sftp-server binary. Neither bundled, nor found in $PATH nor additional directories.
```

**To Reproduce**
1. Connect to an x2go remote that has LXDE
2. Launch an LXDE session

**Expected behavior**
It should just work and show the desktop

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(maciej): `"meros, nixpkgs-20.03pre210116.ec8fd9cc345"`
 - channels(root): `"nixos-20.03pre210639.e59dcf8ccec"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - x2goclient
# a list of nixos modules affected by the problem
module:
```
