### ISSUE TITLE
pkgs.mkShell is executing scripts added to buildInputs

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#79061]
**Describe the bug**
Using `pkgs.writeScript" in `pkgs.mkShell` as `buildInputs` triggers them script to be run on running `nix-shell`, which unitutive

**To Reproduce**
using this shell.nix
```
{ pkgs ? import <nixpkgs> { } }:
let
in pkgs.mkShell {
  buildInputs = with pkgs; [
    (pkgs.writeScript "hack-writeScript" ''
      echo owned-writeScript >> /tmp/hacked
    '')
    (pkgs.writeScriptBin "hack-writeScriptBin" ''
      echo owned-writeScriptBin >> /tmp/hacked
    '')
    (pkgs.writers.writeBash "hack-writeBash" ''
      echo owned-writeBash >> /tmp/hacked
    '')
    (pkgs.writers.writeBashBin "hack-writeBashBin" ''
      echo owned-writeBashBin >> /tmp/hacked
    '')
  ];
}
```

Run `nix-shell --run 'cat /tmp/hacked'` and you get:

```
owned-writeScript
owned-writeBash
```

**Expected behavior**
The file `/tmp/hacked` shouldn't be created at all. The scripts are not just build, they are executed.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.97, NixOS, 19.09.git.1dadefe (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - nixpkgs: `/var/src/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- pkgs.mkShell
- pkgs.writeShell
- pkgs.writers.writeBash
- pkgs.writers.writeDash
# a list of nixos modules affected by the problem
module:
```
