### ISSUE TITLE
services.btrfs.autoScrub: running scrub prevents system suspend

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#79086]
**Describe the bug**

When the filesystem scrubbing service configured via `services.btrfs.autoScrub` is running, the system cannot suspend until the scrubbing is completed.

**To Reproduce**
1. enable the autoscrub service on some Btrfs file system, e.g. by
  ```nix
  services.btrfs.autoScrub = {enable = true; fileSystems = [ "/" ];};
  ```
2. start the resulting service, e.g. `systemctl start btrfs-scrub-.service`
3. suspend-to-ram the system: `systemctl suspend`
4. the system fails to suspend and a trace appropriating this failure tu btrfs can be found in the [system journal](https://github.com/NixOS/nixpkgs/files/4144117/btrfs-scrub-suspend_partial.log)

**Expected behavior**

The scrub should be paused properly when the system suspends.

**More context**

It's likely that this is an upstream bug. I'll ask around on the btrfs mailing list and will update this issue accordingly.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1970.6d9a4a615ee (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"home-manager-19.09, nixos-19.09.1970.6d9a4a615ee, nixos-unstable-20.03pre210639.e59dcf8ccec"`
 - channels(user): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- tasks/filesystems/btrfs.nix
```
