### ISSUE TITLE
i3status-rust: Potentially missing optional dependencies

### ISSUE THREAD

**Issue by atheriel** [NixOS/nixpkgs#79140]
**Describe the bug**

I'm one of the maintainers of [i3status-rust](https://github.com/greshake/i3status-rust), which is packaged here. A user [reported to our bug tracker](https://github.com/greshake/i3status-rust/pull/519) that in order to use the NixOS package:

> make sure to have `sysfsutils` for `sysfs`/battery, and `font-awesome_4` in the `fonts.fonts` list

I believe this is a more appropriate issue for packagers than maintainers, so I am re-filing it here. Note that I am not otherwise familiar with Nix packages, but this seems like the kind of thing that belongs in "optional dependencies".

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: i3status-rust
```
