### ISSUE TITLE
pythonPackages.dask: build fails due to pandas warnings

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#79191]
**Describe the bug**
Dask fails to build due to https://github.com/dask/dask/issues/4568. Fixed by 2.10.1.

Closed by https://github.com/NixOS/nixpkgs/pull/61253. (fixes with simple version bump)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
@fridh
