### ISSUE TITLE
urweb: runtime include icu headers.

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixpkgs#79218]
**Describe the bug**
urweb compiler fails with can't resolve `<unicode/utypes.h>` error in runtime.

**To Reproduce**
1. nix-env -i urweb
2. urweb hello (expecting hello word project)

**Expected behavior**
Binary should work out of the box.

**Additional context**

**Metadata**
- [This is the upstream change](https://github.com/urweb/urweb/commit/c2a217f9121dd865122bc6150c53e77bd662050d) which I believe introduced the problem.
- [This is a nixpkgs commit](https://github.com/NixOS/nixpkgs/pull/62266) which I believe broke this.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: urweb
# a list of nixos modules affected by the problem
module:
```

**Workaround**

Make sure header is include path when using `urweb`. The simplest in my opinion is to use nix-shell for development:

```nix
mkShell {
 buildInputs = [ icu ];
}
```

I'll try to open PR with fix myself.
