### ISSUE TITLE
Sound broken in Firefox 72 (ALSA)

### ISSUE THREAD

**Issue by aij** [NixOS/nixpkgs#79310]
**Describe the bug**
After the upgrade to Firefox 72.0.1, sound no longer works in Firefox. (It continues to work in other programs.)

It used to work in 71.0, but after I got the upgrade to 72.0.1 (with the fix for CVE-2019-17026 -- thanks for that!), things got very quiet. The subsequent upgrade to 72.0.2 did not fix it.

I'm seeing the same on nixos-19.09 and nixos-unstable, on 3 different machines. All have `sound.enable = true;` and no pulseaudio.

**Workaround**

Use the `firefox-esr` package. (Firefox 68.4.2esr)

**To Reproduce**
1. Install Firefox 72 (either the `firefox` package or `firefox-bin`)
2. Go to some site that should play sound. Eg: https://www.youtube.com/watch?v=4fWyzwo1xg0
3. Listen to the silence

**Expected behavior**

Sound should come out of the speakers.

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 19.09.git.7e1f60dfbba (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1662.8e4c9d15456"`
 - channels(aij): `"nixpkgs-19.03pre154584.c65da8b5111"`
 - nixpkgs: `/etc/nixos/aij/stable`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - firefox
 - firefox-bin
# a list of nixos modules affected by the problem
module:
```
