### ISSUE TITLE
`services.phpfpm.pools.<name>.phpEnv` values are not quoted

### ISSUE THREAD

**Issue by davidtwco** [NixOS/nixpkgs#79469]
**Describe the bug**
`services.phpfpm.pools.<name>.phpEnv` values do not require quotation to be parsed correctly by php-fpm, but if the value contains a `=` or is `true`/`false` (and perhaps other values, then the file fails to parse).

**To Reproduce**
1. Use the following NixOS configuration:

```nix
services.phpfpm.pools.foo.phpEnv."bar" = "true";
```

2. Observe that `phpfpm-bar.service` fails to start.
3. Observe that manually quoting `"true"` fixes the issue.

**Expected behavior**
`phpfpm` module appropriately quotes values provided to `phpEnv`.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.88, NixOS, 19.09.1549.45ea6092203 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1549.45ea6092203"`
 - channels(david): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.phpfpm
```
