### ISSUE TITLE
IDLE (Python’s Integrated Development and Learning Environment) fails do run

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#79484]
**Describe the bug**

[IDLE](https://docs.python.org/3/library/idle.html) (Python’s Integrated Development and Learning Environment), which belongs to package `python3`, fails do run because it cannot import `Tkinter`

```
$ nix-shell -p python3
$ idle
** IDLE can't import Tkinter.
Your Python may not be configured for Tk. **
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.0, NixOS, 20.03pre211190.a21c2fa3ea2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre211190.a21c2fa3ea2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3
# a list of nixos modules affected by the problem
module:
```
