### ISSUE TITLE
dhcpd6.machines is broken

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#79576]
**Describe the bug**
DHCPv6 works (slightly) differently from v4 and is also configured (slightly) differently from it.
Namely, the configuration defined [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/dhcpd.nix#L22) is wrong. `hardware ethernet` cannot be matched, because DHCPv6 does not provide it. `fixed-address` should also be `fixed-address6`.

**To Reproduce**
1. Try to use `dhcp6.machines`
2. Observe `dhcp6.service` failing to start.

**Expected behavior**
I did not expect DHCPv6 to work this way. We cannot fix that, though. In my (short) research, I also did not find an easy way to match for the hardware address and instead opted to use the clients' host names.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- dhcp6
```
