### ISSUE TITLE
deja-dup 40.6 - unable to backup to google drive in xfce

### ISSUE THREAD

**Issue by JeffLabonte** [NixOS/nixpkgs#79673]
**Describe the bug**
Everytime I try to initiate a backup, deja-dup seem to be unable to communicate with
google due to a TLS issue.

**To Reproduce**
1. start backup
2. authenticate yourself
3. Faillure

**Expected behavior**
Deja-dup to communicate with google servers

**Screenshots**
![deja-dup_issue](https://user-images.githubusercontent.com/9425955/74114016-af264880-4b75-11ea-891e-6bd0c7875259.png)

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.17, NixOS, 19.09.2036.c49da6435f3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6895_84de821`
 - channels(root): `"nixos-19.09.2036.c49da6435f3"`
 - channels(jflabonte): `"nixpkgs-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/home/jflabonte/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
