### ISSUE TITLE
libtasn1 bump to 4.16.0 broke darwin build, blocks nixpkgs-unstable

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#79749]
**Describe the bug**
The update in ee321af5f54d856d0fb42b20d1d4b98b664ff20b broke the darwin build.

**To Reproduce**
```
$ nix-build -A libtasn1
```
https://hydra.nixos.org/build/112020372

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `libtasn1`
# a list of nixos modules affected by the problem
module:
```
