### ISSUE TITLE
mono build broken

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#79841]
**Describe the bug**
mono does not build on master right now. 3d1007716c2295162274cb9faceca494e29aa104

See https://gist.github.com/ajs124/cdf4bc7dcbe5f33867345f2f5eb57c42 for build logs.
The first one is from my hydra, the second one from a manual `nix-build`.

**To Reproduce**
1. Try to build steam from master
2. Notice that mono does not compile

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
mono
# a list of nixos modules affected by the problem
module:
```
