### ISSUE TITLE
Changing from XFCE4 for Plasma, no kwin launched by default

### ISSUE THREAD

**Issue by JeffLabonte** [NixOS/nixpkgs#79878]
**Describe the bug**
If you install NixOS with a different window manager and desktop environment and you wish to use plasm5 instead, kwin won't start on launch and you will end up without  any window management whatsoever

**To Reproduce**
1. Install XFCE4 initially
2. Change system configuration to plasma
3. restart display-manager or reboot
4. Enjoy!

**Expected behavior**
To have a window manager, i.e kwin, to run by default when installing plasma

**Screenshots**
![image](https://user-images.githubusercontent.com/9425955/74290486-ffc9ad00-4cff-11ea-839b-8674941996a7.png)

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.17, NixOS, 19.09.2036.c49da6435f3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6895_84de821`
 - channels(root): `"nixos-19.09.2036.c49da6435f3"`
 - channels(jflabonte): `"nixpkgs-19.09.2036.c49da6435f3"`
 - nixpkgs: `/home/jflabonte/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
