### ISSUE TITLE
kubeval no longer builds

### ISSUE THREAD

**Issue by groodt** [NixOS/nixpkgs#79960]
**Describe the bug**
The kubeval derivation is no longer building. There have been no changes. I am not sure if the problem is due to the large size or something else.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
