### ISSUE TITLE
pcmanfm right click menu does not appear

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#80029]
**Describe the bug**
When right-clicking in pcmanfm, a menu never appears.

**To Reproduce**
Right click within the pcmanfm window.

**Expected behavior**
A menu with options should appear.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 20.03pre212208.8130f3c1c2b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre212208.8130f3c1c2b"`
 - channels(brad): `"home-manager, nixos-20.03pre199897.471869c9185"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Notify maintainers**

@ttuegel 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pcmanfm
# a list of nixos modules affected by the problem
module:
```
