### ISSUE TITLE
lightdm-gtk-greeter background stays in i3 session

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#80040]
**Describe the bug**
After login to i3 session, lightdm background is still seen.

**To Reproduce**
1. enable i3
2. ensure services.xserver.displayManager.lightdm.background is set (it is by default)
3. ensure there is no wallpaper is set under xorg

**Expected behavior**
There should be no background

**Screenshots**
![Screenshot_20200213_212528](https://user-images.githubusercontent.com/12064730/74466011-794fcf80-4ea7-11ea-99f4-d1a6db540e0e.png)

**Additional context**
The problem is seen on nixos-unstable https://github.com/NixOS/nixpkgs-channels/commit/a21c2fa3ea2b88e698db6fc151d9c7259ae14d96 and upper
There was no such problem on https://github.com/NixOS/nixpkgs-channels/commit/e59dcf8ccec439f54dc52ffd5832610fc3f6c9c2

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
