### ISSUE TITLE
Startx displayManager doesn't pass xserverArgs to X

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#80198]
**Describe the bug**

When you use the startx display manager and try to use xserver options like autoRepeatDelay, they do not get passed on to the X executable (displayManagers are expected to do that).

**To Reproduce**

1. Set an xserver option like autoRepeatDelay
2. Use the startx displayManager
3. Notice there's no effect

**Expected behavior**

It should apply the settings to the X server

**Screenshots**

**Additional context**

If you had the same issue I did and want a quick fix, put your desired args in `~/.xserverrc`.

Xinit has a way for specifying the flags system-wide via the xserverrc which is located in `/etc/X11/xinit/xserverrc` on a normal Freedesktop system.

We are not on such a system though, by looking at the strace of `startx` I found out that it tries to read the config from `${pkgs.xorg.xinit}/etc/X11/xinit/xserverrc` which doesn't exist. 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.102, NixOS, 19.09.2070.b9cb3b2fb2f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2070.b9cb3b2fb2f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.xserver.dislpayManager.startx
```
