### ISSUE TITLE
Electron is broken on macOS on case-sensitive filesystems

### ISSUE THREAD

**Issue by jakobrs** [NixOS/nixpkgs#80361]
**Describe the bug**
`nixpkgs.electron` is broken on macOS, due to the casing of a symlink (`MacOS` is spelled as `MacOs`)

**To Reproduce**
1. `nix-build '<nixpkgs>' -A electron`
2. `ls -l ./result/bin/electron`
3. `cat ./result/bin/electron`

**Expected behavior**
`MacOS` being cased correctly.

**Screenshots**
<img width="1479" alt="Screenshot 2020-02-17 at 16 18 43" src="https://user-images.githubusercontent.com/10761079/74666171-54a67100-51a1-11ea-85fa-2429599cd1d8.png">

**Additional Context**
Electron is the *only* package that cases `MacOs` this way. All other packages appear to be using `MacOS` instead. (source: `grep`)

Patch: #80362

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.2.0, macOS 10.15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixpkgs-20.03pre206786.62ef779f2a5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: electron
# a list of nixos modules affected by the problem
module:
```
