### ISSUE TITLE
mumble build broken

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#80491]
**Describe the bug**
The rnnoise bump in b2492bc444dfab0bf809018a7af3fb6d277f6c98 broke the mumble build on master.

cc @orivej

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
mumble
rnnoise
# a list of nixos modules affected by the problem
module:
```
