### ISSUE TITLE
Kitty does not start more

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#80936]
**Describe the bug**
Kitty does not start more

**To Reproduce**
1. Run nixos-unstable
2. Start Kitty
3. Does not start

**Expected behavior**
Its working

**Screenshots**
```
[055 09:05:46.416468] [glfw error 65542]: GLX: No GLXFBConfigs returned
[055 09:05:46.416497] [glfw error 65545]: GLX: Failed to find a suitable GLXFBConfig
[055 09:05:46.416512] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.09pre214390.ea79a830dcf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(shyim): `"nixos-20.03pre208171.2e8fc97dbfa"`
 - channels(root): `"nixos-20.09pre214390.ea79a830dcf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: kitty
# a list of nixos modules affected by the problem
module:
```
