### ISSUE TITLE
No input devices available

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#80960]
**Describe the bug**
I no longer have any input devices available after updating to the `20.03` beta. Using an HP laptop. I checked with both `pavucontrol` and the standard kde plasma settings manager. Audio output continues to work fine.

**To Reproduce**
1. Update to the `20.03` beta
2. Check if you have a microphone anymore

**Expected behavior**
I was hoping to still have access to my microphone.

**Additional context**
No special configuration I'm aware of:
```
  sound.enable = true;
  hardware.pulseaudio.enable = true;
  hardware.pulseaudio.support32Bit = true;
  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = true;
```

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.5, NixOS, 20.03beta219.153baa26740 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta219.153baa26740"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
