### ISSUE TITLE
Steam login window "slides" down off the screen on launch

### ISSUE THREAD

**Issue by enolan** [NixOS/nixpkgs#80996]
**Describe the bug**
When I launch Steam, the login windows appears in the center of the screen and immediately starts moving downwards. After maybe half a second, it's traveled off the screen and is no longer accessible at all.

**To Reproduce**
1. Be running Awesome WM
2. Launch `steam`, either from the 19.09 channel or unstable

**Expected behavior**
The login window should stay in place and I should be able to type my password.

**Additional context**
My Awesome install is not customized at all, and the behavior appears regardless of whether or not the current desktop is in tiled mode.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.105, NixOS, 19.09.2145.c2c5dcc00b0 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2145.c2c5dcc00b0, unstable-20.03pre200828.1e7ddf233a5"`
 - channels(enolan): `"nixos-19.09.2149.58a9acf75a3, unstable-20.09pre214374.1fe82110feb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [pkgs.steam, pkgs.awesome]
# a list of nixos modules affected by the problem
module:
```
