### ISSUE TITLE
tlp: bump to 1.3.1 needed

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nixpkgs#81049]
**Describe the bug**
Our current version of tlp, 1.2.1, is ancient and misses the large number of fixes in versions 1.3.0 and 1.3.1. A bump is warranted, but is nontrivial since a lot has changed.

**Additional context**
https://github.com/linrunner/TLP/releases

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    - tlp
# a list of nixos modules affected by the problem
module:
    - services.tlp
```
