### ISSUE TITLE
Baloo file indexer runs at 100% CPU 

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#81131]
**Describe the bug**

The Baloo file indexer in KDE is using all my system resources. My CPU runs at 100%, and my fan is running at top speed. My laptop is never like this, unless it's compiling something. This doesn't seem like ordinary behavior, and it's been going on for quite some time. 

**To Reproduce**
1. Have lots of files
2. Run KDE
3. Notice that your computer is about to die from overheating, since it's been running at 100% CPU for hours. 

**Expected behavior**

A file indexer wouldn't run this hot. 

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.21, NixOS, 20.09pre214537.39892985b00 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(jon): `"home-manager, home-manager-sway, nixpkgs-20.09pre214168.686274ea62c"`
 - channels(root): `"nixos-20.09pre214537.39892985b00"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
