### ISSUE TITLE
MATE: no screen lock after suspend

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#81434]
**Describe the bug**
When using the MATE desktop, the screen lock is not activated after suspending to RAM.

**To Reproduce**
1. Set `services.xserver.desktopManager.mate.enable = true;`
2. Set `services.xserver.displayManager.sddm.enable = true;`
3. Suspend the screen with `systemctl suspend`.
4. Wake the screen up again.

**Expected behavior**
The screen lock should activate, asking the user to input their password.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.106, NixOS, 19.09.2166.ce9f1aaa39e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2166.ce9f1aaa39e, u-20.09pre215033.ddc2f887f5f"`
 - channels(m): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mate.mate-screensaver
# a list of nixos modules affected by the problem
module:
```
