### ISSUE TITLE
appimage-run: Hyper 3 does not run

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#81726]
**Describe the bug**
/run/current-system/sw/bin/fish: /usr/lib/libm.so.6: version `GLIBC_2.29' not found (required by /run/current-system/sw/bin/fish)

**To Reproduce**
1. Install fish
2. Install appimage-run
3. Run this image https://github.com/zeit/hyper/releases/download/3.0.2/hyper-3.0.2-x86_64.AppImage

**Expected behavior**
It works

**Screenshots**
![image](https://user-images.githubusercontent.com/6224096/75888334-7d7a6780-5e2b-11ea-8dbe-35d844381a77.png)

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.7, NixOS, 20.03beta377.ebc9620c3f6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(shyim): `"nixos-20.03pre208171.2e8fc97dbfa"`
 - channels(root): `"nixos-20.03beta377.ebc9620c3f6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixo

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: appimage-run
# a list of nixos modules affected by the problem
module:
```
