### ISSUE TITLE
[20.03] dhall-nix broken

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#81834]
**Describe the bug**
package `dhall-nix` is broken

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
