### ISSUE TITLE
Doc: phpfpm.pools.<name>.socket path not clear

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#81908]
**Describe the bug**
The description of `services.phpfpm.pools.<name>.socket` is:

>Path to the unix socket file on which to accept FastCGI requests.
This option is read-only and managed by NixOS.

So i can't set it. But how can i figure out how the socket path is now?

Please add an example to the description!

**To Reproduce**
1. See option desciption https://nixos.org/nixos/options.html#fpm

**Expected behavior**
Useful description.

**Metadata**
same in 19.09 and 20.03

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.phpfpm
```
