### ISSUE TITLE
Option for generators.toINI to preserve order

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#81986]
**Describe the bug**
I use `generators.toINI` and my source data has an intentional order. It would be helpful if the result has also this order. An option would be fine but would it harm anyone if it would be default behavior?

**To Reproduce**
1. `$ echo 'lib.generators.toINI {} { general = { user="test"; password="secret"; host="localhost"; }; }' | nix repl '<nixpkgs>'`

`"[general]\nhost=localhost\npassword=secret\nuser=test\n"`

(the order seems alphabetical)

**Expected behavior**

`$ echo 'lib.generators.toINI { preserveOrder = true; } { general = { user="test"; password="secret"; host="localhost"; }; }' | nix repl '<nixpkgs>'`

`"[general]user=test\npassword=secret\nhost=localhost\n"`

Would that be possible somehow or does Nix evaluate the data as unordered set?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2196.00115f2f9c7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.09.2196.00115f2f9c7, nixos-hardware, nixos-unstable-20.09pre215702.1459b34afa9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: lib.generators.toINI
# a list of nixos modules affected by the problem
module:
```
