### ISSUE TITLE
julia_13 doesn't build

### ISSUE THREAD

**Issue by olynch** [NixOS/nixpkgs#82008]
**Describe the bug**
I haven't tried to build it on my local machine (because it would take forever), but it doesn't build on hydra: https://hydra.nixos.org/build/113989863/nixlog/1/tail. I don't know if people are working on this; is there current information that I could use to debug this?

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- julia_13
# a list of nixos modules affected by the problem
module:
```
