### ISSUE TITLE
Nextcloud upgrade path from 19.09 to 20.03 broken

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#82056]
**Describe the bug**
NixOS 19.09 had Nextcloud 16, while NixOS 20.03 uses Nextcloud 18, which skips one version.
This is a problem, as Nextcloud only supports updating from 16 -> 17 -> 18 and refuses to skip a version.

**To Reproduce**
1. Install NixOS 19.09 with Nextcloud and set it up
2. Upgrade system to 20.03
3. Nextcloud is now unavailable and updating fails with this information:
```
# nextcloud-occ status
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
  - installed: true
  - version: 18.0.0.10
  - versionstring: 18.0.0
  - edition:

# nextcloud-occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
Maintenance mode is kept active
Reset log level
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.nextcloud
# a list of nixos modules affected by the problem
module: services.nextcloud
```
