### ISSUE TITLE
home-assistant `port` doesn't do anything unless `config` is set

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#82076]
**Describe the bug**
If you set `services.home-assistant.port = 4000` but you don't set `services.home-assistant.config` to anything, then nothing changes. You still have to access it on port 8123

**To Reproduce**
1. set
```
services.home-assistant = {
  enable = true;
  port = 4000;
};
```
2. `sudo nixos-rebuild switch`
3. check localhost:4000 and localhost:8123

**Expected behavior**
I will see the landing page on localhost:4000, and not on localhost:8123

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.23, NixOS, 20.09pre215947.82b54d49066 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre215947.82b54d49066"`
 - channels(qolen): `"home-manager, nixos-20.09pre215947.82b54d49066"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: home-assistant
```
