### ISSUE TITLE
home-assistant `port` doesn't do anything unless `config` is set

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#82077]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
