### ISSUE TITLE
Emacs fonts broken

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#82306]
**Describe the bug**

Some normal symbols (e.g., `#`, `'` and `&`) are rendered as empty rectangles in Emacs:

![image](https://user-images.githubusercontent.com/2195834/76392052-7eeee700-6379-11ea-9a6a-3414cb465857.png)

This only happens when running Emacs as its own GUI window. No problems when running Emacs inside a terminal. This happened both with my Spacemacs setting that has worked before and with vanilla Emacs.

**To Reproduce**
1. To use Vanilla emacs, just move your emacs config somewhere: `mv ~/.emacs.d ~/.emacs.d.backup`
2. Open emacs as a separate GUI window: `emacs`
3. Open some buffer and type `#`, `'` and `&`. They aren't rendered correctly.

**Expected behavior**

These symbols should be rendered correctly.

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.100, NixOS, 20.03.git.a21c2fa (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - nixpkgs: `/etc/nixpkgs`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: emacs
# a list of nixos modules affected by the problem
module:
```
