### ISSUE TITLE
xfce, mate: preferences not shown in menu

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#82571]
**Describe the bug**

The default applications menu of Xfce and Mate desktop environments use to present preferences items and a control center (or similar) item for system configuration. Those items stopped appearing in the menu.

**Screenshots**

Screenshots taken for Xfce and Mate running in a local virtual machine:

![Screenshot at 2020-03-14 08-17-02](https://user-images.githubusercontent.com/1217934/76681042-2fa0f480-65cd-11ea-855a-d21ee8c06e4d.png)

![Screenshot at 2020-03-14 08-13-12](https://user-images.githubusercontent.com/1217934/76681043-30d22180-65cd-11ea-9e86-540dcb6bf9d0.png)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.7, NixOS, 20.09pre215947.82b54d49066 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre215947.82b54d49066"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: xfce, mate
```
