### ISSUE TITLE
Tor Browser: can't play audio/video streams

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#82597]
**Describe the bug**
Tor Browser does not correctly display audio/video streams, and instead tries to download it.

**To Reproduce**
1. Open Tor Browser.
2. Open an audio or video stream such as https://libre.fm/listen.php?tag= or https://ipfs.io/ipfs/QmcniBv7UQ4gGPQQW2BwbD4ZZHzN3o3tPuNLZCbBchd1zh.

**Expected behavior**
The stream should play correctly as it does on Tails.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.23, NixOS, 20.03beta448.1f99fd2fdbe (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta570.730453919bd, u-20.09pre216928.991bbef6835"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.tor-browser-bundle-bin
# a list of nixos modules affected by the problem
module:
```
