### ISSUE TITLE
Tribler: missing desktop icons

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#82671]
**Describe the bug**
Tribler does not have any desktop icons, and does not show up in any menus.

There is a desktop file in `/nix/store/*tribler-4.4.4/Tribler/Main/Build/Ubuntu/tribler.desktop` 
But it's not being included by the desktop environment.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.tribler
# a list of nixos modules affected by the problem
module:
```
