### ISSUE TITLE
smartd module notification emails report "lack of SMART capability"

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#82744]
**Describe the bug**
Notification emails generated by the smartd module erroneously report:

```
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.101] (local build)
[...]
SMART support is:     Unavailable - device lacks SMART capability.
[...]
```

This is happening both in test mode and in real notifications.

Running smartctl manually in a shell shows that the device indeed supports SMART:

```
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.101] (local build)
[...]
SMART support is: Available - device has SMART capability.
[...]
```

**To Reproduce**
1. Enable smartd, email notifications and test mode:
```nix
{
  services.smartd = {
    enable = true;
    notifications.mail.enable = true;
    notifications.test = true;
  };
}
```
2. Apply configuration and restart the smartd service to trigger test emails
3. Check root's mailbox, which should have received a report with the incorrect status.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.101, NixOS, 19.09.2201.7d31bbceaa1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2201.7d31bbceaa1, nixos-unstable-20.09pre215872.3d6cdfa24bd"`
 - channels(kea): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- services.smartd.*
# a list of nixos modules affected by the problem
module:
- services/monitoring/smartd.nix
```
