### ISSUE TITLE
3rd party Kvantum themes not selectable

### ISSUE THREAD

**Issue by FrauH0lle** [NixOS/nixpkgs#82769]
**Describe the bug**
Besides the included themes, Kvantum manager is does not allow the user to select other themes installed from packages like `arc-kde-theme` or `adapta-kde-theme`.

--

**To Reproduce**
1. Install `libsForQt5.qtstyleplugin-kvantum`
2. Install `arc-kde-theme`
3. Open Kvantum manager and try to select Arc theme

**Expected behavior**
Being able to select an installed theme.

**Screenshots**
As you can see the themes Adapta and AdaptaNokto do not appear in the drop down menu, even though they are installed in the correct folder. 

![image](https://user-images.githubusercontent.com/10484857/76828099-7f2b2e80-6820-11ea-9494-e8e55987ed2b.png)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2199.d1918bb0d90 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
