### ISSUE TITLE
ant-theme: hash missmatch in FOD

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#82833]
**Describe the bug**
While building ant-theme 3.0 with latest master the following error occurs:
```
 hash mismatch in fixed-output derivation '/nix/store/yd5prhffv26wzhk6ivr05dg1n1aamlas-ant-theme-1.3.0':
   wanted: sha256:07iv4jangqnzrvjr749vl3x31z7dxds51bq1bhz5acbjbwf25wjf
   got:    sha256:1nc66xh5yl794cpfsgvmfh31lmycjlssh1jjrsz654wymas4b35d
```

**To Reproduce**
1. Build ant-theme

**Expected behavior**
- builds

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(maciej): `"nixpkgs-20.09pre217312.d5dda83d915"`
 - channels(root): `"nixos-20.09pre217261.a2e06fc3423, nixos-hardware"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
