### ISSUE TITLE
tibia package has mirror give 503

### ISSUE THREAD

**Issue by mkf** [NixOS/nixpkgs#82857]
I can't install tibia. 503 error on mirror.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: tibia
```
