### ISSUE TITLE
Deprecated child options appear in manual when renaming submodule

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#82862]
**Describe the bug**

When renaming a submodule, the `mkRenamedOptionModule` makes the child options reappear in the docs at the old location.
This did not happen before https://github.com/NixOS/nixpkgs/pull/78135 (ping @Infinisil)

I've encountered the problem in the arion docs when [upgrading](https://github.com/hercules-ci/arion/pull/94/files) its tooling to nixpkgs 20.03. The move is `docker-compose.services` -> `services`. The regression makes the docs start with a mountain of legacy options comprising just under half of all options.
Reverting https://github.com/NixOS/nixpkgs/pull/78135 fixes the problem.

**To Reproduce**
1. Have an option `legacy.services.<name>.enable`
2. Move `legacy.services` to `services`
3. `legacy.services.<name>.enable` is in the docs, despite `legacy.services.visible = false`

**Expected behavior**

The option docs should have at most one entry per renamed option. Any suboptions should be omitted.

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixosOptionDoc
# a list of nixos modules affected by the problem
module: system.build.manual
```
