### ISSUE TITLE
Broken .desktop file for racket 

### ISSUE THREAD

**Issue by y-usuzumi** [NixOS/nixpkgs#82953]
**Describe the bug**
After installing nixos.pltScheme, One cannot run the DrRacket from the desktop menu.

**To Reproduce**
1. Take KDE for example, open the kickoff menu
2. Search 'DrRacket'
3. Hit Enter
4. An error dialog is shown:

![image](https://user-images.githubusercontent.com/1560189/77100232-42457e80-6a50-11ea-8a9f-d5f4aceb8dbd.png)

**Expected behavior**
DrRacket should run successfully.

**Additional context**
So the error message leads to the Exec key in the desktop file:

```
Exec=../../bin/drracket -singleInstance %F
```

which is relative to the .desktop file, but it really should be an absolute path or simply "drracket ...".

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.09pre217446.ddf87fb1baf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre217446.ddf87fb1baf"`
 - channels(kj): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
