### ISSUE TITLE
teeworlds: missing menu icons

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#83033]
**Describe the bug**
Teeworlds does not have a .desktop file so it doesn't show up in any menus.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixos.teeworlds
# a list of nixos modules affected by the problem
module:
```
