### ISSUE TITLE
Gajim: Emoji picker look broken on Pantheon Desktop

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#83053]
**Describe the bug**
![Screenshot from 2020-03-21 05-42-43](https://user-images.githubusercontent.com/91113/77219839-db9c8f80-6b39-11ea-9547-8e3a8215fa25.png)

@worldofpeace have you seen something like that already?

**To Reproduce**
0. open gajim
1. join chat room
2. click emoji picker

**Expected behavior**
the dialog should have a solid background, not transparent

**Additional context**
Find my whole config here: https://github.com/davidak/nixos-config/blob/0b49d91fc42270dda8eaacc13b89ef20174182a3/machines/thinkpad_X230/configuration.nix

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2196.00115f2f9c7 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.09.2284.bf7c0f0461e, nixos-hardware, nixos-unstable-20.09pre217537.d96bd3394b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gajim
# a list of nixos modules affected by the problem
module:
```
