### ISSUE TITLE
Tor Browser: add-ons disabled on start

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#83096]
**Describe the bug**
In Tor Browser, all add-ons, including HTTPS Everywhere and NoScript are disabled when you start up the browser. 

**To Reproduce**
1. Ensure you have Tor Browser 9.0.6 (from 20.03 or unstable).
2. Right-click on the starting page. 
3. Observe that the "NoScript" option is missing.

**Expected behavior**
All add-ons should be enabled on startup.

**Additional context**
This appears to be a regression since 9.0.5 introduced in https://github.com/NixOS/nixpkgs/pull/82754

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.24-gnu, NixOS, 20.03beta591.99a3d7a86fc (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta695.b2935fbecea, u-20.09pre217526.9b3515eb95d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixos.tor-browser-bundle-bin
# a list of nixos modules affected by the problem
module:
```
