### ISSUE TITLE
ansible package name contains wrong version

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#83105]
**Describe the bug**
We have 4 ansible versions currently, but their package name is identical.

![Screenshot from 2020-03-21 21-41-18](https://user-images.githubusercontent.com/91113/77236202-c7e63d00-6bbc-11ea-96a3-310759f91fea.png)

**To Reproduce**
1. https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=ansible

**Expected behavior**
package name should include the actual version

**Metadata**
unstable channel at 93144e0f4a5b21f561e4adda8a73d477d069b703

not reproducible on stable 54a27fb2fc5fbd8927f9f6dc77fe1de1faa05266

![Screenshot from 2020-03-21 21-44-14](https://user-images.githubusercontent.com/91113/77236254-3deaa400-6bbd-11ea-9545-640c9fb97d35.png)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ansible
# a list of nixos modules affected by the problem
module:
```
