### ISSUE TITLE
Weechat declarative scripts cannot be reloaded

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#83137]
**Describe the bug**
Scripts specified declaratively with `weechat.override` are not reloaded on `/python reload` (or `/perl reload`, etc).

**To Reproduce**
1. build 
```nix
let pkgs =  import <nixpkgs> {}; in
pkgs.weechat.override {
  configure = { availablePlugins, ... }: {
    scripts = with pkgs.weechatScripts; [
      wee-slack
    ];
  };
}
```
2. run `result/bin/weechat`
3. `/python list`correctly lists `slack`
4. `/python reload` outputs:
`python: unloading script "slack"`
but nothing about reloading it
5. `/python list` says no python script is loaded

**Expected behavior**
5. `python list` mentions slack

**Metadata**
reproduced on 1ff9d94

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: weechat
# a list of nixos modules affected by the problem
module:
```
