### ISSUE TITLE
libaom aomenc creates only noise

### ISSUE THREAD

**Issue by dali99** [NixOS/nixpkgs#83133]
**Describe the bug**
AOMENC is an AV1 video encoder included in libaom. Using nix the program outputs random noise for all videos encoded with it

**To Reproduce**
1. `nix-shell -p libaom`
2. `aomenc --passes=1 input.mkv -w 960 -h 540 --cq-level=39 --webm -o output.webm`
3. wait a whole bunch

**Expected behavior**
A valid av1 stream  should be created

**Screenshots**
![mpv-shot0003](https://user-images.githubusercontent.com/990767/77249072-f9075180-6c3e-11ea-8b2a-77e6530ce917.jpg)

**Additional context**
I've tested this on nixos and non nixos with nix

**Metadata**
 - host os: `Linux 5.3.0-40-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(slav1): `"nixpkgs-20.09pre215865.e113100be02"`
 - nixpkgs: `/home/slav1/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - libaom
# a list of nixos modules affected by the problem
module:
```
