### ISSUE TITLE
nixos-manual runs as root

### ISSUE THREAD

**Issue by kylesferrazza** [NixOS/nixpkgs#83157]
**Describe the bug**
With `services.nixos-manual.showManual = true;`, a helpful NixOS manual will run on a separate TTY for debugging.

By default, this process is w3m, and is running as the root user.

This means if my computer is locked, someone can come over, switch to the manual TTY, and then press `@` (run shell command and output to w3m). From there, the user can start any process on the system as root (including `/bin/sh`).

**To Reproduce**
1. Add `services.nixos-manual-showManual = true;` to system config.
2. Lock the system.
2. Press `Ctrl-Alt-F8` to switch to the TTY where `w3m` is running the manual.
3. Press `@`. You should see a prompt like `(read shell)!`.
4. Type `/bin/sh 1>&2` (redirect output to stderr so `w3m` doesn't capture it)
5. Type `whoami` to verify you are `root`.

**Expected behavior**
`w3m` does not run as root but an unprivileged user.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.9, NixOS, 20.09pre217537.d96bd3394b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"home-manager, mypkgs, nixos-20.09pre217537.d96bd3394b7"`
 - channels(kyle): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- services.nixosManual
```
