### ISSUE TITLE
haskell.packages.ghc882.http-media failed to build on 20.03

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#83186]
**Describe the bug**
Master builds just fine I think. Probably needs backporting.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
