### ISSUE TITLE
NixOS installer leaves dangling gcroot pointers

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#83207]
**Describe the bug**
On OS Images that we build I always have:
```
$ ls /nix/var/nix/gcroots
lrwxrwxrwx 1 root root   32 Apr 14  2019 profiles -> /build/root/nix/var/nix/profiles
```
and on installs that I have on my machines I always have
```$ ls /nix/var/nix/gcroots
lrwxrwxrwx 1 root root   32 Apr 14  2019 profiles -> /mnt/root/nix/var/nix/profiles
```

these are dangling pointers that are somehow created during installation and images building process. 

Furthermore, they seem redundant as recently an (undocumented) feature has been added to nix that makes `/nix/var/nix/profiles` a direct gcroot even without symlink. I have a feeling this bug has been introduced with this change

https://github.com/NixOS/nix/issues/3060

**To Reproduce**
1. Install NixOS or boot a NixOS cloud image

**Expected behavior**
No dangling pointers

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
