### ISSUE TITLE
redshift-plasma-applet appears to add filters to the screen but never remove them

### ISSUE THREAD

**Issue by werner291** [NixOS/nixpkgs#83250]
**Describe the bug**

The redshift-plasma-applet appears to only add filters to the screen, not removing them when that is necessary. Upon turning on/off and setting changes, the screen becomes progressively darker and redder to the point of being unuseable, need to restart.

**To Reproduce**
1. Add "redshift-plasma-applet" to list of packages in configuration.nix
2. Add the plasma applet to a panel in kde
3. Adjust the brightness/temperature, turn the applet on/off by clicking on it.

**Expected behavior**
Screen brightness and temperature are controlled as expected, turning the applet off removes the redshift effect.

**Screenshots**

**Additional context**

**Metadata**

- system: `"x86_64-linux"`
 - host os: `Linux 4.19.106, NixOS, 19.09.2166.ce9f1aaa39e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2166.ce9f1aaa39e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: redshift-plasma-applet
```
