### ISSUE TITLE
Ncurses package not moving infocmp to bin directory

### ISSUE THREAD

**Issue by bhougland18** [NixOS/nixpkgs#83293]
**Describe the bug**
The Ncurses package is not including the infocmp command line utility in the bin directory. 

**To Reproduce**
1. Install ncurses
2. Open terminal and type "which infocmp"

**Expected behavior**
I expect a path to infocmp to be provided

**Screenshots**
These are the utilities moved to the bin directory:
![image](https://user-images.githubusercontent.com/28444296/77434927-fb40eb80-6db7-11ea-9bb5-399321a9d3f8.png)

According to the install instructions infocmp should also be included:

![image](https://user-images.githubusercontent.com/28444296/77435297-88844000-6db8-11ea-80af-aa7b8f2a30a6.png)

**Additional context**
This is causing an issue when I use the Kitty terminal and run the following command to get a clojure repl:

clojure -Sdeps "{:deps {viebel/klipse-repl {:mvn/version \"0.2.3\"}}}" -m klipse-repl.main

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
