### ISSUE TITLE
dfu-programmer is broken

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#83374]
**Describe the bug**
dfu-programmer cannot find required shared objects

**To Reproduce**
1. Install dfu-programmer 
2. run `dfu-programmer`
3. Read the error message:
```
$ dfu-programmer -h
dfu-programmer: error while loading libusb-1.0.so.0 from libusb-0.1.so.4: libusb-1.0.so.0: cannot open shared object file: No such file or directory
```

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.9, NixOS, 20.09pre217537.d96bd3394b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre217537.d96bd3394b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: dfu-programmer
```
