### ISSUE TITLE
borgbackup: Improve documentation

### ISSUE THREAD

**Issue by ngiger** [NixOS/nixpkgs#83525]
**Missing example for backing up to a remote server**
I am a late newcomer to NixOS and it took me too long to get a backup to my borgbase.com account working. Therefore I decided to try to improve the documentation and will push a pull request soon.

**To Reproduce**
1. Do not know much about NixOS
2. Know how to backup via the command line to borgbase.com
3. Try to follow the example given in https://nixos.org/nixos/options.html#borgbackup

**Expected behavior**
It should be easy to follow the steps in the example to get the backup working

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
- system: `"x86_64-linux"`
- host os: `Linux 5.5.7, NixOS, 20.09pre215947.82b54d49066 (Nightingale)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.3`
- channels(niklaus): `""`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
borgb:
```
