### ISSUE TITLE
Pantheon filechooser not working correctly (not reproducible on a clean install)

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#83624]
**Describe the bug**
I've noticed on my machine that using the `pantheon-filechooser-module` gtk3 module is missing all of its buttons that make it functional. I have a nested configuration of gnome3 which uses the same home directory, so perhaps that has something to do with.
On a clean install I cannot reproduce this.

**To Reproduce**
1. Use the pantheon-filechooser-module (either install elementary-files or enable the pantheon module)
```
environment.sessionVariables.GTK3_MODULES = [ "pantheon-filechooser-module" ];
```
2. Use a filechooser in a gtk3 app
3. Looks broken can't use it

**Expected behavior**
See the screenshots

**Screenshots**
This is a saving dialog
![Screenshot from 2020-03-28 17 49 30](https://user-images.githubusercontent.com/28888242/77834645-886ba380-711c-11ea-9431-7a519c6882d0.png)

This is how it should look
![Screenshot from 2020-03-28 17 59 52](https://user-images.githubusercontent.com/28888242/77834850-37f54580-711e-11ea-90ca-2d1ecfbde7f6.png)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 20.09-7f0e497 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `""`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pantheon.elementary-files
# a list of nixos modules affected by the problem
module: pantheon
```
