### ISSUE TITLE
Agda 2.6.1 slow at loading primitive modules

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#83864]
**Describe the bug**
The new version of Agda is working fine on other systems, but not NixOS. I've reported a bit more about what is known at https://github.com/NixOS/cabal2nix/issues/447.

**To Reproduce**
1. Install Agda 2.6.1
2. Load any `.agda` file (e.g, `echo module Main where >Main.agda && agda Main.agda`)

**Expected behavior**
Agda checks the file quickly and exits.

**Additional context**
Issue in the Agda repository: agda/agda#4526

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.09.git.9c9007b5108 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/home/james/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: agda haskellPackages.Agda
# a list of nixos modules affected by the problem
module:
```
