### ISSUE TITLE
kdenlive doesn't find effects

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#83885]
**Describe the bug**

kdenlive doesn't find most of the effects. On console it's complaining about frei0r with numerous lines similar to:

```
Unknown asset :  "frei0r.sigmoidaltransfer"
```

For instance, Motion->Speed effect is missing.

**To Reproduce**

1. In `configuration.nix`, add:
```
  config.extraPackages = with pkgs; [
    kdenlive
    ffmpeg-full
    frei0r
  ];
```
2. Run `sudo nixos-rebuild test`.
3. Run `kdenlive`.

**Expected behavior**

I expect the normal set of effects to be available.

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 20.09.git.3320a06049f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

There's no maintainer marked in nixpkgs, but @lambda-11235 did some work on #66220.
