### ISSUE TITLE
kernel 5.4.29 broke wireguard

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#84009]
**Describe the bug**
The stable kernel update to 5.4.29 in 7bae57f24921a88e68d16b2e66df661963b3d733 broke the wireguard build. This is an upstream issue, which is potentially fixed by the patch in [this email](https://lists.zx2c4.com/pipermail/wireguard/2020-April/005236.html).

Upstream has not issued a new release yet.

There is also [this](https://git.zx2c4.com/wireguard-linux/log/?h=backport-5.4.y) now, which is a "real backport" of wireguard from 5.6, vs. the compat source we are using now. See [this announcement](https://lists.zx2c4.com/pipermail/wireguard/2020-March/005206.html).

**To Reproduce**
1. Try to build wireguard against 5.4.29
2. observe build failure

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- linuxPackages
# a list of nixos modules affected by the problem
module:
- services/networking/wireguard.nix
```

cc @NeQuissimus @Ma27
