### ISSUE TITLE
lollypop: wrap the binary with one of the tag editors?

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#84060]
**Describe the bug**

lollypop relies on external tag editors to modify any details of the media files. An attempt to modify tag information prompts the user to install one of the external tag editors. Perhaps one of them should be included in the derivation itself?

**To Reproduce**

1. Locate a song within lollypop library.
2. Right click and attempt to modify its details via `Modify information` menu item.
3. See a notification prompting to install one of the external tools.

**Expected behavior**

It works without any additional action on user's part.

**Screenshots**
N/A

**Additional context**

An argument could be made current behaviour mirrors intention of `lollypop` developers leaving the choice of the editor and its installation to the end user.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 20.09pre218613.ae6bdcc5358 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(pbogdan): `""`
 - channels(root): `"home-manager, nixos-20.09pre218613.ae6bdcc5358"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: lollypop
# a list of nixos modules affected by the problem
module:
```
