### ISSUE TITLE
Wrong COLLATE and CTYPE settings on the DB created by the matrix-synapse service

### ISSUE THREAD

**Issue by rihardsk** [NixOS/nixpkgs#84138]
**Describe the bug**
Synapse's Postgres documentation in [docs/postgres.md](https://github.com/matrix-org/synapse/blob/84a901cf0c32650ccd14f3a3ecd03dabed16d554/docs/postgres.md) says that `LC_COLLATE` and `LC_CTYPE` should be set to `'C'` but currently the db defaults to `en_US.UTF-8`. This can cause problems because aparently `glibc` can change UTF8 sort orders - see https://github.com/matrix-org/synapse/issues/6696#issuecomment-575280941.

**To Reproduce**
1. Set up `matrix-synapse` with Postgresql as the db
2. Have `glibc` < 2.28, use Synapse
3. Update to `glibc` >= 2.28, i guess...
4. The db gets corrupted

**Metadata**
- system: `"aarch64-linux"`
- host os: `Linux 5.3.0-rc4, NixOS, 20.09.git.aa0f4d23b3e (Nightingale)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.2`
- channels(root): `"nixos-20.03pre209091.100012e55bc"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nixos/modules/services/misc/matrix-synapse.nix
```
