### ISSUE TITLE
vsftpd: mistake in module help text. 'sslEnable' doesn't exist

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#84188]
The description of `services.vsftpd.forceLocalDataSSL` states:
'Only applies if `sslEnable` is true.'... 
But there is no `sslEnable` option in this module

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.24, NixOS, 19.09.2284.bf7c0f0461e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2284.bf7c0f0461e, nixos-hardware, unstable-20.09pre213994.e2b4abe3c8f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.vsftpd
```
