### ISSUE TITLE
systemd-resolved not working,no unit file installed

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#84201]
**Describe the bug**
The `systemd-resolved.service` unit file is not installed on `services.resolved.enable=true`

**To Reproduce**
1. Add `services.resolved.enable=true` to configuration.nix
2. `nixos-rebuild switch`
3. 
```
systemctl cat systemd-resolved 
No files found for systemd-resolved.service.
```

**Expected behavior**
Resolved installed correctly

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09pre218613.ae6bdcc5358 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200220_4a4521f`
 - channels(root): `"nixos-20.09pre218613.ae6bdcc5358, home-manager"`
 - channels(paki): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- services.resolved
```
