### ISSUE TITLE
Package vagrant broken: camlp4 is not available for OCaml 4.09.1

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#84416]
**Describe the bug**
```
in job ‘vagrant.x86_64-linux’:
camlp4 is not available for OCaml 4.09.1
```

**To Reproduce**
1. Build vagrant on latest master
2. Get error

**Expected behavior**
Builds

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-72-generic, Ubuntu, 18.04.4 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(maciej): `"nixos-20.09pre218613.ae6bdcc5358, nixpkgs-20.09pre218717.05f0934825c"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - vagrant
# a list of nixos modules affected by the problem
module:
```
