### ISSUE TITLE
Pidgin does not find purple plugins

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#84452]
**Describe the bug**
Pidgin does not find purple plugins.

**To Reproduce**
1. Add `pidgin` and `purple-facebook`, `purple-hangouts` and `purple-matrix` to `systemPackages`.
2. `nixos-rebuild switch`
3. Open Pidgin and got to `Accounts` (Ctrl-A)

**Expected behavior**
You are allowed to choose "Facebook", "Hangouts" or "Matrix" as protocol.
Instead, they are not shown.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 20.03beta874.b0c285807d6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta874.b0c285807d6, nixos-unstable-20.09pre218613.ae6bdcc5358"`
 - channels(raskolnikov): `"nixpkgs-19.09pre187222.002b853782e"`
 - nixpkgs: `/home/raskolnikov/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - pidgin
  - purple-facebook
  - purple-hangouts
  - purple-matrix
# a list of nixos modules affected by the problem
module:
```
