### ISSUE TITLE
linphone broken

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#84488]
nix-shell -p linphone

fails with

   test_suite_x509parse
   FAILED (401 / 426 tests (2 skipped))
cc @jluttine 

**Expected behavior**
linphone should build without error

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 19.09.2350.d011e474945 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/nix/store/69abb9my2y6nybxxmhr5bn6sil4715d9-1ifhiyh91n0f3cswkh837f7xavi2lmbk-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
