### ISSUE TITLE
virtualbox kernel drivers broken on latest master with latest kernel

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#84586]
**Describe the bug**
Virtualbox kernel drivers don't build with latest kernel.

**To Reproduce**

**on latest master, channel hasn't updated yet**

1. `d=(import /home/maciej/Projekte/nix { configuration = {pkgs, ...}: { boot.kernelPackages = pkgs.linuxPackages_latest; virtualisation.virtualbox.host.enable = true; }; }).vm   
`
2. `:b d`

**Expected behavior**
Builds

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-20.09pre218613.ae6bdcc5358"`
 - channels(maciej): `"nixpkgs-20.09pre218717.05f0934825c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
