### ISSUE TITLE
builder for '/nix/store/.../...-hg-archive.drv' failed

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#84710]
**Describe the bug**

After upgrading to the latest `nixos-unstable`, I get:

```
abort: HTTP Error 404: Not Found
builder for '/nix/store/hnba9816829ka9n42ylqjgacnirfl2gc-hg-archive.drv' failed with exit code 255
cannot build derivation '/nix/store/0crv5jqipjq4a0b04g7d2rivadr4p6f0-emacs-openwith-20120531.2136.drv': 1 dependencies couldn't be built
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 20.09pre218482.3320a06049f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(philipp): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/lcr3p8f33ksljpzmdk2x06m0ak95bah4-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
