### ISSUE TITLE
xsane fails to start with segmentation fault

### ISSUE THREAD

**Issue by swflint** [NixOS/nixpkgs#84753]
**Describe the bug**
`xsane` fails to start with error loading libusb.

```
xsane: error while loading libusb-1.0.so.0 from libusb-0.1.so.4: libusb-1.0.so.0: cannot open shared object file: No such file or directory
zsh: segmentation fault  xsane
```

**To Reproduce**

With xsane installed as a system package, run `xsane`.

**Expected behavior**

xsane should load and allow scanning.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09pre218613.ae6bdcc5358 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre218613.ae6bdcc5358, nix1709-17.09.3269.14f9ee66e63, nix1803-18.03.133402.cb0e20d6db9, nix1809-18.09.2574.a7e559a5504, nix1903-19.03.173553.6420e2649fa, unstable"`
 - channels(swflint): `"nixos-20.09pre215024.e97dfe73bba"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
