### ISSUE TITLE
gyp: No Xcode or CLT version detected! when using nodePackages version of node-gyp

### ISSUE THREAD

**Issue by shmish111** [NixOS/nixpkgs#84797]
**Describe the bug**
node-gyp causes `gyp: No Xcode or CLT version detected!` if you use the version in `nodePackages_10_x` but it works if you use the version in `nodejs-10_x`.

**To Reproduce**
1. Build a derivation that uses the `node-gyp` command on an OSX machine

**Expected behavior**
Build succeeds

**Additional context**
The fix was added for the nodejs version here https://github.com/NixOS/nixpkgs/pull/57632/files but not for the nodePackages version. I have an example in my project here https://github.com/input-output-hk/plutus/pull/1961/files

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
