### ISSUE TITLE
nix: Socket path too long on macOS (regression)

### ISSUE THREAD

**Issue by mikesperber** [NixOS/nixpkgs#84803]
**Describe the bug**

The tests for nixpkgs.nix generate socket paths that are too long.

**To Reproduce**
1. nix-env -i nix

**Expected behavior**

Successful build

**Screenshots**

    error: socket path '/private/var/folders/gb/5d9sp3js0x569rycy930pbkm000266/T/nix-build-nix-2.4pre7346_5e7ccdc9.drv-0/nix-test/var/nix/daemon-socket/socket' is too long

**Additional context**

This is a regression for this bug:

https://github.com/NixOS/nixpkgs/issues/27121

Reinstating the original fix - setting TMPDIR to tmp - fixes the problem.

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.3`
 - channels(sperber): `"nixpkgs-16.03pre70724.d4bebcb"`
 - nixpkgs: `/Users/sperber/build/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
