### ISSUE TITLE
Gnome 3.36 multiple monitor DPI scaling disables displays with Nvidia driver

### ISSUE THREAD

**Issue by DavidTruby** [NixOS/nixpkgs#84805]
**Describe the bug**
When using multiple 4k displays and setting the scaling in the Gnome settings Displays section, all my monitors are disabled. 

**To Reproduce**
1. Plug multiple 4k monitors into Nvidia graphics card
2. Set scale to 200% in gnome settings

**Expected behavior**
Scale is set to 200% on all monitors.

**Additional Context**
The bug has been reported upstream and there is a patch to mutter that fixes this issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/1128
It seems to have been fixed by this commit: https://gitlab.gnome.org/verdre/mutter/-/commit/bcfb4b726a481783447dc29afd7b832aca4c6cd4

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
