### ISSUE TITLE
transmission-remote-gtk missing icons

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#84983]
**Describe the bug**
The icons at the top part of the transmission-remote-gtk window as well as on the sidebar are nearly all generic squares. I'm just sure this is not how it's intended to look.

**To Reproduce**
1. install transmission-remote-gtk
2. launch transmission-remote-gtk
3. examine the interface carefully

**Expected behavior**
Diverse and meaningful icons so that I may grok a button's function without hovering over it every time or memorizing its position.

**Screenshots**
![2020-04-11-055639_grim](https://user-images.githubusercontent.com/3146494/79042059-12564a80-7bba-11ea-9ebd-6ca1a017a598.png)
![2020-04-11-055854_grim](https://user-images.githubusercontent.com/3146494/79042057-0c606980-7bba-11ea-9688-7b8ab9b39cb2.png)

**Additional context**
I'm using Sway on Wayland, my GTK theme is Adwaita-dark and my icon theme is HighContrast.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 20.09pre220429.9b0d2f3fd15 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre220429.9b0d2f3fd15"`
 - channels(brad): `"home-manager, nixos-20.09pre220429.9b0d2f3fd15"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: transmission-remote-gtk
# a list of nixos modules affected by the problem
module:
```
