### ISSUE TITLE
neat-interpolation: unpin

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#85118]
**Describe the bug**
right now neat-interpolation's version is getting pinned to 0.3.2.6 though I can't see a reason to do so.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
