### ISSUE TITLE
fish shell (3.0.2) unable to find $pager for built-ins

### ISSUE THREAD

**Issue by jhillyerd** [NixOS/nixpkgs#85158]
**Describe the bug**

fish is not able to find it's default pager (less) for built in commands.

**To Reproduce**
```sh
sudo useradd test
sudo su - test
fish
echo hello world
history
```

**Expected behavior**
Output of shell history

**Screenshots**
```
test@cubi ~> history
less -R: command not found
~/nix/store/f5a0n3kxiynv55w6jx5labpwl23mzwik-fish-3.0.2/share/fish/functions/history.fish (line 99):
                builtin history search $search_mode $show_time $max_count $_flag_case_sensitive $_flag_reverse $_flag_null -- $argv | $pager
                                                                                                                                      ^
in function “history”
        called on standard input
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.114, NixOS, 19.09.2399.5fa2612ca27 (Loris)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.3`
 - channels(james): `""`
 - channels(root): `"nixos-19.09.2399.5fa2612ca27"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fish
# a list of nixos modules affected by the problem
module:
```
