### ISSUE TITLE
No error in callHackageDirect when sha256 and ver mismatch

### ISSUE THREAD

**Issue by codygman** [NixOS/nixpkgs#85237]
**Describe the bug**

If you have `haskell-lsp-types.ver == "0.20.0.0"` but you give it `haskell-lsp-types` version 0.21.0.1 sha256 version `0.20.0.0` will be used.

**To Reproduce** (TODO)
1. ...
2. ...
3. ...

**Expected behavior**

An error should be thrown if the version of the package doesn't match `ver`

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
