### ISSUE TITLE
spice-vdagent: 90s timeout on shutdown/reboot

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#85235]
**Describe the bug**
On (not quite latest master), spice-vdagent causes now a 90s downtime when powering off or rebooting my notebook. I didn't do that before.

**To Reproduce**
1. Enable Spice VDAgent in the configuration.nix:

```
    services.spice-vdagentd.enable = true;
```

2. Rebuild with a current master
3. Switch to the new generation and power off/reboot.

**Expected behavior**
"Immediate" powering off without 90s timeout.

**Screenshots**
https://images.sjau.ch/img/e28390be.jpg

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.31, NixOS, 20.09.git.0af01aa8d1fM (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(hyper): `"nixos-19.09pre185402.5eac339829b"`
 - channels(root): `"nixos-20.09pre220429.9b0d2f3fd15"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
