### ISSUE TITLE
Segmentation fault when node script run in nixos test

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#85231]
**Describe the bug**
Weird segmentation fault when node script run in nixos test

**To Reproduce**
1. `nix run git+http://gitlab.comics.unina.it/NS-Thesis/SecureP2PSocialNetworks.git#checks.x86_64-linux.net.driver -c nixos-run-vms`
2. in the qemu window access as root
3. `hyperchat`
4. Input `a` when prompted for the room
5. Segmentation fault
**Expected behavior**
No segmentation fault occurs

**Screenshots**

**Additional context**
No segmentation fault occurs whn the script is run outside the vm.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
