### ISSUE TITLE
Cannot override options with type of `attrs`

### ISSUE THREAD

**Issue by JustinLovinger** [NixOS/nixpkgs#85508]
**Describe the bug**
If an option is declared with `type = lib.types.attrs`, you cannot override values within the attribute set. For example, given

```
foo = mkOption {
  type = types.attrs;
}
```

setting `foo.bar = mkDefault "foobar";` will result in a a value like `foo.bar.content = "foobar";`, instead of `foo.bar = "foobar";` with a priority of 1000.

This becomes particularly visible with RFC 42.

**Expected behavior**
A value set with `mkOverride`, or its derivatives, should set the given value with the given priority.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.28, NixOS, 20.03beta874.b0c285807d6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta874.b0c285807d6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: lib/modules.nix, lib/types.nix
```
