### ISSUE TITLE
Enabling dconf doesn't create /etc/deconf/db

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#85546]
**Describe the bug**
When I put ``dconf.enable = true;`` in my config, rebuild and reboot, dconf doesn't work: ``failed to commit changes to dconf: The connection is closed``.
When I run ``dconf update`` I get ``error: Error opening directory “/etc/dconf/db”: No such file or directory``.
The directory indeed doesn't exist. When I create it manually, and run ``dconf update``, not sure if that's needed), dconf works.
I'm not running any desktopmanager, just i3.

**To Reproduce**
1. put ``dconf.enable = true;`` in your config
2. rebuild
3. reboot

**Expected behavior**
Programs using dconf should be able to commit changes when you enable it.

**Notify maintainers**
@hedning
@jtojnar
@worldofpeace

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.106-rt46, NixOS, 20.09pre221706.b61999e4ad6 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(bart): `""`
 - channels(root): `"nixos-20.09pre221706.b61999e4ad6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
