### ISSUE TITLE
nix-daemon sets /tmp 775 and tempfilesd ignores second entry which should revert to 777

### ISSUE THREAD

**Issue by calbrecht** [NixOS/nixpkgs#85552]
**Describe the bug**
[nix-daemon.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-daemon.nix#L505) sets `/tmp` to `775 root root`

That is written into `/etc/tmpfiles.d/nixos.conf`

`systemd-tmpfiles` ignores duplicate entries and warns when doing 
`sudo nixos-rebuild test` with the message
```
[/etc/tmpfiles.d/tmp.conf:11] Duplicate line for path "/tmp", ignoring.
```

**To Reproduce**
1. Have untouched config option `systemd.tmpfiles.rules`
2. Run `sudo nixos-rebuild test`
3. Read warning from `systemd-tmpfiles`
4. See `/tmp` owned by root and not writeable by unpriviledged users

**Expected behavior**
/tmp should be writeable by unpriviledged users

**Notify maintainers**
@avnik 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.4, NixOS, 20.09.git.a2d9f584333M (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/home/alab/ws/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: systemd.tmpfiles.rules
# a list of nixos modules affected by the problem
module: nixos/modules/services/misc/nix-daemon.nix
```
