### ISSUE TITLE
waybar not showing bar

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#85668]
**Describe the bug**
I can start waybar and the process is running, but no bar appears. This happens since e233a9d4dd1484d2b79e496d45f5e785642638ef (I am still investigating which exact commit on staging broke it).

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
