### ISSUE TITLE
Needed `/run/nginx` for nginx directory absent in 20.03

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#85706]
**Describe the bug**

After #56255, the pid file of Nginx was changed from `/var/spool/nginx/log/nginx.pid` to `/run/nginx/nginx.pid`, but while the `/var/spool/nginx` was kinda guaranteed to be there with the dir being the `stateDir` option, created through systemd-tmpfiles, this is not the case for `/run/nginx`, making the Nginx fail to start.

**To Reproduce**
1. enable nginx while not having a `/run/nginx` directory
2. start nginx
3. watch it fail

**Expected behavior**

Nginx should not fail to start for a valid NixOS configuration.

**Screenshots**

```
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
nginx: configuration file /nix/store/<hash>-nginx.conf test failed
```

**Additional context**

**Notify maintainers**

@Izorkin @thoughtpolice @7c6f434c @fpletz @globin 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.106-hardened, NixOS, 20.03.1422.1e90c46c2d9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"home-manager-20.03, nixos-20.03.1422.1e90c46c2d9, nixpkgs-unstable-20.09pre221814.10100a97c89"`
 - channels(minijackson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nginx
# a list of nixos modules affected by the problem
module:
  - nginx
```
