### ISSUE TITLE
haskellPackages.binary-strict: marked as broken although it builds just fine

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#85722]
**Describe the bug**
In bf21b10ecde416dac593de85e42d1721ee18f476, haskellPackages.binaryStrict is marked as broken although it builds just fine.

I do not know what's the proper way to unbreak it: I already created a PR to do so #85717, but apparently editing the autogenerated hackage-packages.nix directly isn't the way to go.
But as I also cannot find any occurences of `binary-strict` in any of the `configuration-*` files, I do not know how to properly unbreak it.

So I am not only interested it getting that package unbroken, but also in the proper way of doing so.

**Notify maintainers**

@cdepillabout 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
