### ISSUE TITLE
Digitalocean metadata doesn't work anymore after switching to 20.03

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#85796]
**Describe the bug**
It fails to set up metadata as there is no route to the metadata service:

**To Reproduce**

```
[root@localhost:~]# curl  http://169.254.169.254/metadata/v1/hostname
curl: (7) Failed to connect to 169.254.169.254 port 80: No route to hos

```

**Expected behavior**
The metadata service is reachable

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
