### ISSUE TITLE
libva: iris_drv_video.so not found

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#85850]
**Describe the bug**
libva tries to find and use iris_drv_video.so instead of i965_drv_video.so like before

**To Reproduce**
1. Use nixos-unstable channel
2. Open vlc on console to see log
3. Open any video in vlc

**Expected behavior**
i965_drv_video.so is used and no vlc crash happens

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.33, NixOS, 20.09.git.22a3bf9fb9e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(gnidorah): `""`
 - channels(root): `"nixos-20.09pre222138.b3c3a0bd183"`
 - nixpkgs: `/home/gnidorah/tmp/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
