### ISSUE TITLE
mosh fails to build when installing bash completions

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#85893]
**Describe the bug**
The `mosh` package fails to build. It errors out during the installation of bash completions with "Permissions denied".

```
/nix/store/ca9mkrf8sa8md8pv61jslhcnfk9mmg4p-coreutils-8.31/bin/install: cannot create regular file '/nix/store/9w74w172vnlm6x6pg5cdd86mnq3rmvbb-bash-completion-2.10/share/bash-completion/completions/mosh': Permission denied
```

**To Reproduce**
1. nix-build -A mosh

**Expected behavior**
Successful build

**Notify maintainers**
@viric 

**Metadata**
on  324dd670139e8e9e8b8612750c679f3fd210a298

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mosh
# a list of nixos modules affected by the problem
module:
```
