### ISSUE TITLE
virtualisation.azureImage does not exist

### ISSUE THREAD

**Issue by idontgetoutmuch** [NixOS/nixpkgs#86005]
**Describe the bug**
```
sundials@sundials:~/nixpkgs/nixos/maintainers/scripts/azure-new$ ./upload-image.sh ./examples/basic/image.nix
+ image_nix=./examples/basic/image.nix
+ nix-build ./examples/basic/image.nix --out-link azure
error: The option `virtualisation.azureImage' defined in `/home/sundials/nixpkgs/nixos/maintainers/scripts/azure-new/examples/basic/system.nix' does not exist.
(use '--show-trace' to show detailed location information)
```
**To Reproduce**
See above

**Expected behavior**
I think I expected to have a azure host provisioned.

**Screenshots**

**Additional context**
I was using an azure vanilla ubuntu machine on which to run the script.

**Notify maintainers**

**Metadata**
Ah sorry too late - I have torn down the machine

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
