### ISSUE TITLE
libngspice is not built for darwin

### ISSUE THREAD

**Issue by evils** [NixOS/nixpkgs#86039]
**Describe the bug**
[libngspice is currently not built on darwin](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libngspice/default.nix#L24)
this prevents kicad from being built on darwin (official builds of kicad for MacOS are available)
libngspice [appears to support darwin](https://github.com/imr/ngspice/blob/master/build-for-mac-os.sh)

**To Reproduce**
0. on darwin, `nix-build '<nixpkgs>' -A libngspice`

**Expected behavior**
libngspice to build on darwin and be usable by kicad there

**Additional context**
i maintain the kicad package and [already tried pinging the libngspice maintainer](https://github.com/NixOS/nixpkgs/pull/82634#discussion_r403080903)

**Notify maintainers**
@bgamari if you already investigated after the kicad PR ping, nothing relevant changed since.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libngspice
# a list of nixos modules affected by the problem
module:
```
