### ISSUE TITLE
wxPython_4_0 is not built for darwin

### ISSUE THREAD

**Issue by evils** [NixOS/nixpkgs#86040]
**Describe the bug**
wxPython_4_0, [while accounting for darwin somewhat](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/wxPython/4.0.nix#L54), does not build there
likely because it uses wxGTK rather than [wxmac](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/wxwidgets/3.0/mac.nix)
this prevents kicad from being built on darwin

**To Reproduce**
0. on darwin, `nix-build '<nixpkgs>' -A wxPython_4_0`

**Expected behavior**
wxPython_4_0 to build on darwin and be usable by kicad there

**Additional context**
i maintain the kicad package and [already tried pinging the principle contributor](https://github.com/NixOS/nixpkgs/pull/82634#discussion_r403080903)

**Notify maintainers**
while there are no listed maintainers for this package
it was initially contributed by @tbenst (if you already investigated after the kicad PR ping, nothing relevant changed since)
and has a fair amount of contributions by @FRidh

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: wxPython_4_0
# a list of nixos modules affected by the problem
module:
```
