### ISSUE TITLE
glvnd/libGL stubs/mesa missing GLES3/gl3ext.h

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#86057]
**Describe the bug**
`gl3ext.h` isn't in any of `libglvnd.dev`, `libGL.dev`, or `mesa.dev`. I'm not sure exactly where it should be, but it should probably be available _somewhere_. This causes `superTuxKart` to fail to build on aarch64.

**To Reproduce**
1. `nix-build channel:nixos-unstable -A superTuxKart`

**Expected behavior**
Working cached build

**Metadata**

 - system: `"aarch64-linux"`
 - host os: `Linux 5.6.5, NixOS, 20.09pre222244.22a3bf9fb9e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1445.95b9c99f6d0"` (note: not using this)
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - superTuxKart 
 - libglvnd
 - libGL
 - mesa
# a list of nixos modules affected by the problem
module:
```
