### ISSUE TITLE
VirtualBox-GuestAdditions don't match the host

### ISSUE THREAD

**Issue by evils** [NixOS/nixpkgs#86092]
**Describe the bug**
"[for best results, it is recommended to keep the Guest Additions at the same version](https://www.virtualbox.org/manual/ch04.html#guestadd-intro)"

**To Reproduce**
1. [see that we only ship the near-latest virtualbox version](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/virtualbox/default.nix)
2. [see that there are older maintained versions of virtualbox](https://www.virtualbox.org/wiki/Download_Old_Builds)
2.1 [and get used](https://svnweb.freebsd.org/ports/head/emulators/virtualbox-ose/Makefile?view=markup)

**Expected behavior**
either:
* detect the host virtualbox version and install the appropriate version
  * ship support for all maintained versions with the demo appliance?
* offer `virtualisation.guest.variant` for manual selection
* allow installation of the guest additions provided by the host via an `.iso` to the guest

**Additional context**
a friend tried nixos on freebsd's latest virtualbox (5.2) and ran into some compatibility issues with the 6.1.4 guest additions on 20.03

**Notify maintainers**
@svanderburg

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: linuxPackages.virtualboxGuestAdditions
# a list of nixos modules affected by the problem
module: virtualisation.guest
```
