### ISSUE TITLE
mongodb-compass: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by emanueleperuffo** [NixOS/nixpkgs#86126]
**Describe the bug**
MongoDB Compass does not start.
When I launch it from the command line I get:
```
[1]    17977 segmentation fault (core dumped)  mongodb-compass
```

**To Reproduce**
1. Open a terminal
2. Run mongodb-compass

**Expected behavior**
MongoDB Compass starts.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.17, NixOS, 20.03.1405.a17e021b948 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1405.a17e021b948"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
