### ISSUE TITLE
nvidia optimus: display-manager restarts on system upgrades

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#86123]
**Describe the bug**
Display manager restarts on system upgrades on Nvidia Optimus setup
```
$ systemctl status display-manager
апр 27 14:59:08 nixos systemd-coredump[2541]: Process 1580 (X) of user 0 dumped core.
апр 27 14:59:15 nixos lightdm[2606]: pam_unix(lightdm:session): session opened for user gnidorah by (uid=0)
```

**To Reproduce**
1. Use nixos-unstable commit 22a3bf9fb9edad917fb6cd1066d58b5e426ee975
2. Switch to commit 7c399a4ee080f33cc500a3fda33af6fccfd617bd
3. Rebuild system

My configuration
```nix
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.prime.offload.enable = true;
  hardware.nvidia.prime.nvidiaBusId = "PCI:1:0:0";
  hardware.nvidia.prime.intelBusId = "PCI:0:2:0";

```

**Expected behavior**
Display manager doesn't restart.

**Screenshots**

**Additional context**
**Caused by systemd-udev-trigger.service**
Fedora bug report https://bugzilla.redhat.com/show_bug.cgi?id=1378974#c5

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
