### ISSUE TITLE
Default NixOS wallpaper missing after update

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#86146]
**Describe the bug**
The default wallpaper was a NixOS flake. I actually like it and never changed it. Now i miss it.

![Screenshot from 2020-04-27 23-22-13](https://user-images.githubusercontent.com/91113/80422712-f56e8680-88de-11ea-8cab-cecb079147cd.png)

**To Reproduce**
1. use pantheon desktop
2. update to 20.03
3. login

**Expected behavior**
same default wallpaper as before instead of black screen

**Notify maintainers**
@worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1589.9137f05564e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(davidak): `""`
 - channels(root): `"nixos-20.03.1589.9137f05564e, nixos-hardware, nixos-unstable-20.09pre222973.7c399a4ee08"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
