### ISSUE TITLE
Meson: Unknown compiler for cross compilation

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#86229]
**Describe the bug**

At least the following derivations fail on current `nixos-unstable`:

```
nixpkgs.pkgsCross.aarch64-multiplatform.fuse
nixpkgs.pkgsCross.aarch64-multiplatform.xorg.xorgproto
nixpkgs.pkgsCross.aarch64-multiplatform.glib
```

All failures have this log in common:

```
meson.build:1:0: ERROR: Unknown compiler(s): ['cc', 'gcc', 'clang', 'pgcc', 'icc']
The follow exceptions were encountered:
Running "cc --version" gave "[Errno 2] No such file or directory: 'cc': 'cc'"
Running "gcc --version" gave "[Errno 2] No such file or directory: 'gcc': 'gcc'"
Running "clang --version" gave "[Errno 2] No such file or directory: 'clang': 'clang'"
Running "pgcc --version" gave "[Errno 2] No such file or directory: 'pgcc': 'pgcc'"
Running "icc --version" gave "[Errno 2] No such file or directory: 'icc': 'icc'"
```

**To Reproduce**

Build one of `fuse`, `xorg.xorgproto`, `glib` for `aarch64-multiplatform` on `nixos-unstable`.

**Expected behavior**
They used to build.

**Additional context**

Git bisect tells me, that one of these commits are to blame:

9073a0cb8b2f419785a60969e11e96733f29b200..6c162416ca4d95b54a9837293e7e0f1b01f4622c

I couldn't bisect further as that would have taken lots of build time.

**Notify maintainers**

As `meson` seems to be the common denominator, meson maintainers: @jtojnar @rasendubi @brandonedens 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - nixpkgs.pkgsCross.aarch64-multiplatform.fuse
  - nixpkgs.pkgsCross.aarch64-multiplatform.xorg.xorgproto
  - nixpkgs.pkgsCross.aarch64-multiplatform.glib
# a list of nixos modules affected by the problem
module:
```
