### ISSUE TITLE
bcachefs-tools fails to build

### ISSUE THREAD

**Issue by danielfullmer** [NixOS/nixpkgs#86252]
**Describe the bug**
`bcachefs-tools` fails to build in `master`

**To Reproduce**
1. `nix-build "<nixpkgs>" -A bcachefs-tools -I nixpkgs=channel:nixpkgs-unstable`
2. The tests fail to complete.

**Notify maintainers**
CC @davidak @chiiruno

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.33, NixOS, 20.09.git.1daea9b1a9e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"config-tested, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: bcachefs-tools
# a list of nixos modules affected by the problem
module:
```
