### ISSUE TITLE
Gnome insists to open .html files with "Signal Desktop" application eventhough it has no association

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#86314]
**Describe the bug**
If I double click on a `.html` file it opens the Signal Desktop chat app

**To Reproduce**
1. install firefox
2. install signal
3. html files "open" in signal; which makes no sense as signal can't open files

**Expected behavior**
html files open in the browser

**Screenshots**

Firefox according to gnome:
![image](https://user-images.githubusercontent.com/628387/80591164-80559b00-8a1d-11ea-86ae-3d0099373cf9.png)

Signal desktop acording to gnome:
![image](https://user-images.githubusercontent.com/628387/80591207-92373e00-8a1d-11ea-8c3b-75e29925c52c.png)

![image](https://user-images.githubusercontent.com/628387/80591422-f65a0200-8a1d-11ea-820c-c0f8decd42e4.png)

**Would insert a picture of right clicking on an .html file here but PRT-SCR doesn't work when the user is right-clicking in gnome**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
