### ISSUE TITLE
right click "format disk..." stopped working in Gnome Files

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#86315]
**Describe the bug**
I can not format disk in Gnome anymore since updating to 20.03

**To Reproduce**
1. Insert a disk
2. Right click "format" in Gnome Files
3. Nothing happens

**Expected behavior**
The format disk dialog pops up

**Screenshots**
![image](https://user-images.githubusercontent.com/628387/80592247-6cab3400-8a1f-11ea-8343-caffeea6ee9e.png)

**Additional context**
Gnome files logs the following to `journalctl -xef`
```
Apr 29 13:41:57 t490s org.gnome.Nautilus[1875]: Cannot parse integer value “1e00007” for --xid
```

Ubuntu also seems affected: https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1853784

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
