### ISSUE TITLE
NixOS 20.03 will not power off on Ryzen 1700x

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#86360]
**Describe the bug**
after running `poweroff` the screen goes black; all services stop; but the machine keeps running. Need to hold the power button to turn it completely off.

Mostly opening in the hope any other people are running into this too since upgrading to 20.03 and maybe know a way around this or know a way to debug this.

**To Reproduce**
1. type `poweroff`
2. machine doesn't power off

**Expected behavior**
The machine powers off

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
