### ISSUE TITLE
nixos-option doesn't respect NIX_PATH ?

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#86381]
**Describe the bug**
 `NIX_PATH` seems to be ignored?

**To Reproduce**
```

NIX_PATH=nixpkgs=/home/arian/Projects/nixos/nixpkgs nixos-option
terminate called after throwing an instance of 'nix::ThrownError'
  what():  file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/arian/Projects/nixos/nixpkgs/nixos/default.nix:1:60
Aborted (core dumped)
```

**Expected behavior**
Pointing to my fork of nixpkgs using `NIX_PATH` should work.  The application shouldn't coredump

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
