### ISSUE TITLE
[enhancement] docker-containers module: add wanted-by option

### ISSUE THREAD

**Issue by neumantm** [NixOS/nixpkgs#86481]
**Describe the bug**
It would be great if the submodule for the docker-containers module would have a wanted-by option which sets the wanted-by option of the corresponding systemd service.

The default of this option should be set to `[ "multi-user.target" ]` to maintain the current behavior as the new default behavior.

**To Reproduce**
Define a docker-container with a wantedBy option:

```
docker-containers = {
  myContainer = {
    image = "debian";
    wantedBy = [];
  };
};
```

**Expected behavior**
The above example should create a systemd service, which is not enabled.

**Additional context**
This would be useful to me, as I like to define services, which I can start when I need them, but don't auto start. For example a automatic text correction server a text editor can connect to via a TCP Port.

**Notify maintainers**
@benley 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: virtualisation/docker-containers
```
