### ISSUE TITLE
wxGTK31: fails with `with Gtk2 = false;`

### ISSUE THREAD

**Issue by evils** [NixOS/nixpkgs#86609]
**Describe the bug**
building `wxGTK31 { withGtk2 = false; }` fails
after af87f13d0c9ace72a46553de1208755fb52aaa22 by @lovesegfault in #85802

**To Reproduce**
1. `nix-build -E '(import ./. {}).wxGTK31.override { withGtk2 = false; }'`

**Additional context**
<details>
<summary>current failure</summary>

```
configure: error:
The development files for GTK+ were not found. For GTK+ 2, please
ensure that pkg-config is in the path and that gtk+-2.0.pc is
installed. For GTK+ 1.2 please check that gtk-config is in the path,
and that the version is 1.2.3 or above. Also check that the
libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
--libs' are in the LD_LIBRARY_PATH or equivalent.
```
</details>

This prevents `kicad-unstable` from building (i think this is the only package using wxGTK31 without gtk2)

updating `gtk 3.x` to `3.24.20` also fails, but with more colours

<details>
<summary>3.24.20 failure</summary>

```
meson.build:990:0: ERROR: Program(s) ['check-version.py'] not found or not executable
```
</details>

**Notify maintainers**
@vcunat @lethalman @worldofpeace @7c6f434c 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: wxGTK31
# a list of nixos modules affected by the problem
module:
```
