### ISSUE TITLE
`beforePlugins` removed from vim-utils causes issues for some vim plugins

### ISSUE THREAD

**Issue by arizonahanson** [NixOS/nixpkgs#86849]
**Describe the bug**
In this commit, https://github.com/NixOS/nixpkgs/commit/7909787a7d8be8e3964cd602e2151cb3a92ff7f8# the ability to supply `beforePlugins` was removed, which allowed one to specify a section of the customRC that would be placed before the plugin definitions.  Some plugins, such as ALE, require this to be able to configure the plugin.  This was a feature in 19.09 that was removed and breaks vim customization using vim-utils.

**To Reproduce**

      pkgs.vim_configurable.customize {
        name = "vim";
        vimrcConfig = {
            beforePlugins = ''
              let g:ale_cache_executable_check_failures=1
              let g:ale_lint_delay=500
...

**Expected behavior**
I expected this property to continue to work, by inserting the text before the plugin definitions in the vimrc file.

**Notify maintainers**
@kalbasit @timokau @rummik @basilgood 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.116, NixOS, 19.09.2477.a7ceb2536ab (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.03.1619.ab3adfe1c76"`
 - channels(admin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
(trying to upgrade)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.vim_configurable.customize.vimrcConfig.beforePlugins
# a list of nixos modules affected by the problem
module: vim-utils
```
