### ISSUE TITLE
gnujump: crashes with segmentation fault

### ISSUE THREAD

**Issue by iblech** [NixOS/nixpkgs#86906]
**Describe the bug**
gnujump immediately crashes with a segmentation fault after starting. Before the crash, for a short time a black window opens.

**To Reproduce**
1. nix-shell -p gnujump --run gnujump

**Expected behavior**
gnujump should not crash.

**Screenshots**
[video here](https://www.speicherleck.de/iblech/stuff/gnujump-crashes.mkv)

**Additional context**

**Notify maintainers**
@fgaz 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.5, NixOS, 20.09pre222244.22a3bf9fb9e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre222244.22a3bf9fb9e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module:
```
