### ISSUE TITLE
Microsoft Teams shows blank window

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#87069]
**Describe the bug**
I run `teams` under Gnome3 Wayland. It takes a while and then shows a blank window.

**To Reproduce**
1. Run Gnome in Wayland (didn't try anything else)
1. nix-shell -p teams --run teams

Note that the web interface works in Chrome, and other X11 apps work fine. The `teams` command shows no output, runs teams in the background and exits

**Notify maintainers**
@liff 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
