### ISSUE TITLE
zap fails to start

### ISSUE THREAD

**Issue by helinko** [NixOS/nixpkgs#87106]
**Describe the bug**
The package `zap` for ZAProxy seems to be broken. It's at least missing Java in the path, but even after installing `jre` or `jdk` separately it just starts up a grey screen with no errors to the console.

**To Reproduce**
1. Install zap
2. Run it simply as `zap`

**Notify maintainers**

@mogorman 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1619.ab3adfe1c76 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1619.ab3adfe1c76"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zap
# a list of nixos modules affected by the problem
module:
```
