### ISSUE TITLE
Setting libglvnd as a opengl driver does not put other OpenGL drivers in /run/opengl-driver

### ISSUE THREAD

**Issue by uzytkownik** [NixOS/nixpkgs#87470]
**Describe the bug**
Ideally if libglvnd is set as opengl driver the necessary files from other drivers should be available. I haven't check in details but it seems that at least DRI is missing from /run/opengl-driver while X11 is trying to look for it there.

**To Reproduce**
1. Set libglvnd as default opengl driver
2. Start X

**Expected behavior**
X11 starts (assuming drivers are available)

**Screenshots**
N/A (X11 starts but it has not HW acceleration due to lack of dri)

**Notify maintainers**
@FRidh as I don't see meta on github

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

To be filled (I rebooted to my old system)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
