### ISSUE TITLE
extraRules is overridden by default value

### ISSUE THREAD

**Issue by FranklinYu** [NixOS/nixpkgs#87555]
**Describe the bug**
In Nix configuration file, user’s specification of [`security.sudo.extraRules`](https://nixos.org/nixos/options.html#security.sudo.extrarules) will be overridden by the default rules. Default is specified in

https://github.com/NixOS/nixpkgs/blob/29d0e684afcc1a3f4d5a5c60a483ba4c719c73f6/nixos/modules/security/sudo.nix#L176-L180

**To Reproduce**
1. Set any rule in `extraRules`.
2. Apply the rules by running `nixos-rebuild switch` 

**Expected behavior**
In `/etc/sudoers`, the rules I define should be after the default rules.

**Screenshots**
I see that my rules are before the default rules, so it has lower precedence.

**Additional context**
I found this issue when installing from scratch.

**Notify maintainers**
No maintainer found. @lschuermann made #33905 which might be related.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1795.d6c1b566b77 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - security
```
