### ISSUE TITLE
`networking.domain` is ignored

### ISSUE THREAD

**Issue by blitz** [NixOS/nixpkgs#87633]
**Describe the bug**

`networking.domain` is ignored and results in e.g. `hostname --fqdn` to not report the correct domain. This results in problems down the road, because tools like Geary, the Gnome email client, cannot send emails because it fails to send a FQDN in its EHLO STMP request.

**To Reproduce**
1. Set the following in NixOS configuration and rebuild the system:

```
  networking.hostName = "foo";
  networking.domain = "bar";
```

2. `/etc/hostname` contains the hostname without domain (unlike Fedora)
3. `hostname --fqdn` returns the hostname without the domain

**Expected behavior**

`hostname --fqdn` shows a fully-qualified domain name. 

**Notify maintainers**

@Infinisil @abbradar @lheckemann 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.11, NixOS, 20.03.1822.5adf2a6c116 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1822.5adf2a6c116, nixos-hardware, unstable-20.09pre223023.fce7562cf46"`
 - channels(julian): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
 -  network-interfaces
```
