### ISSUE TITLE
vlc crashes with qgnomeplatform enabled

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#87667]
**Describe the bug**
On system with qt5 module and i3wm, vlc launched via dmenu crashes on file open

**To Reproduce**
```nix
  services.xserver.windowManager.i3.enable = true;
  qt5 = {
    enable = true;
    platformTheme = "gnome";
    style = "adwaita-dark";
  };
  environment.systemPackages = with pkgs; [ vlc ];
```

**Expected behavior**
Dialog should open. Instead there is an error
```
(vlc:13061): GLib-GIO-ERROR **: 16:32:34.604: Settings schema 'org.gtk.Settings.FileChooser' is not installed                                                                                                                                  
vlc terminated by signal SIGTRAP (Trace or breakpoint trap) 
```

**Notify maintainers**

@worldofpeace @jtojnar 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.09.git.683c68232e9 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(gnidorah): `""`
 - channels(root): `"nixos-20.09pre222138.b3c3a0bd183"`
 - nixpkgs: `/home/gnidorah/tmp/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: qt5
```
