### ISSUE TITLE
VSCodium desktop file specifies wrong StartupWMClass

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#87768]
**Describe the bug**

The desktop file packaged with VSCodium specifies the wrong StartupWMClass

**To Reproduce**

1. Install `nixpkgs.vscodium`
2. Start VSCodium
3. `xprop WM_CLASS`
4. Click on the started application
5. `cat /path/to/profile/share/applications/codium.desktop | grep StartupWMClass`

**Expected behavior**
Step 4 prints `WM_CLASS(STRING) = "vscodium", "VSCodium"`. Therefore step 5 should print one of those strings. But instead, the file contains `StartupWMClass=Codium`.

**Additional context**
Those must match or else the application won't be linked to the .desktop file when started.

**Notify maintainers**
@Synthetica9 @turion

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.10-arch1-1, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels: `"home-manager, nixpkgs-20.09pre224962.8fc744839bd"`
 - nixpkgs: `$HOME/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
