### ISSUE TITLE
Steam icon is broken and huge with gnome-shell

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#87774]
**Describe the bug**
The steam icon is broken and makes the systray huge.

**To Reproduce**
1. install steam system wide (environment.systemPackages)
2. run Steam with gnome

**Expected behavior**

**Screenshots**

The flameshot icon will return to the normal size if I close steam.

The Steam icon is the first ugly one on the left.

![image](https://user-images.githubusercontent.com/24027/81874776-a23a3c00-954c-11ea-8b71-22f910b994ee.png)

**Additional context**
Resolution: 1920x1080

**Notify maintainers**
@jagajaga

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.09pre225264.683c68232e9 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(bbigras): `"home-manager, unstable-20.09pre225264.683c68232e9"`
 - channels(root): `"nixos-20.09pre225264.683c68232e9, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
