### ISSUE TITLE
nixos/zfs/zed: email notifications are missing the hostname

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#87823]
**Describe the bug**
When receiving email notifications from `zfs-zed.service`, for example after a scrub, the hostname is missing from the subject `ZFS scrub_finish event for rpool on` and from the body of the email:
```
ZFS has finished a scrub:

   eid: 11
 class: scrub_finish
  host: 
  time: 2020-05-14 12:47:05+0000
  pool: rpool
 state: ONLINE
  scan: scrub repaired 0B in 0 days 00:02:03 with 0 errors on Thu May 14 12:47:05 2020
config:

	NAME                               STATE     READ WRITE CKSUM
	rpool                              ONLINE       0     0     0
	  nvme-eui.0025385591506999-part1  ONLINE       0     0     0

errors: No known data errors
```

**To Reproduce**
1. Set up ZFS and zed (`services.zfs.zed.settings.ZED_EMAIL_ADDR` and `services.zfs.zed.settings.ZED_NOTIFY_VERBOSE = true;`)
2. Start a scrub `systemctl start zfs-scrub.service`
3. Wait for the email

**Expected behavior**
Hostname should be present in the subject and body of the email.

**Additional context**
Try adding the following in your configuration and notice how the `hostname` returns nothing:
```
systemd.services.zfs-zed.preStart = ''
  echo "DEBUG hostname='$(hostname)'"
  echo "DEBUG pwd='$(pwd)'"
  echo "DEBUG whoami='$(whoami)'"
'';
```

**Notify maintainers**
@Mic92 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.40, NixOS, 20.03post-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  - zfs/zed
```
