### ISSUE TITLE
Haskell packages that depend on the same C libraries as a dependency fail to build on darwin.

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#87880]
**Describe the bug**

Haskell packages that depend on the same C libraries as a dependency fail to build on darwin.

**To Reproduce**

```
macos$ git clone https://gist.github.com/roberth/39e450b211a485ae8418107781d3e56f
macos$ cd 39e450b211a485ae8418107781d3e56f/
macos$ nix-build --arg 'pkgs' 'import ~/nixpkgs {}'
building '/nix/store/s8dnpd1gh0pn5ds839zql3xlbzlnn9m3-example-0.1.0.0.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/blamkv8vbxc4nyzs61llligwi1bz9v4f-ghc-8.8.3.
ln: failed to create symbolic link '/nix/store/9l6986vbhzr0q3j42pgy3pc49h02xnlv-example-0.1.0.0/lib/links/libboost_context.dylib': File exists
builder for '/nix/store/s8dnpd1gh0pn5ds839zql3xlbzlnn9m3-example-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/s8dnpd1gh0pn5ds839zql3xlbzlnn9m3-example-0.1.0.0.drv' failed
```

See [gist](https://gist.github.com/roberth/39e450b211a485ae8418107781d3e56f)

**Expected behavior**

A successful build

**Additional context**

PR available #87881

**Notify maintainers**

@peti 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - haskellPackages
# a list of nixos modules affected by the problem
module:
```
