### ISSUE TITLE
Open in Visual Studio Code doesn't work in pantheon

### ISSUE THREAD

**Issue by husseinraoouf** [NixOS/nixpkgs#87948]
**Describe the bug**
clicking on a file or folder in pantheon and selecting "Open in Visual Studio Code" doesn't work and shows "Could not open files or URIs with this app"

**To Reproduce**
1. right-click on any file or folder
2. select Open in Visual Studio Code

**Expected behavior**
the file or folder will be opened in vs code

**Screenshots**
![Screenshot from 2020-05-16 15-41-13](https://user-images.githubusercontent.com/23583726/82121329-7c02df00-978c-11ea-9f55-73a0234565be.png)

**Additional context**
I think I could open files in vs code before I switch to pantheon

**Notify maintainers**
@eadwu @Synthetica9 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.17, NixOS, 20.03.1445.95b9c99f6d0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(hussein): `"home-manager-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
  - vscode
module:
```
