### ISSUE TITLE
BOINC use local config only after restart

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#88000]
**Describe the bug**
I have configured BOINC to use all GPUs. But when the computer is bootet, BOINC starts only with one GPU.

**To Reproduce**
1. Setup BOINC to use OpenCL GPU and setup project with GPU WUs (e.g. PrimeGrid)
2. add `<use_all_gpus>1</use_all_gpus>` to `/var/lib/boinc/cc_config.xml`

my full config:

```
<cc_config>
    <log_flags>
    </log_flags>
    <options>
		<report_results_immediately>1</report_results_immediately>
        <use_all_gpus>1</use_all_gpus>
    </options>
</cc_config>
```

3. restart boinc: `systemctl restart boinc`

**Expected behavior**
BOINC using config from local files

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1879.91cdcf31357 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1879.91cdcf31357, nixos-hardware, nixos-unstable-20.09pre225931.32b8ed73809"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: boinc
# a list of nixos modules affected by the problem
module: services.boinc
```
