### ISSUE TITLE
Best way to use pre-commit

### ISSUE THREAD

**Issue by glasserc** [NixOS/nixpkgs#88022]
**Describe the bug**
I'm trying to best understand how to use the `pre-commit` derivation to set up hooks on projects that I work on. So far I have tried:

- Adding `pre-commit` to the `buildInputs` of the project, entering a development environment using `nix-shell`, and running `pre-commit install`. However, my text editor is not inside any `nix-shell`.
- Installing `pre-commit` globally using `nix-env -iA nixos.gitAndTools.pre-commit`.

I've had failures because `pre-commit` cannot find `virtualenv` to set up a Python environment, or because the virtualenv it sets up for a hook does not have access to `six`.

I guess the situation is complicated because `pre-commit` tries to build its own "repositories" in a somewhat Nix-like way, but outside Nix and relying on a global Python installation.

I am starting to think that instead of using `pre-commit install` to generate `.git/hooks/pre-commit`, I should just hand-write a simple one that does `nix-shell && pre-commit run`. This seems dangerous too, since the repositories that `pre-commit` creates will be influenced by the shell that they're being run in, and since they're re-used, could break in other projects with other inputs in their `shell.nix`.  I was wondering if this is the expected behavior or if there's something obvious I'm missing.

**To Reproduce**
- Create a new git repository.
- Add a `shell.nix` that provides `pre-commit`. Something like this is fine:

```
{ pkgs ? import <nixpkgs> {} }:
pkgs.stdenv.mkDerivation {
  name = "quartermaster-elm-dev";
  nativeBuildInputs = [
    pkgs.pre-commit
  ];
}
```

- Create a `.pre-commit-config.yaml`. This one is fine:

```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
```

- Commit these two files.
- `nix-shell --command "pre-commit install"`
- Touch another file and try to commit it.

**Expected behavior**
The git hook will be run successfully.

**Additional context**
I also found https://github.com/cachix/pre-commit-hooks.nix, maybe that's what I should be using instead?

**Notify maintainers**
@borisbabic

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.40, NixOS, 20.03.1885.885a6658073 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(ethan): `""`
 - channels(root): `"nixos-20.03.1885.885a6658073"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
