### ISSUE TITLE
Stepmania: missing icon

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#88030]
**Describe the bug**
The menu icon for Stepmania is missing.

**To Reproduce**
1. Install `stepmania`
2. Try to find it in the Applications menu.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1866.a7c70f2e10b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1879.91cdcf31357, u-20.09pre225976.2608a278ffb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: stepmania
# a list of nixos modules affected by the problem
module:
```
