### ISSUE TITLE
Fractal Missing libsecret Dependency

### ISSUE THREAD

**Issue by IGJoshua** [NixOS/nixpkgs#88094]
**Describe the bug**
Fractal cannot save or reuse credentials because of a lack of libsecret.

**To Reproduce**
1. Run fractal: `nix-shell -p fractal --run "fractal"`
2. Login
3. Fractal logs the following:
```
fractal_gtk::appop::login: Can't store the password using libsecret
fractal_gtk::appop::login: Can't store the token using libsecret
```

**Expected behavior**
Fractal correctly saves and reuses the given credentials.

**Notify maintainers**
@dtzWill @worldofpeace 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1896.025deb80b24 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1896.025deb80b24"`
 - channels(suskeyhose): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - fractal
# a list of nixos modules affected by the problem
module:
```
