### ISSUE TITLE
linux-steam-integration is broken

### ISSUE THREAD

**Issue by puzzlewolf** [NixOS/nixpkgs#88460]
**Describe the bug**
`linux-steam-integration` does not build.

**To Reproduce**
in the local clone of `nixpkgs`, run
`$ nix-build -A linux-steam-integration`. 
Last lines of output:
```
Project name: linux-steam-integration
Project version: 0.7.3
Using 'CC_FOR_BUILD' from environment with value: 'gcc'
Using 'AR_FOR_BUILD' from environment with value: 'ar'
Using 'CC' from environment with value: 'gcc -m32'

meson.build:1:0: ERROR: Compiler gcc -m32 can not compile programs.
```

**Expected behavior**
It should build :)

**Notify maintainers**
@etu

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.10, NixOS, 20.03.1926.f45ccd9d20b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(nora): `"home-manager-20.03"`
 - channels(root): `"nixos-20.03.1926.f45ccd9d20b, nixos-hardware, nixos-unstable-20.09pre225264.683c68232e9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: linux-steam-integration
# a list of nixos modules affected by the problem
module:
```
