### ISSUE TITLE
wireguard-go: binary has wrong name, breaks wireguard-tools

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#88567]
**Describe the bug**
The `wireguard-go` package is supposed to vend a binary called `wireguard-go`. Instead it's vending a binary called `wireguard`. The upstream repo has a Makefile that explicitly passes `-o wireguard-go` to `go build`. I don't see any equivalent in our `wireguard-go` package (which bypasses the Makefile).

This is a problem both because of breaking expectations, and also because the `wireguard-tools` package makes the assumption that `wireguard-go` provides a binary called `wireguard-go`. In particular, the `wg-quick` script tries to invoke the binary `wireguard-go` as part of the `wg-quick up` subcommand.

**To Reproduce**
1. Build `wireguard-go`
2. See what binaries it provides

**Expected behavior**
It should provide `wireguard-go`.

**Notify maintainers**
@elseym @kirelagin @yegortimoshenko @zx2c4

Also the `wireguard-tools` maintainers, in case the resolution is to change `wireguard-tools` to use the name `wireguard` instead of `wireguard-go`: @elseym @ericsagnes @mic92 @zx2c4 @globin @ma27 @xwvvvvwx

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(lilyball): `"nixpkgs-20.09pre226388.a0d7927a8c7"`
 - nixpkgs: `/Users/lilyball/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [wireguard-go, wireguard-tools]
# a list of nixos modules affected by the problem
module:
```
