### ISSUE TITLE
nftables fails to restart after libvirtd gets started

### ISSUE THREAD

**Issue by meh** [NixOS/nixpkgs#88643]
**Describe the bug**
`libvirtd` seems to be able to bring up iptables and load the `ip_tables` module even when it's in the blacklist, this seems to be similar to what was happening in #24318, and the `libvirtd` module is in fact including `pkgs.iptables` instead of `config.networking.firewall.package` which I guess would make it work when using `pkgs.iptables-nftables-compat`.

**To Reproduce**
1. Enable `nftables`.
2. `nixos-rebuild switch`
2. Enable `libvirtd`.
3. `nixos-rebuild switch`
4. **BOOM**

**Expected behavior**
For `libvirtd` to use the right firewall package and not load the `ip_tables` module.

**Additional context**
I've used `libvirtd` before with `iptables-nft` on Arch, and it was working properly.

**Notify maintainers**
@globin @fpletz 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.09pre226148.0f5ce2fac0c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nixos/modules/virtualisation/libvirtd.nix
```
