### ISSUE TITLE
Recent dbus session changes break notifications with Dunst

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#88691]
**Describe the bug**

```
$ notify-send "test"
```

When installed, [dunst](https://dunst-project.org/) should display freedesktop's notifications.

**To Reproduce**
1. install dunst
2. install libnotify

Make sure dunst is the only notification daemon (I use the i3wm window manager).

Switch to `nixos-unstable` branch and apply these 2 commits from `master`:

- 0f1eb8cd79182640fb26db149c6810b013e8209f
- effceb8bfe14554537085b52a8be1b0c4127b64a

Run

```
$ notify-send "test"
```

**Expected behavior**

A popup with the text "test" appears.

**Actual behavior**

Nothing is shown

**Notify maintainers**

@adisbladis 

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.09.git.52f0b860b1e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `""`
 - nixpkgs: `/home/cassou/Documents/projects/nixos/system`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
