### ISSUE TITLE
keepassxc: Segmentation fault

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#88893]
**Describe the bug**
program crash when clicking button

https://gist.github.com/davidak/399bf0129ecaa1d6da422bbb3be2f17b

**To Reproduce**
1. open a database in keepassxc
2. click settings, secret service integration
3. enable freedesktop integration
1. click edit database settings

**Expected behavior**
dialog open or something, no crash

**Screenshots**
![Screenshot from 2020-05-25 21 45 54](https://user-images.githubusercontent.com/91113/82839949-4f0fa400-9ed1-11ea-8e5a-9395149abc92.png)

**Notify maintainers**
@jonafato @turion

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"home-manager-20.03, nixos-20.03.1950.48723f48ab9, nixos-hardware, nixos-unstable-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: keepassxc
# a list of nixos modules affected by the problem
module:
```
