### ISSUE TITLE
intel-media-sdk references gcc

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#88939]
**Describe the bug**

`intel-media-driver` references `gcc-unwrapped` because `autopatchelfHook` is in the inputs and it patches the samples at `$out/share/...`:

https://github.com/NixOS/nixpkgs/blob/fdecd9eedab4dca3e526005b666a3bb5a14d16d6/pkgs/development/libraries/intel-media-sdk/default.nix#L14-L15

**To Reproduce**

```
nix why-depends nixpkgs.intel-media-sdk nixpkgs.gcc-unwrapped
```

**Expected behavior**

No reference.

**Additional context**

I'm up to patchelf binaries that we ship, but:

1) `ffmpeg-full` depends on intel-media-sdk and users of it shouldn't get gcc in their closure for this.
2) We don't have even to ship the samples to everyone. Maybe split the outputs?

**Notify maintainers**

@midchildan .

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.09pre226148.0f5ce2fac0c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c"`
 - channels(doron): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: intel-media-sdk
# a list of nixos modules affected by the problem
module:
```
