### ISSUE TITLE
libgme references gcc-unwrapped

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#88953]
**Describe the bug**

`libgme` references `gcc-unwrapped`. I can't figure out yet why.

**To Reproduce**

```
nix why-depends nixpkgs.libgme nixpkgs.gcc-unwrapped
```

**Expected behavior**

No gcc reference.

**Additional context**

`libgme` is a dependency of `gst-plugins-bad` which is a common dependency for many applications.

**Notify maintainers**

@lheckemann 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.09pre226148.0f5ce2fac0c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c"`
 - channels(doron): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libgme
# a list of nixos modules affected by the problem
module:
```
