### ISSUE TITLE
Does beesd actually work?

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#88955]
**Describe the bug**

I have a NixOS system with 250 LXC containers (running NixOS) from the same LXC image. They are initially about 600 MB and content is identical. So i thought that this is a perfect scenario for deduplication, but only 10 GB are saved from 170 after i let beesd do its thing for 4 days.

**To Reproduce**

I might try to reproduce it with a simpler setup when i have time.

1. ...
2. ...
3. ...

**Expected behavior**
250 x 600 MB are deduplicated to 1x 600MB, since the nix store is read only and never changes

**Additional context**

**Notify maintainers**
@charles-dyfis-net 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
