### ISSUE TITLE
NixOS can’t be installed on MBR+UEFI system

### ISSUE THREAD

**Issue by volb** [NixOS/nixpkgs#89197]
**Describe the bug**
NixOS does not install on MBR+UEFI systems with default instructions (or any I’ve found). 

**To Reproduce**

I have a laptop with Windows 10 and until recently it also had a Fedora dual boot with an ext4 /boot partition. I deleted Fedora and the /boot partition and nixos-install complains whether I follow the GPT/UEFI instructions or the MBR/BIOS instructions. Either it complains that I don’t have GPT (which I cannot switch to without wiping my computer) or it can’t find /boot (which I am not supposed to have according to the MBR instructions). 

**Expected behavior**
It should not complain about a /boot partition if I do not need one. 

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
