### ISSUE TITLE
mkl-paradiso support

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#89316]
**Describe the bug**

I'm currently hacking together a nix-expression for a legacy fortran tool. This tool links against mkl, and specifically mkl-paradiso. AFAIK neither mkl-paradiso nor anything fortran related is in the mkl package. What is the way to go here?

**Notify maintainers**

@bhipple 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.14, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1950.48723f48ab9, nixos-unstable-20.09pre226148.0f5ce2fac0c"`
 - channels(wucke13): `"nixos-unstable-20.09pre227577.135073a87b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - mkl
# a list of nixos modules affected by the problem
module:
```
