### ISSUE TITLE
newtonwars: nix does not install anything

### ISSUE THREAD

**Issue by josephtheengineer** [NixOS/nixpkgs#89377]
**Describe the bug**
Installing newtonwars appears to do nothing

**To Reproduce**
1. Install `newtonwars`
2. Run `newtonwars`

**Expected behavior**
newtonwars binary should be in path

**Screenshots**
```
> nix-env -f nixpkgs -iA newtonwars
replacing old 'newtonwars-20150609'
installing 'newtonwars-20150609'
> newtonwars
newtonwars: command not found
```

**Notify maintainers**

@pSub

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15, NixOS, 20.09pre227577.135073a87b7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c"`
 - channels(josephtheengineer): `"nixos-19.09pre186326.62cb4f72282"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: newtonwars
# a list of nixos modules affected by the problem
module:
```
