### ISSUE TITLE
Missing desktop file for ranger

### ISSUE THREAD

**Issue by dmarcoux** [NixOS/nixpkgs#89432]
**Describe the bug**
The desktop file for ranger exists, but it's not symlinked under `/run/current-system/sw/share/applications/`.

**To Reproduce**
1. Install ranger
2. `ranger.desktop` isn't under `/run/current-system/sw/share/applications/`

**Expected behavior**
I expect `ranger.desktop` to be symlinked under `/run/current-system/sw/share/applications/`

**Notify maintainers**
@toonn @magnetophon

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.03.2015.e7752db2fb6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"home-manager-20.03, nixos-20.03.2015.e7752db2fb6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ranger
# a list of nixos modules affected by the problem
module:
```
