### ISSUE TITLE
Missing desktop file for vim

### ISSUE THREAD

**Issue by dmarcoux** [NixOS/nixpkgs#89431]
**Describe the bug**
When installing vim with [vim_configurable](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vim/configurable.nix), vim's desktop file exists, but it's not symlinked under `/run/current-system/sw/share/applications/`.

**To Reproduce**
1. Install vim with `vim_configurable`
2. `vim.desktop` isn't under `/run/current-system/sw/share/applications/`

**Expected behavior**
I expect `vim.desktop` to be symlinked under `/run/current-system/sw/share/applications/`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.03.2015.e7752db2fb6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"home-manager-20.03, nixos-20.03.2015.e7752db2fb6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: vim_configurable
# a list of nixos modules affected by the problem
module:
```
