### ISSUE TITLE
vscode-with-extensions can't find any extensions

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#89494]
**Describe the bug**

the vscode-extensions directory has the structure

```
└── share
    └── vscode
        └── extensions
                 .. stuff
```

so `code` should be called with the argument `--extensions-dir /nix/store/<dir>/share/vscode/extensions/` instead of `--extensions-dir /nix/store/<dir>`

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
