### ISSUE TITLE
cargo-watch broken on master

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#89541]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.30, NixOS, 20.03beta1155.29eddfc36d7 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(poscat): `""`
 - channels(root): `"nixos-20.03beta1155.29eddfc36d7, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cargo-watch
# a list of nixos modules affected by the problem
module:
```
