### ISSUE TITLE
krb5.realms.<realm>.kdc should allow multiple hosts

### ISSUE THREAD

**Issue by mrschyte** [NixOS/nixpkgs#89626]
**Describe the bug**
In the krb5 module (nixpkgs/nixos/modules/config/krb5) the `krb5.realms.<realm>.kdc` option should allow multiple hosts to be defined. Kerberos allows multiple entries for fault tolerance, however the module only allows a single host to be defined.

**Expected behavior**
The kdc option should be a list of strings, for example:

```
krb5.realms = {
  "CORP" = {
    admin_server = "dc01.corp.lan";
    kdc = [
      "dc01.corp.lan"
      "dc02.corp.lan"
    ];
  };
}
```

which should produce the following config:

```
[realms]
CORP = {
  admin_server = dc01.corp.lan
  kdc = dc01.corp.lan
  kdc = dc02.corp.lan
}
```

**Notify maintainers**

@eqyiel @Mic92 @pvgoran @volth 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.2015.e7752db2fb6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2015.e7752db2fb6"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - krb5
```
