### ISSUE TITLE
ncurses-5's libtinfo.so symlink is broken

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#89769]
**Describe the bug**
When instantiated with `abiVersion="5"` the `ncurses` derivation creates a symlink from `libtinfo.so` to `libncursesw.so`. This is not a robust way to produce an ABI compatibility wrapper since the `soname`  will be `ncurses` rather than `tinfo` as expected. This results in issues like #85924, where the dynamic linker notices the inconsistency and fails.

**To Reproduce**

See #85924 for one manifestation of this issue.

**Expected behavior**
`libtinfo.so` can be loaded without any trouble.

**Notify maintainers**

@OmnipotentEntity @Mic92 @matthewbauer @Ericson2314 @andrew-d 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
