### ISSUE TITLE
clementine stopped functioning

### ISSUE THREAD

**Issue by marius851000** [NixOS/nixpkgs#89792]
**Describe the bug**
Since some day, clementine refuse to work. I bisected the error to the commit 247b54688976d7220889f2207e1b92fb17759d53 .

The error message in the terminal is:
    realloc(): invalid pointer
    fish : Tâche , './result/bin/clementine' terminée par le signal SIGABRT (Abandon)

**To Reproduce**
go to a nixpkgs git tree
`git checkout 247b54688976d7220889f2207e1b92fb17759d53`
`nix-build . -A pkgs.clementine`
`./result/bin/clementine`

**Expected behavior**
clementine start as expected

**Notify maintainers**

@ttuegel 
**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15, NixOS, 20.09pre228245.bfcead18cda (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre228439.c9057b3751a"`
 - channels(marius): `"home-manager, mariusnur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.clementine
# a list of nixos modules affected by the problem
module:
```
