### ISSUE TITLE
Unable to import pandas when using `nix run`

### ISSUE THREAD

**Issue by swflint** [NixOS/nixpkgs#89811]
**Describe the bug**
When using `nix run nixos.python3 nixos.python3Packages.pandas -c python3` and importing pandas with `import pandas as pd` I get an error, namely `ModuleNotFoundError: no module named 'pandas'`

**To Reproduce**
1. See above

**Expected behavior**

Pandas should be imported and available for use.  Note, the equivalent `nix-shell` call works with no problem.

**Notify maintainers**

@raskin @fridh @knedlsepp

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.5, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre228622.029a5de0839, nix1709-17.09.3269.14f9ee66e63, nix1803-18.03.133402.cb0e20d6db9, nix1809-18.09.2574.a7e559a5504, nix1903-19.03.173553.6420e2649fa, unstable"`
 - channels(swflint): `"nix2003-20.03.1950.48723f48ab9, nixos-20.09pre226148.0f5ce2fac0c, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.pandas
# a list of nixos modules affected by the problem
module:
```
