### ISSUE TITLE
gdk-pixbuf-xlib include dir in .pc file is wrong

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#90168]
**Describe the bug**

`lib/pkgconfig/gdk-pixbuf-xlib-2.0.pc` contains the line:

```
Cflags:-I${includedir}/gdk-pixbuf-xlib-2.0
```

But the header files are installed at `include/gdk-pixbuf-2.0`. Notice the missing `xlib` in the directory name.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.16, NixOS, 20.09.git.0cd503d6ff1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre228622.029a5de0839"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gdk-pixbuf-xlib
# a list of nixos modules affected by the problem
module:
```
