### ISSUE TITLE
qutebrowser / QtWebEngine is out of date? (Chromium 69.0.3497.128)

### ISSUE THREAD

**Issue by josephtheengineer** [NixOS/nixpkgs#90220]
**Describe the bug**
Latest QtWebEngine is at 77.0.3865.98?

**To Reproduce**
1. `nix-env -i qutebrowser`
2. `qutebrowser`
3. `:version`

**Notify maintainers**
@matthewbauer 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.16, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre228622.029a5de0839"`
 - channels(josephtheengineer): `"nixos-19.09pre186326.62cb4f72282"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: qutebrowser, QtWebEngine
# a list of nixos modules affected by the problem
module:
```
