### ISSUE TITLE
discord 0.10.0 broken on master

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#90265]
**Describe the bug**
Discord 0.10.0 cannot be built on master

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: discord
# a list of nixos modules affected by the problem
module:
```
