### ISSUE TITLE
fish shell documentation is installed to `share/doc/index.html`, creating conflicts

### ISSUE THREAD

**Issue by jonas-schievink** [NixOS/nixpkgs#90484]
**Describe the bug**
The `fish` derivation installs its HTML documentation directly into `/share/doc`, cluttering the shared namespace. This can cause file conflicts with packages that have the same bug.

**To Reproduce**
1. Install `fish`
2. `/nix/store/m1bid6zqjjd8kszsn4ya2h1693i6z4mz-fish-3.1.2/share/doc/index.html` exists (or similar).

**Expected behavior**
The documentation should be installed in a `fish` subdirectory.

**Notify maintainers**

@ocharles @cole-h 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.14-arch1-1, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixpkgs-20.03pre203598.f97746ba272"`
 - channels(jonas): `"home-manager, nixpkgs-20.09pre229671.9d0c3ffe678"`
 - nixpkgs: `/home/jonas/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- fish
# a list of nixos modules affected by the problem
module:
- programs.fish
```
