### ISSUE TITLE
Open-vm-tools fails to install due to missing gdk-pixbuf-xlib-2.0

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#90544]
**Describe the bug**
Open-vm-tools fails to install:

```
checking for gdk-pixbuf-xlib-2.0 >= 2.21.0 (via pkg-config)... no
configure: error: gdk-pixbuf-xlib-2.0 not found. Please configure without X11 (using --without-x) or install the gdk-pixbuf-xlib-2.0 devel package.
builder for '/nix/store/aryy4mq9nr08dlvmhb2prm6zpyk2dmzr-open-vm-tools-11.0.5.drv' failed with exit code 1
```

**To Reproduce**
```
virtualisation.vmware.guest.enable = true;
```
in /etc/nixos/configuration.nix

**Notify maintainers**
joamaki 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.44, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(alex): `"home-manager"`
 - channels(root): `"nixos-20.09pre229574.0a146054bdf, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: open-vm-tools
# a list of nixos modules affected by the problem
module: virtualisation.vmware.guest
```
