### ISSUE TITLE
LightDM background no longer can be set to a simple color, conflicting with the documentation

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#90558]
**Describe the bug**
Commit 3d1706c28df08ca09e9502ef9e17322ea71a70a4 changed the type of the NixOS configuration option `services.xserver.displayManager.lightdm.background` from `str` to `path`, requiring that it be set to the path of an image that is to be used as the desktop background.  Formerly it also was allowed to set the background to a solid color, e.g., I have it set to `"#000000"`, and the option documentation still claims that this is allowed: <https://github.com/NixOS/nixpkgs/blob/0aa73fdf13bba1d4b380c487dd40817075834ba5/nixos/modules/services/x11/display-managers/lightdm.nix#L138-L140>

Given that the option documentation still claims that setting the background to a color is allowed, I suppose commit 3d1706c28df08ca09e9502ef9e17322ea71a70a4 was in error.

**Notify maintainers**
@jtojnar @worldofpeace

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43-hardened, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre229574.0a146054bdf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: []
# a list of nixos modules affected by the problem
module: [services.xserver.displayManager.lightdm]
```
