### ISSUE TITLE
lutris / wine: takes forever to compile

### ISSUE THREAD

**Issue by josephtheengineer** [NixOS/nixpkgs#90668]
**Describe the bug**

**To Reproduce**
1. `environment.systemPackages = with pkgs; [
   lutris-free`
2. `sudo nixos-rebuild switch --upgrade`

**Expected behavior**
The update to finish within a day

**Screenshots**
![Screenshot](https://i.imgur.com/Iraugl6.png)

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.16, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre229574.0a146054bdf"`
 - channels(josephtheengineer): `"nixos-19.09pre186326.62cb4f72282"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: wine / wine64 / winewow / lutris
# a list of nixos modules affected by the problem
module:
```
