### ISSUE TITLE
tor-browser-bundle-bin derivation upstream sources missing

### ISSUE THREAD

**Issue by HanEmile** [NixOS/nixpkgs#91062]
**Describe the bug**
The upstream sources used in the [tor-browser-bundle-bin](https://github.com/NixOS/nixpkgs/tree/01d4e2fe332420684803170597d1b88e9f826303/pkgs/applications/networking/browsers/tor-browser-bundle-bin) derivation are not availible anymore. ([9.0.9](https://dist.torproject.org/torbrowser/9.0.9/) is missing, but [9.0.10](https://dist.torproject.org/torbrowser/9.0.10/) now exists → version bump needed).

**To Reproduce**
1. Build the `tor-browser-bundle-bin` derivation

**Expected behavior**
The `tor-browser-bundle-bin` derivation should be built.

**Additional context**

So here's the problem:
```
$ nix-shell -p tor-browser-bundle-bin
these derivations will be built:
  /nix/store/489pchclwhli5ahcwk0i513v14sl98rf-tor-browser-linux64-9.0.9_en-US.tar.xz.drv
  /nix/store/r7x81b9jyg120wn1z71kbmvgzbycq27f-tor-browser-bundle-bin-9.0.9.drv
building '/nix/store/489pchclwhli5ahcwk0i513v14sl98rf-tor-browser-linux64-9.0.9_en-US.tar.xz.drv'...

trying https://dist.torproject.org/torbrowser/9.0.9/tor-browser-linux64-9.0.9_en-US.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download tor-browser-linux64-9.0.9_en-US.tar.xz from any mirror
builder for '/nix/store/489pchclwhli5ahcwk0i513v14sl98rf-tor-browser-linux64-9.0.9_en-US.tar.xz.drv' failed with exit code 1
cannot build derivation '/nix/store/r7x81b9jyg120wn1z71kbmvgzbycq27f-tor-browser-bundle-bin-9.0.9.drv': 1 dependencies couldn't be built
error: build of '/nix/store/r7x81b9jyg120wn1z71kbmvgzbycq27f-tor-browser-bundle-bin-9.0.9.drv' failed
```

**Notify maintainers**

@offline @matejc @doublec @thoughtpolice @joachifm @hax404 @cap

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.03.2015.e7752db2fb6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(emile): `"nixos-20.09pre225673.8ba41a1e149"`
 - channels(root): `"nixos-20.03.2015.e7752db2fb6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: https://github.com/NixOS/nixpkgs/blob/01d4e2fe332420684803170597d1b88e9f826303/pkgs/applications/networking/browsers/tor-browser-bundle-bin/default.nix
```
