### ISSUE TITLE
Some Mesa drivers break with patchelf 0.11

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#91145]
**Describe the bug**
```
$ glxinfo
zsh: segmentation fault (core dumped)  glxinfo
```

Bisected to d020ee07cda36787d5bc5fe8a0da0dbbed63859a

**To Reproduce**
1. `git checkout d020ee0`
2. `sudo ln -snf $(nix-build . -A mesa.drivers) /run/opengl-driver`
3. `glxinfo`

**Expected behavior**
The same test does not segfault with `d020ee0^`

**Additional context**
This is on a machine with an Intel iGPU, in case this ends up being a driver-specific problem rather than core Mesa / breaking all drivers.

**Notify maintainers**
@domenkozar for patchelf
@primeos @vcunat for mesa

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15-hardened, NixOS, 20.09.git.53bbb34d874 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(delroth): `""`
 - nixpkgs: `/etc/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
