### ISSUE TITLE
nixos-rebuild: Git not found; cannot figure out revision

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#91199]
**Describe the bug**

nixos-rebuild tries to use git, but it is not a dependency

```
building '/nix/store/0jlghfnbhn57dlnlys0ywsbgaywqcrx9-nixos-rebuild.drv'...
building Nix...
warning: Git not found; cannot figure out revision of /home/davidak/nixpkgs
building the system configuration...
```

**To Reproduce**
1. git clone nixpkgs
2. remove git
3. `nixos-rebuild switch -I nixpkgs=~/nixpkgs/`

**Expected behavior**
nixos-rebuild should be pure and not depend on manually installed dependencies

**Additional context**
building from master, not a problem for users of channels

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.46, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre230335.9480bae3370"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

;)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
