### ISSUE TITLE
Rust Nightly is missing a library

### ISSUE THREAD

**Issue by witchof0x20** [NixOS/nixpkgs#91314]
**Describe the bug**

As of rust nightly 2020-06-22, Rust nightly cannot find libz.so.1
This issue is not present in Rust nightly 2020-06-21.

**To Reproduce**
```
nix-shell -p rustup
rustup update nightly
rustup run nightly rustc
```
```
/home/jade/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

**Expected behavior**
rustc works

**Additional context**
This also happens with rust nightly from https://github.com/mozilla/nixpkgs-mozilla

**Notify maintainers**
@Mic92

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.46, NixOS, 20.03.2262.2b417708c28 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2262.2b417708c28, nixpkgs-unstable-20.09pre221694.342eaba9ebb"`
 - channels(jade): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
