### ISSUE TITLE
aerc / notmuch: broken build - 4 tests failed.

### ISSUE THREAD

**Issue by josephtheengineer** [NixOS/nixpkgs#91326]
**Describe the bug**
```
Notmuch test suite complete.
1108/1115 tests passed.
3 broken tests failed as expected.
4 tests failed.
make: *** [test/Makefile.local:75: test] Error 1
builder for '/nix/store/s0zxf8gwp3bz3qa3r5rrmi75qz7azab7-notmuch-0.29.3.drv' failed with exit code 2
cannot build derivation '/nix/store/k6124nx5mrr5bnmvcwgawvy9n3bhds88-aerc-unstable-2020-02-01.drv': 1 dependencies couldn't be built
```

**To Reproduce**
1. `nixos-rebuild switch --upgrade`

**Screenshots**
[Log](https://hastebin.com/poqufiruzu.cs)
![Screenshot](https://i.imgur.com/82vEZ8D.png)

**Notify maintainers**
@tadeokondrak @flokli @puckipedia 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.2, NixOS, 20.09pre229574.0a146054bdf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre230335.9480bae3370"`
 - channels(josephtheengineer): `"nixos-19.09pre186326.62cb4f72282"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: aerc, notmuch
# a list of nixos modules affected by the problem
module:
```
