### ISSUE TITLE
python37Packages.progressbar2 fails to build with "error: option --addopts not recognized"

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#91492]
**Describe the bug**

When trying to build the package

**To Reproduce**

Any of 
* `nix-env -iA nixos.python37Packages.progressbar2`
* look at https://hydra.nixos.org/build/123012472

**Additional context**

According to https://hydra.nixos.org/api/scmdiff?uri=https%3A%2F%2Fgithub.com%2Fnixos%2Fnixpkgs.git&rev1=bbd12947de648afdf0895f6f816a29955c3b0e38&rev2=6f72f0b0df954e904d9fd1ef8a69fa3cc60059a9&branch=&type=git, `progressbar2` wasn't changed itself, so probably the python framework changed in a way such that you can't give `--addopts` manually anymore.

**Notify maintainers**

@ashgillman 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.47, NixOS, 20.09pre231796.22a81aa5fc1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"musnix, nixos-20.09pre231796.22a81aa5fc1, nixos-hardware"`
 - channels(turion): `"home-manager, nixos-19.03-19.03.173691.34c7eb7545d, nixos-unstable-newer-20.09pre231796.22a81aa5fc1, nixpkgs-20.09pre231837.2cd2e7267e5"`
 - nixpkgs: `/home/turion/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - python37Packages.progressbar2
# a list of nixos modules affected by the problem
module:
```
