### ISSUE TITLE
NixOS power.ups module does not generate all needed config files

### ISSUE THREAD

**Issue by cmm** [NixOS/nixpkgs#91681]
**Describe the bug**
The following `configuration.nix` snippet:
```
power.ups = {
  enable = true;
  mode = "standalone";
  ups = {
    usb-ups = {
      driver = "usbhid-ups";
      port = "auto"; 
      description = "A cheapo USB UPS";
    };
  };
};
```
results in services failing to start due to missing config files etc.
`upsmon`: `Can't open /etc/nut//upsmon.conf: No such file or directory`
`upsd`: `stat /etc/nut//upsd.conf: No such file or directory`

(`upsdrv` fails too, but that could be down to the fact that I haven't plugged the UPS in yet -- but for the record, it complains `Can't chdir to /var/lib/nut/: No such file or directory`)

**Expected behavior**
I'd expect the services to start successfully (and probably complain about the missing actual UPS).

**Notify maintainers**
(The UPS module appears to have received only drive-by changes for the last several years, so no idea who to bug personally).

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.48, NixOS, 20.03.2351.f8248ab6d9e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2351.f8248ab6d9e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.monitoring.ups
```
