### ISSUE TITLE
AnyDesk: Accept connection window is empty

### ISSUE THREAD

**Issue by fleimgruber** [NixOS/nixpkgs#91782]
**Describe the bug**
When a client connects to AnyDesk the window to accept the connection request opens up but is empty.

**To Reproduce**
1. Start AnyDesk on NixOS.
2. From another client connect to the NixOS AnyDesk via its Desk Address.

**Expected behavior**
Window to accept the connection request opens up and contains button to accept the connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/7400038/86044756-d7421580-ba4a-11ea-9b51-48ae74e55243.png)

**Additional context**
If one tries to close the empty window, after a while one sees this Warning
![image](https://user-images.githubusercontent.com/7400038/86045658-2dfc1f00-ba4c-11ea-9813-32c20c7d9951.png)  

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.48, NixOS, 20.03.2351.f8248ab6d9e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2351.f8248ab6d9e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
