### ISSUE TITLE
tor-browser-bundle-bin: Input method integradion does not work

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#91925]
**Describe the bug**
Input method does not work in torbrowser `tor-browser-bundle-bin` version `9.5`.

**To Reproduce**
1. Add it with home-manager or `nix-env`.
2. Type command `torbrowser` 
3. Try switching ~~fcitx~~fcitx5 input method engines.

**Expected behavior**
Dvorak and Chewing installed with fcitx can be used in Tor Browser.

**Screenshots**

**Additional context**
It starts from version `9.5`. (Thanks a lot to all the people that make 9.5 available!)
The input method framework I'm using is ~~fcitx~~ (now fcitx5).
I'm not sure if it is an upstream issue, nor if it is on purpose (to harden or something).

**Notify maintainers**

@offlinehacker @matejc @doublec @thoughtpolice @joachifm @hax404 @scaredmushroom 

**Metadata**
(`nix-shell -p nix-info --run "nix-info -m"` result)
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.09pre228204.467ce5a9f45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1"`
 - channels(shamrock): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tor-browser-boundle-bin, torbrowser
# a list of nixos modules affected by the problem
module:
```
