### ISSUE TITLE
w32api fails to build on mingwW64

### ISSUE THREAD

**Issue by gustavderdrache** [NixOS/nixpkgs#91983]
**Describe the bug**
The derivation `windows.w32api` fails to build for 64-bit mingw targets.

**To Reproduce**
1. `$ nix-build '<nixpkgs>' -A pkgsCross.mingwW64.windows.w32api`

**Expected behavior**
The w32api derivation builds like it does for `pkgsCross.mingw32`.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-7648-generic, Pop!_OS, 19.10`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(gustavderdrace): `"nixpkgs-20.09pre232692.7db146538e4"`
 - nixpkgs: `/home/gustavderdrache/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
