### ISSUE TITLE
Got the error "fatal: reference is not a tree" when using nix-prefetch-git

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#91998]
**Describe the bug**

**To Reproduce**
`nix-prefetch-git https://github.com/haskell/haskell-language-server --rev 77c31c37aceb822ceb5b60f11f4933419353c675 --fetch-submodules`

**Expected behavior**
nix-prefetch-git should not produce an error

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.49, NixOS, 20.09pre232692.7db146538e4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"home-manager, nixos-20.09pre232692.7db146538e4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nix-prefetch-git
# a list of nixos modules affected by the problem
module:
```
