### ISSUE TITLE
Brasero: can't make 1-to-1 copy of discs

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#92087]
**Describe the bug**
Brasero is missing some library which should have the name "readom"

**To Reproduce**
1. Open brasero
2. Choose a "Disc copy" project
3. Choose source and destination (iso image name)

**Expected behavior**

To be able to copy a disc to a iso image.

**Screenshots**

https://imgur.com/QsCILY5

**Additional context**

**Notify maintainers**

@jtojnar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
