### ISSUE TITLE
syncthing is broken in stable

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#92271]
**Describe the bug**
Folders added in syncthing are not accessible to anyone.

**To Reproduce**
1. Enable syncthing via `services.syncthing.enable = true;`
2. `nixos-rebuild switch`
3. Configure a folder to be shared

**Expected behavior**
The folder is available to everyone in the `syncthing` group under `/var/lib/syncthing/folderlocation`.

**Additional context**
The rights to `/var/lib/syncthing` seem to be "user `syncthing` can read/write, everyone else cannot do anything" which doesn't work. Setting `user = "philipp"` results in `/var/lib/syncthing` to be `rwx` for the user "237" in my case, and I still cannot access it.

Also, the syncthing version is very old and not the latest stable.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.03.2437.d6260a33e43 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2437.d6260a33e43"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
