### ISSUE TITLE
Can't change display resolution in Virtualbox

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#92356]
**Describe the bug**
when i change the display resolution in KDE in Virtualbox, the window changes for 0.5 sec. and changes back to 800x600

it makes no difference if it is the live image or installed

https://peertube.social/videos/watch/31518aaa-5363-4513-822e-e3e583819d1b

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
be able to changes display resolution

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.03.2425.9a3e34ae601 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
