### ISSUE TITLE
gitolite creates directories through systemd.tmpfiles.rules

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#92473]
**Describe the bug**

My server uses an encrypted filesystem /data that I have to mount manually after reboot.
Gitolite is configured to use /data/gitolite.
I have configured gitolite-init to only run once /data is mounted.
Mounting of /data always fails, as gitolite uses systemd.tmpfiles.rules to generate directories and thus the mountpoint is not empty. Manual cleanup is required every time.

**Expected behavior**
Gitolite should create its directories in gitolite-init.service.

**Additional context**
systemd-tmpfiles-setup.service runs before the system is fully initialized, so I cannot delay that service.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.50, NixOS, 20.03.2451.74f2559a69f (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2451.74f2559a69f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: gitolite
```
