### ISSUE TITLE
sage: Test failure

### ISSUE THREAD

**Issue by jpas** [NixOS/nixpkgs#92518]
**Describe the bug**

The tests related to sagenb fail. https://hydra.nixos.org/build/123157309/nixlog/1
This failure seems to be cause by the deprecation of SecureCookie in werkzeug as of 1.0 (in pr #89723).

Sagenb is deprecated https://wiki.sagemath.org/sagenb, so we could disable these tests to fix the build.

It may also be worthwhile to put some effort into packaging Sage 9.1 and 9.2. But these use python3 as a base so the update may be non-trivial.

**Notify maintainers**
@timokau 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
