### ISSUE TITLE
brasero: displaying generinc icon when Alt-Tab'ing

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#92585]
**Describe the bug**

Gnome displays the wrong icon for brasero when Alt-Tabb'ing

**To Reproduce**
1. Open brasero
2. Press Alt-Tab
3. Notice missing icon and wrong name

**Expected behavior**

**Screenshots**

https://imgur.com/a/2i6l2hM

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
