### ISSUE TITLE
fish and motd options conflicting

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#92639]
**Describe the bug**
When `fish` is enabled as default shell and a `motd `message is set, the `fish`'es welcome message is displayed instead of `motd`.

Configuration:
```
programs.fish.enable = true;
users.defaultUserShell = "/run/current-system/sw/bin/fish";
users.motd = "Message of the day";
```
What is displayed:
```
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
```

**To Reproduce**
1. use the configuration provided
2. login with a new user
3. notice the message of the day

**Expected behavior**
motd to take precedence over fish'es welcome message

**Screenshots**

**Additional context**

**Notify maintainers**

CC @ocharles @cole-h 
**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
