### ISSUE TITLE
nextcloud: allow hosting with apache httpd webserver

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#93070]
**Describe the bug**
The nextcloud service is heavely nginx-attached. It has code like:

`chown -R nextcloud:nginx ${cfg.home}/config ${cfg.home}/data ${cfg.home}/store-apps`

where it uses nginx group for the user which owns those folders.

So this is a request to make nextcloud service webserver-independent.

**Notify maintainers**

@schneefux @bachp @globin @fpletz @ma27

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51-gnu, NixOS, 20.09.git.e5e50216072 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
