### ISSUE TITLE
Steam fails to launch several Zachtronics games.

### ISSUE THREAD

**Issue by aiverson** [NixOS/nixpkgs#93205]
**Describe the bug**
Ironclad Tactics, Opus Magnum, Shenzhen I/O fail to launch in steam linux runtime on nixos.

**To Reproduce**
1. Download one of the mentioned games
2. Press Play
3. Watch the game not start.

**Expected behavior**
The game should launch and create a window and be playable.

**Screenshots**

**Additional context**
Inspecting the logs seems to indicate the lack of /etc/ld.so.cache and /sbin/ldconfig being problems.

**Notify maintainers**
@jagajaga 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.4, NixOS, 20.09pre231796.22a81aa5fc1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(aiverson): `"home-manager"`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1, stable-19.03.173691.34c7eb7545d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - steam
# a list of nixos modules affected by the problem
module:
```
