### ISSUE TITLE
AX200 Bluetooth doesn't work on NixOS

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nixpkgs#93452]
**Describe the bug**
I just replaced the wifi card on my laptop with an Intel AX200. While WiFi worked right away I could not get bluetooth to work on this card. even `rfkill` wouldn't show any bluetooth devices.

**To Reproduce**
1. Install AX200 card
2. `rfkill` -> check that there is no bluetooth device

**Expected behavior**
For bluetooth to work like it did in my 9560 card

**Screenshots**

**Additional context**

**Notify maintainers**

@jtojnar who has a system with the same card

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/run/current-system/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
