### ISSUE TITLE
Cross-compiling argyllcms for aarch64 fails

### ISSUE THREAD

**Issue by noneucat** [NixOS/nixpkgs#93507]
**Describe the bug**
`argyllcms` fails to build when attempting to cross-compile to aarch64 on `nixpkgs`:

```
...
aarch64-unknown-linux-gnu-gcc: error: unrecognized command line option '-m64'
aarch64-unknown-linux-gnu-gcc: error: unrecognized command line option '-m64'
aarch64-unknown-linux-gnu-gcc: error: unrecognized command line option '-m64'
...
```

**To Reproduce**
`nix-build '<nixpkgs>' -A pkgsCross.aarch64-multiplatform.argyllcms`

**Expected behavior**
`pkgsCross.aarch64-multiplatform.argyllcms` builds without error.

**Metadata**
- nixpkgs `c71518e75bf`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsCross.aarch64-multiplatform.argyllcms 
# a list of nixos modules affected by the problem
module:
```
