### ISSUE TITLE
appimage-run can't find GSettings schemas

### ISSUE THREAD

**Issue by billop** [NixOS/nixpkgs#93561]
**Describe the bug**
AppImages on presumably non-Gnome systems cannot find GSettings schemas.

**To Reproduce**
1. Download https://github.com/project-slippi/slippi-desktop-app/releases/download/v1.4.5/Slippi-Launcher-1.4.5-x86_64.AppImage
2. `chmod +x Slippi-Launcher-1.4.5-x86_64.AppImage`
3. `appimage-run Slippi-Launcher-1.4.5-x86_64.AppImage`
4. Click "Configure Settings"
5. Attempt to specify a path by pressing the upload icon

This will cause the appimage to crash with the error message:
`(slippi-desktop-app:30146): GLib-GIO-ERROR **: 16:00:35.251: No GSettings schemas are installed on the system`

**Expected behavior**
App shouldn't crash and open up a filesystem dialog.

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.03.2533.76adfc180c0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2533.76adfc180c0, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
