### ISSUE TITLE
istioctl doesn't include charts

### ISSUE THREAD

**Issue by teozkr** [NixOS/nixpkgs#94163]
**Describe the bug**

Our build of istioctl doesn't include charts, which breaks the `istioctl install` mechanism.

**To Reproduce**
1. Install Docker
2. Create K8s cluster: `nix run nixpkgs.kind -c kind create cluster`
3. Try to install Istio into the cluster: `nix run nixpkgs.istioctl -c istioctl install`
4. Install fails with:

> Error: failed to apply manifests: compiled in charts not found in this development build, use --charts with local charts instead or run make gen-charts

**Expected behavior**
Istio is installed into the cluster.

**Screenshots**

![image](https://user-images.githubusercontent.com/649832/88782681-297f6f00-d18e-11ea-8888-35f768866339.png)

**Additional context**

**Notify maintainers**
@veehaitch 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-arch1-1, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(teo): `"nixpkgs-20.09pre236138.970b2b853d4"`
 - nixpkgs: `/home/teo/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- istioctl
# a list of nixos modules affected by the problem
module:
```
