### ISSUE TITLE
electrum-ltc: GUI cannot start under GNOME

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#94238]
**Describe the bug**
electrum-ltc fails with a Qt error. The CLI is still accessible

**To Reproduce**
1. `nix-env -iA electrum-ltc`
2. `electrum-ltc`
3. observe stderr

**Expected behavior**
Application should start normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/15657735/88936198-ed7a0600-d282-11ea-9ae8-e97a853b0a0b.png)

**Additional context**
I think it's just a matter of a wrapQtApp since BTC Electrum does that and works on the same machine.

**Notify maintainers**
orphan package

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.03.2670.b33ff917c60 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2670.b33ff917c60"`
 - channels(louis): `"nixpkgs-20.03.2668.7c85b915892, nixpkgs-unstable-20.09pre236343.78215a8395f"`
 - nixpkgs: `/home/louis/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
