### ISSUE TITLE
pythonPackages.uranium name squatted by Ultimakers Uranium package

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#94498]
**Describe the bug**
The python package name uranium has been squatted by the package of the same name from Ultimaker.

IMO the ultimaker package should be renamed to ultimaker-uranium, since the pypi name should take precedence.

**Expected behavior**
Pypi should be the authoritative place for package names

**Notify maintainers**

 @abbradar @gebner

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pythonPackages.uranium
# a list of nixos modules affected by the problem
module:
```
