### ISSUE TITLE
wireguard: service file naming breaks lookup via systemctl

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#94665]
The names for wireguard peer services generated by nixpkgs are broken in a way that they cannot be used with `systemctl`.
Example:
```bash
[root@vpnserver:~]# systemctl list-units | grep wg0-peer
wireguard-wg0-peer-jNoocGTmICAKB8ksy\x2bGKqGfv2k8bXejPhCZq4vAjAUo\x3d.service            loaded active exited    WireGuard Peer - wg0 - jNoocGTmICAKB8ksy+GKqGfv2k8bXejPhCZq4vAjAUo=
wireguard-wg0-peer-T4mc\x2b1RuHU4BABdyf-gKa6P89hBY5H58zGp1y\x2bNAOnQ\x3d.service         loaded active exited    WireGuard Peer - wg0 - T4mc+1RuHU4BABdyf/gKa6P89hBY5H58zGp1y+NAOnQ=

[root@vpnserver:~]# systemctl status wireguard-wg0-peer-jNoocGTmICAKB8ksy\x2bGKqGfv2k8bXejPhCZq4vAjAUo\x3d.service
Unit wireguard-wg0-peer-jNoocGTmICAKB8ksyx2bGKqGfv2k8bXejPhCZq4vAjAUox3d.service could not be found.

```

**Notify maintainers**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - networking.wireguard
```
