### ISSUE TITLE
`services.xserver` naming is confusing

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#94799]
From the man page:

> The X Window System (X11) provides the basis of NixOS’ graphical user interface. It can be enabled as follows:
> ```nix
> services.xserver.enable = true;
> ```

From the default generated `configuration.nix`:

```nix
# Enable the X11 windowing system.
services.xserver.enable = true;
```

The file is also located in `nixos/modules/services/x11/xserver.nix`

**BUT**

I need to set `services.xserver.enable = true`, even though I use Gnome on Wayland **without any X11 running**. The name `xserver` and its relation to the X11 configuration is really misleading

**Additional context**

I was wondering why my GUI wasn't showing up until I found out that I must set `services.xserver.enable = true;`.

**Notify maintainers**

Didn't find any.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.03.2685.977000f149b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: `services.xserver`
```
