### ISSUE TITLE
tahoe-LAFS 1.13.0     won't install, broken package

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#94834]
**error: txaio-20.4.1 not supported for interpreter python2.7**   
**during nixos-rebuild switch**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.09pre234242.c71518e75bf (Nightingale)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre234242.c71518e75bf"`
 - channels(k): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
