### ISSUE TITLE
audacity: segmentation fault during startup

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#94865]
**Describe the bug**
audacity crashes during start up. Last time it did make it to the "send bug report" form, but crashed when closing it.

**Metadata**
Crashes with nixpkgs at 2d6cbbe4627f6fe4a179c681537b0a3e4f59b732.
At 20.03 it works fine though.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: audacity
# a list of nixos modules affected by the problem
module:
```
