### ISSUE TITLE
Some builds fail with invalid gcc flag "-Xarch_x86_64" (Linux+CMake+PCH)

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#94905]
**Describe the bug**

Building of `tdesktop-2.2.0` (Telegram Desktop) on my NixOS unstable system fails with the message:
```
g++: error: unrecognized command line option '-Xarch_x86_64'; did you mean '-march=x86-64'?
```

**Notify maintainers**

@primeos @abbradar 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.12, NixOS, 20.09.git.4254de4a41f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre237279.8e2b14aceb1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tdesktop
# a list of nixos modules affected by the problem
module:
```
