### ISSUE TITLE
Nheko fails to build on master / latest channells

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#94942]
**Describe the bug**

The build fails, see https://hydra.nixos.org/build/124911367/nixlog/1/tail

I haven't succeeded in bisecting this, using `stdenv = clangStdenv` "fixes" the issue with warnings such as:

```
  clang-7: warning: argument unused during compilation: '-Xarch_x86_64 -include/build/source/build/CMakeFiles/nheko.dir/cmake_pch_x86_64.hxx'
   [-Wunused-command-line-argument]
```

Instead of the errors, but I'm perplexed as to what could be the source of this issue.

cc @ekleog @fpletz

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nheko
# a list of nixos modules affected by the problem
module:
```
