### ISSUE TITLE
OpenJDK 14 build fails with "output 'openjfx-modular-sdk-14-ga' is not allowed to refer to the following paths: openjdk-headless-11.0.8+10"

### ISSUE THREAD

**Issue by jerith666** [NixOS/nixpkgs#95117]
**Describe the bug**
as described in https://github.com/NixOS/nixpkgs/issues/93922#issuecomment-669549775, the build fails with:

```
output '/nix/store/94403zyixykw7gqm6ri26did2kslpq2b-openjfx-modular-sdk-14-ga' is not allowed to refer to the following paths:
  /nix/store/qkkif6z2wsn4gqqjsgk9s475lq3s1dhc-openjdk-headless-11.0.8+10
```

**To Reproduce**
Since this is a dependency of openjdk14, reproduce with: `nix-build -A pkgs.openjdk14`

**Additional context**
This broke somewhere between 840c782d507 and b50ef9afa11; I'm bisecting now.

**Notify maintainers**

@abbradar @edwtjo @mweinelt @bachp @piegamesde

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.09.git.9d8a04db84 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/home/matt/git/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
