### ISSUE TITLE
wlroots 0.11.0 fails to build

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#95205]
**Describe the bug**
```
Installing /build/source/build/meson-private/wlroots.pc to /nix/store/b8agl7hzn30y05b9fibhalg1mqz1vc30-wlroots-0.11.0/lib/pkgconfig
cp: -r not specified; omitting directory 'libwlroots.so.6.p'
builder for '/nix/store/7ldr6kdb6kd39qskqy37mhayqbz56wav-wlroots-0.11.0.drv' failed with exit code 1
```

**To Reproduce**
1. git checkout master
2. nix-build -A wlroots

**Notify maintainers**
@primeos 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: wlroots
# a list of nixos modules affected by the problem
module:
```
