### ISSUE TITLE
Add power management config for nvidia

### ISSUE THREAD

**Issue by thongpv87** [NixOS/nixpkgs#95307]
**Describe the bug**

Power Management config (https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/dynamicpowermanagement.html) is very useful for saving power on laptop with Nvidia graphic card. Current nvidia module does not have any option to enable that

**Notify maintainers**
@eadwu @vcunat 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
