### ISSUE TITLE
zabbix.server-mysql and zabbix.server-pgsql broken on master

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#95532]
**Describe the bug**

`zabbix.server-mysql` and `zabbix.server-pgsql` broke recently: https://hydra.nixos.org/build/122059780. I briefly poked around but I'm not sure what the problem or solution is. If anyone has any insight much appreciated.

@jonringer took a quick look as well and had [this](https://github.com/NixOS/nixpkgs/issues/95475#issuecomment-674441702) comment.

**To Reproduce**
1. `nix-build -A zabbix.server-mysql` on `master`, see build failure: `configure: error: LIBXML2 library not found`

**Expected behavior**

I expected the program to compile.

**Screenshots**

**Additional context**

**Notify maintainers**

@PsyanticY

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zabbix.server-mysql zabbix.server-pgsql
# a list of nixos modules affected by the problem
module: services.zabbixServer
```
