### ISSUE TITLE
Plasma broke after recent updates on unstable channel

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#95636]
**Describe the bug**
A lot of kde widgets and functions broke after recent updates on the unstable channel (nixos-unstable). Opening the bluetooth widget shows this error message:
> Error loading QML file: file:///nix/store/74xnbqp5gmaq5s3b1xs6d7iaahkjrh72-bluedevil-5.17.5/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/BluetoothApplet.qml:24:1: module "org.kde.bluezqt" is not installed

Other broken widgets/functions includes bluetooth widget, printer widget and desktop (the desktop disappeared resulting in a black background)

xsession log: https://fars.ee/Z2vb

**To Reproduce**
1. Install plasma
2. open plasma

**Expected behavior**
Plasma widgets should work normally

**Screenshots**
A broken widget:
![image](https://user-images.githubusercontent.com/53291983/90347928-e7976980-e065-11ea-8363-a163b584781b.png)

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.15, NixOS, 20.09pre238896.16fc531784a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(root): `"nixos-20.09pre238896.16fc531784a, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.xserver.desktopManager.plasma5
```
