### ISSUE TITLE
pantheon: log out stalls from wingpanel-indicator-session

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#95658]
**Describe the bug**
When I click log out in wingpanel-indicator-session it stalls for a really long time before logging out.

**To Reproduce**
1. Open popover for wingpanel-indicator-session
2. Click log out
3. It stalls a really long time or doesn't happen

**Expected behavior**
It should log out really quickly.

**Additional context**
Maybe related to https://github.com/NixOS/nixpkgs/issues/84634?

**Logs**
TODO: I need to get these

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.57, NixOS, 20.09.20200810.dirty (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/n91kpnknj9jgj43kx710ha3aik4hy1l6-ww95ysky2vm95fri2vqqi4glklvg0qya-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pantheon
# a list of nixos modules affected by the problem
module: pantheon
```
