### ISSUE TITLE
`50-user.conf` fontconfig file no longer generated

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#95712]
**Describe the bug**

When `fonts.fontconfig.includeUserConf` is set `50-user.conf` file should be placed somewhere under /etc/fonts.

**Expected behavior**

I expect `50-user.conf` to exist under /etc/fonts.

**Screenshots**

N/A

**Additional context**

N/A

**Notify maintainers**

**Metadata**

nixpkgs revision: https://github.com/NixOS/nixpkgs/commit/16fc531784ac226fb268cc59ad573d2746c109c1

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
