### ISSUE TITLE
keepassx-community: Text and images are cut-off

### ISSUE THREAD

**Issue by TomSmeets** [NixOS/nixpkgs#95749]
On both the latest nixpkgs-unstable and on master (08639bcd134) the keepassx-community looks very broken. This is probably something to do with Qt, but I only noticed it with this app.

**To Reproduce**
1. start keepassxc

**Expected behavior**
Readable text and images

**Screenshots**
![2020-08-18-142526_1918x1158_scrot](https://user-images.githubusercontent.com/6740669/90513022-560c2280-e15f-11ea-9152-72c6db2fa897.png)

![2020-08-18-143421_958x568_scrot](https://user-images.githubusercontent.com/6740669/90513431-f19d9300-e15f-11ea-8845-a721c5a7e7ac.png)

**Notify maintainers**
@jonafato 
@turion 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.09.git.aa9a4f5f185 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre238896.16fc531784a"`
 - channels(tom): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - keepassx-community
# a list of nixos modules affected by the problem
module:
```
