### ISSUE TITLE
pinentry-curses doesn't provide `pinentry-curses` in PATH, when installed with nix-env

### ISSUE THREAD

**Issue by jumper149** [NixOS/nixpkgs#95777]
**Describe the bug**
After installing pinentry-curses with `nix-env -iA nixpkgs.pinentry-curses` the actual derivation that is installed is `nixpkgs.pinentry`.

**To Reproduce**
```
nix-env -iA pinentry-curses
ls -l ~/.nix-profile/bin/pinentry*
```
this will only list `pinentry` and not `pinentry-curses`.

**Expected behavior**
After `nix-env -iA nixpkgs.pinentry-curses` both `pinentry` and `pinentry-curses` are in path.

I'm not sure what the package `pinentry` should provide. Maybe everything from `pinentry-curses`, `pinentry-gnome`, ...?

**Additional context**
I noticed a problem when using gpg on the tty. It will try to use `pinentry-curses`, but won't find it and say something like: `No pinentry`

**Metadata**
`nix-shell -p nix-info --run "nix-info -m"`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.03.2806.cb1996818ed (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2806.cb1996818ed"`
 - channels(jumper): `"nixpkgs-20.09pre239139.a19e16756b6"`
 - nixpkgs: `/home/jumper/.nix-defexpr/channels/nixpkgs`
```

Maintainer information (I hope I got this right ^^):
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
pkgs.pinentry
pkgs.pinentry-curses
# a list of nixos modules affected by the problem
module:
```
