### ISSUE TITLE
nix-channel --help not working

### ISSUE THREAD

**Issue by hloeffler** [NixOS/nixpkgs#96032]
**Describe the bug**
nix-channel --help 
shows
`sh: nroff: command not found`

**To Reproduce**
1. nix-channel --help

**Expected behavior**
output

**Additional context**
nix-channel --help =>` sh: nroff: command not found`

man man =>`man: no manual entry for 'man'`

nixos-option documentation.man.enable => `Value:true`

this is working:

nix run nixpkgs.groff -c nix-channel --help

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.03.2835.ebf59916232 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2835.ebf59916232, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
