### ISSUE TITLE
SideQuest is unfree, not MIT

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#96107]
**Describe the bug**
The SideQuest (version 0.10.11) package is marked as MIT licensed. This is not the case for versions 0.10.5 and above, which are unfree and do not have source code available.

**To Reproduce**
Steps to reproduce the behavior: N/A

**Expected behavior**
SideQuest should be marked as unfree. In addition, it may be worthwhile to add a `sidequestFree` package with 0.10.4.

**Screenshots**
N/A

**Additional context**
https://old.reddit.com/r/OculusQuest/comments/gdd9dy/a_sad_update_about_sidequest_we_cannot_remain/
https://github.com/the-expanse/SideQuest/compare/v0.10.4...master

**Notify maintainers**
@joepie91 @rvolosatovs 

**Metadata**
N/A

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sidequest
# a list of nixos modules affected by the problem
module:
```
