### ISSUE TITLE
mariadb/mysql permission denied 

### ISSUE THREAD

**Issue by Kloenk** [NixOS/nixpkgs#96166]
**Describe the bug**
The ExecStartPost script is failing on mariadb, because the user seems missing. this could be fixed with `-u root` (I think)

**To Reproduce**
1. install mariadb as the mysql service
2. create a user via services.mysql.ensureUsers
3. see it fail

**Expected behavior**
The user should be created

**Notify maintainers**

CC @thoughtpolice 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
nixpkgs = master

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.mysql
```
