### ISSUE TITLE
kdesu fails to build because kdesu-search-for-wrapped-daemon-first.patch no longer applies

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#96667]
**Describe the bug**
kdesu is [failing to build](https://hydra.nixos.org/build/126229404/nixlog/1).

```
applying patch /nix/store/ymmrh039wrqallgyvx2g3yba9f116gxg-kdesu-search-for-wrapped-daemon-first.patch
patching file src/client.cpp
Hunk #1 FAILED at 378.
1 out of 1 hunk FAILED -- saving rejects to file src/client.cpp.rej
```

I bisected this problem to efb45f7638ca900575a5ee8da8de77f9ca87ae42 “Merge master into staging-next” (#96437). This is the merge commit that combines c6743ed565aa6fa5f6226cf4312cbcd7c123aafb “kde-frameworks.kdesu: search the daemon first in /run/wrappers/bin” (#93306) with 8a6bb6073a79eae7f1e3123905e9d07533521523 “kdeFrameworks: 5.71 -> 5.73” (#95893).

**To Reproduce**
`nix build -f . kdesu`

**Notify maintainers**
@ttuegel @romildo @peterhoeg @FRidh 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(anders): `""`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [kdesu]
# a list of nixos modules affected by the problem
module: []
```
