### ISSUE TITLE
nixosTests.networking.networkd.macvlan fails nondeterministically

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#96709]
**Describe the bug**
The last several Hydra trunk-combined runs have been blocked by (among other problems) a [failing nixos.tests.networking.networkd.macvlan.x86_64-linux](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.networking.networkd.macvlan.x86_64-linux/all), which was recently added back(?) to release-combined in 656f88a59c7d144edc26cd55c9356cd4bdfc70bb (#86486). When I run the test locally it sometimes succeeds and sometimes hangs forever.

**To Reproduce**
1. `nix build --no-link -Lf . nixosTests.networking.networkd.macvlan`
2. If it succeeded, clear the result with `nix-store --delete "$(nix eval --raw '(toString (import ./. {}).nixosTests.networking.networkd.macvlan)')"` (is there a better way to do that?) and try again.

**Notify maintainers**
@flokli @Ma27 @charvp 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.16, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - channels(anders): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [nixosTests.networking.networkd.macvlan]
# a list of nixos modules affected by the problem
module: []
```
