### ISSUE TITLE
mcfly: hash mismatch in fixed-output derivation

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#96846]
**Describe the bug**

```
installing
hash mismatch in fixed-output derivation '/nix/store/mczhz828q733skd0qh37cccwn3xrjl7j-mcfly-0.5.0-vendor.tar.gz':
  wanted: sha256:1jfk5a33f01g2a68igdkwxnc9rkhz7mfg3zg25r6agib7scjbgj3
  got:    sha256:0y6sjbzg5qqqip9sc9ajyd5ra3n2wwvarj6nhpzjhh05kqz3qja4
cannot build derivation '/nix/store/2mp8nab6bnk9q9b8q3rx5ymizg4vrc2a-mcfly-0.5.0.drv': 1 dependencies couldn't be built
```

**To Reproduce**
1. `nix-build -A mcfly`

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@melkor333 @marsam

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-zen1, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre237686.96069f7d890"`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
