### ISSUE TITLE
mongodb: setting initialScript leads to evaluation error

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#96902]
On unstable and 20.03 the following trivial config:
```nix
{ pkgs, ... }:
{
  services.mongodb.enable = true;
  services.mongodb.initialScript = pkgs.writeText "init-script" ''test'';
}

```
raises the following Error:
error: cannot coerce null to a string, at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/databases/mongodb.nix:178:60

I assume it requires authentication to be enabled or a password set. But this should probably be caught earlier and return a descriptive error.

**Notify maintainers**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - mongodb
module:
  - mongodb
```
