### ISSUE TITLE
nixos-container: Unknown option: I

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#96916]
**Describe the bug**

I can create a VM with:

`nixos-rebuild build-vm -I nixpkgs=~/code/nixpkgs/ -I nixos-config='/home/davidak/root'`

i was not able to connect to the VM via network, so i tried to use container:

`sudo nixos-container create test --config-file ~/root -I nixpkgs=~/code/nixpkgs/`

but got this error

`Unknown option: I`

**To Reproduce**
1. see above

**Expected behavior**
vm and container should have consistent commands

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 20.03.2868.ff6a070b4ef (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"home-manager-20.03, nixos-20.03.2868.ff6a070b4ef, nixos-hardware, nixos-unstable-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
