### ISSUE TITLE
gst_all_1.gst-rtsp-server has double prefix in it's .pc file

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#96946]
**Describe the bug**

When trying to use this package, I'm getting:

```
gcc -I... -I/nix/store/y5nlv3w8ddvy35aw3rcq8d4n5ig6ad5d-gst-rtsp-server-1.16.2-dev//nix/store/y5nlv3w8ddvy35aw3rcq8d4n5ig6ad5d-gst-rtsp-server-1.16.2-dev/include/gstreamer-1.0 -I/build/source/build -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -fPIC -MD -MQ sr
c/wfd/libwfd-server.a.p/wfd-media.c.o -MF src/wfd/libwfd-server.a.p/wfd-media.c.o.d -o src/wfd/libwfd-se
rver.a.p/wfd-media.c.o -c ../src/wfd/wfd-media.c
../src/wfd/wfd-media.c:3:10: fatal error: gst/rtsp-server/rtsp-media.h: No such file or directory
    3 | #include "gst/rtsp-server/rtsp-media.h"
```

**To Reproduce**

```
grep -R includedir $(nix-build --no-out-link -A gst_all_1.gst-rtsp-server.dev)/lib/pkgconfig
```

**Additional context**

I'm currently disabling gst-rtsp-server's split outputs in order to actually use it.

**Notify maintainers**

@bkchr 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gst_all_1.gst-rtsp-server
# a list of nixos modules affected by the problem
module:
```
