### ISSUE TITLE
openmw-tes3mp: Move CoreScripts to writeable directory

### ISSUE THREAD

**Issue by rendeko** [NixOS/nixpkgs#97039]
**Describe the bug**
CoreScripts is written to nix-store, where it cannot be modified. Without the ability to modify CoreScripts, the server portion of this package is not usable. 

**To Reproduce**
1. Install openmw-tes3mp package
2. See that CoreScripts is written to nix-store and not modifiable.

**Expected behavior**
CoreScripts should be in a user modifiable directory where files can be freely modified and added.

**Notify maintainers**
@gnidorah

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.03.2668.7c85b915892 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: openmw-tes3mp
# a list of nixos modules affected by the problem
module:
```
