### ISSUE TITLE
initrd static ipv6 does does not work

### ISSUE THREAD

**Issue by bluecmd** [NixOS/nixpkgs#97127]
**Describe the bug**

It appears to be impossible to configure static IPv6 for the inird.

**To Reproduce**
1. Configure with these options:
```
  initrd.network.enable = true;
  boot.kernelParams = [
    "ip=[2a10:xyz:zbc::12]::[2a10:xyz:zbc::1]:64:somehost::off"
  ];
```
2. Apply and reboot
3. See the error `ipconfig: can't parse IP address '[2a10'`.
**Expected behavior**
The IPv6 address passed to the kernel would be accepted and configured on the interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/149442/92250509-d9ea3c80-eecb-11ea-9538-bd033368b6b9.png)

**Additional context**
It appears to be a problem here:

https://github.com/NixOS/nixpkgs/blob/740b2f851f95fc5d6390fc6e52c989b2cfbb5e1b/nixos/modules/system/boot/initrd-network.nix#L109-L120

**Notify maintainers**

@edolstra and @fpletz seems to have been the ones touching the code around the affected line last.
Sadly it has been some time (5 years) since the code was written it seems.

**Metadata**
![image](https://user-images.githubusercontent.com/149442/92251114-a360f180-eecc-11ea-9193-43be4403e1bd.png)

(Sorry for the image, I only have console access right now)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: boot.initrd.network.enable
# a list of nixos modules affected by the problem
module: system/boot/initrd-network.nix
```
