### ISSUE TITLE
plasma-workspace: plasmashell not working properly after recent upgrade

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#97157]
**Describe the bug**
After `nixos-rebuild boot --upgrade`, the menu bar of konsole doesn't show correctly, the scroll bar doesn't work, and input method cannot be used inside konsole.
Similar problems happen to spectacle and kate after doing `home-manager switch` in an unaffected (previous) system-generation.
When this happen, `plasmashell --replace &` may fail, or be unable to detach from the terminal emulator.

The change is pushed to nixos-unstable between September 1st and September 5th (UTC+8). The version
`20.09pre237279.8e2b14aceb1 (Nightingale)` is fine (without issue).

**To Reproduce**

**Expected behavior**
* Menu bar and buttons to be shown correctly.
* Input method to be usable in a qt application.

**Screenshots**
![Screenshot_20200905_060928](https://user-images.githubusercontent.com/44064051/92288146-9250c880-ef3e-11ea-9210-f946187681f1.png)

**Additional context**

**Notify maintainers**

@ttuegel 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.136, NixOS, 20.09pre237279.8e2b14aceb1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(shamrock): `"home-manager"`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: plasma-workspace, konsole, spectacle, kate
# a list of nixos modules affected by the problem
module:
```
