### ISSUE TITLE
Loading the i915 module hangs the linuxPackages_5_7.kernel on Haswell era hardware

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#97167]
**Describe the bug**

When i915 module is loaded (e.g. during boot) the kernel hangs and does not react to input. The only way out is to power cycle.

**To Reproduce**
1. Grab haswell era hardware (Intel CPUs in 4000 series)
2. Update to a 5.7 kernel through e.g. unstable-small channel
3. Reboot

**Expected behavior**

Boot should succeed.

**Screenshots**

N/A

**Additional context**

It appears that the hang happens regardless of when the i915 is loaded. If loading of this module, or more precisely modesetting, is prevented with the `nomodeset` argument, the kernel won’t hang.

Booting with `intel_iommu=on` argument set also makes the boot succeed.

This bug report is primarily here to block propagation of the 5.7 kernel out of the `unstable` channel.

**Notify maintainers**

@thoughtpolice

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 20.09pre242124.8c7ed979b98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre242124.8c7ed979b98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: thoughtpolice
# a list of nixos modules affected by the problem
module: boot
```
