### ISSUE TITLE
Gotify's HTTP framework is in debug mode

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#97210]
**Describe the bug**

The Gotify web framework (GIN) is in debug mode.

**To Reproduce**

1. Set `services.gotify.enable = true;`
2. The second log of `journalctl -xeu gotify-server` is a warning that GIN is running in debug mode:

```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:        export GIN_MODE=release
 - using code:        gin.SetMode(gin.ReleaseMode)
```

**Expected behavior**

GIN is running in release mode, as recommended.

**Additional context**

I think this comes for [this](https://github.com/gotify/server/blob/5f21ad93775fbfa182c5cf5683ffe7eb16e8f070/mode/mode.go) source file, that sets `var mode = Dev` even in tagged commits, and uses this variable to set GIN's mode.

**Notify maintainers**

@doronbehar 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.61-hardened, NixOS, 20.03.2881.5607e74b1dd (Markhor)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2881.5607e74b1dd, home-manager-20.03, nixpkgs-unstable-20.09pre239581.1c014d4a0ec"`
 - channels(minijackson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - gotify-server
# a list of nixos modules affected by the problem
module:
  - services.gotify
```
