### ISSUE TITLE
Steam does not run anymore

### ISSUE THREAD

**Issue by VanCoding** [NixOS/nixpkgs#97234]
**Describe the bug**
After upgrading my system, I'm unable to run steam. The output is
```
bwrap: Can't find source path /System: No such file or directory
```

I have no idea why it is expecting to have a Folder at /System...

**To Reproduce**
1. Build a nixos system with the latest NixOS unstable, and with steam
2. run `steam`

**Expected behavior**
Steam should open as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/595361/92307517-64e43900-ef97-11ea-99b7-4caefbe354e8.png)

**Additional context**
Steam worked fine after my upgrade at 2020-08-22 on NixOS unstable, nixos-system-nixos-20.09pre239053.1e3f09feaa5

**Notify maintainers**
@jagajaga @Atemu 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.16, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(patrik): `"nixos-19.09pre190978.8d1510abfb5"`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam?
# a list of nixos modules affected by the problem
module:
```
