### ISSUE TITLE
TexLive 2019 arara start script broken

### ISSUE THREAD

**Issue by alwinber** [NixOS/nixpkgs#97265]
**Describe the bug**
The `arara` build tool (part of texlive) can't be started. The Error says `Error: Unable to access jarfile`

**To Reproduce**
1. nix-env -iA nixos.texlive.combined.scheme-medium nixos.jdk11
2. arara

**Expected behavior**
Arara should start.

**Additional context**
The Problem is in the script `arara.sh` (texlive-arara-4.0.6/scripts/arara/arara.sh) which wraps the java app.
It should use `basename` to strip the `.sh` suffix and start the `.jar`, but does not use the required argument, so the script tries to start `arara.sh.jar`
The Problem was fixed by upstream here:
https://github.com/TeX-Live/texlive-source/commit/dbaf12f4a47dcd62bcc96346f65493fda3fec2c8
But it is still in the snapshots of texlive 2019 which nixpkgs uses.

**Notify maintainers**

@veprbl 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(alwin): `"nixos-2003-20.03.2868.ff6a070b4ef"`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  texlive.combined.scheme-medium
  texlive.combined.scheme-full
# a list of nixos modules affected by the problem
module:
```
