### ISSUE TITLE
clinfo segfaults with AMD ROCm OpenCL stuff installed

### ISSUE THREAD

**Issue by billop** [NixOS/nixpkgs#97311]
**Describe the bug**
Installing opencl stuff for AMD:
```
hardware.opengl.extraPackages = [
  rocm-opencl-icd
  rocm-runtime-ext
];
```
and running clinfo results in a segfault.

**To Reproduce**
1. Have a AMD GPU (I have Radeon VII)
2. Follow the steps here for AMD: https://hydra.nixos.org/build/124333142/download/2/nixos/index.html#sec-gpu-accel (rocm-runtime instead of rocm-runtime-ext since it was removed)
3. `sudo nixos-rebuild switch`
4. `clinfo`
5. segfault

**Expected behavior**
clinfo should not segfault

**Notify maintainers**

@danieldk

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.60, NixOS, 20.03.20200822.ebf5991 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(root): `"nixos-20.03.2668.7c85b915892, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
