### ISSUE TITLE
pythonPackages.pam is a duplicate of (and breaks the definition of) pythonPackages.python-pam

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#97355]
**Describe the bug**
4e71d7ed466e5f80cda34e15d8f8a3b9172aca36 added pythonPackages.pam, which provides the "pam" namespace to everything in python-packages. This is fine, except this also broke the definition of pythonPackages.python-pam, which packages the *same library* at the same version.

**To Reproduce**
1. nix build nixpkgs.python3Packages.python-pam
2. cat result/lib/python3.8/site-packages/pam.py
3. libpam points at a non-existent SO in the "pam" Python package

**Expected behavior**
Only one, working definition of this Python package.

**Additional context**

**Notify maintainers**

@abbradar @mkg20001 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/home/lukegb/depot/third_party/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - pythonPackages.pam
  - pythonPackages.python-pam
# a list of nixos modules affected by the problem
module: []
```
