### ISSUE TITLE
OpenCV videoio Darwin/Mac issue/discussion

### ISSUE THREAD

**Issue by jeff-hykin** [NixOS/nixpkgs#97575]
**Describe the issue**
In the opencv build for mac, why is `videoio` off by default?

https://github.com/NixOS/nixpkgs/blob/193a6a2307b7b29aa11bee309d4aa41840686ab0/pkgs/development/libraries/opencv/4.x.nix#L258-L261

What needs to be done to enable it? (either development work, dependencies that aren't yet nixpkgs, or, if possible, how to manually override the argument and simply set to `=ON`)

**To Reproduce**
See above

**Expected behavior**
There may be a good reason it's disabled, so I can't say that I'd expect videoio to be enabled by default.

**Notify maintainers**
@basvandijk

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixpkgs-20.09pre234801.1facbd61b17"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
