### ISSUE TITLE
php73Extensions.intl broken

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#97591]
**Describe the bug**
nix-shell -p php73Extensions.intl
**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
