### ISSUE TITLE
unityhub: network not working

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#97610]
**Describe the bug**

**To Reproduce**
1. Install unityhub
2. Install unity2020 from there and create a new project
3. Try to use the package manager or any service that requires network, it fails with some dns errors

**Expected behavior**
Network works

**Screenshots**
![image](https://user-images.githubusercontent.com/7735145/92664903-87fb4980-f305-11ea-995f-291bb3e583c6.png)

**Additional context**
I'm using a custom DNS setup with stubby DNS that works as it should, unsure if the application is at fault or the userenv is not correctly propagating the DNS config

**Notify maintainers**
@tesq0 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.63, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre242769.61525137fd1, nixpkgs, solaros"`
 - channels(maciej): `"nixpkgs-20.09pre242495.3c0e3697520, solaros"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- unityhub
# a list of nixos modules affected by the problem
module:
```
