### ISSUE TITLE
Zulip opens blank

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#97646]
**Describe the bug**
When opening Zulip on recent nixos-unstable, the application starts, but the only display is a completely grey window. Things were fine a couple of weeks ago – for example at commit 1e3f09feaa5667be4ed6eca96a984b4642420b83. This is probably an Electron problem, though most other Electron applications still work on my machine.

**To Reproduce**
1. Install `zulip` from nixpkgs at commit 61525137fd1002f6f2a5eb0ea27d480713362cd5.
2. Run `zulip`.

**Expected behavior**
Graphical application opens with channels and messages visible.

**Screenshots**
![2020-09-10-095533_1366x768_scrot](https://user-images.githubusercontent.com/5139265/92705916-febb3580-f34b-11ea-8194-c926fc968fed.png)

**Additional context**
None

**Notify maintainers**
@jonafato 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.62, NixOS, 20.09.git.2d093e0ca68 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(james): `"home-manager, nixpkgs-20.09pre242495.3c0e3697520"`
 - nixpkgs: `/home/james/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: zulip
# a list of nixos modules affected by the problem
module:
```
