### ISSUE TITLE
gnat: failed to build (gentoo-gnatboot-wrapper-4.1/nix-support/add-flags.sh: line 36: cInclude: unbound variable)

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#97733]
**Describe the bug**
Building `gnat` fails with the following error message:
> /nix/store/nv40l4sh3l6pycy9dj05dbmz01wb2afx-gentoo-gnatboot-wrapper-4.1/nix-support/add-flags.sh: line 36: cInclude: unbound variable

**To Reproduce**
1. Execute `nix-shell -p gnat`.

**Expected behavior**
It enters a nix-shell with the `gnat` command available.

**Screenshots**
None

**Additional context**
The build log is available at [https://gist.github.com/omasanori/e3a7d487829f94dbce9207409643a37f](https://gist.github.com/omasanori/e3a7d487829f94dbce9207409643a37f).

**Notify maintainers**
@Lucus16 (gnatboot) and @peti (gnat)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.104-microsoft-standard, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(omasanori): `"nixpkgs-20.09pre242495.3c0e3697520"`
 - nixpkgs: `/home/omasanori/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnat
# a list of nixos modules affected by the problem
module:
```
