### ISSUE TITLE
cjdns: Not possible to bind on multiple interfaces

### ISSUE THREAD

**Issue by Nemo157** [NixOS/nixpkgs#97759]
**Describe the bug**
The [`cjdns.UDPInterface`](https://github.com/NixOS/nixpkgs/blob/a4ba0920891b8e5cd3ba923da508382f5b1b812d/nixos/modules/services/networking/cjdns.nix#L131) configuration only allows specifying a single interface on which to bind and connect to peers; this is then feed into [the array of interfaces](https://github.com/NixOS/nixpkgs/blob/a4ba0920891b8e5cd3ba923da508382f5b1b812d/nixos/modules/services/networking/cjdns.nix#L50) that the configuration supports. It should be possible to specify multiple UDP interfaces to bind on like the underlying config supports, e.g. for binding on both IPv6 and IPv4.

**Notify maintainers**
@ehmry

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
