### ISSUE TITLE
zoom-us: problem signing in via google when chrome is default browser

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#97782]
**Describe the bug**
Zoom Google Login with Chrome fails

**To Reproduce**
1. Open zoom-us
2. Sign in > Google
3. Select account in chrome

**Expected behavior**
Logs in, returns to zoom

**Screenshots**
"An error occured" page

**Additional context**
Probably the URL isn't passed properly to chrome or properly parsed by chrome

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.63, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre242769.61525137fd1, nixpkgs, solaros"`
 - channels(maciej): `"nixpkgs-20.09pre242495.3c0e3697520, solaros"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - zoom-us
 - google-chrome
# a list of nixos modules affected by the problem
module:
```
