### ISSUE TITLE
boot.initrd.network.ssh.hostKeys cannot be types.str

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#97876]
**Describe the bug**
The `ssh.hostKeys` option is given the type `types.listOf (types.either types.str types.path)`, but `types.str` does not work when passing the values to `boot.initrd.secrets` which expects `types.attrsOf (types.nullOr types.path)`.

**To Reproduce**
1. Set `boot.initrd.network.ssh.hostKeys` to `[ "/path/to/hostkey" ]`
2. Rebuild

**Expected behavior**
Strings should either be converted to path or not accepted at all.

**Additional context**

```
error: The option value `boot.initrd.secrets.../../secrets/machines/hostname/initrd/ssh_host_ed25519_key' in `/nix/store/02z7a8c44cmz7bf07ccxyx3v4finmszh-nixpkgs-src/nixos/modules/system/boot/initrd-ssh.nix' is not of type `null or path'.
```

**Notify maintainers**

@emilazy 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: boot.initrd.networking.ssh
```
