### ISSUE TITLE
Update protonmail-bridge to 1.3.x

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#97991]
**Describe the bug**

This is not really a bug, but neither it's a new package request.

AFAIU, we currently have a version of `protonmail-bridge` whose source code is not available

https://github.com/NixOS/nixpkgs/blob/4c9e280001518328ae3be74cf80cb7b6e3017952/pkgs/applications/networking/protonmail-bridge/default.nix#L5

Recently, the source code has been made available at https://github.com/ProtonMail/proton-bridge/

Although I have **not** tried to build it with Qt, I managed to get it built with CLI support (which is enough for my needs because I use it as a systemd user service anyway), you can see my take on this here

https://github.com/stefano-m/nix-stefano-m-nix-overlays/blob/master/protonmail-bridge/default.nix

maybe this can be integrated into nixpkgs so other people may benefit from the latest version of the bridge? I'd be happy to help.

Thanks!

**Notify maintainers**

Cc @lightdiscord 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.64-hardened, NixOS, 20.03.2964.252bfe01075 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2964.252bfe01075"`
 - channels(user): `"unstable-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    - protonmail-bridge
# a list of nixos modules affected by the problem
module:
```
