### ISSUE TITLE
ckb-next doesn't provide ckb-next-daemon

### ISSUE THREAD

**Issue by adamlwgriffiths** [NixOS/nixpkgs#98045]
**Describe the bug**
When running the ckb-next application, an error dialog appears stating the ckb-next-daemon isn't running.
When looking at the available systemd daemons, ckb-next-daemon isn't there.

Have installed ckb-next using both system nix configuration and home-manager. Both exhibit the same issue.
Have tried rebooting.

ckb-next doesn't seem to provide the systemd daemon required for the application to communicate with the devices.

**To Reproduce**
1. add `ckb-next` application to either system configuration.nix or home-manager home.nix
2. `sudo nixos-rebuild switch` or `home-manager switch`
3. Run ckb-next

**Expected behavior**
ckb-next app appears and runs

**Screenshots**

![image](https://user-images.githubusercontent.com/1239156/93209389-6be22700-f7a1-11ea-9c1c-26e7c00848af.png)

**Notify maintainers**
@kierdavis 

**Metadata**
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.62, NixOS, 20.03.2913.4bd1938e03e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"home-manager-20.03, nixos-20.03.2913.4bd1938e03e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ckb-next
# a list of nixos modules affected by the problem
module: ckb-next
```
