### ISSUE TITLE
mdns support for nss does not work when networkd is enabled

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#98050]
**Describe the bug**
Remote .local domains cannot be resolved when networkd is enabled

I noticed that `resolve` comes before `mdns_minimal` in the generated `nsswitch.conf`:
```
passwd:    files systemd
group:     files systemd
shadow:    files

hosts:     files mymachines resolve [!UNAVAIL=return] mdns_minimal [NOTFOUND=return] dns mdns myhostname
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```
while archwiki recommended putting `mdns_minimal` before `resolve`: https://wiki.archlinux.org/index.php/Avahi#Hostname_resolution

not sure if this is the cause

**To Reproduce**
1. enable `services.avahi.nssmdns`

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
