### ISSUE TITLE
mmc-utils: Update to 2019-10-04

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#98108]
**Describe the bug**
While Nixpkgs provides `mmc-utils` version 2018-12-14, there are some fixes landed since then.

**Notify maintainers**
@dezgeg

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.62, NixOS, 20.03.2910.42674051d12 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2910.42674051d12"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - mmc-utils
# a list of nixos modules affected by the problem
module:
```
