### ISSUE TITLE
spark with python3 - export PYSPARK_PYTHON=python3

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#98102]
**Describe the bug**
PySpark does not adopt the change in Python2 to Python3
- via "`export PYSPARK_PYTHON=python3`"

**To Reproduce**
Install spark
export PYSPARK_PYTHON=python3
pyspark

**Expected behavior**
should use python3 (not python2) 

**Screenshots**

**Additional context**

**Notify maintainers**

@thoughtpolice 
@offline 
@kamilchm 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10, NixOS, 20.03.2652.076c67fdea6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200622_334e26b`
 - channels(ae): `"home-manager-20.03, home-manager-unstable, nixos-20.03.2652.076c67fdea6, nixpkgs-20.03.2652.076c67fdea6, unstableNix-20.09pre235652.7d557a5d1b3, unstableOS-20.09pre235279.5717d9d2f7c"`
 - nixpkgs: `/home/ae/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
