### ISSUE TITLE
Missing stdlibc++.so.6

### ISSUE THREAD

**Issue by jgedri** [NixOS/nixpkgs#98233]
**Describe the bug**
Running a build task in VS Code or `haxelib run lime build (platform)` fails.

**To Reproduce**
1. Create a lime project.
2. Open project in VS code.
3. Try to build.

**Expected behavior**
A lime project should be built and run.
**Additional context**

**Notify maintainers**
@MarcWeber 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.03.2819.f0924dbf552 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(jorin): `"nixpkgs-20.09pre239985.a332da8588a"`
 - nixpkgs: `/home/jorin/.nix-defexpr/channels/nixpkgs`
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
