### ISSUE TITLE
devilutionx fails to build on master and release-20.09

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#98242]
**Describe the bug**

`devilutionx` fails to build on `master` and `release-20.09`.

**To Reproduce**
1. `nix-build -A devilutionx`

**Expected behavior**

**Screenshots**

**Additional context**

Build failure ends with...
```
[ 98%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/tcp_server.cpp.o
make[2]: *** No rule to make target '/nix/store/gs1y2f04ljx7gy7cz8l4nqad5zxlb47x-SDL2-2.0.12/lib/libSDL2main.a', needed by 'devilutionx'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/udp_p2p.cpp.o
make[1]: *** [CMakeFiles/Makefile2:109: CMakeFiles/devilutionx.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
builder for '/nix/store/10kkkhdvfziz408xf28vs4z52sshkx3v-devilutionx-1.0.1.drv' failed with exit code 2
error: build of '/nix/store/10kkkhdvfziz408xf28vs4z52sshkx3v-devilutionx-1.0.1.drv' failed
```

Also see https://hydra.nixos.org/build/126792976

**Notify maintainers**

ping @karolchmist 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: devilutionx
# a list of nixos modules affected by the problem
module:
```
