### ISSUE TITLE
r-modules/generic-builder.nix does not run `R CMD check`, contrary to comments

### ISSUE THREAD

**Issue by bcdarwin** [NixOS/nixpkgs#98575]
**Describe the bug**

In `pkgs/development/r-modules/generic-builder.nix` we find:

```
  checkPhase = ''
    # noop since R CMD INSTALL tests packages
  '';
```

but this is not actually true; when building any package one doesn't see the output of running `R CMD check <r-cmd-build-output.tar.gz>`

**To Reproduce**

nix-build -A rPackages.lenses '<nixpkgs>' --pure

**Expected behavior**

We should see the output of running R CMD check, i.e.

```
 ... lots of other checks ...
* checking tests ...
  Running 'testthat.R'
 OK
* checking PDF version of manual ... OK
* DONE

Status: OK
```

**Screenshots**

**Additional context**

**Notify maintainers**

@peti 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
