### ISSUE TITLE
DHCP in initrd does not wait for network device to appear

### ISSUE THREAD

**Issue by matthias-t** [NixOS/nixpkgs#98741]
**Describe the bug**
Using initrd networking on a low-end device (Raspberry Pi 3B+), DHCP networking fails because it executes before the device appears. The following fails with `ip: SIOCGIFFLAGS: No such device` and `udhcpc: SIOCGIFINDEX: No such device`.

  ```nix
  { boot.initrd.network.enable = true;
    networking.useDHCP = false;
    networking.interfaces.eth0.useDHCP = true; }
  ```

While the following will first fail to enable `eth0` a few times but eventually succeed.

 ```nix
{ boot.initrd.network.enable = true;
   boot.initrd.network.postCommands = ''
    until ip link set eth0 up; do sleep .1; done
    ip addr add <...> dev eth0
    ip route add default via <...> dev eth0
   ''; }
 ```

**To Reproduce**

Get a Raspberry Pi 3B+ and try the configurations above. Don't forget `boot.initrd.kernelModules = [ "smsc95xx" "usbnet" ];`.

**Expected behavior**
Expect DHCP to wait for interfaces to appear, here:

https://github.com/NixOS/nixpkgs/blob/236eb73d1bd3bd734995c51acd2ec0611f5af64f/nixos/modules/system/boot/initrd-network.nix#L123-L135

**Notify maintainers**

@fpletz and @edolstra, according to `git blame`.

**Maintainer information:**
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- boot.initrd.network.enable
# a list of nixos modules affected by the problem
module:
- system/boot/initrd-network.nix
```
