### ISSUE TITLE
sleepyhead is broken

### ISSUE THREAD

**Issue by freezeboy** [NixOS/nixpkgs#98752]
**Describe the bug**
sleepyhead doesn't compile anymore, I tried to update to the newest version, but the project looks abandoned (not proper release from their gitlab / homepage), and homepage contains a message to say the project is no more active.

Should we remove it or mark it broken ?

@krav Any suggestion ?

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
