### ISSUE TITLE
k3s module: dns not working (reply from unexpected source)

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#98766]
**Describe the bug**
I set up k3s via `services.k3s.enable = true`. DNS was not working in the cluster.

To further debug, I followed the instructions on: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
With the following results:
```
# k3s kubectl exec -ti dnsutils -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5

```

```
# k3s kubectl exec -i -t dnsutils -- nslookup kubernetes.default
;; reply from unexpected source: 10.42.0.3#53, expected 10.43.0.10#53


;; reply from unexpected source: 10.42.0.3#53, expected 10.43.0.10#53
;; reply from unexpected source: 10.42.0.3#53, expected 10.43.0.10#53
;; connection timed out; no servers could be reached

command terminated with exit code 1

```

**Additional context**
The host machine uses a static ip address configuratio with dns servers "8.8.8.8" and "8.8.4.4"

**Notify maintainers**

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - k3s
  - services.k3s
```
