### ISSUE TITLE
gnome3.epiphany frequently crashes in webprocess

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#98819]
**Describe the bug**
Since GNOME 3.36 (which enabled sandboxing in epiphany) I would often see this crash in epiphany 
```
Cannot get default EGL display: EGL_BAD_PARAMETER
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)

** (epiphany:26790): WARNING **: 22:25:48.939: Web process crashed
```

and I can still reproduce this in GNOME 3.38.

Quite honestly epiphany in NixOS is broken. And it seems to be related to sandboxing and probably an issue in webkitgtk itself.

**To Reproduce**
1. Use epiphany for a period of time
2. After a certain amount of activity on any sites it will crash

**Notify maintainers**
@NixOS/gnome 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnome3.epiphany
# a list of nixos modules affected by the problem
module:
```
