### ISSUE TITLE
Transmission daemon cannot connect to trackers on unstable channel

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#98904]
**Describe the bug**
Transmission daemon is unable to connect to trackers. This happened somewhere after commit `7f69fdd182ef28ae049417a2a41153640ac185c6`.

relevant transmission daemon log:
```
Call to getaddrinfo_async with no evdns_base configured. (/build/source/libtransmission/trevent.c:232)
```

edit: I believe this is caused by commit `2a49db6a89efb8825379aa2211b183f734164b31` since the daemon is able to connect to trackers again after I commented out the systemd service file hardenings introduced in that commit.

**To Reproduce**
1. enable transmission daemon
2. add a torrent with `trasnmission-remote -a <file>`
3. `transmission-remote -t all -i -it`

**Expected behavior**
The transmission daemon should be able to connect to tracker

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.66, NixOS, 21.03pre244045.1179840f9a8 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `"nixos-21.03pre244045.1179840f9a8, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services/torrent/transmission.nix
```
