### ISSUE TITLE
[20.09] OVA deliverable fails to produce from failed virtualbox build

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#98949]
**Describe the bug**
20.09 is blocked by the OVA test https://hydra.nixos.org/job/nixos/release-20.09/tested
https://hydra.nixos.org/build/127947924

This is the broken virtualbox build: https://hydra.nixos.org/build/127906211
Build log: https://hydra.nixos.org/build/127906211/nixlog/2

OVA release.nix: https://github.com/NixOS/nixpkgs/blob/master/nixos/release.nix#L195
```
nix-build nixos/release.nix -A ova.x86_64-linux
``` 
**Additional context**
> OVA =  Bootable VirtualBox virtual appliance as an OVA file (i.e. packaged OVF).

https://github.com/NixOS/nixpkgs/pull/97411 was merged recently. Any ideas @Ma27?

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: virtualbox nixos.ova
# a list of nixos modules affected by the problem
module:
```
