### ISSUE TITLE
tdesktop: Needs libwebrtc for video calls (or crashes)

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#98994]
**Describe the bug**
Application crashes when other side enables camera in video call

**To Reproduce**
1. Open telegram-desktop
2. Make a video-call

**Expected behavior**
It works

**Screenshots**

**Additional context**
It hangs instead with the app being frozen and some ffmpeg errors

**Notify maintainers**

@primeos @abbradar 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244416.daaa0e33505, nixpkgs, solaros"`
 - channels(maciej): `"nixpkgs-21.03pre243895.72b9660dc18, solaros"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - tdesktop
# a list of nixos modules affected by the problem
module:
```
