### ISSUE TITLE
sddm-kcm doesn't install themes in the right folder

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#98997]
**Describe the bug**
sddm-kcm doesn't install themes in the right folder. it installs the themes in / instead of the sddm/themes default directory

**To Reproduce**
1. Install sddm-kcm
2. install a theme (system settings -> startup and shutdown -> sddm -> theme tab -> install theme)
3. the theme is installed in /

**Expected behavior**
the themes should be installed under sddm/themes.

**Additional context**
I was trying to install the sddm sweet theme but from [what I read online](https://www.jorel.dev/blog/Overcoming-NixOS-Problems/), it is not easily doable without desactivating the nix-store read-only mode which I don't want to do.

**Notify maintainers**
@peterhoeg 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.66, NixOS, 21.03pre244416.daaa0e33505 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(narice): `"home-manager, nixpkgs-21.03pre243353.6d4b93323e7"`
 - channels(root): `"nixos-21.03pre244416.daaa0e33505, musnix"`
 - nixpkgs: `/home/narice/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: sddm
```
