### ISSUE TITLE
colmapWithCuda fails to build

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#99098]
**Describe the bug**

`colmapWithCuda` fails to build

**To Reproduce**
1. `nix-shell -p colmapWithCuda`

**Expected behavior**

A shell with CUDA-enabled colmap

**Screenshots**

```
...
[ 92%] Built target colmap
[ 92%] Linking CXX static library libpoisson_recon.a
[ 92%] Built target poisson_recon
[ 92%] Linking CXX static library libflann.a
[ 92%] Built target flann
make: *** [Makefile:149: all] Error 2
builder for '/nix/store/0c55vkshc00ldkfbwlq6146jglrg2k91-colmap-3.5.drv' failed with exit code 2
error: build of '/nix/store/0c55vkshc00ldkfbwlq6146jglrg2k91-colmap-3.5.drv' failed
```

**Additional context**

**Notify maintainers**

@lebastr

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.10-1-default, openSUSE Tumbleweed, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixpkgs-21.03pre243895.72b9660dc18"`
 - channels(serge): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: colmapWithCuda
# a list of nixos modules affected by the problem
module:
```
