### ISSUE TITLE
suil-qt5: build failure, both in all-packages.nix and aliases.nix

### ISSUE THREAD

**Issue by ckauhaus** [NixOS/nixpkgs#99286]
**Describe the bug**

Cannot build suil-qt5, because it is listed both in all-packages.nix and aliases.nix. I could fix it, but I don't know which one to keep.

**To Reproduce**
1. `nix-build -A suil-qt5`

**Expected behavior**

Builds derivation

**Notify maintainers**
@cillianderoiste 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-47-lowlatency, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channel: `nixos-20.09.0cfe5377e8`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - suil-qt5
# a list of nixos modules affected by the problem
module:
```
