### ISSUE TITLE
osinfo-db for nixos 20.09

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#99341]
**Describe the bug**
We should add 20.09 to https://gitlab.com/libosinfo/osinfo-db/ when it's released.
Using https://gitlab.com/libosinfo/osinfo-db/-/blob/master/scripts/updates/nixos.py

cc @NixOS/gnome 
cc @mmilata 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: osinfo-db
# a list of nixos modules affected by the problem
module:
```
