### ISSUE TITLE
moving from `users...hashedPassword` to `passwordFile` breaks `/etc/shadow`

### ISSUE THREAD

**Issue by Jake-Gillberg** [NixOS/nixpkgs#99433]
**Describe the bug**
In cleaning up my `configuration.nix` for upload to github, I switched from configuration

```
users = {
  mutableUsers = false;
  extraUsers.<userName> = {
    isNormalUser = true;
    hashedPassword = "<thehash>"
  }
};
```
to
```
users = {
  mutableUsers = false;
  extraUsers.<userName> = {
    isNormalUser = true;
    passwordFile = "/path/to/file/containing/the/hash"
  }
};
```

This broke `/etc/shadow` after `nixos-rebuild`, with the the hash appearing twice on the same line, and I was no longer able to log in as <userName>

```
<userName>:<theHash>:<theHash>:
```

I worked around this by deleting the <userName> entry in `/etc/shadow` and `nixos-rebuild`.

**Notify maintainers**
pinging everyone who contributed to nixos/modules/config/update-users-groups.pl
@edolstra 
@ruediger 
@matthewbauer 
@Infinisil 
@fpletz 
@domenkozar 
@cole-h 
@bjornfor 
@adisbladis 

**Metadata**

Maintainer information:
```yaml
- users.extraUsers.<name>.hashedPassword
- users.extraUsers.<name>.passwordFile
attribute:
# a list of nixos modules affected by the problem
module:
- users-groups.nix
```
