### ISSUE TITLE
The NixOS logo looks squashed in KDE live environment

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#99676]
**Describe the bug**
![signal-2020-10-06-021234](https://user-images.githubusercontent.com/91113/95145072-87c26280-077a-11eb-8146-7f76f4f97e11.jpeg)

desktop icon, info app, menu item

**To Reproduce**
1. boot graphical plasma iso

**Expected behavior**
show logo with right dimensions

**Additional context**
Came up in https://github.com/NixOS/nixpkgs/issues/99648

**Notify maintainers**

**Metadata**
nixos-plasma5-20.09beta538.0cfe5377e89-x86_64-linux.iso

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
