### ISSUE TITLE
KDE contains emoji picker app, but no emojis

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#99678]
**Describe the bug**
![signal-2020-10-06-021234](https://user-images.githubusercontent.com/91113/95145495-a412cf00-077b-11eb-9fda-748c74958ba9.jpeg)

**To Reproduce**
1. boot graphical plasma iso
2. open emoji app

**Expected behavior**
have emojis to pick

**Additional context**
we need full support for emojis to be a serious desktop distro in 2020

in browsers, text editors and terminal!

**Notify maintainers**

**Metadata**
nixos-plasma5-20.09beta538.0cfe5377e89-x86_64-linux.iso

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
