### ISSUE TITLE
Show NixOS short version in KDE info app

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#99677]
**Describe the bug**
long version is shown

![signal-2020-10-06-021234](https://user-images.githubusercontent.com/91113/95145276-1931d480-077b-11eb-91e0-349ea2f718af.jpeg)

**To Reproduce**
1. boot graphical plasma iso

**Expected behavior**
short version like in https://github.com/NixOS/nixpkgs/issues/74276

this is more user friendly

you still get the full version with `nixos-version` or `nix-info -m`

**Additional context**
Came up in https://github.com/NixOS/nixpkgs/issues/99648

**Notify maintainers**

**Metadata**
nixos-plasma5-20.09beta538.0cfe5377e89-x86_64-linux.iso

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
