### ISSUE TITLE
Hydra graphs take 4 minutes to load

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#99687]
**Describe the bug**
![Screenshot from 2020-10-06 04-13-08](https://user-images.githubusercontent.com/91113/95151237-7719e880-078a-11eb-84f1-702486bf26bc.png)

**To Reproduce**
1. open for example https://hydra.nixos.org/job/nixos/release-20.09/nixos.iso_minimal.i686-linux#tabs-charts

**Expected behavior**
page loads in acceptable time. i think waiting 5 seconds would be OK, more than a minute is unaccaptable

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
