### ISSUE TITLE
Unable to create screenshots in KDE

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#99680]
**Describe the bug**
I'm testing the graphical KDE iso and want to create a screenshot of an issue. That seem not to be possible.

IRC suggested https://superuser.com/questions/1179749/is-there-a-way-to-take-a-screenshot-in-kde-desktop-by-pressing-only-the-prtsc

but it does nothing and the shortcut does not exist

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
in other desktops like pantheon (and gnome i guess) i can just press PRINT and a screenshot is saved in Pictures/Screenshots

**Screenshots**
:smile: 

**Additional context**

**Notify maintainers**

**Metadata**
nixos-plasma5-20.09beta538.0cfe5377e89-x86_64-linux.iso

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
