### ISSUE TITLE
Python packages depending on qt5, use qt514 while all-packages.nix defaults to qt515, causing incompatibilities.

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#99937]
**Describe the bug**

Experienced here: https://github.com/NixOS/nixpkgs/pull/99465#issue-497263839 and here: https://github.com/NixOS/nixpkgs/pull/99685#issuecomment-704782836

How come pyqt5 winds up with qt-5.14 in it's inputs and in it's references? Considering:

https://github.com/NixOS/nixpkgs/blob/433db454f3f6925addb1d7e26f134ef67567ac02/pkgs/top-level/all-packages.nix#L15002-L15003

And:

https://github.com/NixOS/nixpkgs/blob/433db454f3f6925addb1d7e26f134ef67567ac02/pkgs/top-level/python-packages.nix#L5278-L5280

**To Reproduce**

```
nix-store --query --references $(nix-build --no-out-link -A python3.pkgs.pyqt5) | grep 5.14
```

**Expected behavior**

No qt5.14 references.

**Screenshots**

**Additional context**

**Notify maintainers**

cc @sander

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python.pkgs.pyqt5
# a list of nixos modules affected by the problem
module:
```
