### ISSUE TITLE
[20.09] electrum: qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#99982]
The Electrum wallet GUI fails with a coredump because the Qt platform is unable to load plugins.

**To Reproduce**
1. `nix run nixpkgs.electrum --command electrum`

**Expected behavior**
Electrum should launch without crashing.

**Screenshots**
```
nix run nixpkgs.electrum --command electrum
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**Additional context**
The electrum package already uses the Qt wrappers, and they worked fine at some point. I've compared the generated scripts to those of `qutebrowser`, which is working, and I didn't see any difference that could explain the problem.

**Notify maintainers**

@ehmry @joachifm @np

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.13, NixOS, 21.03.git.cfc9214a8ad (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/home/emmanuel/projects/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: electrum
# a list of nixos modules affected by the problem
module:
```
